### ISSUE TITLE
Translation Support Question

### ISSUE THREAD

**Issue by MadCoder253** [Roll20/roll20-character-sheets#10168]
@wing-it 
We have volunteer working on French and Russian translations for the GURPS character sheet. They use a professional toolset to translate the Json files directly. They would like to talk to someone who is a crowdin admin that could help using those translated files. Would you able to help with that?

Thanks,
Ken

**Comment by comradekingu** [comment]
@MadCoder253 Just upload them in a PR.
Also, use Weblate instead of Crowdin :)

**Comment by Anduh** [comment]
> Just upload them in a PR.

Where?
Roll20 [accepts only translations through CrowdIn](https://github.com/Roll20/roll20-character-sheets#internationalization--translations) for character sheets, which is the whole reason this issue was created.

**Comment by comradekingu** [comment]
@Anduh Unapologetically.
You can make a Crowdin account and upload them yourself. Crowdin itself isn't actually broken in that sense.
Without it we have a true control-group for of how many people want to translate a lot of strings using it, and the answer is nobody.
The translator has different preferences too.
I'll be right here in solidarity recommending Weblate when you get done reading the Crowdin terms and conditions, etc. :)
Without being able to upload files from upstream, and mishandling fuzzy strings we get
>Sheet translations submitted outside of Crowdin will not be accepted and/or will be overwritten by Crowdin.

as an exercise in how to use Crowdin to prevent translations to its capacity.
Happy to help.

**Comment by MadCoder253** [comment]
> It's possible to [upload .json files to CrowdIn directly](https://support.crowdin.com/offline-translation/#uploading-translations), but requires the project manager(Roll20) to [allow Offline translations](https://support.crowdin.com/advanced-project-setup/#privacy)-option, for ordinary translators to be able to do this.
> 
> I suggest you make a Help Center ticket with this info, or you might wait for a long time for them to spot this issue.

Thank you @Anduh I'll forward this information!

Ken

**Comment by MadCoder253** [comment]
The person doing the translations hasn't heard from anyone, they wanted to talk with someone about methods for getting translated files into crowdin. They contacted each of the admin's identified by crowdin and submitted a ticket but no one replied.

**Comment by MadCoder253** [comment]
@nmbradley Would you know who to contact for asking questions for Crowdin? The translator wants the ability to submit a translated file instead of using the interface.

**Comment by nmbradley** [comment]
I'm not directly familiar with how the CrowdIn integration is managed on CrowdIn's side, but If you provide the file here and make it clear what sheet it is for, and which language, I can upload it.

**Comment by comradekingu** [comment]
@nmbradley You can't sublicense the work of someone else.

**Comment by nmbradley** [comment]
@comradekingu I have no idea what this means or how it's relevant to this conversation.

**Comment by comradekingu** [comment]
Uploading the work to Crowdin means accepting the terms on Crowdin on part of the person doing it, and that must be a person that holds the rights to the work.

It doesn't meet "subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software."

**Comment by nmbradley** [comment]
That's certainly an inspired reading of the terms of service and MIT license. I don't think you're approaching this conversation in good faith, given you seem to be concern trolling a bunch of CrowdIn related conversations while contributing to a competitor product, but I will run this by our legal team to ensure that we're acting in compliance. Thanks for the advice.

**Comment by comradekingu** [comment]
My reasons for raising actual concerns with the usability and terms of Crowdin is derived form having used the product, and having read every single terms and conditions document it has to offer, before it all expands into the services it uses, sells data to or buys from. I am also a Crowdin-contributor. As a matter unrelated to me or my prior suggesting for the translator to do it, anyone else needs permission or rights.

https://tldrlegal.com/license/mit-license
>You must include the copyright notice in all copies or substantial uses of the work.Include LicenseYou must include the license notice in all copies or substantial uses of the work.

https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html
> The MIT License captures this idea by giving a license “to any person obtaining a copy of … the Software”. As we’ll see later, there is also a condition to receiving this license that ensures others will learn about their permission, too.

>Anyone who might get a sublicense under the MIT License will probably end up with a copy of the license telling them they have a direct license, too.

>If you give someone a copy of the software, you need to include the license text and any copyright notice.

>Everyone who gets a copy should get a copy of those licensor protections, too.

>If you don’t follow The MIT License’s conditions, you don’t get the permission the license offers. So failing to do what the conditions say at least theoretically leaves you open to a lawsuit, probably a copyright lawsuit. 

Its protections are "for the licensor against lawsuits by licensees".

**Comment by Anduh** [comment]
@nmbradley

It's possible to [upload .json files to CrowdIn directly](https://support.crowdin.com/offline-translation/#uploading-translations), but requires the project manager(Roll20) to [allow Offline translations](https://support.crowdin.com/advanced-project-setup/#privacy)-option, for ordinary translators to be able to do this. Could you msg this forward and see if this could be enabled? This would resolve this "can't submit `.json`-files"-situation.

**Comment by MadCoder253** [comment]
Yes, If it's possible. The person making the translations would love to talk with someone about the ability to upload the files. If it's something Roll20 can't support, please let me know and I'll close this ticket.

**Comment by Anduh** [comment]
@nmbradley said the following on another place:

> Long and short is, there was a historical reason we didn't allow json uploads, but that concern might now be resolved. We're doing some investigation.

**Comment by MadCoder253** [comment]
old, closing
