### ISSUE TITLE
[Pathfinder by Roll20] Stats don't account for CON Damage

### ISSUE THREAD

**Issue by kaykuhl** [Roll20/roll20-character-sheets#10179]
**Stats don't change for CON damage:**

For every 2 points of con damage you take you apply a -1 penalty to your fortitude saving throw. 

Also: You also lose your Hit Dice (usually your level) in both total and current hit points. So a level 10 character who took 4 points of con damage would instantly lose 20 hit points.  **This request might be more difficult to accomplish

**Comment by nmbradley** [comment]
This pertains to an official sheet and has been moved to an internal ticket.
