### ISSUE TITLE
[Mutant Year Zero] Merged pull request #10153 not published

### ISSUE THREAD

**Issue by dwarfwing** [Roll20/roll20-character-sheets#10188]
The PR [Mutant Year Zero] Fixed buddy checkbox #10153 was merged but does not appear anywhere, not in production and not on the dev server. All sheets still state version 2.03 and not 2.04, and the issue the PR fixes is still there. It is a small change but a bug fix so without it players will continue experiencing this issue. 

Can someone please look into this?

**Comment by nmbradley** [comment]
Hi @dwarfwing 

I've manually updated the sheet on the server. Are you able to verify for me that the change is now visible?

**Comment by dwarfwing** [comment]
I checked one of my test and the game we will play tomorrow, and the version is updated and the fix is there. Thanks for your help, much appreciated!

Is there anything I did wrong that caused this or was it a github or build pipeline issue? Anything that I or the community can do to avoid this happening?

**Comment by nmbradley** [comment]
I think we've identified a race condition where really small updates make their way through the build pipeline faster than our server expects. I don't think there's anything you can do to mitigate it (other than make larger PRs, which is dumb), we'll have to hunt it down on our end. 

This was a good test case to start identifying the issues though, so thanks!

**Comment by dwarfwing** [comment]
@nmbradley, could I ask you to also look at the PRs [[Alien RPG] Fixed ship armament rolls](https://github.com/Roll20/roll20-character-sheets/pull/10159/files#) #10159 as it is also not appearing in spite being merged 3 days ago?
Please let me know if you want me to open a separate Issue for this. 

[[AlienRPGroller] v2.00 - Updating stress on pushing roll #1451](https://github.com/Roll20/roll20-api-scripts/pull/1451) is also pending review and merge, but I believe the API scripts go on a different PR review schedule. Can you let me know what is the schedule for reviewing and merging API Script PRs?
