### ISSUE TITLE
[Forbidden_Lands] French  translation

### ISSUE THREAD

**Issue by hades3000** [Roll20/roll20-character-sheets#10206]
Hello,
As the official French version is out, there are some differences with the character sheet, especially in the name of the skills. can I provide you with an updated version that corresponds to the terms of the vf ?

best regards

**Comment by vince-roll20** [comment]
Hi hades3000,
if you feel so inclined, you can join Crowdin to make translation suggestions for the FL sheet (and/or any other roll20 sheet that includes translation code).  More info on the roll20 wiki here: https://wiki.roll20.net/Character_Sheet_Translation and here: https://wiki.roll20.net/CrowdIn
Cheers

**Comment by hades3000** [comment]
thanks for the information, i will do that.
