### ISSUE TITLE
Merge Upstream and line ending issues

### ISSUE THREAD

**Issue by MadCoder253** [Roll20/roll20-character-sheets#10243]
I noticed the file _/.gitattributes_ that was added a few months ago, which is great. However, some people must be committing directly to the repo or doing something else, because the past three times when I perform _git merge upstream/master_ there are several files that have **CRLF**, and git correctly converts them to **LF** BUT they are showing as changed files. I can't do a pull request because those are not my files, and I can't stash them because git keeps converting back to **LF**.

The only way I've been able to fix it, is copy my changed files to a secure location, delete my local repo, do _merge upstream/master_ on github, then clone again, make a new branch, copy files over, commit, and do a pull request. I really hope there's a way to stop this from happening, it's rather time-consuming.

**Comment by vince-roll20** [comment]
I've had the same issue with incorrect line endings in other authors files too many times to count over the last 12 months... ;-(

**Comment by MadCoder253** [comment]
Thanks for the comment @vince-roll20 .

I also just remembered a gotcha with adding the line ending rules to `/.giattributes` file. If you had already checked the repo and, I think (?), you had worked on that file before, the line endings won't be committed correctly, they will continue using the line endings you had previously. 

We had a similar issue with a work project. For work, I use the default windows GIT setting, check-out as is, commit as LF. But we ran into an issue where we were using csv files for importing into a MS SQL Server database and they used CRLF, but they were being committed with LF, so I added the `./giattributes` file that used the same rules that Roll20 does. However, the other devs repo still committed the CSV files with just a LF. To fix it, they had to delete their repo and clone the repo again.

**Comment by vince-roll20** [comment]
I have edited my local gitattributes file for LF and have vscode set to LF.  I normally just update my online account repo to be synced with the latest merge and then fetch from my local fork to sync with my online master.

Are you saying that perhaps the authors that are submitting with CRLF issues might need to delete and reclone in order for roll20's /.giattributes file to work properly?

**Comment by MadCoder253** [comment]
Right now that is my best guess. I did start using the merge upstream on github and I didn't have any line ending issues when creating a new branch, maybe that will resolve the problem. I just noticed that feature just over a week ago.

**Comment by MadCoder253** [comment]
Lol, me too!

**Comment by ggutenberg** [comment]
This SO post also seems to fix the issue locally - https://stackoverflow.com/a/41041863/177943

> Remove every file from Git's index.
`git rm --cached -r .`
> 
> Rewrite the Git index to pick up all the new line endings.
`git reset --hard`

**Comment by MadCoder253** [comment]
Thanks @ggutenberg 

I'm closing this out. I'm not sure what actions will be taken to prevent incorrect line endings from being committed.
