### ISSUE TITLE
SWN Ship: Deleting wrong fields

### ISSUE THREAD

**Issue by kevinsearle** [Roll20/roll20-character-sheets#1032]
Deleting the repeatable fields for Weapons, Defense, or Fitting will delete rows in the other.

For example:
1. Enter information for one weapon.
2. Enter information for one defense.
3. Delete the defense.
4. Close sheet.
5. Reopen sheet. All weapons, defenses, and fittings are gone.

**Comment by RonaldZ** [comment]
Took a quick peak at it and I think I see what is going on. All three have the same name repeating_weapons. This could be causing the adverse behavior you are seeing.

I will do a quick patch up for it.

**Comment by kevinsearle** [comment]
I thought the same thing and my tests showed it to still behave strangely. I'm thinking of switching from repeatable fields to a fixed number. It's not as if you have unlimited hard points, anyway.

**Comment by RonaldZ** [comment]
Are you sure? I made the changes and loaded it into a test game and seems to be working fine.

Fields are no longer being deleted after the edit. Going to push it up unless you are seeing something else.

**Comment by kevinsearle** [comment]
Maybe something else was wrong with my test. Thanks for taking that one.

**Comment by RonaldZ** [comment]
Patch has been merged in. How's it looking on your end kevin?

**Comment by kevinsearle** [comment]
Sorry for taking so long to get back to you. It definitely works!
