### ISSUE TITLE
[WFRP4CharSheet] Missing translation and translation separation change request

### ISSUE THREAD

**Issue by NatiQuaris** [Roll20/roll20-character-sheets#10332]
Hi,
I was recently helping to translate WFRP4CharSheet into Polish and discovered a couple of issues with translation that require support in the code of character sheet.  

1. Buttons "Add" and "Modify" across whole character sheet don't seem to be supported by translation files
2. Separate translation of character "Name" (Main tab) from the rest where "Name" is also used (Skills, Talents, Weapons, Trappings, etc). The reason behind is that translation in other languages (Polish for example) can vary depending on the context where the "Name" is used and for character it could translate to "Imię" where for skills, weapons etc it could be more generic as "Nazwa". I have also marked this in the translation project at Crowdin but this requires dev change and wasn't sure, if raising this at Crowdin was enough.

Thanks!
NatiQuaris

**Comment by Robak132** [comment]
@NatiQuaris I tried to localize "Add" and "Modify", but I think that can't be easily done. These names are set by Roll20 scripts, not by the character sheet itself. But I'm not an expert in this field, maybe someone more experienced can make some kind of workaround.

**Comment by nmbradley** [comment]
There's no way to modify these words, unfortunately. Closing.
