### ISSUE TITLE
[The Between] Most recent update appears to not actually have made it to the roll20 site, but is correct in github

### ISSUE THREAD

**Issue by cbkcook** [Roll20/roll20-character-sheets#10367]
The most recent update to The Between sheet appears to not actually have made it to the roll20 site, but is correct in github.
(This is mostly a correction to the Dawn Questions for the Undeniable, which were accidently the same as the Vessel in the older version).
The update was pushed about a month ago - I didn't know it wasn't showing up until a user reached out.

**Comment by nmbradley** [comment]
Hi @cbkcook 

I have manually updated this sheet. Could you check and see if it is now displaying as intended?
