### ISSUE TITLE
[Warhammer 4e Character Sheet] - What features are still WIP? 

### ISSUE THREAD

**Issue by Robak132** [Roll20/roll20-character-sheets#10417]
@Djjus Do you have a list of talents that require implementation/fixes? Also, do you have any proper testing method for it? Changing source code of roll20 in chrome isn't the most pleasant and I wonder if you have a better method.

**Comment by Djjus** [comment]
@Robak132, yes the ones you have added visibility for recently. Which i think are all situational (so will not add to the auto calc of SL). This is why they are left till last, they need to be added in a certain way.

I test via Custom Sandbox which you get with Roll20 Pro account, it's by far the easiest way.

**Comment by Robak132** [comment]
@Djjus Do you have plans for integrating Armour Qualities? It shouldn't be hard and will be quite useful for Partial or Weak Spots.

**Comment by Djjus** [comment]
Armour Qualities are not that easy to add properly because you can not really target other players, so when you roll your attack this roll can not know the Armor etc of the target. Right now you can up some info in the Armor Qualities text field, which displays when you Perform a Parry and Dodge rolls (i.e. defensive opposed roll). 

![image](https://user-images.githubusercontent.com/59532170/161767318-02beb0b4-5126-4b4e-b97c-0651fc6bae44.png)

![image](https://user-images.githubusercontent.com/59532170/161767392-ee12830a-14c1-48ce-a40a-a84c4c27cbac.png)

There is no easy way around this issue right now.

**Comment by Robak132** [comment]
@Djjus You could add it as checkboxes to add info to the opposed test. Using that you don't need to remember each effect.
Having full armor with Partial, Weakpoints and Impenetrable can be quite difficult to track.

**Comment by Djjus** [comment]
BTW i'm looking to add the logic for the remaining Talents this week.

**Comment by Djjus** [comment]
Ok its not hard, i'll put something together for next release

**Comment by Robak132** [comment]
Also if spells names in the spellbook have any meaning? There are plans to add some logic to them?

**Comment by Djjus** [comment]
Their was, but i was made to remove it. Copy Rights etc

**Comment by Robak132** [comment]
So you are planning to remove them at some point or keep them. If second option I will opt to make them localisable.

**Comment by Djjus** [comment]
I see no reason to remove them.

**Comment by Djjus** [comment]
<img width="166" alt="image" src="https://user-images.githubusercontent.com/59532170/161822083-5b295863-c77b-42af-905e-03e05238fdf7.png">

**Comment by Robak132** [comment]
Yesterday I found problem with x2 Encumbrance penalty. It seems like you only have -10 instead of -20 to Agility. Sadly, I'm not sure how to fix that.

**Comment by Robak132** [comment]
And one extra suggestion: adding Pummel to ranged weapons (sling ammo has this quality)

**Comment by Djjus** [comment]
> Yesterday I found problem with x2 Encumbrance penalty. It seems like you only have -10 instead of -20 to Agility. Sadly, I'm not sure how to fix that.

Looks ok to me, at the moment. Maybe only under certain conditions? Note minimum Agi is 10 due to this penalty.

> And one extra suggestion: add Pummel to ranged weapons (sling ammo has this quality)

Ill add this now, as i'm working on this part anyway

**Comment by Robak132** [comment]
> > Yesterday I found problem with x2 Encumbrance penalty. It seems like you only have -10 instead of -20 to Agility. Sadly, I'm not sure how to fix that.
> 
> Looks ok to me, at the moment. Maybe only under certain conditions? Note minimum Agi is 10 due to this penalty.
> 
> > And one extra suggestion: add Pummel to ranged weapons (sling ammo has this quality)
> 
> Ill add this now, as i'm working on this part anyway
![Zrzut ekranu 2022-04-06 150808](https://user-images.githubusercontent.com/31622617/161981850-9cf60fea-78d5-4b1f-bbc0-6637f6851b3a.png)
![Zrzut ekranu 2022-04-06 150943](https://user-images.githubusercontent.com/31622617/161982062-e8deb7c8-d140-4b2a-a343-23c605dfb379.png)

"Zw"="Ag", it looks like it only giving -10

**Comment by Djjus** [comment]
ok i see it, will take a look

**Comment by Robak132** [comment]
It appears that this character sheet is broken, recreating it fixed all issues

**Comment by Robak132** [comment]
Another suggestion: Archives of Empire II added a skill called "Ranged (War Machine)" used to fire cannons, balistas other siege artillery also there is "Ranged (Catapult)" in Up in Arms. I don't see a point in adding that specific skills but maybe you can add "Ranged (Misc)" and "Melee (Misc)" as you have Channeling (Misc) for similar reasons.

**Comment by Djjus** [comment]
Yes, advanced ranged has not been added yet, I'm still considering how to do it exactly, It might bne as you say with Misc. Or perhaps more targeted if it makes sense. and add the Crew Quality. But its not that high of a priority right now. It's not very hard to do, but would be good it it makes sense.

**Comment by Robak132** [comment]
@Djjus I have another idea for a feature that shouldn't be hard and I think that I can try to code it myself. We don't have any place on the character sheet to store Psychologies such as Hatred or Animosities. I propose another field similar to injuries on the main tab to store such information.

**Comment by Robak132** [comment]
I can remove them, but want to know your opinion

**Comment by Robak132** [comment]
@Djjus Some bugs I found:
- Tiring + Impact don't show additional dmg (Impact alone works, Tiring + Damaging works too)
- Suffuse With Ulgu and Beneath Notice are not on the Talents list
- My Psychology tab doesn't work (and I don't know why :D)
- 2xEncumbrance Penalty broke again (I'm pretty sure it is breaking when you have exact 30 Agility, and set and unset penalties multiple times)

**Comment by Robak132** [comment]
Maybe It needs one day to fully process all changes, but it's quite weird because my interface changes are in live.

**Comment by Robak132** [comment]
@Djjus how hard would be to add more custom skills to minor NPCs. For example with 'add' and 'modify' buttons like talents?

**Comment by Djjus** [comment]
Hey do you mean this specifically..

![image](https://user-images.githubusercontent.com/59532170/164441628-6422746c-d503-4835-a27e-1af85a159b9a.png)

A few static ones could be added, that's not a big deal I think. 
But repeating field inside repeating field will not work sadly.

**Comment by Djjus** [comment]
OR drop down select is a alternative too

<img width="135" alt="image" src="https://user-images.githubusercontent.com/59532170/164441974-df4d6bdf-9a50-4750-bc04-7e1fe04f0f57.png">

**Comment by Robak132** [comment]
![Zrzut ekranu 2022-04-22 110034](https://user-images.githubusercontent.com/31622617/164673724-5dc47320-b1e7-4fbd-b9dc-d6d400fcfed7.png)
Probably we have a little bug in Fast Shot. SL are not calculated properly: 9 + 1 = 9

**Comment by Robak132** [comment]
Do the checkbox in the equipment list have any meaning? I suppose it should lower the encumbrance by one, but it's not working like that.

**Comment by Djjus** [comment]
In Inventory no, it removes the item from the Calc if unticked. This is since the original sheet still.
Armor will be -1 if worn is ticked. I think weapons have no mod right now.

**Comment by Robak132** [comment]
How hard would be to implement this?

**Comment by Djjus** [comment]
i'm not sure it make sense, items in inventory are not worn. so dont gain -1

**Comment by Djjus** [comment]
at the moment..

**Comment by Djjus** [comment]
OR do we say everything in Inventory is Carried, and we change the checkbox to Worn?

**Comment by Djjus** [comment]
quite a small change..

**Comment by Robak132** [comment]
I got confused with this issue. I think the best solution would be 2 checkboxes, one for carried (it is practical to write sth that is temporarily not on you) and second for worn (sturdy boots, robes, clothing, ropes can be worn) like with containers.

**Comment by Robak132** [comment]
It would be also good if we can do weapon length integration (similarly to size integration) to automatically add -10 to attack with the shorter weapons.

**Comment by Robak132** [comment]
Additionally, I found a bug. If you roll 100 the label will say "Automatic Failure" only, but 100 is also Fumble because it's double 0 on dices

**Comment by Djjus** [comment]
- I have removed the Carried? for now, one thing i have noticed is player tend to list too much in Inventory. then suddenly say oh i have this and has been carrying it around for ages, but with no Enc. Should be fine, if you se no actual value in Enc its still has no weight.
- Auto Fail/Fumble at 100 should be addressed.
- Weapon reach, I have thought about it many time, it is too fiddly in my view, you would need to set it every time you attack. We did play test it, but didnt like it. At the moment it shows it in the roll output what reach you have, GM can then adjust as he see's fit.

**Comment by Djjus** [comment]
like maybe VsReach > / = /<

**Comment by Robak132** [comment]
Another bug: 'Worn?' option for containers is broken.

**Comment by Djjus** [comment]
No its intended to be on/off Enc. According to CRB Page 301, the Enc for containers is as shown, i suppose that means they are not modified.

**Comment by Djjus** [comment]
Containers are carried, not worn. i dont think i will change the page spelling, Worn fit in the space lol.

**Comment by Robak132** [comment]
Sling Bag and Backback can be worn. CRB 301.

**Comment by Robak132** [comment]
Hmm, your PR was merged but it seems like the changes didn't apply. Weird.

**Comment by Djjus** [comment]
Yes, its odd because the master seem updated, but they are not merging into live website. I think its our Double PRs, yours did not make the master. and then mine did not make the webpage. I will repost with yours included.

**Comment by Robak132** [comment]
Maybe we should merge our changes in one fork and then go with only one PR to Roll20:master.

**Comment by Djjus** [comment]
I think we will have too, let take our convo to Discord:
Justi#7934

**Comment by Djjus** [comment]
No never seen this issue. I suspect its our double PRs for some reasonGet Outlook for Android
