### ISSUE TITLE
CWOD-V20 Character sheet problems...

### ISSUE THREAD

**Issue by sonoftheright** [Roll20/roll20-character-sheets#1043]
It looks like Unicode characters placed directly in the CSS document aren't working anymore (I seem to have had some success in replacing them with escaped code sequences, but am not confident I know how Github works/those CSS files work well enough to post). There are a lot of other problems I'm not expert enough to track down, too. Suffice it to say, the sheet is really broken. Looks nothing like the preview on any browsers I use. 
![broken page](https://cloud.githubusercontent.com/assets/989262/9628129/e2af2714-5136-11e5-824f-aabfd60f00f4.JPG)

**Comment by SteveKoontz** [comment]
@sonoftheright I'm not seeing this behavior. It might be an issue local to you, or be a specific browser/OS issue.

**Comment by aquaalex** [comment]
@sonoftheright  I agree with @SteveKoontz  I use Google Chrome

Please check if it is settings in your browser or try a different browser and let us know. If all good pelase close the issue.
