### ISSUE TITLE
Fallout 2d20: Attribute+Skill button does not work for NPC sheets.

### ISSUE THREAD

**Issue by veratulmp** [Roll20/roll20-character-sheets#10510]
![image](https://user-images.githubusercontent.com/60524628/164996329-8ddd4c96-bebe-4b64-83fc-4720f7791e4b.png)

The custom attribute + skill button does not work if the sheet was created as an NPC sheet. This appears to be related to the character creation steps built in for Player Character sheets which calculates the Ranks (tag + points). If you build a character to start with as an NPC sheet, these rank values are never set.

![image](https://user-images.githubusercontent.com/60524628/164996634-01b9a638-e47d-4217-9d44-9963da47428f.png)

@coyotegrey

**Comment by coyotegrey** [comment]
Thanks for the detail! I'll take a look and add it to the sheet backlog.

**Comment by coyotegrey** [comment]
I have a fix ready for this one in the next build.

**Comment by coyotegrey** [comment]
#11886 has a fix for this issue.
