### ISSUE TITLE
[Cyberpunk Red Roll20] missing roll buttons

### ISSUE THREAD

**Issue by Tealk** [Roll20/roll20-character-sheets#10542]
The roll buttons are only visible in edit mode

![image](https://user-images.githubusercontent.com/12276250/167445057-e9871f73-d5d1-4432-a653-984bf4240ec7.png)

Edit Mode:
![image](https://user-images.githubusercontent.com/12276250/167445105-c9fd01c3-fee3-4a7b-9a92-0864f69504bf.png)

**Comment by nmbradley** [comment]
These are missing by design. They calculate Humanity Loss, and are only needed when the cyberware is first being entered.
