### ISSUE TITLE
[etoiles] directory missing

### ISSUE THREAD

**Issue by eblaise** [Roll20/roll20-character-sheets#10640]
Hi
I coded character sheets etoiles and last update was merged with success 
https://github.com/Roll20/roll20-character-sheets/pull/10475
Today the character sheet is not on the repository anymore. Someone can exply me why?

**Comment by nmbradley** [comment]
Hi. It is in the repository, it's right here: https://github.com/Roll20/roll20-character-sheets/tree/master/etoiles

**Comment by eblaise** [comment]
> Hi. It is in the repository, it's right here: https://github.com/Roll20/roll20-character-sheets/tree/master/etoiles

Thanks ! Why the character sheet is not available anymore when I want to create a game ?

**Comment by nmbradley** [comment]
![image](https://user-images.githubusercontent.com/7937613/176734934-6c6a0f52-ee60-4b39-ba33-976d4be62c18.png)

Sheet appears available. Closing.
