### ISSUE TITLE
CofD Derived Stats don't work on Firefox

### ISSUE THREAD

**Issue by Zharthalus** [Roll20/roll20-character-sheets#10707]
When using Firefox, the community CofD sheet does not have any derived statistics like Size, Speed, Defense or Initiative actually visible.

Tried to change game types, even editions in the settings. This problem is universal across every iteration of the character sheet for me, no add-ons were used to modify anything.

![firefox_16_06_2022-02_25_25](https://user-images.githubusercontent.com/107590854/173960280-10e48f0e-f8a6-4c2f-8682-827de41951b8.png)

**Comment by Zharthalus** [comment]
It's been a while since I've made this thread, so I've come back to draw some attention to this problem, since it is still present to this day.

Risky mention of the latest actually active sheet contributor: @AdolfoDomingues 

Is there anything that can be done to fix this? I've wanted to run a game for months using this sheet but I'm unwilling to give up Firefox for it, any help is genuinely appreciated.

**Comment by AdolfoDomingues** [comment]
I don't really know how to fix this issue. Maybe @PrimalZed knows?

**Comment by PrimalZed** [comment]
From what I can tell, it's not that they don't work, it's that the width is too narrow to display the number and the browser's number spinner arrows.

Should be able to have those removed with css styling rule `-moz-appearance: textfield;`.

I'm afraid I don't currently have a pro subscription to try out such a change to the sheet's css myself.

**Comment by Zharthalus** [comment]
Thank you both for your help, I hope this isn't too demanding, since I know the sheet is a community project, but I'd appreciate if this could be 'fixed' in the near future.

**Comment by Zharthalus** [comment]
@PrimalZed, my apologies for the continuation and the mention, but scheduling changes in my group have necessitated that I expedite my timetable for having this minor issue sorted. Since you've got a genuine grasp on the problem, I'm turning to you for help.

I have given your account (hopefully it's your account, 'Primal Zed' with the same profile picture), enough money to purchase a Pro subscription on Roll20, I hope this isn't far too imposing and impolite, but you are quite literally my only hope for getting this resolved.

**Comment by PrimalZed** [comment]
I got it thank you. I'll set up the change for this tonight.

**Comment by Zharthalus** [comment]
> I got it thank you. I'll set up the change for this tonight.

Thank you very much for your help, I think with that guarantee that I can mark this issue as closed.

**Comment by PrimalZed** [comment]
Normally would keep an issue open until the fix has been distributed.

I submitted a pull request for it. The Roll20 team generally goes through these pull requests on Mondays, and I think accepted changes get distributed on the Roll20 platform on Tuesdays.
