### ISSUE TITLE
Exalted: Third Edition character sheet issues

### ISSUE THREAD

**Issue by Alanith** [Roll20/roll20-character-sheets#1075]
The character sheet for exalted third edition does not seem to properly display certain aspects of itself. For example, the radio buttons do not appear at all, merely a black square that disappears when I click on it. Check boxes also appear to be nonfunctional, having a "?" appear in them when selected.

**Comment by Lithl** [comment]
I have basically redone the Ex3 sheet from scratch, which should address many if not all of the issues with the current sheet. I've just submitted PR #1598 for it.
