### ISSUE TITLE
[ACKS] New Character Sheet

### ISSUE THREAD

**Issue by omonubi** [Roll20/roll20-character-sheets#10769]
How does one get a new character sheet added to this repo? Note that the current ACKS sheet was uploaded 5 years ago and isn't being maintained.

**Comment by mcglincy** [comment]
tldr; submit a pull request to the github repo to add/edit the sheet code.

There are some wiki pages that talk about the process in more detail:
- https://wiki.roll20.net/Beginner%27s_Guide_to_GitHub
- https://wiki.roll20.net/Building_Character_Sheets#Minimum_Requirements
