### ISSUE TITLE
[Witcher TRPG] Alchemy Recipes Visual Issue

### ISSUE THREAD

**Issue by fireflyege** [Roll20/roll20-character-sheets#10805]
The Witcher TRPG sheet is having a line discrepancy. As you can see, the icon for the "Sol" reagent is in the upper line and its amount is in the lower line, making it really hard to understand and visually confusing too. It came after we got the tools and consumables section so it might not be intentionally made. I would like to request a fix to make them two balanced lines for easier clarity.

![Ekran görüntüsü 2022-07-17 150731](https://user-images.githubusercontent.com/109466223/179397951-308937aa-07c0-40f7-a471-1895184b16e1.png)

**Comment by Stexinator** [comment]
Fixed by #10803
