### ISSUE TITLE
SWN: Ship weapon range

### ISSUE THREAD

**Issue by kevinsearle** [Roll20/roll20-character-sheets#1084]
Add field for range

**Comment by kevinsearle** [comment]
@Berserker66 I'm not seeing anything in the core rules about weapon range, other than:

> starships have to
close in to mere tens of thousands of kilometers in order to give
their hardware any chance of connecting successfully

Do you know anything more about this?

**Comment by Berserker66** [comment]
Skyward Steel has a bunch of extra space combat rules. But to cover them all there'd be some major changes needed.

**Comment by kevinsearle** [comment]
The only reference I can see in Skyward Steel to weapon ranges are Sunshine Fields being only effective at Short Range and Brakers not being useful for short range. I'll avoid adding this since I can't find definitive RAW text or table data for it.
