### ISSUE TITLE
Shadowrun6e sheet wound modifiers should round up, not down

### ISSUE THREAD

**Issue by awilner** [Roll20/roll20-character-sheets#10857]
https://github.com/Roll20/roll20-character-sheets/blob/39124ca040a374f3c27a94cfb81b52f0bd631ece/Shadowrun%20Sixth%20World/Shadowrun6thEdition.html#L7420

This line and the next should use ceil() instead of floor(). The current behaviour causes the first 2 wound boxes not to inflict any dice pool penalties, then boxes 3 to 5 cause a -1 penalty, etc. - when it actually should be boxes 1-3 causing -1 penalty, 4-6 causing -2, etc.

**Comment by awilner** [comment]
I created https://github.com/Roll20/roll20-character-sheets/pull/10869 to fix this.

**Comment by jaculpiii** [comment]
This is patently incorrect, per the Core Rulebook: City Edition: Seattle page 38.  The change proposed and requested will break the sheet away from the rules as written.
`When a row of boxes on a monitor is filled, the character takes a –1 dice pool penalty to all tests except Damage Resistance. `
when a row of boxes on a monitor is filled means when all 3 boxes for that monitor are full not a portion thereof.

**Comment by awilner** [comment]
D'oh! My fault for not reading it properly. Sorry, I come from SR1 and 2, haven't played in a long time and was getting ready to get back at it.

**Comment by jaculpiii** [comment]
No worries, if you find other stuff that isn't as expected and you don't feel like trying to wade through 10000 lines of code feel free to drop me a line here or on Discord in the Shadowrun Missions Online or DWB RPG servers (Chuz#6906) and I'm happy to look into it.
