### ISSUE TITLE
SWN: Ship weapon magazine size

### ISSUE THREAD

**Issue by kevinsearle** [Roll20/roll20-character-sheets#1085]
Add field for magazine size

**Comment by kevinsearle** [comment]
This seems to already be covered by the Ammo field according to this:

> a number of rounds equal to the weapon’s Ammo rating can be fit into one free mass unit

and

> For each ship class larger than the minimum required to mount the weapon, double the stored ammo per unit

@Berserker66 have any thoughts on this?

**Comment by Berserker66** [comment]
I don't think those fields existed back in 2015.

**Comment by kevinsearle** [comment]
I think you're right. I'll close this one!
