### ISSUE TITLE
[Mutacao] line feed errors

### ISSUE THREAD

**Issue by MadCoder253** [Roll20/roll20-character-sheets#10874]
Hello, I just merged roll20-character-sheets using the github's website tool into my fork. However, there are 3 files that have invalid line feeds which is now causing issues because my local git repo is automatically converting to normal LF line feed. Now they are showing as modified fields. Please fix these files. I also noticed for some reason these files were uploaded, according to the notes, instead of using git. 

Mutacao\Mutacao.css
Mutacao\Mutacao.html
Mutacao\sheet.json

**Comment by vince-roll20** [comment]
+1

**Comment by vince-roll20** [comment]
pr to fix
https://github.com/Roll20/roll20-character-sheets/pull/10907

**Comment by nmbradley** [comment]
Merged and fixed
