### ISSUE TITLE
[Shadowrun 6 (GERMAN)] Hardly any contrast since last update in dark mode

### ISSUE THREAD

**Issue by Markus1204** [Roll20/roll20-character-sheets#10901]
The buttons for the actions as well as the damage monitors are in light gray font on a white background since the last update. You CAN see what is written there, but you have to look very closely.

**Comment by jaculpiii** [comment]
I noticed that myself the problem is with Roll20's darkmode changes as I have not touched the css for darkmode since it was introduced.   I'll take a look during the upcoming development cycle to see what can be done.   What specific elements are you finding the hardest to discern?

Thanks,
Chuz - Developer for the Shadowrun: Sixth World character sheet.

**Comment by Markus1204** [comment]
First and foremost, it's about the status monitors and the fields / buttons for the actions (main action, 1st / 2nd subplot, ...).

Everything else does not seem to be impacted by the latest Roll20 change. And yes... I know that you are not responsible for that as it is the same "bug" they had with the map picker... Although they reverted that, they forgot everything else impacted by this (Links in Handouts, Dropdowns etc.)...

**Comment by jaculpiii** [comment]
Oh, I'm sorry, I responded thinking you were referring to the "Shadowrun: Sixth World" sheet that I maintain, not the German version.  I'm not even sure who maintains that sheet at this time I'm afraid.  It looks like that sheet has not been touched for 16 months, though if it was stable then there would have been no need.

I wish I could help, good luck,
Chuz

**Comment by Markus1204** [comment]
The sheet itself works fine. It is just the "contrast" of those fields I cannot stand... those fields are really hard to use now... And all because of the recent Roll20 CSS Change... xD
