### ISSUE TITLE
Legend of the Five Rings Sheet issues.

### ISSUE THREAD

**Issue by Hawk-v3** [Roll20/roll20-character-sheets#1090]
It appears the hotlinked icons for the five ring stats have been moved, and they are now broken.

Also, the notes for the weapons and bows are all interlinked.

**Comment by AmishNinja** [comment]
Seems like it would be good to add icons to the repo since they're small enough. I'll see about adding this in.

**Comment by AmishNinja** [comment]
Add it up! https://github.com/Roll20/roll20-character-sheets/pull/1130
