### ISSUE TITLE
Palladium-Rifts is not an option in roll20

### ISSUE THREAD

**Issue by RonaldZ** [Roll20/roll20-character-sheets#1092]
May have something to do with #1009. Overhauled the sheet, then shortly after the pull request was accepted the sheet was no longer an option in roll20.

Best I can think of, is that the folder name of the sheet changed from "Palladium- Rifts" to "Palladium-Rifts"

If that is the case, my apologies. If not, can we get someone to look into what is going on?

**Comment by Rhallinan** [comment]
I replied on the forums but I'll go ahead and comment here too. I must have had a small issue on my merges last week and didn't notice it before I pushed the change to our main branch. Riley caught the issue and had to rollback the update which I believe caused the Rifts sheet to disappear as the website was looking for your updated sheet but couldn't find it. I have everything fixed on my end and am just waiting for it to go live.

**Comment by RonaldZ** [comment]
Thanks, looks like the sheet is live. Thanks for the speedy response.
