### ISSUE TITLE
Exalted 3e Sheet disappeared from roll20

### ISSUE THREAD

**Issue by Rats808** [Roll20/roll20-character-sheets#1093]
The Ex3 Sheet has disappeared from the list.
I'm guessing it might have something to do with a change made by #1086, but I'm not sure what the issue is.

**Comment by Rhallinan** [comment]
(As copied from the Rifts issue, ) I replied on the forums but I'll go ahead and comment here too. I must have had a small issue on my merges last week and didn't notice it before I pushed the change to our main branch. Riley caught the issue and had to rollback the update which I believe caused the Exalted 3e sheet to disappear as the website was looking for your updated sheet but couldn't find it. I have everything fixed on my end and am just waiting for it to go live.
