### ISSUE TITLE
 12 Sheets(73 files) with CRLF line endings were merged Monday...

### ISSUE THREAD

**Issue by vince-roll20** [Roll20/roll20-character-sheets#10967]
Sorry, I don't mean to be obnoxious, but can't we find a solution for this? (pr to fix #10966)
 Maybe this suggestion from a recent roll20 Discord discussion?;
> Looks like there is a github action, that could be triggered on PR to the repo and block PR with CRLF line ending: https://github.com/marketplace/actions/check-crlf
That way github could block the merge of PR with CRLF line ending
But that must be setup by the Roll20 folks, editing top-level files and all

**Comment by Kurohyou** [comment]
Seconding this!

**Comment by Stexinator** [comment]
I am thinking about stopping to support all my sheets because of this. It introduces so much unnecessary work which could be avoided by configuration...
