### ISSUE TITLE
5e Community Contributed Skills Broken

### ISSUE THREAD

**Issue by Kurohyou** [Roll20/roll20-character-sheets#10975]
Commit a1c0b9f by @JasperEX appears to have broken the skills rolls (and potentially other rolls as well).

[Relevant forum post](https://app.roll20.net/forum/post/11057711/5e-community-contributed-sheet-problem)

**Comment by JasperEX** [comment]
Oh no! I'll fix it tonight.

**Comment by betttris13** [comment]
Looks like the cantrips are also broken. It appends a two to the start of the damage macro. We are working around by adding a -2+[[roll]] for now.

There is also some broken text for spell saves.

**Comment by JasperEX** [comment]
I'll do a full check when I get back to my computer.

**Comment by JasperEX** [comment]
I've fixed the skills (#10977) Turns out the Cantrip thing was poorly explained feature. The Dmg Scale checkbox adds the appropriate number of damage dice for cantrip damage, if checked. A note has been added to explain the feature.

**Comment by JasperEX** [comment]
I pushed a few more commits on the same pull request that address the broken text on spelll saves, as well as a fix for the added weapon slots.
