### ISSUE TITLE
[Ironsworn] Better management of changelog

### ISSUE THREAD

**Issue by idispatch75** [Roll20/roll20-character-sheets#10997]
Having the full changelog popping up for each new sheet is a bit annoying, and I'm not convinced people are that interested this info.
It could just be displayed in the Settings page.

**Comment by aureyia** [comment]
I would argue you might only wanna put important changes in the log, as there are times when we did a large migration it was important to show it to notify players. The worry is if you bury it in settings nobody will never see those. It might be worth seeing if there is some way to not get it to trigger on sheet creation.

**Comment by idispatch75** [comment]
OK.
Maybe on sheet:opened we can detect that the sheet is new (the type of sheet is not set yet for instance) and set the changelog as read in this case.
