### ISSUE TITLE
[Star Trek Adventures by Roll20] Issues with official STA sheet

### ISSUE THREAD

**Issue by ShowMeBillyJo** [Roll20/roll20-character-sheets#11042]
There are a couple of small but annoying bugs in **v 1.5** of the official [Star Trek Adventures by Roll20](https://github.com/Roll20/roll20-character-sheets/tree/master/Star%20Trek%20Adventures%20by%20Roll20) sheet.

* ~~When setting the number of challenge dice to roll in the Dice Roller section, the user must remove focus from the input field (tab or click outside) _before_ clicking the roll button.~~ (apparently intended)
* The Arc Milestones field is read-only (user can't change), defaulted to `0`, and never auto-calculated.
* When updating Security on a player character sheet, weapon damage rolls aren't updated. Individual weapon damage stats must be updated to a different value, tabbed out, then reverted to original value ~~, and finally tabbed out again before rolling (same bug as Dice Roller section)~~. Not tested on ship sheet.
* When maximum Stress is reduced due to reduction in Fitness or Security, current Stress should be reduced to the new max if above (nice to have).

I have a bucketful of other items, but they're clearly in the vein of enhancement requests.

I'll be happy to split this into multiple issues should it be requested.

**Comment by ShowMeBillyJo** [comment]
I'm also offering my aid in contributing to these issues further through code research and/or development. A similar request was accommodated in #6188 ([official/migrated repo](https://github.com/Roll20/roll20-character-sheets/tree/master/Chronicles%20of%20Darkness%20by%20Roll20), [community repo](https://github.com/Roll20/roll20-character-sheets/tree/master/Chronicles%20of%20Darkness)). To be clear, though, I don't want to maintain my own truly separate version of the sheet independent of the official version, but I'd like to contribute changes that can be pulled upstream _into_ the official version. I get that there may be some security concerns or other hurdles to overcome in that regard. I'm happy to chat further with anybody who can help me out!

**Comment by Lockbox313** [comment]
"When setting the number of challenge dice to roll in the Dice Roller section, the user must remove focus from the input field (tab or click outside) before clicking the roll button."

There is no way around this. The underlying firebase database is only updated when focus is lost.  The button code that is run when the button is pressed pulls data from the firebase database.  Sheet authors have zero control over this.

**Comment by ShowMeBillyJo** [comment]
Bump. I'm not sure who to ping to bring attention to this, but I'm still willing to contribute.

**Comment by ShowMeBillyJo** [comment]
Closing given the recent update to the sheet by the R20 team
