### ISSUE TITLE
Warhammer fantasy 4e sheet Xp issue (WFRP4e)

### ISSUE THREAD

**Issue by zblahz** [Roll20/roll20-character-sheets#11173]
Hello love the sheet. been using it for my players for almost a year now. we ran into a problem where Toughness characteristic is adding exp back to the player. other players say other characteristics have the problem but i have not been able to recreate that. if you can please fix it the villager class of the group will forever be grateful, thank you!

**Comment by Djjus** [comment]
Hi, i guessing you mean my unofficial "Warhammer 4e Character Sheet". Then i'm aware of this. 

And it should be fixed in the upcoming PR #11174 proably on Monday now.

What happens is its reflecting the last selection, rather the current one.

**Comment by zblahz** [comment]
yep thats what i meant and thank you!
