### ISSUE TITLE
[Shadowrun 5e] Roll results output as plain text

### ISSUE THREAD

**Issue by Demid65** [Roll20/roll20-character-sheets#11395]
Few days ago character sheet started outputting roll results not as plain text, but not as decorated boxes.
![изображение](https://user-images.githubusercontent.com/49491468/213868501-0ea00f71-c014-4d3b-93f7-8184cfac288a.png)

**Comment by Stexinator** [comment]
https://github.com/Roll20/roll20-character-sheets/pull/11388

**Comment by Tzigamm** [comment]
Yep, spent 30 or so minutes testing before I felt that was good enough, I now know it definitely wasn't! I'm working on an even bigger change and I've learned my lesson, I'll set it as a custom sheet on my game so we can do a full run to beta test it *before* pushing it.

TL;DR: I'm a living proof engineers need QA testers

**Comment by Stexinator** [comment]
@Tzigamm what do you want to do?

**Comment by Tzigamm** [comment]
@Stexinator I'm currently switching the old tab system to the new way of doing things, that way when multiple people are accessing the same sheet (say a player and the DM) they'll be able to see different tabs (currently changing tabs changes it for everyone)

Once that's done I'll try to fix the few bugs I've seen, how npc sheets don't hide magic/resonance settings fields for instance, or how the PC sheet some things on two lines when 1 would be enough (like the ammo counter or the armor special resistances)

I'd also want to only show the Living Persona tab to emerged characters, same with the complex form panel and the the magic tab.

Maybe a drug tab would be nice? Somewhere where you can setup your drugs and then enable/disable them

Having a way to actually print the effect of a spell would be nice, especially for spells that don't deal damage

Maybe having a way to hide the augs tab? If you don't have any that seems a bit useless to have it constantly displayed

Pre-filling skills with the correct attribute and limit would be a nice QoL feature

Having a way to pre-fill spirits and sprites would be nice too, probably through the charactomancer (I'll see if there's a way to do it without) but I need to check SR5's license to check we can do that, I know Chummer5a does it and they seem to be fine but might as well be sure.

If anyone has any feature request I'd be happy to consider it too

**Comment by Demid65** [comment]
@Tzigamm

1. AI character support would be good.
2. There is a bug in the sheet, that ASDF rolls are never whispering to gm (even if whispering is enabled).
3. Languages automatically set up for Charisma attribute, but it probably should be Intuition.
4. Overhaul of Chummer importer would be REALLY appreciated. 
5. Settings tab is off to the side (see picture)

Regarding tab changes, I think it would be best to make hiding tabs an option, so that users could enable or disable them (settings tab?) 
Interactive drug tab would be good for some characters, but I doubt it would be doable. 
Printing effects of the spell is present in DnD 5e sheet, maybe do something similar?
 
I might help with testing, as I host games quite often. And maybe with coding, but don't expect much.
If you'd like to take on chummer importer, please contact me, I'll try to help as much as possible.

Oh, and please, keep the current version of the sheet available, maybe as Shadowrun 5e Legacy sheet. QoL changes might not be appreciated by everyone.

![изображение](https://user-images.githubusercontent.com/49491468/214834706-ac15ff41-3a4e-48f0-88db-5fee44c3fcec.png)

**Comment by Demid65** [comment]
Indeed, let's have this issue closed.

**Comment by Stexinator** [comment]
What is your reasoning to using this sheet instead of the Shadowrun 5th Advanced? Funneling efforts into one sheet might be better

**Comment by Demid65** [comment]
@Stexinator 
As for me, this sheet is a lot more user-friendly than Advanced one.
Yeah, Advanced might be a bit better in terms of automation, but in design terms it is an eyesore excel sheet.
Can't say that about non-advanced one.

**Comment by Stexinator** [comment]
Oh yeah, I would for an UX-Designer to look at the sheet

**Comment by Demid65** [comment]
It might be a good idea to merge Advanced sheet into non-Advanced one. Keep the best design and internals we have.
