### ISSUE TITLE
[Yellow King] Sheet translation don't appears on Crowdin

### ISSUE THREAD

**Issue by RodrigoBigg** [Roll20/roll20-character-sheets#11456]
I updated the HTML with the data-i18n tag, created translation.json and made the pull request, but the sheet does not appear in Crowdin to be translated.

**Comment by nmbradley** [comment]
We had a service provider failure on character sheet translations. This should have now been resolved by #11469

Could you double check that this is now resolved?

**Comment by RodrigoBigg** [comment]
OK, is revolved!
