### ISSUE TITLE
Whisper ability for Traveller character sheet

### ISSUE THREAD

**Issue by Choltan49** [Roll20/roll20-character-sheets#11505]
Why doesn't the Traveller character sheet have the ability for the Referee to Whisper die rolls like can be done in the Roll20 official D&D character sheet? This would be extremely useful for a referee who doesn't want to publicly roll all die rolls in his Traveller game. Having to type in chat using /w is cumbersome at best. Please add this functionality to the Traveller character sheet.

**Comment by AdmiralFatcat** [comment]
It is the Mongoose Traveller 2022 Updated version that I'm using for the game.

**Comment by brookesi** [comment]
Have added a whisper checkbox and pushed to GitHub, also rolltemplate dark mode support, pull request in flight 👍

**Comment by brookesi** [comment]
Whisper toggle and dark mode changes should now be on the live sheet
