### ISSUE TITLE
[Roll20 Shadowrun 5e Character Sheet] "Import button has not been pressed yet." Issue according to sheet

### ISSUE THREAD

**Issue by ThePlagueDoctor** [Roll20/roll20-character-sheets#11526]
Trying to import a character and according to the boxes for character data to be (and not to be) updated "Import button has not been pressed yet." This appears after pressing the Import button which is confusing. The Results even say that a valid JSON was pasted. This has been tried with both the nightly and milestone builds, but nothing seems to work.

JSON link: https://pastebin.com/iekyBDYz

Can provide more information if required.

**Comment by Stexinator** [comment]
Can you add a screenshot?

**Comment by Stexinator** [comment]
@ThePlagueDoctor is the issue resolved?

**Comment by Stexinator** [comment]
@nmbradley no response - please close this issue
