### ISSUE TITLE
[DoubleCross 3rd Character Sheet] Merged character sheets are not retrieved from the site.

### ISSUE THREAD

**Issue by tateck-develop** [Roll20/roll20-character-sheets#11580]
https://github.com/Roll20/roll20-character-sheets/pull/11572

This is the character sheet that was merged yesterday,
but the character sheet is not retrieved when creating a game in Rolll20. Is it not applied yet?

It is announced to take effect approximately 10 minutes after merging. I write because I was told to write an issue if it does not apply after a day.
I hope you can play the game with this sheet as soon as possible.

**Comment by rotorri** [comment]
안녕하세요! 현재 해당 시트 Roll20에서 사용가능한 것 같습니다 리얼서버 배포에 지연이 있었나봐요! :)

**Comment by nmbradley** [comment]
This all seems resolved now, as @rotorri  said. I'll mark as closed.
