### ISSUE TITLE
Shadowrun 5th Edition (Advanced): Vehicles-Tab > Tests "Clearsight" > Roll a Perception Test

### ISSUE THREAD

**Issue by 3D-vice** [Roll20/roll20-character-sheets#11608]
The following issue occurs when being in "Jumped-in", "Remote", and "Manual" mode:

When rolling a Perception/EW Test on the Vehicle/Drone section (Clearsight-Button), the Perception/ElectronicWarfare (EW) Skill is calculated incorrectly. It seems that the values for Perception and Electronic Warfare are both added to the total value.

In my example (see screenshots):
Intuition (6) 6
Perception (6) 3+3
Electronic warfare (4) 4+0

Perception/EW Test with Vehicle (10) 3+3,4+0

When rolling a Perception/EW Test with a Vehicle/Drone, the roll should include EITHER Perception, OR Electronic Warfare. Since a Vehicle/Drone-based Perception Test can be made using "Perception" or "EW", this would requide an additional pop-up window asking which skill should be used for the roll (similar to the pop-up-window when choosing between Speed and Handling when rolling a Driving Test).

![Shadowrun 5th Edition (Advanced) BugReport PerceptionTest](https://user-images.githubusercontent.com/82933178/226196986-14fe3f52-482c-4191-952e-cca1330ee293.jpg)

**Comment by Stexinator** [comment]
This is most likely a display issue. It keeps the highest of the two pools. Can you check the total amount of dice? Thanks

**Comment by 3D-vice** [comment]
You are right, it is a display issue. The total amount of dice is correct: In my example, it takes the value of the Perception Skill, since it is the highest of the two pools. I've double-ckecked and raised EW to 8 in my example: The system then takes the value of the EW Skill, instead of Perception.

So it just displays "Perception plus EW", but uses the appropriate higher value of the appropriate single skill.

**Comment by Stexinator** [comment]
I cannot modify the display value. This is completly in the hands of roll20. So you can close it
