### ISSUE TITLE
Goblin Quest and Worlds Without Number: Incorrect Line Endings

### ISSUE THREAD

**Issue by vince-roll20** [Roll20/roll20-character-sheets#11649]
[Goblin Quest](https://github.com/Roll20/roll20-character-sheets/tree/f9a2525f4d31787a29939df4b72610354a1bd4fe/goblin%20quest)
[Worlds Without Number](https://github.com/Roll20/roll20-character-sheets/tree/ac1b3c728c1ae5bfef1ac67a3ff49638120f4360/WWN)
CRLF is fine locally(windows), but line endings should be LF on the repo.

![image](https://user-images.githubusercontent.com/10321187/227984156-8bed9c32-b7c7-4e63-9e9f-f90fd59498fe.png)

**Comment by nmbradley** [comment]
Fixed by #11650
