### ISSUE TITLE
Earthdawn line ending issues

### ISSUE THREAD

**Issue by vince-roll20** [Roll20/roll20-character-sheets#11653]
.css file
https://github.com/Roll20/roll20-character-sheets/pull/11643/files

pr  #11655 submitted

![image](https://user-images.githubusercontent.com/10321187/228122391-a486d78d-ef3e-44fc-bee8-14f290544779.png)

**Comment by vince-roll20** [comment]
Maybe we need to add another line to the sheet PR checklist...
ie
[ ] Files have appropriate line endings.

**Comment by Stexinator** [comment]
https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings Per-repository settings would set it for all users of the repository

**Comment by nmbradley** [comment]
https://github.com/Roll20/roll20-character-sheets/blob/master/.gitattributes

This has been set for a while, but it doesn't seem to stop the line endings issues. My hypothesis is that folks haven't updated their own forks for some time and have copies without this file.

**Comment by nmbradley** [comment]
I've temporarily added a workflow to check line endings (#11662). It's currently very naive, checking every file every time a PR is made, because I couldn't quickly find a way to pipe two workflows together. If it turns out that it is disproportionately expensive, I will have to remove it again.
