### ISSUE TITLE
[Shadowrun 5th Edition (Advanced)] Technomancer Complex Forms are not working properly

### ISSUE THREAD

**Issue by Dragonmoy** [Roll20/roll20-character-sheets#11674]
Every time you would roll for a complex form, regardless of changes to bonuses, skills, and levels, the complex forms will only roll with a software skill of two [2], ignoring any in-sheet bonuses, and setting the fading value to a flat Fade = [Level] + 0, regardless of whatever changes done. Situational bonuses still change the amount of dice rolled, but anything else is ignored.

**Comment by Stexinator** [comment]
While I found an error in the formula I cannot reproduce your errors.
I publish the fix to the formula and then you can try again. If the issue persists I need your values for everything software related, resonance and an example complex form

**Comment by Stexinator** [comment]
https://github.com/Roll20/roll20-character-sheets/pull/11676

**Comment by Stexinator** [comment]
@Dragonmoy the fix is live

**Comment by Stexinator** [comment]
@nmbradley due to no further feedback: this can be closed
