### ISSUE TITLE
[Reclaim the Wild] Sheet unadapted to the system

### ISSUE THREAD

**Issue by MeixDev** [Roll20/roll20-character-sheets#11682]
Hi !

Admin for the Reclaim the Wild community here. We got a few people complaining about the Sheet for Reclaim the Wild on Roll20 not working + being in French, though we didn't even know we had one that was approved.

As it turns out, someone created a simplified sheet for their own game, and made it French since it's the language they're using themselves (see https://github.com/Roll20/roll20-character-sheets/pull/10305). It's fine by itself, but the approved.yaml file does contain the mention of "Reclaim the Wild Unofficial" on lines 4421 and 4422 ; being misleading towards players who would be interested in trying the system on Roll20. 

https://github.com/Roll20/roll20-character-sheets/blob/43bbc7e998c143a8ffb3bcc160b4c87e0b6ae7ac/approved.yaml#L4421
https://github.com/Roll20/roll20-character-sheets/blob/43bbc7e998c143a8ffb3bcc160b4c87e0b6ae7ac/approved.yaml#L4422

We did have a working sheet at some point that players were using that I could maybe open a Pull Request for. In the meantime, is it possible to make it so this sheet doesn't come up when looking for Reclaim the Wild ?

Thanks a lot !

**Comment by TheOnlyPhos** [comment]
@roll20deploy please see this request

**Comment by nmbradley** [comment]
Apologies for the slow response, for future reference, roll20deploy is a bot account and has not yet reached a full enough level of sentience to respond to pings :)

I've removed the sheet.
