### ISSUE TITLE
[Neon City Overdrive] Edit Button not working

### ISSUE THREAD

**Issue by keloide** [Roll20/roll20-character-sheets#11716]
The edit button to unlock the sheet is invisible while using mozilla, while it's visible if using google chrome, unlocking in chrome unlocks the editing in mozilla too.

**Comment by nmbradley** [comment]
@micka9fr I do not know if you are still maintaining this sheet, but if so, here is a bug report.

**Comment by micka9fr** [comment]
Hi sorry, for not responding quickly. I m going to see what wrong with this button a fix it.
