### ISSUE TITLE
[Liminal] Dark-mode labels are too light on character sheet

### ISSUE THREAD

**Issue by scoltman** [Roll20/roll20-character-sheets#11730]
When viewing a character sheet with dark mode enabled, the field label colors are too light.

I believe this is because it is missing a style override.

![image](https://user-images.githubusercontent.com/195347/232730860-e811f9da-0cc6-4a54-8bd1-03bfc550d4d1.png)

**Comment by SavageSpiel** [comment]
I've updated the CSS to sort out these labels. Colours should be consistent now.
