### ISSUE TITLE
[Blood and Gold] New Sheet Code not active on roll20.net

### ISSUE THREAD

**Issue by Rnedlose** [Roll20/roll20-character-sheets#11734]
PR was merged almost 29 hours ago, and still not reflected on roll20.net for my game character sheet Blood and Gold.

**Comment by vince-roll20** [comment]
Looks like it's up.
![image](https://user-images.githubusercontent.com/10321187/233479110-0fed58e0-a561-426b-8ec6-8ac400d7cd82.png)

**Comment by nmbradley** [comment]
I have forced an update on the sheet, just to make sure. @Rnedlose let me know if this is still not working.

**Comment by Rnedlose** [comment]
Thanks Nic.  That worked.  I appreciate it.

Rodney Nedlose
