### ISSUE TITLE
[GURPS] Character Sheet Rename

### ISSUE THREAD

**Issue by MadCoder253** [Roll20/roll20-character-sheets#11895]
Hi, how can I have the GURPS character sheet be renamed from **GURPS** to **GURPS 4E** on the create new campaign drop-down menu?

![gurps-4e](https://github.com/Roll20/roll20-character-sheets/assets/9192404/9142e2d3-3473-441f-91be-0537f69409e3)

Also, in the image, there's a Character Sheet named **Conspiracy X** that is listed under **gurps**. This character sheet has nothing to do with GURPS, can it be moved to somewhere else?

thanks,

**Comment by MadCoder253** [comment]
@nmbradley We noticed this file. `approved.yaml`

Can we just make the following changes to fix the name and Conspiracy X?

```
conspiracyx:
- ConspiracyX
- Conspiracy X
- Unisystem
gurps:
- GURPS
- GURPS 4E
- GURPS
```

**Comment by nmbradley** [comment]
@MadCoder253 These changes were made a couple of weeks ago at a helpdesk request. Is it not working?

**Comment by MadCoder253** [comment]
Thanks @nmbradley !!! The email told me to create a ticket on here. It's been updated!
