### ISSUE TITLE
[Rogue Trader Improved] Hit roll

### ISSUE THREAD

**Issue by ne2ox** [Roll20/roll20-character-sheets#11942]
I'm not 100% sure, but I think there is a bug in the update of the sheet when calculating hit rolls.

The calculation was "(45+(0+10)+(0)+(20-67))++10)/10" which would give me 1.8, but the sheet says 0.

![Bug Roughe Trader](https://github.com/Roll20/roll20-character-sheets/assets/12926187/d629c8a0-1cfa-4928-950c-e65223a13a09)

Other than that, thanks for the great work

**Comment by Robak132** [comment]
You probably submitted "+10" modifier instead of "10" and calculation broke because now there are two "+" side by side.

**Comment by ne2ox** [comment]
Thank you for the quick reply
