### ISSUE TITLE
[Ars Magica 5th] Sheet broken after release on Roll20

### ISSUE THREAD

**Issue by Riernar** [Roll20/roll20-character-sheets#11951]
### Description

After release on the Roll20 website, the Ars Magica 5th sheet appears broken: fonts are not loaded in rolltemplate, causing the browser to use some kind of default.
In some setup, including my own, this is problematic as the fallback font is not legible:

#### Expected rolltemplate
![rolltemplate_expected](https://github.com/Roll20/roll20-character-sheets/assets/29373041/3a8cc3da-94a8-4327-826b-c5a6b4eafe0d)

#### Actual rolltemplate
![rolltemplate_actual](https://github.com/Roll20/roll20-character-sheets/assets/29373041/9e8e71fc-bedb-4436-a773-3fdff3fd6d54)

There is no problem when setting a game to `Custom` sheet and pasting the HTML, CSS and translation JSON from this repository master branch, so I believe the problem comes from the release process.

### Step to reproduce
Broken game using the released sheet:
1. Start a new Roll20 game, or use an existing one
2. Set the sheet to "Ars Magica 5th"
3. In the character sheet, click to the "Abilities" tab. Create a new, dummy ability on the right repeating section, and click the dice symbol to roll it
4. See that the chat result uses some default font, that varies from OS+browser combination to another (the `leverage` part is the easiest)

Functional game using a custom sheet with the same sources:
1. Start a new Roll20 game or use an existing one
2. Set the sheet to "Custom"
3. In the game settings, copy-paste the HTML, CSS and translation JSON found in the `Ars_Magica_5th/` folder in this repo
4. Repeat the step 3 and 4 from the first listing, see the rolltemplate works properly

### Additional context
I'm a maintainer of the Ars Magica 5th, and I couldn't reproduce the bug in either a custom sheet game or the Sheet Sandbox. Being unable to reproduce, I have no idea how to fix it.

**Comment by nmbradley** [comment]
Hi @Riernar 

If I was going to make a guess, I would presume that the CSS validator on the VTT is rejecting, for some reason, your CSS font imports. For obscure, arcane, and frankly silly reasons, the Custom Sheet option in campaigns, and the sheet sandbox uses a slightly more permissive CSS validator in contrast with what is piped from github, through the microservice, and delivered to the VTT. 

Things I would suggest: 

- Altering your font imports to use a single import.
- Ensuring no fonts are being sourced from anywhere other than google fonts.
- Ensuring that you're using the old google fonts reference methods.
- Removing any comments or extraneous code from your css file.
- Running your compiled CSS through a validator to ensure that nothing might be causing the error.

**Comment by nmbradley** [comment]
I will also note that often, but not always, CSS validation errors are thrown in the VTT, so I'd check your dev console when the sheet is loaded.

**Comment by Riernar** [comment]
Hi Nic,

Thanks for the tips. I already checked the  dev console, and found no error. Though I just found the `<style>` element that contains rolltemplate's CSS and indeed only the first `@import` is there. I'll investigate further to see what is causing the other two to be removed.

**Comment by Riernar** [comment]
Sadly #11954 didn't fix it. If someone would be so kind as to re-open this issue (for some reasons I can't), that would be great for tracking.

As far as I can tell,

- [x] Ensuring no fonts are being sourced from anywhere other than google fonts.
- [x] Ensuring that you're using the old google fonts reference methods.
- Altering your font imports to use a single import.
  Not possible with the kScaffold framework, but Scott C, the creator, never had issues due to that.
- [ ] Removing any comments or extraneous code from your css file.
- [ ] Running your compiled CSS through a validator to ensure that nothing might be causing the error.

I'm starting to think the `Material+Symbol+Outline` family contains a forbidden string, and cause its own line and the next line to be sanitized out.

**Comment by Anduh** [comment]
Isn't the issue here that there can only be one font import statement? https://wiki.roll20.net/Character_Sheet_Development/CSS#Google_Fonts

**Comment by Riernar** [comment]
That is indeed the case, and the K-Scaffold framework I used injected it's own import before mine, hence the problem.
I fixed that by re-ordering stuff and forgot to close this issue, sorry about the noise
