### ISSUE TITLE
[Ars Magica 5e] Virtue and Flaw categories not saving

### ISSUE THREAD

**Issue by Medieve** [Roll20/roll20-character-sheets#11956]
An odd issue that feels relatively new. 

For Virtues and Flaws in the repeating fields, the drop-down selection to make them (Free, Minor, Major) acts like they are pulling from bad data. Closing and reopening the sheet sets them back to Free. I tested other input fields and drop-downs in the Abilities sections but those seem to be saving fine. 

Checking the HTML it's a fairly simple section so not sure what kinda issue this might be.

**Comment by Medieve** [comment]
@Riernar

**Comment by Riernar** [comment]
Hi @Medieve , thank for the pin.

I'll have look ASAP. Do you get the issue on multiple characters, or only a specific one?

**Comment by Riernar** [comment]
take

**Comment by Riernar** [comment]
I can reproduce in the sandbox, looking at the underlying attribute changing the value of the select doesn't update the attribute
I haven't found out why yet

**Comment by Riernar** [comment]
After investigating, this is because both the `repeating_virtue` and `repeating_flaw` repeating sections use the same name `VirtueType` for saving the type. They interfere with each other.

IIRC this used to be perfectly safe, I wonder if there was any change on the Roll20 side
