### ISSUE TITLE
[PortesMonstresTresors] Background image replaced by a huge icon

### ISSUE THREAD

**Issue by Zharkol** [Roll20/roll20-character-sheets#11979]
Hello,

There seems to be a problem with the background image of the character sheet for Portes, Monstres & Trésors.

Instead of the normal background image, there is a huge icon that makes the text of the sheet very difficult to read. 

Here are two screen captures :
![PMT_ROLL20_b](https://github.com/Roll20/roll20-character-sheets/assets/138759054/3c690433-8595-41fc-b8d9-83cedae7cd98)

![PMT_ROLL20_a](https://github.com/Roll20/roll20-character-sheets/assets/138759054/a9130c2d-61ce-402a-a6c6-fdaa4a95bf15)

**Comment by vince-roll20** [comment]
I would send Natha(sheet author) a DM
https://app.roll20.net/users/75857/natha
The background image should be copied to the roll20 repo. and the css url updated to point to it.

**Comment by vince-roll20** [comment]
If you do not not get a reply from Natha, just post back and I'll at least link up a similar background image already on github.  There are many sheets that use something similar.

**Comment by vince-roll20** [comment]
I've submitted a fix. Natha is welcome to update/change as well.
https://github.com/Roll20/roll20-character-sheets/pull/11996
