### ISSUE TITLE
[DCC] Saves, Weapon Attacks, and other buttons missing modifiers

### ISSUE THREAD

**Issue by DBendit** [Roll20/roll20-character-sheets#12132]
![image](https://github.com/Roll20/roll20-character-sheets/assets/242696/894fd73d-f30c-425b-b147-824edd7f7ba7)

I'm assuming this is the source of the problem: https://github.com/Roll20/roll20-character-sheets/commit/8a5f241345ce5a387c3ddf3337b781140fc897ab

Buttons for the various saves and weapon attacks are missing the total modifier value and the values are missing from the "Attributes & Abilities" tab.  Clicking those buttons rolls the saves, but no modifiers are included (shows `Rolling 1d20+ = (18)`). It's as if setting those fields `readonly` removed them from various Roll20 sheet functionality.

**Comment by DBendit** [comment]
Pinging @sturtus , since it's their commit :)

**Comment by DBendit** [comment]
Manually setting `(WILL|REF|FORT)Check` causes the buttons to populate as expected.

**Comment by sturtus** [comment]
I don't have a Pro account anymore so I can't really test. Insane that Roll20 makes us pay to contribute to their product.

**Comment by DBendit** [comment]
I'm in the same boat 🤣 The most I can recommend is rolling back the change, which will at least take it back to a known more-functional state.

**Comment by sturtus** [comment]
I had a friend with Plus. Was able to test/fix and submitted a new PR.

**Comment by DBendit** [comment]
https://github.com/Roll20/roll20-character-sheets/pull/12133

**Comment by sturtus** [comment]
This got merged in and looks good to me.

**Comment by DBendit** [comment]
Confirmed, looks like the issue's resolved. Thanks!
