### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by Ulthark** [Roll20/roll20-character-sheets#12342]
Hi guys,

my group and me are suffering from the german translations,  i.e. english "Feats"as "Heldentaten", that is Heroic acts, the correct Translation for "Feats" is "Talente".

That is just one of the countless Translation errors.

P.S. Fixed the errors and switched them with the official D&D 3.5 Terms.

**Comment by akibi90** [comment]
I modified the translation. It will be available soon.
