### ISSUE TITLE
Portuguese translation Mage V20

### ISSUE THREAD

**Issue by haoasakura12** [Roll20/roll20-character-sheets#12436]
Dear, the file pt.json inside the translation folder in CWOD-M20 is the English version. Can I translate the sheet and submit as a new "code"? 

I'm a native (Brazilian) Portuguese speaker that wants to introduce my friends in the storyteller system through Mage and Demons games but they don't speak English. So it's hard to use the sheet now (English) in the Roll20.. 

I can also translate the demon the fallen sheet...

**Comment by BronsonHall** [comment]
Hey @haoasakura12 

   Sorry for the late reply! Translations to community sheets are always greatly appreciated.  However, we don't accept translations directly through this repo anymore - instead, you can translate these sheets through Crowdin!  
   [This article](https://help.roll20.net/hc/en-us/articles/20495433257623-How-to-Contribute-to-RPG-Character-Sheet-Translations-on-Roll20) should walk you through the process to add translations, but don't hesitate to reach out if you have any further questions!

**Comment by haoasakura12** [comment]
I finally could translate it from Crowdin. 
There are other World of Darkness sheets I want to translate, but I didn't find them on the website (CWOD-Mage, CWOD-Demon, and CWOD-Changeling). These folders are here on Github, but I couldn't find them there. Could someone help me?

**Comment by BronsonHall** [comment]
Hey @haoasakura12 

Those games are missing translation support on sheet-side.  For a sheet to be translatable, it needs `data-i18n` attributes on its labels/other elements in html, and a `translation.json` file in the main sheet folder.  [This wiki page](https://wiki.roll20.net/Character_Sheet_Translation) explains the process in further detail!  Once the translation.json file is there with only english translations, the sheet will appear on Crowdin, and autogenerate the "two-letter" translation files in its "translations" folder that you saw in CWOD-M20.  From there, you can take the same steps with that sheet to add Portuguese translations.  

To clarify, this initial setup - the translation.json and data-i18n attributes - can be submitted as a PR to this repo!  It's just the two-letter translation files that we don't handle here, and leave to Crowdin.

Please don't hesitate to reach out with any further questions about this process!  Sorry it's a few extra hoops to jump through, but we don't make translation support a requirement of new sheets, so many are added without - and need the little extra setup to get onto Crowdin with proper keys.

**Comment by haoasakura12** [comment]
Thank you for your support. 


Hum... I'll read the Wiki you sent me. 
I think.. Is there a problem if I use the current HTML file in the folders as a base for changing it to the data-i18n format?

**Comment by BronsonHall** [comment]
Hey @haoasakura12 

That's exactly the right idea - you'll want to start with that HTML file, then start adding data-i18n attributes to each label or bit of static text you want to be translatable., and submit it together with the translation.json as an update to that sheet folder.

To test sheets you're editing on Roll20 properly, you'll want to use either the [Custom Sheet Sandbox](https://wiki.roll20.net/Custom_Sheet_Sandbox) (this one's much nicer to use) or [Custom Sheet Editor](https://wiki.roll20.net/Sheet_Editor) to load your sheets in progress on the VTT and see if they work as expected.  These features are limited to Pro accounts, however.

**Comment by haoasakura12** [comment]
Ok
Thank you again!
