### ISSUE TITLE
Help! My local GIT keeps changing Skyfall/imgs/logo.png for some reason

### ISSUE THREAD

**Issue by MadCoder253** [Roll20/roll20-character-sheets#12622]
For some reason, when I pulled master to my local repo, GIT is changing the file Skyfall/imgs/logo.png but I can't tell what it's doing or why it's doing that. Any ideas? I can do a hard reset because GIT just changes the file again.

Here's a screenshot from GitHub Desktop

![image](https://github.com/Roll20/roll20-character-sheets/assets/9192404/d3559ea0-2b1e-4508-902a-0fe940dbb171)

**Comment by MadCoder253** [comment]
@NorWhal Sorry, not sure who else to add. I figured out the cause. Windows doesn't support having two files with different cases. In the report there's `logo.png` and this one with capital L, `Logo.png`. That is why it's showing as updated. Is it possible to please have someone delete one of the files?

**Comment by nmbradley** [comment]
Fixed by #12623 

You may need to `git reset --hard origin/master` on your master branch

**Comment by MadCoder253** [comment]
@nmbradley Yay!!! It worked.
