### ISSUE TITLE
Vaesen RPG character sheets

### ISSUE THREAD

**Issue by Noarfang** [Roll20/roll20-character-sheets#12668]
Hello,

I noticed a problem in the Vaesen RPG character sheet. In the "Vaesen" part of the sheet, there is a problem in the macro for the attacks. An error message appears in the chat instead of the dice roll when i click on the attacks.
I sent a report to Roll20 that redirected me here to make an issue.
Is it possible for someone to correct this ?

I made an screenshot of the problem and of what appears in the chat.
<img width="1308" alt="Capture d’écran 2024-03-02 à 12 27 48" src="https://github.com/Roll20/roll20-character-sheets/assets/162047044/20303657-3a94-47e5-82c7-0f9207c46327">

Thanks in advance for the answer !

**Comment by Noarfang** [comment]
@Velczer hello, i am sorry to disturb you ^^', but i thought maybe you could help as you worked on this sheet.
I tried as you suggested : to send a ticket on the Roll20/help. but they didn't help. 
Really sorry for the disturbance

**Comment by Velczer** [comment]
Hello, I will try to look into it and fix it.
Thank you.

**Comment by Noarfang** [comment]
Thank you !!
Tonight is my first try mastering this game and your sheet is really helping !

**Comment by dwarfwing** [comment]
This was fixed in PR [12702](https://github.com/Roll20/roll20-character-sheets/pull/12702), Perhaps close this Issue, @Noarfang @Velczer @NorWhal ?
