### ISSUE TITLE
Files for Medievo Oscuro have wrong line endings

### ISSUE THREAD

**Issue by Triqueon** [Roll20/roll20-character-sheets#12744]
As stated in the title, the Files for Medievo Oscuro seem to have CRLF line endings instead of the usual LF. This is extremely annoying, as my git is configured to automatically replace those, which results in those files being marked as changed although I'm working on something entirely different...

**Comment by MadCoder253** [comment]
FYI What I've done in the past is make a pull request for that character sheet to fix the line endings, seems to be the fastest response.

**Comment by vince-roll20** [comment]
Incorrect line endings have been a major pain in the past... 
but it seems to have at least diminished recently. Until now that is.  ;P

**Comment by VJRolmasters** [comment]
Hi 
Trying to solve that in the next pull request for fix some bugs of the sheet, I will change the CRLF endings to LF.
Thanks for the advice.
