### ISSUE TITLE
Missing Sheet Contribution - The Unofficial Hollow Knight RPG

### ISSUE THREAD

**Issue by Ccmaci** [Roll20/roll20-character-sheets#12841]
Last month, my Github sheet submission for The Unofficial Hollow Knight RPG was accepted and pushed to the public Roll20 page. Today I found out that the sheet is no longer publicly available. However, the sheet's code is still in the Github sheet repository. Not sure what happened, I received no emails indicating a takedown. Please re-instate the character sheet if possible! The Github repository folder is called "Hollow_Knight_Unofficial_TTRPG".

**Comment by BronsonHall** [comment]
Hey @Ccmaci 

This should be fixed for this sheet as of last week - we had a change in our sheet approval process that inadvertently marked some new sheets as hidden on release.  The sheet is showing up for me again, and I'm closing this issue, but let me know if you spot any further problems - thanks for your patience!
