### ISSUE TITLE
Dark Heresy 2nd Edition = Degrees of Success

### ISSUE THREAD

**Issue by Mistwolf** [Roll20/roll20-character-sheets#1288]
Degrees of Success are calculated based on the Dark Heresy 1st edition rules and not based on the Dark Heresy 2nd edition rules.

**Comment by CoalPoweredPuppet** [comment]
Yes, and I commented on the sheet's thread.

**Comment by CoalPoweredPuppet** [comment]
Submitted a pull request with the fix: https://github.com/Roll20/roll20-character-sheets/pull/1289
