### ISSUE TITLE
ChroniquesOubliees: Roll20 displays documentation instead of sheet.

### ISSUE THREAD

**Issue by Ulty** [Roll20/roll20-character-sheets#12949]
Although the sheet.json specifies co.html as the sheet file, Roll20 displays doc.html as the file.

**Comment by thibautrety** [comment]
Hello, 
We are many users to be annoyed by this issue. Would you please give us some visibility on when a fix will be deployed on roll20 ?

Thank you very much!

Kind regards

**Comment by Ulty** [comment]
It seems that commit 1bdedd8 fixed the issue with the html file used for the sheet. 

But the rest of the sheet.json file is still not correctly read: the preview displayed is `logo_ta.png` instead of the specified `co_v4.jpg`, and the useroptions just don't show anymore, so we cannot change them. In addition, in existing games, it seems that these options are just ignored or reset. This is part of the sheet functionnality, so I hope this get solved soon too.

**Comment by Ulty** [comment]
Issue was fixed with commits ce1703c44ee7ea3e25a700c37d861e8b9aafbf76 and 793067de8d30ae7c025c38fc3b04b5d426865c07. Thanks!
