### ISSUE TITLE
Character sheet is not displaying correctly on any browser

### ISSUE THREAD

**Issue by MarieWessels** [Roll20/roll20-character-sheets#12951]
This might be associated with https://github.com/Roll20/roll20-character-sheets/issues/12949 
The sheets are essentially unusable at the moment. 

![image](https://github.com/Roll20/roll20-character-sheets/assets/35840963/5abea560-9502-486f-be6a-dbde815e390f)

**Comment by roguetradermago** [comment]
Hello marie, im the RTI sheet author, the roll20 bug fix did not solve the issues
I submitted a PR to update the sheet to CSE, so it no longer uses the legacy sanitation

**Comment by MarieWessels** [comment]
> Hello marie, im the RTI sheet author, the roll20 bug fix did not solve the issues I submitted a PR to update the sheet to CSE, so it no longer uses the legacy sanitation

Thanks Mago! Displays correctly now. Glad you could fix it.
