### ISSUE TITLE
[Stars_Without_Number_Revised] Merged Changes not in sheet after 24h

### ISSUE THREAD

**Issue by trevor-coleman** [Roll20/roll20-character-sheets#13087]
My [PR adding Adventurer Subclasses](https://github.com/Roll20/roll20-character-sheets/pull/13077) which was merged yesterday, but doesn't seem to be live on the site.

Not sure if this is a normal delay or not, but the README says to open an issue, so here I am!

Apologies if I'm being annoying in any way typical of people making their first contribution. 😅

**Comment by NorWhal** [comment]
Hi @trevor-coleman - you're not being annoying at all, thanks for raising this to our attention!
We're looking into this now. In the future, please feel free to open an issue after an hour if you don't see your changes.

**Comment by NorWhal** [comment]
Hey @trevor-coleman!
Sorry for not spotting this in the initial PR, but it appears you made changes to the pug files without building them into HTML! From what I can tell in your sheet's package.json folder, all you should have to do is enter `npm run build` into your terminal at after navigating to the sheet's directory, and the updated HTML should build from what you've got.
Once that's done, you can make a new PR and we'll merge it through!

**Comment by trevor-coleman** [comment]
Ahhhh sorry -- I'm used to that being done in CI/CD. I've been spoiled! 😂

I'll rebuild and push when I get back to a computer. Thanks!

**Comment by trevor-coleman** [comment]
PR with the rebuilt HTML: https://github.com/Roll20/roll20-character-sheets/pull/13103
