### ISSUE TITLE
[ProjectMoonTRPG + Other sheets] Sheets not updating

### ISSUE THREAD

**Issue by BeautiDemise** [Roll20/roll20-character-sheets#13395]
It doesn't appear that changes made during the last sheet update are being applied to campaigns for some character sheets

I've looked through a few sheets to check and can confirm that both the [Project Moon TRPG Sheet](https://github.com/Roll20/roll20-character-sheets/pull/13379/commits) and [Rolemaster Unified Official Sheet](https://github.com/Roll20/roll20-character-sheets/pull/13382) are affected. No sheet.json, HTML or JavaScript changes from either pull request are appearing in campaigns

Other sheets look to have updated correctly, such as the [Mongoose Traveller 2e Sheet](https://github.com/Roll20/roll20-character-sheets/pull/13384)

**Comment by NorWhal** [comment]
@BeautiDemise 
We've think this is resolved; the new PRs for both sheets named here and those appear to have built correctly and persisted to our site. Can you confirm for us that the changes you expect from both PRs on Project Moon are appearing?

**Comment by BeautiDemise** [comment]
@NorWhal I can indeed confirm that all changes have gone though!

**Comment by NorWhal** [comment]
Great! Closing the issue :)
