### ISSUE TITLE
Mage: The Ascension 20th Anniversary Edition (cWoD)

### ISSUE THREAD

**Issue by mantonyz** [Roll20/roll20-character-sheets#1354]
Ascension is spelled incorrectly in the pull-down menu on the "Campaign Settings" page.  It has not a "t" in it.

**Comment by smalone11** [comment]
For a typo on the Campaign Settings page that would be something to bring up on the [Bug Reports & Technical Issues](https://app.roll20.net/forum/category/18) section of the forums. We can't fix that here unfortunately, but I made a post on the forums for you. You can follow it [here](https://app.roll20.net/forum/post/2990361/typo-on-character-sheet-templates) if you want.

**Comment by mantonyz** [comment]
Thanks Stephen

**Comment by aquaalex** [comment]
can we close this issue please
