### ISSUE TITLE
Fate core with roll and Fate core with roll French

### ISSUE THREAD

**Issue by sioc-de-narf** [Roll20/roll20-character-sheets#1390]
hello,

my 2 character sheets : Fate core with roll and Fate core with roll French are no longer available.

Why are they gone ?

**Comment by pjbehr87** [comment]
![screen shot 2016-02-11 at 11 24 25 am](https://cloud.githubusercontent.com/assets/4982464/12985947/2961117c-d0b2-11e5-95b3-b87cf37e1611.png)
![screen shot 2016-02-11 at 11 24 03 am](https://cloud.githubusercontent.com/assets/4982464/12985950/2b7117a0-d0b2-11e5-9e11-1855b84dea51.png)

You mean these?

**Comment by sioc-de-narf** [comment]
yes, i don't find them in github

**Comment by pjbehr87** [comment]
https://github.com/Roll20/roll20-character-sheets/tree/master/fate_core_with_rolls
https://github.com/Roll20/roll20-character-sheets/tree/master/fate_core_with_rolls_VF

Github sorts all uppercase before all lowercase, so they were near the bottom of the list. When in doubt check the approved.yaml file, where it links the folder location to the name displayed on the list.

**Comment by sioc-de-narf** [comment]
thanks
