### ISSUE TITLE
Blades in the Dark: Friend/rival text boxes don't stay distinct

### ISSUE THREAD

**Issue by brocktopus** [Roll20/roll20-character-sheets#1486]
Currently, if you type in details in the text fields under "Shady Friends," the two default boxes--ostensibly one for a friend and one for a rival--will echo the other, so if you type in something for box A, that same detail will then appear in box B. If you were to change the content of box B, it would impact box A as well.

The current workaround seems to be to use an additional checkbox+text field combo, but this is not necessarily an intuitive solution to the problem.

I'm not certain if making more use of <code>fieldset class="repeating_friend"</code> (e.g., "_friend1" "_friend2" etc.) around the default boxes would help in this regard, but I can't immediately think of another possible answer.

**Comment by brocktopus** [comment]
Ok, I'm 99% sure it's due to a repeated field name:

`<input` type="text" **name="attr_friend_info"** class="sheet-friend-info">

under both "attr_friend1"/"attr_rival1" **AND** "attr_friend2"/"attr_rival2"

**Comment by Silvyre** [comment]
FYI @smalone11 another user has reported the same issue in this thread: https://app.roll20.net/forum/post/3113426/blades-in-the-dark-error-in-deadly-friends-fields

**Comment by smalone11** [comment]
Oh geez. I totally missed this. I'll look into fixing it.

**Comment by smalone11** [comment]
Alright. It was an easy fix. I noticed the same problem with the Harm boxes so that will be fixed as well.

**Comment by brocktopus** [comment]
This looks resolved to me--I can reproduce the desired results now with a BitD character sheet in-game.
