### ISSUE TITLE
[FIX MERGED] [WFRP-2nd-Ed] Broken Characteristics Rolls

### ISSUE THREAD

**Issue by Silvyre** [Roll20/roll20-character-sheets#1518]
@Wrathborn 
@timothystone 

https://app.roll20.net/forum/post/3133323/wfrp-bug-warhammer-fantasy-role-play-sheet

The issue appears to be that it is not possible to /roll within an emote.

**Comment by Silvyre** [comment]
https://app.roll20.net/forum/post/3144850/warhammer-2nd-edition-rpg-main-profile-problem

**Comment by timothystone** [comment]
Submitted pull request to address the issue. Unsure of reason for loss. However, @Wrathborn 's commit did significantly reformat the sheet. Some entity encoding was lost and this broke the buttons inline macros. I've restored the entity encoding and formatting.

**Comment by timothystone** [comment]
Pull Request #1530 in queue. Assign and close.

**Comment by timothystone** [comment]
@Silvyre you can assign this to me if you like. That way I can mark it closed when it is merged to master.

**Comment by timothystone** [comment]
@Silvyre you can close this. Merge to master is complete.

**Comment by timothystone** [comment]
Reopen. Validation in production failed. Checked the repo, the code is there, but the merge seems to have purged it. Looking for another solution.

**Comment by pjbehr87** [comment]
It's merged, it not live yet

**Comment by timothystone** [comment]
@pjbehr87 thanks!

**Comment by pjbehr87** [comment]
We don't like to make server pushes in the afternoon while the site is the most busy, it will most likely happen tomorrow morning sometime. Look for it at least after mid-day tomorrow to be sure.

**Comment by timothystone** [comment]
I've validated in production. #1530 looks fixed.

**Comment by timothystone** [comment]
Please Close @Silvyre
