### ISSUE TITLE
WFRP 2e Character Sheet Title

### ISSUE THREAD

**Issue by timothystone** [Roll20/roll20-character-sheets#1537]
Update the `approved.yaml` with the edition key.

**Comment by timothystone** [comment]
Attaching a patch.

**Comment by timothystone** [comment]
[patch-issue1537.diff.zip](https://github.com/Roll20/roll20-character-sheets/files/191914/patch-issue1537.diff.zip)

**Comment by pjbehr87** [comment]
I agree, and the other WFRP games don't follow the same naming convention. I'm going to go ahead and standardize them all as well.

**Comment by aquaalex** [comment]
if this is fixed can we close the issue?

**Comment by timothystone** [comment]
yes. I'll close.
