### ISSUE TITLE
Mekton Z Sheet buttons not displaying correctly

### ISSUE THREAD

**Issue by Meduna** [Roll20/roll20-character-sheets#1541]
I can see by the screen shot that at the top of the sheet there should be buttons that read Character, Skills, Gear, Mecha Combat, All, etc.

However when I load this sheet in game it has unnamed radio bubbles instead. It appears to still be functional, but I was hoping someone might be able to fix whatever is causing this issue.

![example](https://cloud.githubusercontent.com/assets/14899272/14096986/c597329a-f521-11e5-8eee-e4d4a927254f.PNG)

**Comment by CoalPoweredPuppet** [comment]
The sheet was built for Chrome, and it looks like you are using Firefox.

Whiel there are ways to fix this, I do not have the time for a couple of weeks.

**Comment by Meduna** [comment]
I appreciate the reply in any case. While it would be great if it could be fixed, knowing that I can use Chrome is still helpful. Thank you!

________________________________
