### ISSUE TITLE
Black Crusade Request for Unnatural Attributes.

### ISSUE THREAD

**Issue by phantam23** [Roll20/roll20-character-sheets#1580]
Not too sure if this is the best place to request changes to the sheets but if a section could be added for unnatural attributes that would be nice, especially given how easy it is for a Black Crusade character to get them.

**Comment by clevett** [comment]
Hello,

I'm working on closing the old Issues on GitHub. This may be best to added to the Character Sheets forum as a request, https://app.roll20.net/forum/category/277980 . If it continues to be an issue please let me know.

Thanks,

Cassie
