### ISSUE TITLE
More open character sheets editor

### ISSUE THREAD

**Issue by guumaster** [Roll20/roll20-character-sheets#1584]
I really like Roll20 platform. So much that I'm willing to collaborate with this open source project to include more sheets and translate them to my language (spanish). 

But I'm not sure why the character sheets editor is a PRO feature only. You could only use the sheets editor only if you pay? Is it possible to create a small project or simulator or some kind of mock so people with a free accounts and a basic html/css knowledge can also contribute in a better way? How many of the subscription base are creating content? How many know JavaScript/HTML? 

I've recently contributed with a small and simple translation, but after reading the docs, I know that I could do a much better work. But it is really cumbersome without a way to test it before submission. Please open it for more collaboration.

**Comment by tarantegui** [comment]
+1

**Comment by elvis-pereira** [comment]
Yeah +1 for this

I also wold love to contribute with some sheets and translations, but without a way to test it before sending... Well it discourages the work. Come on roll20, you already have it implemented, only make available a place to test the sheets before submitting it, you may continue with the actual system of custom sheets only for PRO accounts, it does not need to change.

**Comment by bitspersecond** [comment]
+1 for me as well guys...   except this isn't the place to make this suggestion.  If you have any votes left (I do not) you might try voting for this suggestion: https://app.roll20.net/forum/post/2445509/custom-sheets-should-be-a-base-feature

**Comment by Berserker66** [comment]
The problem with the suggestion voting is that this would affect so few people directly that it won't get voted up.
Indirectly it may well affect almost every user, but they don't even understand the significance of it.

**Comment by clevett** [comment]
Hello,

I'm working to close outstanding issues on Github. This should be moved to the forums over on the [suggestion board,](https://app.roll20.net/forum/category/385189). The suggestions there are monitored and consider for implementation. 

Thanks,

Cassie
