### ISSUE TITLE
SWN: a few quality of life improvements

### ISSUE THREAD

**Issue by Berserker66** [Roll20/roll20-character-sheets#1701]
Some things I'd really like to see added to the Stars Without Number sheet:
A field for permanent system strain, which prevents the system strain field to go below this number. (Pg. 45 core book)

Encumbrance current and max calculated  and displayed (Pg. 32 core book)
readied items current and max calculated and displayed (Pg. 32 core book)

Move the weapon area to the top of the gear section or make it a seperate one above the gear section.
Reason: In combat you'll often switch between rolling skills, rolling weapon and adjusting ammo clip, as it is a lot of scrolling is required.
In a perfect world there'd be a combat tab with health, system strain, weapons, gear, skills; in that order, that allows all combat related stuff in one view.

I'd do it myself, but it looks like I'd need to pay for the privilege of developing it, which I'll nope out of, tyvm.

**Comment by kevinsearle** [comment]
I'll look at this (unless someone else does before I get to it)

**Comment by Berserker66** [comment]
That'd be great!

**Comment by kevinsearle** [comment]
@Berserker66 Would you be available to test the System Strain changes?

**Comment by kevinsearle** [comment]
Got these done except moving the weapon area. This was moved to issue #2339

**Comment by kevinsearle** [comment]
@Berserker66 or @pjbehr87 - this issue should be closed.
