### ISSUE TITLE
4e version 2.0 character sheet

### ISSUE THREAD

**Issue by jcheraz** [Roll20/roll20-character-sheets#1750]
My group is having an issue where certain parts of the character sheet "lose" data, especially when the DM moves our tokens from one page to another.

For example, all of our character sheets lost the **Bloodied** value, **Surge Value**, and any values in the **Ability** column of **Defenses** (even though the Setup tab > Setup > Defenses is correctly selected for each character). Sometimes the Icons selected for the character go missing, as well, although this is not as frequent.

In the attached example pictures, I've included the relevant Stats tab and Settings tab for the same character. You can see that the Bloodied and Surge Value fields have "0" instead of the proper values in them, an the Ability column similarly has "0" instead of the proper values. In the other example picture, the settings for that character show that the player has selected the proper values for the Ability column for Defenses, but it is not using those values. (That character is using Heavy armor, so selected None for AC.)

![example 4e v2](https://cloud.githubusercontent.com/assets/20342946/16662751/56239912-444f-11e6-93fc-1f627618e382.PNG)

![example 4e v2 settings](https://cloud.githubusercontent.com/assets/20342946/16662755/5bb38072-444f-11e6-9c08-f9adff72b75a.PNG)

**Comment by clevett** [comment]
Hello,

I'm working to close old issues in the GitHub. Do you know if this is still an issue? Let me know if I can help.

Thanks,
Cassie

**Comment by jcheraz** [comment]
The last time we used the sheet it was still a problem. However, we closed down our 4e game and have moved entirely to 5e now (partly because this issue was so annoying, I'm sad to say). That would be mid to late 2017. I'm not sure if it still is a problem. 

Sorry, I can't be more of a help.

**Comment by clevett** [comment]
This has been helpful! I appreciate the update. I'll add this to my list for further investigation. 

Thank you,
Cassie

**Comment by olivier-grech** [comment]
I could not reproduce the issue. Maybe tag this as "Could not reproduce"?
