### ISSUE TITLE
[Conan 2d20] Issues with inline rolls

### ISSUE THREAD

**Issue by Silvyre** [Roll20/roll20-character-sheets#1788]
Line 220: ?{Dice|2}d20sa<@{Stealth_Focus} should be ?{Dice|2}d20sa**cs**<@{Stealth_Focus}

**Comment by Silvyre** [comment]
Another issue, present at least on lines 218-220: cf20<[[...]] should probably be cf<[[...]]

**Comment by suntzu777** [comment]
there are a few bugs in the current sheet , working on an update and extra functions for NPC's and magic

**Comment by Silvyre** [comment]
Sounds good!

**Comment by suntzu777** [comment]
just submitted a new pull request
