### ISSUE TITLE
Issue with Unnatural abilities as well as Dark Eldar 

### ISSUE THREAD

**Issue by RMcD94** [Roll20/roll20-character-sheets#1840]
You can get unnatural in a lot of places but there's no place to add it to the sheet such that it is counted for the rolls. 

Dark Eldar do not start with Low Gothic but you have it on the sheet anyway. There's also no place to record pain tokens. There aren't separate columns for quantity and weight in the inventory (so for example amount of doses, etc), nor weight/quantity under acquisitions so you have to write the same stuff twice.

As posted here: https://app.roll20.net/forum/post/3806050/rt-question-regarding-rogue-trader-character-sheet-and-unnatural-agility/?pageforid=3806050#post-3806050

**Comment by clevett** [comment]
Hello,

I'm working to close out old issues on the GitHub. Do you know if this is still an issue? If so it may be best posted to the forum again as a request to have the sheet updated. Please let me know if this is still on going.

Thanks,
Cassie

**Comment by clevett** [comment]
Hello,

Since I've not heard back and this is a really old issue this ticket will be closed. If you need it opened again just let me know.

Thanks,
Cassie
