### ISSUE TITLE
Translation overwrite

### ISSUE THREAD

**Issue by Alzam01** [Roll20/roll20-character-sheets#1883]
Hello,

I'm doing the french translation for the shaped character sheet, and just noticed that my translation of "ARMOR_CLASS" (armure) was automatically reverted back to "Classe d'armure" (bbace459abd8bb9699074741e3159012a23e65a3).
While I agree that this is the correct translation, it doesn't fit into the sheet.

I guess this is because "ARMOR_CLASS" is already translated in your database. Is it possible for me to "lock" that translation so it can't be changed ?

Thanks

**Comment by pjbehr87** [comment]
I might have forgotten to upload the updated translation before committing the changes. You can make the change again and I'll be sure not to miss this step this time.

**Comment by Alzam01** [comment]
Thanks for the answer :)
