### ISSUE TITLE
Moldvay: Monster multiple monster attack die

### ISSUE THREAD

**Issue by kevinsearle** [Roll20/roll20-character-sheets#1897]
Allow monsters to do XdX damage per attack. Currently they can only do 1dX.

**Comment by RhOmicron** [comment]
I'll see if I can add something for this, if you're still active. And seeing as how Moldvay got added a year ago I assume it's not really active.

Ill try to fix #1898 as well.

**Comment by RhOmicron** [comment]
I was looking into the character sheet, is that used as well for monsters?

I assume the game is D&D Moldvay (Natha)

**Comment by kevinsearle** [comment]
It is Moldvay and there is a Monster tab for the sheet, which this issue is referring to. The original author is @amandasearle. I'm not sure if she's working on these issues or not.

**Comment by RhOmicron** [comment]
Seems David Bendit updated it on the 6th of December.

**Comment by RhOmicron** [comment]
I'll see if I can make a pull request for the things you need.

**Comment by RhOmicron** [comment]
Are the saves from the player sheet enough for the monster ones? Or are they different.

**Comment by kevinsearle** [comment]
However you want to do it as long as saves with a roll button are available on the Monster tab.

**Comment by amandasearle** [comment]
I actually have this all in and working locally for some time.  I will do the request.

**Comment by RhOmicron** [comment]
Aight, seems I don't have to fix things.  Got the monster dice to be XdX. And was working on saving throws.

**Comment by amandasearle** [comment]
For some reason, I thought I had checked in all the fixes, but I guess I got distracted along the way :)

**Comment by RhOmicron** [comment]
I pretty much dirty hack (as long as it looks good) in new elements in html anyway. As I don't really know html coding. Trial and error.
