### ISSUE TITLE
Call of cthulhu 7ed (When I hit dice roll they do 3 1d100 roll) BUG ?

### ISSUE THREAD

**Issue by Marc1533** [Roll20/roll20-character-sheets#1922]
Whenever I hit the roll next to a stats or skill. It automaticaly roll 3time 1d100 ??? I only want one roll not 3

**Comment by NathaTerrien** [comment]
This is not a bug. The sheet template has to roll several d100 to handle the different cases. There's no other way in Roll20, without using the API. I suggest that you deactivate the 3D dice with this sheet.

**Comment by aquaalex** [comment]
I fixed this as it is a bug
There is one roll that needs to be compared to the normal, 1/2 or 1/5 result
But then there is also the option where you need to roll 2 sets of 10's and 1 set of 1's and this I am busy writing worker script for

**Comment by aquaalex** [comment]
Bonus dice and penalty dice are not trifling small additions or subtractions of a few percentage points, and so should not be used without good cause. If a factor is so small that it would only modify a roll by a few percentage points then don’t bother with it. Driving in light rain should not inflict a penalty die, but torrential rain so thick that you can barely see, even with the wipers on full speed—now there’s your penalty!

**Comment by aquaalex** [comment]
Roll an additional "tens" percentage die alongside the usual pair of percentage dice when making a skill roll. You are now rolling three separate dice: one "units" die and two "tens" dice. If you have a bonus die, you should use the "tens" die that yields the better (lower) result. For a penalty, use the "tens" die that yields the worse (highest) result.

**Comment by aquaalex** [comment]
So this is not the same as rolling 3 sets of D100 dice.

**Comment by aquaalex** [comment]
Old Template:
[Image](http://prnt.sc/eu4gyd)

New Template:
[Image](http://prnt.sc/eu4g4b)

**Comment by aquaalex** [comment]
Sheet has been updated with 1 roll. please close this issue

**Comment by aquaalex** [comment]
I have added 2 roll buttons.
1 for the complex roll template and 1 for the simple roll template
