### ISSUE TITLE
Godbound: HP Miscalculation

### ISSUE THREAD

**Issue by ChosenCyan** [Roll20/roll20-character-sheets#2017]
Current implementation for calculating HP from constitution modifier located in 'Godbound.html' is incorrect:

`"8 + 4*(@{adj_level}) + ceiling((@{adj_level}) * (@{con_mod}) / 2)"`
Yields improper increase in HP via constitution modifier for odd numbered levels.

Suggested fix should appropriately calculate per level HP increase with respect to constitution modifier:
`"8 + (@{con_mod}) + (@{adj_level})*(4 + ceiling((@{con_mod}) / 2))"`

**Comment by Anduh** [comment]
Did anyone follow up on this? This guy https://github.com/Roll20/roll20-character-sheets/issues/3017 also found it.

**Comment by Anduh** [comment]
This sheet got a complete remake a month ago, so shouldn't be possible that this would still be an issue. https://github.com/Roll20/roll20-character-sheets/pull/3854

**Comment by Almos80** [comment]
This issue can be closed since the redesign has changed this calculation.
