### ISSUE TITLE
Open Legend RPG Basic: Calculations and Formatting

### ISSUE THREAD

**Issue by raihje** [Roll20/roll20-character-sheets#2019]
How the defenses are calculated has changed, attacks now largely face Evasion.
The small arrows for raising/lowering defense contributors are jumbled, and text on buttons is jumbled as well.
When one clicks the "manage" button for Actions, you can delete but not move them around.

**Comment by BuildAndDie** [comment]
Lots of fixes and updates have been waiting for 6+ days (about when you posted this) to merge, should fix these issues.

**Comment by BuildAndDie** [comment]
Seems there is known issue with Mozilla/Firefox that isn't registering to take away the "spinners" (arrow up and down buttons). Also seems to be cutting off text slightly (is this what you meant by jumbled?). Will try and issue a fix. Works fine with webkit browsers (such as chrome).

Can not duplicate the "manage" button you are mentioning. Able to reorder without issues (in latest version not yet merged).

**Comment by BuildAndDie** [comment]
Issued the fixes for Mozilla Firefox, soon as the merge goes through, all these issues should be resolved.

**Comment by BuildAndDie** [comment]
Everything should be fixed with Mozilla. For repeating fields, the "+Add" and "Modify" button text is squeezed together, however in the version on github is up-to-date with a fix on that issue. Just have to wait for a merge and then for it to trickle down to the website.

**Comment by BuildAndDie** [comment]
This is no longer an issue, if it could be closed?
