### ISSUE TITLE
Pathfinder Simple

### ISSUE THREAD

**Issue by Cazra** [Roll20/roll20-character-sheets#2065]
Autocalculations for skills are not updating properly sometimes.

**Comment by Cazra** [comment]
False alarm... The values eventually updated. My group must have just hit a bad spike of character sheet server lag.

**Comment by HansHauge** [comment]
Yep, same thing here. I came here to report that last week we could not get our stat sheets to properly calculate attack bonuses in the "attacks" section. Today, I went back to try to figure out what's going on and it's working fine. I guess there was just some server connection issues that are not happening at the moment.
