### ISSUE TITLE
Dark Heresy 2e: Unnatural Characteristics

### ISSUE THREAD

**Issue by blogg10** [Roll20/roll20-character-sheets#2142]
There doesn't seem to be any support to add Unnatural Characteristics as part of the base sheet. These are somewhat important since character bonuses are used to automatically calculate certain things like soak and weapon damage, and not being to add unnatural characteristics means having to manually add damage to all weapons, and also adding extra toughness soak as 'armour' which is both annoying and incorrect per the rules (as armour can be penetrated, while toughness soak cannot).

**Comment by RandomnessUK** [comment]
Hi blogg, 

If you look at the Only War sheets they include unnatural characteristics. I'll share the code with the dh2 sheet author.

**Comment by RhOmicron** [comment]
If the sheet author gets back to you I guess he'll work it out. In the mean time though, I'll see if I can fix this as well as the characteristic rolls not working properly (issue #2147 ).

**Comment by RandomnessUK** [comment]
@RhOmicron 

I've uploaded a recent updated DH2e sheet, are you aware of any ongoing issues with the new version?

**Comment by RhOmicron** [comment]
I don't actually play dark heresy, I am but interested in finding out/reading up on the rules and fixing sheets . Making them more streamlined.

**Comment by messiahcide** [comment]
This issue should be closed

**Comment by Craftomega** [comment]
This issue has been resolved.
