### ISSUE TITLE
[L5R] Insufficient slots for Macro-Skills for some Schools

### ISSUE THREAD

**Issue by kbernges** [Roll20/roll20-character-sheets#2229]
For example, the Kakita Artisan, which may have possibly three Artisan or three Perform Skills, the Kaiu Engineer, which has two Craft Skills, and any school which has both a Macro skill and any of the Any <category> choices that could include the relevant Macro Skill. There is also the possibility an individual may wish to spend xp on other macro skills that brings them up above the space on the sheet.

An optimal solution would be a button to add additional lines for each macro skill, though implementation might be complicated given the effect skill ranks have on Insight, and thus a way to tally up the Skill Ranks in all macro skills created by such a button would be needed. At the very least expansion of the Macro Skills that presently only have one slot to three would at least cover the cases of Schools that presently cannot even put their starting skills all on the sheet.

**Comment by RhOmicron** [comment]
Is this the sub-type field? Or how does this work?

**Comment by kbernges** [comment]
You see how Lore works on the sheet, where there's three separate slots? Macro-skills groupings skills that are different skills yet operate mechanically identically. Sort of "skill buckets" of similar-functioning skills. Artisan, Perform, Lore, and Craft are examples. You might have 2 ranks in Artisan: Poetry, and simultaneously 3 ranks in Artisan: Sculpture. Or similarly two ranks in Craft: Bowyer while also having six ranks in Craft Weaponsmith. They are different skills that fall into the same category.

Lore got 3 slots, the others got 1. Probably to cover the Asako Loremaster that, unlike the other two that this Issue is intended to address, which are in supplements. The sheet only has one slot for those other ones, but as mentioned in the initial Issue posting, there are Schools (the term for character class essentially in this system) that start with multiple skills in the other macro-skill categories.

Thanks for the prompt response to all the issues I've posted, by the way. These are things that have bothered me for a long time with these sheets, but I didn't know there was a Git repo for them until the other day.

**Comment by RhOmicron** [comment]
Right, I think I got it. I'll add a button to add more skills. 

The trouble I see now is the Insight bonus. Which I've posted in the approriate thread.

**Comment by RhOmicron** [comment]
Would only the high skills and merchants skills need a 'add more skills' field?

**Comment by kbernges** [comment]
Actually it's only specific ones that have any use for it; most skills are not macro skills. The macro skills include:
Artisan
Games
Lore
Perform
Weapons
Craft

All other skills are not relevant to this issue.

**Comment by RhOmicron** [comment]
Which of the weapons would be needed? All things under Bugei Skills?

**Comment by kbernges** [comment]
...Huh, never noticed that before. There is a skill specifically called Weapons that is another macro-skill. It doesn't get much use as it's a catch-all skill for any weapon that might not be covered by the rules as written.

It's not on the sheet at all presently.

**Comment by RhOmicron** [comment]
Which skill would be linked to it?

**Comment by kbernges** [comment]
It's probably one of those ones where it's wise to have an Agility/Reflexes drop-down, since Agility is generally the weapon skill attribute for melee and Reflexes for ranged.

**Comment by RhOmicron** [comment]
Ill just add another field to merchant skills and everything should be done.

**Comment by kbernges** [comment]
For Craft, I assume? Thanks for your hard work.

**Comment by RhOmicron** [comment]
Aye.

**Comment by RhOmicron** [comment]
I guess the weapon one wouldnt have to be repeatable? Or are you able to have it more than once?

**Comment by kbernges** [comment]
It's like the other Macro-Skills, but it's a lot less critical for it to have it given it's a catch for anything not covered, essentially. Example: perhaps you might take Weapons (Crossbow) and Weapons (Matchlock), things that aren't covered by the core book as written. Theoretically you might have a bunch of them, but the vast majority of weapons are covered by the other categories.

**Comment by RhOmicron** [comment]
#2237

**Comment by RhOmicron** [comment]
Should me merged along with. #2228 and #2227
