### ISSUE TITLE
[L5R] Serious alignment breaks of the Bugei Skills section of the sheet

### ISSUE THREAD

**Issue by kbernges** [Roll20/roll20-character-sheets#2300]
The most recent update seems to have caused this issue. The Athletics skill in particular has serious alignment issues.

**Comment by RhOmicron** [comment]
I guess this has something to do with all the translation changes people put through. Ill have a look what changed.

**Comment by RhOmicron** [comment]
#2301

**Comment by RhOmicron** [comment]
I assume you're referring to the repeating skill box I made as well for high skills. It seems the alignment is coded in CSS. Which I'm not familiar with. I'll have to see if I can fix that.

**Comment by RhOmicron** [comment]
Made a rough fix to the alignment issues to repeating skill as well.

**Comment by RhOmicron** [comment]
Everything should be coming back up as soon as roll20 gets the merge.

**Comment by kbernges** [comment]
Thank you for your efforts, as always.
