### ISSUE TITLE
[GURPS] Encumberance calculation doesn't take Lifting ST into account when displaying your current load.

### ISSUE THREAD

**Issue by calibraptor** [Roll20/roll20-character-sheets#2323]
https://i.gyazo.com/8f5f2de6f6b0a334dde8241a6e6e4561.png

It's currently displaying encumbrance as being at light when it should actually be at none here.

EDIT: This is due to the character's Base ST being 10, but having a Lift ST of 12. It doesn't take the modified Lift ST into account.

**Comment by RhOmicron** [comment]
Encumbrance level seems to be stuck at calculating the unmodified lift ST value.

**Comment by RhOmicron** [comment]
Hopefully there is someone that can fix your problems. I tried to look into it but I don't know how to read the code that is used for the calculations.

**Comment by calibraptor** [comment]
I have zero competency when it comes to the coding of these sheets so I'm just noting the bugs here in hopes that somebody who is will eventually correct them.

**Comment by calibraptor** [comment]
But yeah, I'll edit this to more accurately reflect what the problem actually is

**Comment by sdJasper** [comment]
Your 100% right. The code was pulling the strength_base value for the encumbrance calculation. I've fixed this and will be submitting a pull request with this and other issues soon.

**Comment by sdJasper** [comment]
This issue was fixed, can it be closed now?

**Comment by KlingonMike** [comment]
Yes the issues has been fixed for some time now.
