### ISSUE TITLE
[D&D_Moldvay] Halfling Bonus

### ISSUE THREAD

**Issue by mistatipsta** [Roll20/roll20-character-sheets#2325]
The modifiers granted by Halfling tick box under ATTACKS could be assumed when choosing the Halfling bullet under CLASS ABILITIES.

**Comment by amandasearle** [comment]
With Sheet Workers this is now possible and I have it working in my test environment.

**Comment by amandasearle** [comment]
This is now live in production - please verify and close this issue.

**Comment by mistatipsta** [comment]
This is resolved as of the recent update.
