### ISSUE TITLE
[D&D_Moldvay] Encumbrance Calculation 

### ISSUE THREAD

**Issue by mistatipsta** [Roll20/roll20-character-sheets#2326]
Encumbrance doesn't take the quantity field into account when tallying total weight.

**Comment by amandasearle** [comment]
The inventory is going to get a complete rework into repeating sections to help with space since sheet workers can now sum repeating section values.  Once this is in I will have the quantity value count towards the total weight.

**Comment by clevett** [comment]
Hello,

I'm working on closing outstanding issues on the Github. Is this still an issue? If it is please let me know and I'll leave it open.

Thanks,
Cassie

**Comment by clevett** [comment]
As I've not heard back this issue will b e closed. If it needs to be reopened just let me know.

Thanks,
Cassie
