### ISSUE TITLE
[D&D_Moldvay] Font Inconsistency 

### ISSUE THREAD

**Issue by mistatipsta** [Roll20/roll20-character-sheets#2327]
On my end in the browser (testing with Firefox and Chrome) the sheet uses a font that looks like comic sans (https://i.imgur.com/8m9WiiI.png), however on mobile it appears as a different font (https://i.imgur.com/t3U6kWi.png), not sure what that cause of that might be. Ideally the browser version would use a font better than comic sans.

**Comment by amandasearle** [comment]
The reason that fonts don't show correctly is because of [Bug] imgsrv.roll20.net proxy delivering content insecurely #265 .

Within chrome, you can allow the fonts to be used - I'm not sure if it will keep those settings or not.

**Comment by mistatipsta** [comment]
This issue has been resolved as of the most recent update.
