### ISSUE TITLE
[D&D_Moldvay] Attribute Label Inconsistency

### ISSUE THREAD

**Issue by mistatipsta** [Roll20/roll20-character-sheets#2328]
Adjusting some of the attribute labels to line up with an internal consistency. For example most of the abbreviations are in all caps, but "gp" isn't. Multi-word attributes sometimes use hyphens, underscores or a capital the letter of the next word (OpenDoors-Chance, Attack_Type, PlayerName).

**Comment by amandasearle** [comment]
Changing the name of attributes isn't feasible.  Since they already have values assigned to them, those values would be lost if the name was changed.

**Comment by mistatipsta** [comment]
Ah, I see. I thought it was doable.
