### ISSUE TITLE
[D&D_Moldvay] Less Dropdowns, More Flexibility 

### ISSUE THREAD

**Issue by mistatipsta** [Roll20/roll20-character-sheets#2332]
I think the damage die section should be a blank text field to add some more flexibility than the drop down box can offer, the same goes for the Alignment and HP Die dropdowns and the Attack section under the Monster tab.

**Comment by amandasearle** [comment]
This was pushed to live some time ago - can you verify?

**Comment by mistatipsta** [comment]
Yep! This was changed in the latest version of the character sheet.
