### ISSUE TITLE
[D&D_Moldvay] Default/Autofill Saving Throws

### ISSUE THREAD

**Issue by mistatipsta** [Roll20/roll20-character-sheets#2333]
Default saving throws for a Normal Man are 15, so those boxes could be auto-filled on new characters, at least auto-filled on the Monster tab.

**Comment by amandasearle** [comment]
This is in place in my test environment.

**Comment by amandasearle** [comment]
This is now live in production - please verify and close this issue.

**Comment by mistatipsta** [comment]
This is resolved as of the recent update.
