### ISSUE TITLE
[GURPS] Dodge skill level incorrect under Combat tab

### ISSUE THREAD

**Issue by calgodot** [Roll20/roll20-character-sheets#2365]
The automatically calculated Dodge scores under the Combat tab are not displaying correctly. It appears that any number placed in the Modifier for Dodge on the General page is not being carried over or added to the Combat tab. Attached screenshots of the two tab screens.

![kraugar sheet - combat tab - 2017-03-01 at 11 34 59 am](https://cloud.githubusercontent.com/assets/26123160/23477594/590d0634-fe73-11e6-9eef-71e4704a92d0.png)
![kraugar sheet - general tab - 2017-03-01 at 11 34 46 am](https://cloud.githubusercontent.com/assets/26123160/23477593/59084374-fe73-11e6-9682-9ea1d040367c.png)

**Comment by sdJasper** [comment]
This character has a current HP of 0. So, the sheet is reducing dodge down.

**Comment by calgodot** [comment]
Thank you for pointing out this detail.
