### ISSUE TITLE
Das Schwarze Auge 4.1 Character Sheet - a few (minor) issues

### ISSUE THREAD

**Issue by YuanRamirez** [Roll20/roll20-character-sheets#2366]
Started playing my first (roll20-assisted) campaign last weekend. Have to say: **awesome work**! Most of the stuff works like a charm and it's not even complicated. But we also came across the following issues. I'm not really into HTML/PHP and such, so I thought I should post what we found here instead of trying (and quite possibly failing) to fix it myself.

- Magic resistance ("Magieresistenz"), Lifepoints ("Lebensenergie"), Stamina ("Ausdauer") and Astral energy ("Astralenergie") are not rounded properly (decimals up to .4 should be rounded down).
- Lifepoints, Stamina and Astral Energy are calculated with base attributes only (should be base + modifiers)
- "Behinderung" (BE) (obstruction?) and active weapon modifiers are not taken into consideration when rolling for initiative (INI-Basis - BE + Mod + 1d6 = INI)
- "Behinderung" (BE) is not taken into consideration when rolling any ability checks either. Although, maybe the player is supposed to enter the modifier for that into the input-value dialog manually?
- "Passierschlag" is not calculated correctly. It should be "Attacke" - 4 but right now it's just the value of "Attacke", as far as I can tell.

Also, could you maybe add a place to note your Experience Points (Abenteuerpunkte)? Not super-important, though, since we can just use the "Notizblock" for that.

The following screenshots show the stats of the same character:
![bugreport_github_dsacharactersheet](https://cloud.githubusercontent.com/assets/24588007/23528938/e575a4ae-ff9b-11e6-9e54-1e8804efc8f3.png)

Lebensenergie-Basis should be (Konstitution+Konstitution+Körperkraft)/2 = (13+13+10)/2 = 18
Ausdauer-Basis should be (Mut+Konstitution+Gewandtheit)/2 = (13+13+16)/2 = 21

Magieresistenz-Basis should be (Mut+Klugheit+Konstitution)/5 = (13+10+13)/5 = 7.2 (rounded to 7)

![bugreport_github_dsacharactersheet2](https://cloud.githubusercontent.com/assets/24588007/23528947/e8f417fa-ff9b-11e6-918b-a55ce7ed95b3.png)

Passierschlag should be 6 (Attacke-4 = 10-4= 6) and the button to roll that is also missing.
INI should be: INI-Max - BE + WeaponINI = 11 - 1 + (-1) = 9

**Comment by kreuvf** [comment]
Somebody please assign me to this issue. I will respond in more detail to this later. If not, please send a reminder. ^.^

**Comment by YuanRamirez** [comment]
While you're at it, could you perhaps add hidden GM-rolls to the abilities (Talente)? Right now I had to copy/paste like 15 ability macros. I mean, it works. It's just not really comfortable ^^

**Comment by kreuvf** [comment]
@YuanRamirez Not sure if Roll20 can assign me to this issue. So could you re-open this issue in my repository? If possible, please split it into one issue per ... issue, so that I can close them one by one and discussion becomes easier/more targeted. https://github.com/kreuvf/roll20-character-sheets/issues

**Comment by YuanRamirez** [comment]
@kreuvf Done. If you need any additional information, I'll gladly provide screenshots or whatever

**Comment by kreuvf** [comment]
@YuanRamirez Thank you very much. I will get back to you within this week. Locally (aka not yet pushed to GitHub), I already found fixes for the LE/AU/MR issues.

**Comment by kreuvf** [comment]
@YuanRamirez If my current PR gets merged (https://github.com/Roll20/roll20-character-sheets/pull/2704), most of the points you raised in this issue should be fixed.

**Comment by kreuvf** [comment]
@YuanRamirez As far as I can see, only the second issue mentioned in here is still open. I will not fix this prior to the sheet worker scripts conversion. Since the corresponding issue on my tracker is still open, I recommend closing this issue.
