### ISSUE TITLE
Shadow of the Demon Lord

### ISSUE THREAD

**Issue by dontonibg** [Roll20/roll20-character-sheets#2399]
Today I busied myself with making characters for a oneshot and found it impossible to try and input any details on the custom character sheet. 

Here is a print screen of what I am seeing, it seems values are in mismatched places: 

http://prntscr.com/ehpafl

Mentioned above, the weapons attacks can't be added, asking for a boon value modifier?  I put it in, click accept, and it does nothing. 

Would appreciate someone looking into this!

The issue is on the production server but the sheet appears to be okay on the development server

**Comment by aymarfisherman** [comment]
Here's a PR waiting approval that should fix those and add bonus features to the sheet:
https://github.com/Roll20/roll20-character-sheets/pull/2389

**Comment by joesinghaus** [comment]
Yep, this is ancient and can be closed.
