### ISSUE TITLE
[L5R] - Untrained acting skill rolls are not working

### ISSUE THREAD

**Issue by Vyzzini** [Roll20/roll20-character-sheets#2420]
When I use the untrained roll for the acting skill, I have the following error:

No attribute was found for @{Kitsu Mizudo|roll_acting}
No attribute was found for @{Kitsu Mizudo|keep_acting}
SyntaxError: Expected "(", ".", "[", "abs(", "ceil(", "d", "floor(", "round(", "t", "{", [ |\t], [+|\-] or [0-9] but "K" found.

**Comment by RhOmicron** [comment]
Going to put up a fix for this in the next pull.

**Comment by RhOmicron** [comment]
#2422

**Comment by RhOmicron** [comment]
This should now be live.
