### ISSUE TITLE
[Exalted 3rd Edition]Display Issues with Firefox (and one in Chrome)

### ISSUE THREAD

**Issue by Kerredai** [Roll20/roll20-character-sheets#2450]
In Firefox, the Current Personal and Peripheral Essence pool boxes are hidden beneath the white CSS for the "Personal" and "Peripheral" essence labels, making them extremely difficult to read and edit without just using tokens as a workaround.

In Firefox, when the sheet is popped out, items in a list cannot be properly reordered with the "Modify" button.

In Chrome, when the Modify button beneath a list is clicked, a white filter appears over the list's contents, making it impossible to read any but the first few items.

**Comment by clevett** [comment]
Hello,

Is this issue still on going? I'm working to clean up some of the older issues in our GitHub and am checking in on the unresolved ones.

Thanks,

Cassie

**Comment by clevett** [comment]
I'm going to close this issues as I've not heard back and it has been open for an extended period of time. If it needs to be opened again let me know. 

Thanks,
Cassie
