### ISSUE TITLE
Dresden Files Accelerated Edition DFA.html bugs

### ISSUE THREAD

**Issue by rentarded** [Roll20/roll20-character-sheets#2458]
Bug 1: Approach roll buttons

"Mantle"/Customisable approach button is currently tied to @{intelligence} rather than @{mantle-approach} as it should be. So when you hit the button, it rolls for intelligence, not whatever's in the mantle box.

Bug 2: Refresh

Refresh isn't updating.  Whenever I input new refresh costs into either conditions or stunts, @{refresh-spent} resets to value=NaN. There is no listed value for @{refresh-spent}, but I don't THINK that's the issue. 

3 things I see that MIGHT be involved (or might not be issues, in which case I have no idea what the problem is)
1 - attr_stunt-cost does not have a title, unlike attr_condition-cost, so var 'stuntCost' is trying to retrieve a non-existent value.
2 - Lines 247-259 sets var 'stressCost', which relies on "repeating_stress", a value that doesn't exist anywhere else.
3 - refresh-spent relies on summing up conditionCost, stuntCost, and stressCost. I assume this translates back to @{refresh-spent} which might be why the value messes up (if it's pulling blank values for stuntCost and stressCost)

**Comment by clevett** [comment]
Hello,

I'm working on closing up the older issues on the Github. Can you let me know if this is still an issue?

Thanks,
Cassie

**Comment by Anduh** [comment]
@clevett this issue can be closed as solved, as [mentioned here](https://app.roll20.net/forum/post/7839685/dresden-files-accelerated-bug/?pageforid=7845428#post-7845428).

**Comment by clevett** [comment]
Thanks for the update.
