### ISSUE TITLE
[Call of Chtulhu 7th edition sheets]

### ISSUE THREAD

**Issue by Thaelia** [Roll20/roll20-character-sheets#2466]
Hello!
I was just about to start a chtulhu campaign, but my players are having this error when trying to roll a statistic:

No attribute was found for @{???|appraise}
No attribute was found for @{???|appraise}
No attribute was found for @{???|appraise}
SyntaxError: Expected "(", ".", "[", "abs(", "ceil(", "d", "floor(", "round(", "t", "{", [ |\t], [+|\-] or [0-9] but "?" found.

If i roll the statistic myself, i am able to, but the roll only takes into consideration the base value of the skill, and not whichever score my players have put into it.

What are we missing?

**Comment by aquaalex** [comment]
I am looking at this, but I also notice attribute rolls do 3 rolls? Why would you do 3 rolls for one check? Should it not be 1 Roll compared against the Level of success?

**Comment by aquaalex** [comment]
To quote the rules: 

> Bonus dice and penalty dice are not trifling small additions or subtractions of a few percentage points, and so should not be used without good cause. If a factor is so small that it would only modify a roll by a few percentage points then don’t bother with it. Driving in light rain should not inflict a penalty die, but torrential rain so thick that you can barely see, even with the wipers on full speed—now there’s your penalty!

> Roll an additional "tens" percentage die alongside the usual pair of percentage dice when making a skill roll. You are now rolling three separate dice: one "units" die and two "tens" dice. If you have a bonus die, you should use the "tens" die that yields the better (lower) result. For a penalty, use the "tens" die that yields the worse (highest) result.

**Comment by aquaalex** [comment]
Old Template: - Unnecessarily complex and limited to 2 dice penalty/bonus
[Image](http://prnt.sc/eu4gyd)

New Template: - cleaner but does not allow for penalty/bonus
[Image](http://prnt.sc/eu4g4b)

**Comment by aquaalex** [comment]
If the issue is no longer there please close
