### ISSUE TITLE
[L5R] - Attack with emphasis don't display the weapon name

### ISSUE THREAD

**Issue by Vyzzini** [Roll20/roll20-character-sheets#2482]
When I use the emphasis attack button the name of the weapon is not displayed in the emote message:
_Julien (GM) Kitsu Mizudo makes an attack with Emphasis with their !_

It works properly with the trained or untrained attack buttons:
_Julien (GM) Kitsu Mizudo makes a Trained attack with their Bo of Water!_
_Julien (GM) Kitsu Mizudo makes an Untrained attack with their Bo of Water!_

**Comment by RhOmicron** [comment]
I'll look into it.

**Comment by RhOmicron** [comment]
For me I get which weapon used in all the boxes with emphasis roll, what I noticed though is that the top two bow are broken. The first bow one doesnt roll emphasis and the second doesnt roll any of them.

**Comment by Vyzzini** [comment]
You're right it's working fine when I use the button directly in the character sheet.
I was testing from the tool bar (I dragged and dropped the emphasis button for the character I play) and actually in that case it's not only the weapon name that is missing but the roll is wrong too (4k4 instead of 6k3).

**Comment by RhOmicron** [comment]
Unsure how it works when used from the tool bar. Does it work fully from within the sheet?

**Comment by Vyzzini** [comment]
Yes everything works fine from within the sheet.

**Comment by RhOmicron** [comment]
I found what was wrong with bow 1 and 2. Unsure how to fix your problem though. Does it still not work if you re add it to the tool bar(if this is how it works)?

**Comment by Vyzzini** [comment]
No, but it's not a big deal. 
I can use the button directly from within the sheet.

**Comment by RhOmicron** [comment]
Right, I've made a pull request for the bow fix.
