### ISSUE TITLE
[SWN] Psionic Abilities Template Request

### ISSUE THREAD

**Issue by mistatipsta** [Roll20/roll20-character-sheets#2501]
Requesting the addition of a field on the character sheet to write Psionic abilities and a button to print them to chat in a template.

**Comment by clevett** [comment]
Hello,

I'd recommend moving this request over to the [Character Sheets](https://app.roll20.net/forum/category/277980) forum. I'm going to close this issue on the GitHub. If it needs to be opened again please let me know.

Thanks,

Cassie
