### ISSUE TITLE
 [SWN] Blank/Custom Skill Request

### ISSUE THREAD

**Issue by mistatipsta** [Roll20/roll20-character-sheets#2506]
Requesting a short list of blank skills options so anyone can add their own skills. This could act as a replacement for the customizable  Culture and Profession fields.

**Comment by clevett** [comment]
Hello,

I'd recommend moving request over the the [Character Sheet](https://app.roll20.net/forum/category/277980) forum. I'm going to go ahead and close this issue in GitHub.

Thanks,
Cassie

p.s. Sorry for sounding like a robot. I've typed this to you a few times. There are like 80+ issues to get through. :)
