### ISSUE TITLE
[SWN] Unarmed Attack Damage Miscalculation

### ISSUE THREAD

**Issue by mistatipsta** [Roll20/roll20-character-sheets#2507]
Unarmed attacks should add the Combat/Unarmed skill to the damage  (Star Without Number Core Rules p60), currently when selected the Combat/Unarmed skill on the sheet it does not add this value to the damage.

**Comment by kevinsearle** [comment]
I'll include this in the next release.

**Comment by mistatipsta** [comment]
This is resolved as of the 0.1.6 update.

**Comment by kevinsearle** [comment]
Can you set this to Closed?
