### ISSUE TITLE
[D&D_Moldvay] Background Image Tweak

### ISSUE THREAD

**Issue by mistatipsta** [Roll20/roll20-character-sheets#2508]
The low-res grid paper image being used on the Monster tab right now is blurry to the point where it's actually pretty hard on the eyes. I slapped together some grids for this, I'm not sure if roll20 sheets can repeat/pattern images or not so I made some small and large versions that you can use. Also added some variants with noise. You can find all of those [here](https://imgur.com/a/9ERyW).

**Comment by amandasearle** [comment]
Pull Request submitted

**Comment by amandasearle** [comment]
This is now live in production - please verify and close this issue.

**Comment by mistatipsta** [comment]
This is resolved as of the recent update.
