### ISSUE TITLE
Syntax error : Unexpected Token

### ISSUE THREAD

**Issue by MindlessCalm** [Roll20/roll20-character-sheets#2561]
Whenever I try to use this sheet with the API of roll20 it doesn't work and I get this error ?

**Comment by RhOmicron** [comment]
I assume this is the error you get in L5R? And this is linked to what you asked in #2526?

**Comment by MindlessCalm** [comment]
Yes in the roll20 api script section. please feel free to contact me on skype for easier explanations, MindlessCalm.

**Comment by clevett** [comment]
Hello,

I'm working to close out the older Github issues. If this is still an issue please contact me to reopen it.

Thanks,
Cassie
