### ISSUE TITLE
[SWN] Saving Throw Template UI Alignment Error

### ISSUE THREAD

**Issue by mistatipsta** [Roll20/roll20-character-sheets#2564]
In the 0.1.6 version of this character sheet a failed saving throw misaligned the results. This occurs on all saving throws, and in Firefox and Chrome. [Screenshot](https://i.imgur.com/LqRJhjQ.png).

**Comment by kevinsearle** [comment]
Revamping roll templates because of this.

**Comment by kevinsearle** [comment]
Merged, awaiting deployment.

**Comment by mistatipsta** [comment]
This has been resolved as of the 0.1.7 update.
