### ISSUE TITLE
[D&D_Moldvay] Monster Tab Overlapping UI Error

### ISSUE THREAD

**Issue by mistatipsta** [Roll20/roll20-character-sheets#2565]
In the latest version of the character sheet, on the monster tab a there is a small overlapping UI near the saving throws. This occurs in Firefox and Chrome. [Screenshot](https://i.imgur.com/OS02rS8.png).

**Comment by amandasearle** [comment]
There is a fix in the pipeline for this.

**Comment by amandasearle** [comment]
This has been fixed.
