### ISSUE TITLE
[L5R] - Honor, Glory, Status and Taint ranks display when opening the sheet 

### ISSUE THREAD

**Issue by Vyzzini** [Roll20/roll20-character-sheets#2568]
Hi,

Would it be possible, when opening the character sheet, to have the 4 ranks in display mode?
Right now a character sheet is opened, they are in modification mode, so users have to click on each of them to display the actual value.

Vyzzini

**Comment by RhOmicron** [comment]
Why is the hide function there to begin with? You seem to be able to change the value in any of the states.

**Comment by Vyzzini** [comment]
Here's the look of the ranks when I open the character sheet:
![image](https://cloud.githubusercontent.com/assets/26441800/25531803/f14a16fa-2bf8-11e7-8d62-de4eac9aede7.png)

I have to click on the four red ? to put it in "view" mode, everytime I open the sheet:
![image](https://cloud.githubusercontent.com/assets/26441800/25531844/080c0b78-2bf9-11e7-8458-0a48639a8823.png)

I think it would be better to set it like that by default when opening the sheet (if possible).

**Comment by RhOmicron** [comment]
I can make it be in view mode all the time, and I assume the amount of circles is linked to something else apart from the numbers in the boxes. Couse I just get 10 circles filled with question marks.

http://imgur.com/a/O4Rb3

**Comment by RhOmicron** [comment]
Anyway, I've pushed a fix to skill calculation(initiative) and made the ranks show all the time.
