### ISSUE TITLE
L5R repeating_rcraft, rweap, rehigh spam when rolling initiative.

### ISSUE THREAD

**Issue by Vandaag12** [Roll20/roll20-character-sheets#2578]
Whenever a player rolls their initiative on their character sheets, modified or unmodified, their chatbox is spammed with the attached error. This doesn't seem to effect any other dice rolling button.
![rvlgmfn](https://cloud.githubusercontent.com/assets/27614490/25444464/3d95f532-2a79-11e7-9a9f-977bcc4fff2c.png)

**Comment by RhOmicron** [comment]
I'll revert the changes I made to skill calculation and it will probably fix this. You will have to add up the repeating skill points instead.

Will try get to it on Friday.

**Comment by RhOmicron** [comment]
A workaround might be to add so there is 5 empty repeating rows on high skill, weapon skill and craft skill. 

For the time being.

**Comment by RhOmicron** [comment]
Fix coming with the next merge.

**Comment by RhOmicron** [comment]
What is weird though is that I don't get these errors when I roll initiative. It is being changed in the upcoming update. 

But can anyone else confirm that this happens to them if possible?
