### ISSUE TITLE
[Bug] imgsrv.roll20.net proxy delivering content insecurely

### ISSUE THREAD

**Issue by Ramblurr** [Roll20/roll20-character-sheets#265]
Roll20 uses TLS by default, yay! But the content proxy server (`imgsrv.roll20.net`) isn't set up to deliver content over TLS, so the browsers are complaining.

Firefox is the most strict in this regard. For [passive content](https://developer.mozilla.org/en-US/docs/Security/MixedContent#Mixed_passive.2Fdisplay_content) (e.g., images), this isn't a big deal as Firefox allows the content. But for "active" content (e.g., fonts) the content is blocked completely.

This makes it impossible to use webfonts in our character sheets on Firefox.

![image](https://cloud.githubusercontent.com/assets/14830/3130951/ea80f7d0-e7fe-11e3-8dec-cc49d4980157.png)

**Comment by IanDominey** [comment]
Yeah, this issue is really causing me pain and it seems reasonably easy to fix.

**Comment by bitspersecond** [comment]
I'm in agreement.  I'd like to see this addressed as well.  Has anyone put a suggestion on the suggestion forum?  I'd sacrifice one of my votes to add it to this if others go along as well.  One vote isn't likely to get it noticed….

**Comment by Ramblurr** [comment]
Place a link here and I'll vote for it.

**Comment by bitspersecond** [comment]
Okay, I spent a bit of time trying to look at this again (to familiarize myself with the issues), but I have much to learn in this area.  If I figure it out I'll make the suggestion and let you know.  Otherwise, somebody who's already got a handle on it can do that and I'll commit a vote (after I figure out which one I'm sacrificing :-( )

**Comment by IanDominey** [comment]
I don't get why this isn't resolved yet.  All it requires is setting up a TLS cert on the proxy server.  They could even buy and use a wildcard cert on all of their services.

**Comment by Ramblurr** [comment]
@IanDominey Tell me about it...

**Comment by amandasearle** [comment]
2017 and this still isn't fixed :(

**Comment by jbogrand** [comment]
Reminder to remediate .

**Comment by Goury** [comment]
Why is it closed?
The bug is present by this day.
