### ISSUE TITLE
L5R HP Problem.

### ISSUE THREAD

**Issue by shakasannin** [Roll20/roll20-character-sheets#2740]
Can we fix the HP? is terribly calculated there. The wounds table for a character with 2 Earth should be

10 = (E)arth * 5
4 = E *2
4 = E *2
4 = E *2
... and so on.

And not

10 = (e) *5
14 = 10 + E*2
...

that dont even make sense. lol. ty.

**Comment by NathaTerrien** [comment]
Which sheet does this concern?

**Comment by RhOmicron** [comment]
Probably L5R It seems to fit his description.

**Comment by RhOmicron** [comment]
Is there a rules page I can read so I can have a reference. Unless someone else fix it.

**Comment by RhOmicron** [comment]
Or is it litterally 10 14 18 22 26 30 34 38?

**Comment by RhOmicron** [comment]
If I understand correctly though you get your first wound at 10 then the next step would be earth * 2 which it is doing at the moment?

**Comment by clevett** [comment]
Hello,

I'm working to resolved some of the older issues in Github. Is this still a concern? 

Thanks,
Cassie

**Comment by shakasannin** [comment]
No, it was never an issue actually, there's no problem with it, although there's a problem with the SIFRpg in the Damage and Wounds area. But i dont think this is the correct place to post it.

**Comment by clevett** [comment]
Thanks for the update. I'm going to close this issue but it if it needs to open again please let me know.
