### ISSUE TITLE
Spell Description Area

### ISSUE THREAD

**Issue by shakasannin** [Roll20/roll20-character-sheets#2741]
This is most important, a new box with the description of the spells would be nice, even if we need to copy and paste it from the book. It would even nicer if you could send the text from it to the chat area. Like on the D&D sheets. Thank you!

**Comment by NathaTerrien** [comment]
Which sheet does this concern?

**Comment by RhOmicron** [comment]
Probably also for L5R

**Comment by RhOmicron** [comment]
#2771
