### ISSUE TITLE
Dark Heresy 2nd Edition - dmg roll gives you 2x your Sb

### ISSUE THREAD

**Issue by butchistan** [Roll20/roll20-character-sheets#2826]
As said in title, I noticed it giving your dmg roll +2x Sb.
It's, for example, 1d10+weapon dmg+Sb+(floor((Strength/10) (which basically is your Sb...).
Still nice work, hope you will fix it soon :)

Sincerely, butchistan

**Comment by Craftomega** [comment]
Is this on the advanced sheet or the regular sheet?

Also are you placing your SRT and AGI bonus in the small box? Because that is for Unnatural Bonuses not regular.

Because I just tested it and your issue appears to not be occurring on the regular sheet.
