### ISSUE TITLE
Change Character Sheet Name to Crônicas RPG

### ISSUE THREAD

**Issue by leandrotavaresrocha** [Roll20/roll20-character-sheets#2844]
Hello,

I would to request that in the next update the name of the character sheet called "Creation of Crônicas" be change to "Crônicas RPG". Here is a screenshot of the character sheet:

https://drive.google.com/file/d/0B1Vh7_gHrCMHQmw0V25fcjRKaUk/view?usp=drivesdk

Thanks

**Comment by clevett** [comment]
Hello,

I'm working to resolved some of the older issues in our GitHub. Is this still on going? If so please let me know.

Thanks,
Cassie

**Comment by clevett** [comment]
Hello @leandrotavaresrocha ,

As this is a request rather than and issue and over a year old I'm going to close it out. If it needs to be opened again just let me know.

Thanks,
Cassie
