### ISSUE TITLE
Multiple issues with new Black Crusade sheet

### ISSUE THREAD

**Issue by Nitroxylin** [Roll20/roll20-character-sheets#2847]
- every character sheet by default has chaos space marine traits listed and won't delete them until you replace their text with anything
 - experience savings lost while updating sheets
 - weapon type constantly resets to Pistol after editing, closing and reopening the sheet

**Comment by clevett** [comment]
Hello,

I'm checking in on these old issues in Github to see if they are still on going. Can you let me know if this remains an issue with the Black Crusade sheet?

Thanks,
Cassie

**Comment by Nitroxylin** [comment]
Hello there!
The weapon type issue looks like it is no longer, but the chaos marine traits persist.

**Comment by clevett** [comment]
@Pixizz Is this your sheet by chance and if so are you interested in doing an update?
