### ISSUE TITLE
Issue with Warhammer Deathwatch update

### ISSUE THREAD

**Issue by GomDionysus** [Roll20/roll20-character-sheets#2862]
Rolled Inquiry, which pulls from my fellowship which is 42.

This is what the roll was;

rolling floor((((42 + 0/2) + 10)-1d100)/10)  floor((((42+0/2)+10)-(40))/10)= 1

It should have been 
42/2

Also, someone else looked into it and stated the following;

Looks like the sheet got a commit 13 days ago to add the advanceX attributes to the skill rolls, without wrapping them in parentheses. For example

<select class="charaselect" name="attr_InquiryCharacteristic">
    <option value="@{Fellowship}">(Ag)</option>
</select>

Became

<select class="charaselect" name="attr_InquiryCharacteristic">
    <option value="@{Fellowship} + @{advanceFel}">(Fel)</option>
</select>

The roll button is then using "@{InquiryCharacteristic}/2", which is getting expanded to "@{Fellowship} + @{advanceFel}/2"

This issue is happening for all the basic untrained rolls.

**Comment by clevett** [comment]
Hello,

I'm checking in on these older Github issues to see if they have been resolved. Do you know if this needs to remain open?

Thanks,
Cassie

**Comment by GomDionysus** [comment]
It does not, thank you

**Comment by clevett** [comment]
Awesome. Thanks for the update. :) I'll close it. If something changes let me know.
