### ISSUE TITLE
[D&D 5E OGL] Character sheet layout bugged

### ISSUE THREAD

**Issue by chrisbiasbas** [Roll20/roll20-character-sheets#2899]
Character sheets were fine a week ago but now several boxes are misaligned and overlapping: http://imgur.com/a/X6AK7

**Comment by Project462** [comment]
I've seen this come up on Roll20. Apparently, it's an issue with zoom.
Try pressing CTRL 0 to reset your zoom or CMD 0 on a Mac.
Alternatively, you can resize zoom in incremments with CTRL + and CTRL - (Not sure if they are they same but with CMD on a Mac)

**Comment by chrisbiasbas** [comment]
That fixed it! Thanks!
