### ISSUE TITLE
[D&D_Moldvay] Equipment Carried Columns

### ISSUE THREAD

**Issue by mistatipsta** [Roll20/roll20-character-sheets#2989]
Previously the Magic Item and Normal Item columns were side-by-side, as they appear in the original sheet this is based on ([image](https://i.imgur.com/Ow31p01.png)), however somewhat recently these two item sections on the Roll20 sheet are placed right above each other as a single column creating a lot of wasted blank space ([image](https://i.imgur.com/2dBdFgM.png)). I believe there are other sections of the character sheet that have this same issue, including the Monster Tab but I can't site specific examples.

**Comment by amandasearle** [comment]
I just checked in a live game on Chrome and the item sections look okay.  What browser are you using?

**Comment by mistatipsta** [comment]
This happens on both Chrome and Firefox, just checked to make sure, even on Microsoft Edge.

**Comment by joesinghaus** [comment]
You're using inline-blocks together with negative letter-spacing for the layout on the inventory rows. This is prone to breaking for people who have different fonts than you do. Perhaps you should use a flexbox-based layout for these rows instead, then you can get rid of the hacky letter-spacing stuff.

**Comment by mistatipsta** [comment]
> You're using inline-blocks together with negative word-spacing for the layout on the inventory rows. This is prone to breaking for people who have different fonts than you do. 

I can't speak on the code, but that does seem in line with [another issue](https://github.com/Roll20/roll20-character-sheets/issues/2327) I've brought up.

**Comment by mistatipsta** [comment]
This issue has been resolved as of the most recent update.
