### ISSUE TITLE
Godbound Sheet

### ISSUE THREAD

**Issue by SantoSama** [Roll20/roll20-character-sheets#3017]
Hello, i'm trying to set up a Godbound campaign on roll20, and the only sheet available for that purpouse is the one you made. I'm noticing a lot of mistakes, that if possible i'd like fixed. I considered buying a pro account and fix them myself, but i'm afraid im not good enough with css to do that.
Here is a list of the errors i've noticed so far:

- The total HP is missing the con modifier you get at level 1.
- You can't modify the effort, while some gifts give you extra effort.
- You can only delete the last fact of the list. This isn't a major issue, but it's still a mild annoyance.
- Automatic save rolls don't work properly.
- I've been told that the phone version of the sheet is a mess.
- Weapon rolls only work for the last weapon. If you have multiple weapons you can't edit or roll them.
- The damage chart is wrong. If you roll 10 or more it's 4 dmg, not 3.

I would really appreciate an answer, either positive or negative, so i could know how to move from here. Thanks in advance, Santo.

**Comment by Anduh** [comment]
Did you chech the game's readme? Because it says:
"Contributing and Feedback

Report any problems, suggestions, or features by sending a private message on Roll20 to jfredett, and open a ticket for it on this Github repo (be sure to send me a link to the issue)!

If you'd like to contribute, I'd be happy to help answer questions about how the sheet works, and would love to coordinate with you. Please contact me as above if you are looking to help."

**Comment by Anduh** [comment]
If you absolutly know what you are doing, you can submit a pull request for any fix you manage to make after contacting the author. I doubt this issue is tagged to him, so he isn't aware unless you have contacted the author. If you have gotten no response in a long time, you could be extra careful and just try to fix anything you think you are able.

**Comment by SantoSama** [comment]
I have sent 2 pms over roll20 to jfredett (one before of finding this github, the other after making this thread, linking to it). I didn't have any idea of how github really works (i still don't, as a matter of fact) so i thought this was an "issue"? since it's in the "issues" tab? I sent a link of this thread to jfredett over roll20. Here is word by word what i sent to him the second time:

**I discovered the Github where you post the sheet coding. I made an issue over there, pointing out some problems i found with the godbound sheet. If you could give me a positive or negative answer to know where im standing, it would be appreciated. Here is the link to the issue: https://github.com/Roll20/roll20-character-sheets/issues/3017**

I have pretty much given up about getting a fix, me and my group are handling it with manual sheets, but it would be nice to have a roll20 sheet we can use without problems. And i am fully aware i can modify the sheet in roll20, but i simply don't know how to do the coding. I just noticed a load of errors involving the rules of the game in relation to what the sheet does.

**Comment by Anduh** [comment]
Okay, he haven't been playing lately it seems or whatever, too bad.

**Comment by SantoSama** [comment]
Too bad indeed :(

**Comment by Anduh** [comment]
The sheets are made in html/css code with snippets of roll20 chatcommands, and here everyone can look at the code and then make an own copy of it, here is a quick guide how it works, if someone feels brave in your group.https://wiki.roll20.net/Beginner's_Guide_to_GitHub
Can't say much about some of the stuff you mentioned without learning the game and looking at the char sheet, but here are my guesses:
-The weapon roll only existing for one weapon propably means that the roll button is accidentally outside the <fieldset> tag, that makes it so you can add more weapons to the list.
-The damage chart should be findable in the code, it should be somewhat easy to just change number for that spot.

**Comment by clevett** [comment]
A pull request went out that reported fixed the issues here. I'm going to close out this request. If there are still issues please let me know.

Thanks,
Cassie
