### ISSUE TITLE
Starfinder NPC Initiative issue

### ISSUE THREAD

**Issue by falantar** [Roll20/roll20-character-sheets#3049]
1) When I roll Init on the NPC section of a character sheet, it always adds a +4 initiative regardless of the modifiers I put in. 
2) the DEX mod is always 0 here even if the dex-bonus is filled in at the lower portion of the sheet.
3) the tiebreaker is always 0.04

**Comment by clevett** [comment]
I'm going to go ahead and close out this issue as its been reported fixed. If this is still an issue please let me know.

Thanks,
Cassie
