### ISSUE TITLE
[Arcane Codex] Betäubender Schaden (B) / Bashing Damage

### ISSUE THREAD

**Issue by Markus1204** [Roll20/roll20-character-sheets#3088]
Gibt es eine Möglichkeit, ein zweites Schadensfeld in den Charakterbogen zu implementieren für den Betäubenden Schaden?

Denn laut Regelwerk ist es ja so, dass Betäubender Schaden klar nicht tödlich ist, aber wenn die Max-LeP überschritten werden, die Differenz in T Schaden umgewandelt werden. Diese Logik vermisse ich komplett.

Is there a way to implement a second field for Bashing damage (B) in the Character Sheet?
Regarding the Rules, you don't die from bashing damage, but if bashing damage exceeds Max Life, the gap between Max Life and B-damage is converted to T damage... This is completely missing in the character sheet...

**Comment by clevett** [comment]
Hello,

I am working to clean up these old Github issues. Is still still a feature that the sheet needs?

@Omegazoyd  Are you interested in this issue?

Thanks,
Cassie

**Comment by Markus1204** [comment]
Hello,
At the moment we are not playing Arcane Codex, but it'd still be a nice feature for the sheet to have because at the moment you have to take notes yourself about bashing damage the character takes...

But if no one is interested in implementing / changing it, then it can't be helped...

It's not a must have, but as said, nice to have...

**Comment by nmbradley** [comment]
This issue is over 4 years old, and doesn't seem to have gained any traction during that time, so I'm going to close it out.
