### ISSUE TITLE
Blades in the Dark: 12-tick clock is bugged on 6 ticks.

### ISSUE THREAD

**Issue by NikolaSama** [Roll20/roll20-character-sheets#3121]
Currently, if you set up a 12-tick project clock and fill it up half way, the clock appears as full visually. This is specific for this clock on this tick, as far as I understand.

**Comment by joesinghaus** [comment]
Thanks for the report, it's a known issue but fixed in 2.4. Will be fixed once 2.4 goes live.

**Comment by joesinghaus** [comment]
This is now fixed and can be closed.
