### ISSUE TITLE
Cyberpunk 2K20 character sheet

### ISSUE THREAD

**Issue by Celeuril** [Roll20/roll20-character-sheets#3163]
Various fields do not save information typed. Specifically: lifepath events, all relatives, friends, enemies, contacts, etc...'s names, occupations, main location. Also EVERYTHING in players Bio EXCEPT for Style and Age. Not having any of that save at all is a huge pain.

**Comment by joesinghaus** [comment]
It seems that whoever made that sheet did not add a type for text inputs, which is required by Roll20. I ran a quick regexp over it to fix it via pull request #3164 .

**Comment by Celeuril** [comment]
That fixed it just right! Thank you so much for your help!
