### ISSUE TITLE
[D&D_Moldvay] Missing Images Error

### ISSUE THREAD

**Issue by mistatipsta** [Roll20/roll20-character-sheets#3179]
The images used for AC, Current Hit Points, and Maximum Hit Points are missing. Here are replacements that are 100x100 pixels, I don't know what size the previous version were.

https://i.imgur.com/7a2cmtV.png
https://i.imgur.com/3AR0UGN.png
https://i.imgur.com/wcEOrmc.png

**Comment by vince-roll20** [comment]
https://github.com/Roll20/roll20-character-sheets/pull/3194

**Comment by mistatipsta** [comment]
This has been resolved as of the most recent update.
