### ISSUE TITLE
[Pathfinder] Wound Threshold applies penalty twice on skill checks

### ISSUE THREAD

**Issue by blackanthrax** [Roll20/roll20-character-sheets#3190]
The Wound Threshold penalty reduces the skill bonus and adds a penalty to the roll, effectively reducing the rolls by double the indicated amount.

**Comment by clevett** [comment]
Hello,

I'm working to follow up & resolve old issues in Github. Can you let me know if this is still on going?

Thanks,
Cassie

**Comment by vince-roll20** [comment]
I believe this was actually related to another bug where conditions affecting skills were getting penalized twice (once within the skill total and again directly with the macro).  
Should no longer be an issue.

**Comment by clevett** [comment]
Aweomse! I'll close the issue. Thanks for the update.
