### ISSUE TITLE
Fonts don't display correctly on Linux machines

### ISSUE THREAD

**Issue by Atrixium** [Roll20/roll20-character-sheets#325]
Hi, I participate in a Dark Heresy campaign and I have noticed that the fonts used on the sheet are not Linux compatible. Cambria for example is only licensed for use on Windows Operating systems and Hoefler is distributed through Apple. Essentially what happens is you end up with a character sheet that has the field labels all jumbled.

Here's a site for free embeddable fonts: http://www.fontsquirrel.com/home

And here is an article on setting up browser-agnostic font embedding with CSS with the above site: http://www.midwinter-dg.com/permalink-font-face_embedding_made_simple_with_font_squirrel_2010-12-22.html

**Comment by Anduh** [comment]
Backup fonts are a thing. And this is propably solved.

**Comment by Ramblurr** [comment]
I'm not maintaining this any more but I would be happy to merge in a fix and release it to roll 20.

**Comment by clevett** [comment]
Hello,

I'm working to clean up the old issues in out Github. I'm going to go ahead and close this one. If it is still an issue let me know and I'll re-open.

Thanks,
Cassie
