### ISSUE TITLE
Aberrant Character sheet- not displaying correctly

### ISSUE THREAD

**Issue by Yerbuti** [Roll20/roll20-character-sheets#3289]
The Aberrant character sheet (under Storyteller system sheets) will not display correctly on any browser. I am no expert but I looked at the HTML code and it could be that the CSS may not be applying. Is listed as AEON-Aberrant in github. Thanks!

**Comment by Yerbuti** [comment]
Is listed as AEON-Aberrant in github.

**Comment by Anduh** [comment]
It could be that there is a problem with the css, I have encountered a similar problem with another sheet I worked with myself, but that was selfinflicted. Looks indeed as if the css is "broken"

Anyway, when was the last time the sheet looked normal? It updated last time 5 months ago by @cowtankerous , was it normal back then?

**Comment by clevett** [comment]
Hello,

I'm working to resolve and close the older issues in Github. Is this still on going?

Thanks,
Cassie

**Comment by CoalPoweredPuppet** [comment]
Provided my changes are done properly, this issue should be fixed.

**Comment by CoalPoweredPuppet** [comment]
Thank you.  More work on my part needs to be done, but this major issues are fixed
