### ISSUE TITLE
[Uncharted Worlds] Add Expanded Careers/Origins

### ISSUE THREAD

**Issue by EightAndAHalfTails** [Roll20/roll20-character-sheets#3305]
Add the extra careers and origins from the Far Beyond Humanity expansion to the career/origin dropdowns and include their logos.

New Careers:
- Augmented
- Chosen
- Consul
- Fanatic
- Kinetic
- Psychic
- Shaper

New Origins:
- Forlorn
- Occult
- Primal
- Programmed
- Spiritual

**Comment by kaffo** [comment]
:+1:

**Comment by RhOmicron** [comment]
I've sent the creator a message. Either he does it himself (last update a year ago), or I make a pull request if I get permission from him.

**Comment by RhOmicron** [comment]
Should be live whenever.
