### ISSUE TITLE
[Open Legend] Character sheet doesn't allow for invisible GM rolls

### ISSUE THREAD

**Issue by seppe2468** [Roll20/roll20-character-sheets#3421]
There is currently no option to use the roll macros on character sheets and make them invisible to players.

**Comment by BuildAndDie** [comment]
1st) Which Open Legend sheet do you mean, though I don't think either one does this (nor a lot of charactersheets)

2) there isn't a lot of need for it in most cases, though for the sheet I have considered it, but it isn't a priority right now

3) This isn't really an issue, but a feature request, see: https://community.openlegendrpg.com/t/roll20-character-sheet/162

**Comment by seppe2468** [comment]
1) The charactersheet on Roll20 simply named "Open Legend", we're not using the minimalist one.
2) While it's perfectly possible to GM the game without it, it would make fudging the numbers as the GM a lot easier.
3) My apologies, it's my first time using these channels.

**Comment by BuildAndDie** [comment]
For #3, no worries, just harder for a person that works on sheets to see issues posted here unless the author is mentioned/pinged, hence why it took me 25 days to notice it.

For #2, not a personal fan of fudging numbers, BUT, I understand some people want to. I was planning to implement a way to send various rolls to the GM, though not for fudging, for players that want to do something without the party knowing about it. It of course can be used by the GM in a similar fashion.

I'll actually be working on the sheet some over the next 2 weeks, though I will probably be working on other things first, so not sure If I'll get something implemented for GM rolls this stretch, but possibly after I get back from my next trip.

Again, feel free to post in the forum topic I linked above, I take lots of requests there, and it will help remind me.
