### ISSUE TITLE
[Deathwatch - Onlywar] Translation

### ISSUE THREAD

**Issue by Vindikaell** [Roll20/roll20-character-sheets#3429]
Hi, 

How we can add Character Sheet i18n for the Deathwatch and Onlywar caracter sheet? I shall like translate them in french.

Thanks

**Comment by Anduh** [comment]
Wiki page for how to do it:
https://wiki.roll20.net/Character_Sheet_i18n

Example of sheet that uses i18n in the sheet:
https://github.com/Roll20/roll20-character-sheets/tree/master/CWOD-V20

**Comment by clevett** [comment]
Hello,

I'm working on resolving older issues in Github. Were you able to get the translations done? If you still need help with this issue please let me know.

Thanks,
Cassie

**Comment by clevett** [comment]
Hey there,

I'm going to go ahead and close this issue out.  Anduh included directions on how to get started with translate. If you have any other questions please let me know.
