### ISSUE TITLE
Legacy: Life Among the Ruins sheets not appearing in sheet dropdown?

### ISSUE THREAD

**Issue by James-Iles** [Roll20/roll20-character-sheets#3440]
After submitting these sheets it looks like they were approved, and added to the _approved.yaml_ file, but they're not appearing in the selection dropdown on the site. It's looking like nothing added below Fire Emblem Tabletop in the _approved.yaml_ file is available on the site - is it just a matter of waiting for things to filter through, or can I do something else to speed things along?

**Comment by Anduh** [comment]
When I submitted new sheets there usually have taken longer time for new sheets to appear than any updates to existing ones, so surely they are up within 24h now. But yeah often this occurs on Tuesdays.

**Comment by Solarswordsman** [comment]
We delayed our push for the character sheets code this week until today, the sheets should be going live within a few minutes.  Though we do our best to push out these out regularly each Tuesday after they are accepted into the repository, on occasion there are times at which we delay the push to the following day or later.

Thank you for your patience on our part; if the PR was accepted, it will eventually (usually within 24h) be live on the site.
