### ISSUE TITLE
Pathfinder Simple - d20 Oddness

### ISSUE THREAD

**Issue by KoshiirRa** [Roll20/roll20-character-sheets#3450]
We're seeing an issue right now where one player's sheet isn't adding any modifiers to the d20 rolls.  Attacks, initiative, skills - anything with a d20 is just getting the d20 roll.  After today's game we're going to have him re-create his character sheet from scratch just to see if that fixes it.

**Comment by KoshiirRa** [comment]
Update: A new character sheet does not have the issue.

**Comment by clevett** [comment]
Hello,

I'm working to close out the old Github issues. Since changing to a new character seem to resolve the issue I'm going to go ahead and close this. If it need to be reopened please let me know.

Thanks,
Cassie
