### ISSUE TITLE
[LotFP] Encumbrance/Speed Miscalculation

### ISSUE THREAD

**Issue by mistatipsta** [Roll20/roll20-character-sheets#3464]
I have recently begun playing Lamentations, and have found many areas for improvement for the Roll20 character sheet, and other areas that are plain erroneous or absent.

In the current version of the character sheet under the Equipment, there is no field for quantity, which has lead to many new players to assume this is what the weight field is for, which makes them much much slower than intended. I would propose  making an additional column just for quantity and/or labeling the columns, with the addition of a separate field just to note movement speed.

I understand it would be more work, but I think the ideal solution would be to more closely following the shape and design of the physical character sheet's presentation of encumbrance and perhaps include toggles for the armor type so distance is accurately and automatically calculated.

**Comment by Anduh** [comment]
@joesinghaus might have an opinion?

**Comment by joesinghaus** [comment]
Yes, one could make improvements along the lines you suggested to make the sheet actually adhere to the rules. I'm personally not very motivated to make those changes, however, since I'm not currently playing LotFP.

**Comment by clevett** [comment]
Hello,

I'm working to resolved the issues on Github currently opening. I would suggest making request on the [Character Sheet](https://app.roll20.net/forum/category/277980) forum. Some one there may be able to do this update. For now I will close this issue but if it needs to be open again please let me know.

Thanks,
Cassie
