### ISSUE TITLE
LotFP: Ability Rolls & Reaction Roll Alteration 

### ISSUE THREAD

**Issue by mistatipsta** [Roll20/roll20-character-sheets#3465]
In the character sheet under Abilities the clickable button there rolls a d20+ the reliant modifier, however LotFP doesn't really use a d20 for task resolution, merely combat actions and saving throws. The base chance of success for most skill is 1 in 6, often being adjusted by the ability score modifier, situational bonus/penalties, and the class's boons (Rules & Magic p17, p31-41). This area could also use a separate numerical field to record long term bonuses to these scores, such as magic items or class adjustments.

Additionally there is no built-in button or template for rolling reactions/morale, which are a 2d6 + same previously mentioned modifiers (Rules & Magic p51, p56, p60).

**Comment by Anduh** [comment]
Best likelihood for any response here is to ask someone  related to the sheet directly like @joesinghaus who is the latest person to edit.

**Comment by joesinghaus** [comment]
Same answer as to the other question: I probably won't make any changes myself. Feel free to make the changes you want to make...

**Comment by nmbradley** [comment]
This issue is now 3 years old, and doesn't appear to have gained any traction, so I'm going to close it out.
