### ISSUE TITLE
Translation file keep old one after Merged and some bug make error

### ISSUE THREAD

**Issue by zeteticl** [Roll20/roll20-character-sheets#3469]
Translation file keep old one after Merged 
https://github.com/Roll20/roll20-character-sheets/pull/3455/files
"majorwound-u" ,"pulphp-u" and "unarmed-u" is miss, so coc 7ed character sheet miss some word now.

 
also
 Call_of_Cthulhu_7th_Ed_Chinese_Traditional/coc_7th_ed.html
https://github.com/Roll20/roll20-character-sheets/pull/3468/files
my mistake.
i miss a word sheet:opened, so it will show error message when the character roll dice.

**Comment by Anduh** [comment]
Maybe Jacob's words [here](https://app.roll20.net/forum/post/6095404/pull-request-question) shines some light on this issue?

**Comment by clevett** [comment]
Hello,

I'm working on closing out old issues on the Github. Is this issue still an on going one?

Thanks,
Cassie

**Comment by zeteticl** [comment]
done.
thankyou!
