### ISSUE TITLE
[SavageWorlds-Tabbed] Add support for Mutant Chronicles 3rd Edition

### ISSUE THREAD

**Issue by clflo** [Roll20/roll20-character-sheets#3549]
Please add support for playing Mutant Chronicles 3rd Edition with Savage Worlds. There's a new Derived Stat: Willpower, calculated as 2+half Spirit die type. It would also be cool if the background from the MC3 character sheet could be selected.
@wing-it

**Comment by Anduh** [comment]
Tag the author in the issue, contact them in some other way or this might never be noticed in a timely fashion. Few of the many dozen sheet authors stalks the issue page to the extent that any relevant issues would be brought to their attention this way. Some authors have even a recommended way to contact them.

**Comment by clevett** [comment]
Hello,

I would suggest making this request over on the [Character Sheet forums](https://app.roll20.net/forum/category/277980). I'm going to go ahead and resolve this issue in Github but if it needs to be opened again please let me  know.

Thank you,
Cassie
