### ISSUE TITLE
DCC_Tabbed_Sheet - The Broken Star Fumbles

### ISSUE THREAD

**Issue by sebastianperezperaza** [Roll20/roll20-character-sheets#3577]
When character level 0 gets The Broken Star birth right the fumble roll does not work as it is supposed to.

The option should double the luck modifier.

Instead it subtract it once and then it subtract it doubled.

![fumble_error](https://user-images.githubusercontent.com/20133113/37579093-474741aa-2b1b-11e8-93f0-9e3c7c83adeb.png)

**Comment by Anduh** [comment]
Tag the author in the issue, contact them in some other way or this might never be noticed in a timely fashion. Few of the many dozen sheet authors stalks the issue page to the extent that any relevant issues would be brought to their attention this way. Some authors have even a recommended way to contact them stated on sheet documentation.

**Comment by clevett** [comment]
@amandasearle Are you interested in this issue?

If this issue has been resolved can some one let me know so I can close it.

Thanks,
Cassie

**Comment by nmbradley** [comment]
This issue is now 3 years old and doesn't appear to have gained any traction during this time. I'm going to close this issue. If it's still a problem, creating a new issue might encourage fresh eyes.
