### ISSUE TITLE
[7th Sea 2e] Missing Hero Point indicator

### ISSUE THREAD

**Issue by dipndawtz** [Roll20/roll20-character-sheets#3693]
We've been using the 7th sea 2e sheet ( created by @CoalPoweredPuppet ) for a while, but all of a sudden my players are complaining that the hero point indicator in the top right is missing (see below image)
![missing-hero-point-indicator](https://user-images.githubusercontent.com/38708687/39220804-6f589ef2-4801-11e8-9ba6-f799f2015bdc.png)

Another issue we noticed before it disappeared is it was always limiting players to a max of 3 hero points, which as far as I can tell isn't correct, as I can't find anything in the rule books about there being a max number a player can have.

**Comment by Anduh** [comment]
Tag the author in the issue, contact them in some other way or this might never be noticed in a timely fashion. Few of the many dozen sheet authors stalks the issue page to the extent that any relevant issues would be brought to their attention this way. Some authors have even a recommended way to contact them stated on sheet documentation.
