### ISSUE TITLE
[Mutant Year Zero] Fight roll malfunctions when dragged to macro toolbar or referenced as an ability

### ISSUE THREAD

**Issue by HelmicNewciv** [Roll20/roll20-character-sheets#3698]
Both %{fight} and dragging the macro to the macro toolbar results in an empty custom roll rather than using the Fight/Assault skill, which is kind of an issue as that's one of the more common roles in combat.  It makes creating macros using that skill more difficult.

**Comment by clevett** [comment]
Hello,

I'm working to get some of these older Github issues closed. Do you know if this is still an issue? Also there is a new sheet for this, Mutant Year Zero Alternative. 

Thanks,
Cassie

**Comment by HelmicNewciv** [comment]
This is in reference to the Alternative sheet that's currently the only available choice from the Roll20 site.  This is still an issue.

**Comment by clevett** [comment]
@nodos-7 Would you be interested in this? If not no worries, I'll mark it as looking for help.

**Comment by nodos-7** [comment]
I honestly didn't see it before. I'll give it a look. I wouldn't turn down the help though.
