### ISSUE TITLE
[Mutant Year Zero] No initiative

### ISSUE THREAD

**Issue by HelmicNewciv** [Roll20/roll20-character-sheets#3699]
There's no initiative shortcut on the character sheet.  Initiative is just 1d6 with ties broken by Agility or Stability (could possibly be automated by adding the stat as a decimal?), followed by an unmodified die roll until the tie's broken.

**Comment by clevett** [comment]
Hello,

I'm working on resolving the old Github issues. Can you let me know if this is still an on going issue? If so we can try pinging the character sheet creator.

Thanks,
Cassie

**Comment by HelmicNewciv** [comment]
Hello, there's still no initiative shortcut.  I would ping the creator if I knew what their username here was - I don't know how to get in contact with them.

**Comment by clevett** [comment]
Hey here,

I'll flag this as helped wanted and ping @nodos-7 . 

Thanks,

Cassie

**Comment by clevett** [comment]
Added button in #5151
