### ISSUE TITLE
[Mutant Year Zero] Gear and weapon macros

### ISSUE THREAD

**Issue by HelmicNewciv** [Roll20/roll20-character-sheets#3700]
Gear and weapons lack any macros to help automate rolls.  Gear could have its own repeating section for each skill it applies to and the bonus it gives to that skill, making it easier for players to drag buttons to the macro toolbar to speed up play.  Gear that's being creatively used can fall back on the macros in the skills section that prompts for the number of gear dice.

**Comment by HelmicNewciv** [comment]
The same should also apply to armor, click a button and get back your armor roll against damage.  Attacks should be able to optionally query a token for its armor value to speed up combat - it just rolls its armor and uses that to calculate the total damage before stunts and modifiers from the target using Defense or Cover.  Since this is all done in one click, there's no need to wait on either the player or GM to roll dice and helps further clarify who is attacking who.

**Comment by clevett** [comment]
@nodos-7  Are you interested in this issue?

**Comment by SpaceDiceMan** [comment]
This would be so useful!

**Comment by clevett** [comment]
Added an armor button in #5151 . The rest is a bit more complicated than it seems when referencing repeating sections. As the original sheet author has not completed the request in over a year, I'm going to close this request. I'm working on a new sheet to deprecate this one in the future. I'll add this to my project plan.
