### ISSUE TITLE
[Mutant Year Zero] No roll modifications

### ISSUE THREAD

**Issue by HelmicNewciv** [Roll20/roll20-character-sheets#3701]
The sheet currently doesn't have a way to handle modifications to your rolls.  Players should be prompted for the modifier when they go to roll a skill or program, and when combined with #3700 this should be the only thing that needs extra player input.

When rolling from the skill/program section, modifications should be prompted for first as that's what players will need to modify most often, the gear roll should almost always be 0 unless the player's making creative use of gear.

**Comment by clevett** [comment]
@nodos-7  Are you interested in this issue?

**Comment by clevett** [comment]
Going to close this issue as its more than a year old. With the current sheet there is not an easy way to do this give that skills either subtract from die pool or roll a d6 and subtracts hits.
