### ISSUE TITLE
[Mutant Year Zero] Mutation tracker limitations

### ISSUE THREAD

**Issue by HelmicNewciv** [Roll20/roll20-character-sheets#3702]
While the current radio buttons resemble the character sheet, these are actually really bad for actual play in Roll20.  It's not clear exactly what your energy is just by looking at it, it looks like it's impossible to have 0 Mutation/Feral/Energy/Ability points but because there's 10 dots and you normally have a capacity for 10 points it gives you the wrong impression of what the @{mutation} attribute actually is, you're off by one.  And since there's only 10 dots, the maximum points you can actually have is 9, which is wrong.

This also causes issues if a character took a talent or secondary function that increases their maximum capacity or if robots have chosen to store their energy somewhere.  For example, Backup Power for robots increases that character's Energy capacity to 12.  The only way to work around this right now is to always have a token on-screen with one of the three attribute slots in a game that has a lot of resources to track or to manually adjust the @{mutation} attribute on the attributes tab.

This also makes it more difficult for GM's that wish to use houserules to change how that works, maybe wanting to use a larger capacity for a higher power campaign.

Instead, the sheet should just use a normal number field, with a current value and a max value that defaults to 10.  It makes it much easier for players to quickly modify and plays nicer if they choose to use that stat on their token.

**Comment by nodos-7** [comment]
That makes a lot of sense and the ui is already established with the stat max section.

**Comment by clevett** [comment]
Reworked Points in #5151 . This sheet does not support house rules and currently does not support the 12 capacity of robots. I'll consider that in a new sheet that is being created for this.
