### ISSUE TITLE
True AI

### ISSUE THREAD

**Issue by samueldcorbin** [Roll20/roll20-character-sheets#3772]
Now that the sheet supports Space Magic as well as Psionics, it would be nice if it supported True AI as well.

It would need:

1. Remove psionics skill names (True AI routines don't have associated skills).

2. Change "Effort" to "Processing".

3. Add tracking for AI Processing points (requires some way of tracking max processing nodes, ideally allow adding multiple sources since losing access to a node drops down to the next largest node you have access to).

4. Replace cybernetics with integrated equipment (capacity is 2 items per level).

**Comment by Anduh** [comment]
I reccommend to tag the author or an active contributior if you want this to be noticed at all.

**Comment by samueldcorbin** [comment]
I understand - I only brought it up since space magic is also a paid feature and seems to have been added.

**Comment by joesinghaus** [comment]
@clevett we have our own issue tracker for SWN, you can close this one as well.

**Comment by clevett** [comment]
Awesome! Thank you for the update!
