### ISSUE TITLE
Blades in the Dark Sheet Version 3.5 Chrome: Heat / Rep Check boxes not visible

### ISSUE THREAD

**Issue by delwaterman** [Roll20/roll20-character-sheets#3787]
<img width="235" alt="screen shot 2018-05-22 at 1 00 53 pm" src="https://user-images.githubusercontent.com/70605/40378031-63fd90a6-5dc0-11e8-82d3-ea19332f115a.png">

![screen shot 2018-05-22 at 1 03 36 pm](https://user-images.githubusercontent.com/70605/40378134-a5cc9c52-5dc0-11e8-95e6-ba0aab2d2c51.png)

**Comment by joesinghaus** [comment]
This was some local issue for one user, I think it can be closed safely.

**Comment by clevett** [comment]
Thanks! It shall be closed. If it need be open again just let me know.
