### ISSUE TITLE
Trying to complete a character sheet for the D6 Star Wars RPG.

### ISSUE THREAD

**Issue by odriscolltj** [Roll20/roll20-character-sheets#382]
I saw that there are 3 D20 Star Wars character sheets, but no D6 sheets.

  I don't have any previous experience with HTML/CSS, but I have plugged in all of the bare bones required for the sheet, and plan to improve it later.
  How do I accomplish the uploading with GITHUB?
   - I have created the .json file and verified it.
   - I have built the HTML file.
   - I have created the CSS file.
   - I took a .png snip of the character sheet, but keep getting errors on upload.

Please let me know what you need me to do.

![d6starwarspreview](https://cloud.githubusercontent.com/assets/8289651/3744157/928e6378-1788-11e4-9b79-cc3127eea642.PNG)

**Comment by vince-roll20** [comment]
I have added a new image.

**Comment by vince-roll20** [comment]
This sheet is still not showing as a community sheet...?  Pull request was completed 4 days ago.

**Comment by vince-roll20** [comment]
Issue is now solved and the sheet is live.

**Comment by IanDominey** [comment]
If this issue is resolved, can you close the issue?

**Comment by vince-roll20** [comment]
I think only the OP or perhaps someone with elevated permissions (Steve and Riley) can close an issue.  At least I can't seem to find an obvious method...
