### ISSUE TITLE
Mutants and Masterminds 2e Skills.

### ISSUE THREAD

**Issue by akenyon0001** [Roll20/roll20-character-sheets#3829]
The following skills are using DEX to calculate the total not the relevant stat. Ranks and Misc work fine for them and the Ability box shows the correct mod. You can test the issue by setting Dex Base to 12 [1] and having other stats at 10 [0]. Ability box will show 0 but the total box will show 1.

Search [Int]
Sense Motive [Wis]
Survival [Wis]
Swim [Str]

**Comment by Anduh** [comment]
It's best to ping the author or some of the active M&M sheet contributors if you want this to be noticed in any timely manner. 

Seldomly have the relevant people stumbled into the Issue-section and saw these without being notified of the issue.

**Comment by clevett** [comment]
@UltraGuyver Are you interested in checking this issue out?

Thanks,
Cassie

**Comment by UltraGuyver** [comment]
Hello

Sorry for the late reply I've been away. Fixed the sheet and have created the pull request.

**Comment by clevett** [comment]
Awesome! Thanks @UltraGuyver ! I'll go ahead and close this issue.
