### ISSUE TITLE
[The Sprawl] Result of rolls

### ISSUE THREAD

**Issue by WallaceMcGregor** [Roll20/roll20-character-sheets#3860]
Could be posible to add the total result of a roll?

I think @timdenee made the sheet, I am not sure.

**Comment by timdenee** [comment]
It's something we've discussed before. Unfortunately it's not currently possible within Roll20 to show both the individual dice/bonuses and the total at the same time. My personal philosophy is that with a system as simple as PBTA, it's important for everyone at the table to be aware of exactly what's going in to every result - the dice roll, the relevant stat modifier, and any +1/-1 forward etc. I favour transparency in that sense.

**Comment by WallaceMcGregor** [comment]
I undestand. I didn't know that Roll20 can't show both valors. In that case is ok.

Thanks.
