### ISSUE TITLE
RunequestGQS Full Release Abilities duplicating

### ISSUE THREAD

**Issue by tauboy** [Roll20/roll20-character-sheets#3872]
hi
I've just tried out the new version of the RunequestGQS Sheet (updated 27/06) and am using the Full release version 

I've filled in the abilities and saved the sheet but when I open it I can see every ability has duplicated itself numerous times, this includes ones I haven't entered
see screenshot below

![capture](https://user-images.githubusercontent.com/206768/42038639-58bb6610-7ae3-11e8-975d-6ebb9fdeecc3.PNG)

**Comment by tauboy** [comment]
just wanted to give some more information on this, the character sheet above is a character I created last week using the old version of the sheet. I've created one today from scratch and the issue didn't happen, however the abilities only appear once you've saved the character twice before that you only have the headers for abilities
![capture](https://user-images.githubusercontent.com/206768/42056822-63dfa210-7b13-11e8-893d-d4f90dd0f6e1.PNG)

**Comment by Lockbox313** [comment]
The skills are added when you open the sheet, you must have closed it before it had finished setting it up.

**Comment by tauboy** [comment]
now I've worked out that you need to edit the sheet to essentially save it, I'm not getting this issue, the first time I opened the sheet, saw that there were no skills listed and manually added them.

then when I next opened the game all the abilities had duplicated themselves (see first pic)

anyway putting that aside it's a brilliant sheet and thanks for putting it together
