### ISSUE TITLE
Format change in chat

### ISSUE THREAD

**Issue by WallaceMcGregor** [Roll20/roll20-character-sheets#3882]
I don't know why, but today the chat rolls and "broadcast" have changed their format. It looks like a little "broken/ugly". It shows all table borders. I have watched in Eirendor/D&D5th and The Sprawl. Is this an issue or a change?

**Comment by WallaceMcGregor** [comment]
Well. Since nobody has commented anything (not even on Twitter) I have been looking at the forums and it seems that these changes will force the creators of the sheets to update them. I hope that @timdenee  has time to fix it again The Sprawl, because it was perfect.

**Comment by joesinghaus** [comment]
I fixed the roll template in #3896.

**Comment by joesinghaus** [comment]
The fix is now live.

**Comment by WallaceMcGregor** [comment]
Thanks. It's perfect again.

**Comment by joesinghaus** [comment]
@WallaceMcGregor it would be great if you could close this to shrink the list of issues.
