### ISSUE TITLE
The Sprawl UI Got Glitchy?

### ISSUE THREAD

**Issue by DeusExBrockina** [Roll20/roll20-character-sheets#3893]
Sorry for the bad title, I didn't know how else to explain... >.<

My Sprawl group went on a year long hiatus and recently started playing again, and we noticed that the cards for when a character rolls seem like they aren't displaying how they're supposed to/how they did when we played a year ago.

The other thing is that the boxes you can tick to measure your health seem like they're wider than they're supposed to be -- they go off the edge of the character sheet in the default width.

![weird grid](https://user-images.githubusercontent.com/5420197/42147301-b2921024-7d92-11e8-836d-7f37af797a47.png)
![wide health](https://user-images.githubusercontent.com/5420197/42147304-b5552ed6-7d92-11e8-9b10-ef6a0f03e7d1.png)

**Comment by joesinghaus** [comment]
@timdenee probably a result of roll20's CSS changes.

**Comment by joesinghaus** [comment]
Took some time to fix the roll template CSS in #3896.

**Comment by joesinghaus** [comment]
The fix is now live

**Comment by joesinghaus** [comment]
@DeusExBrockina it would be great if you could close this to shrink the list of issues.
