### ISSUE TITLE
Shadowrun Anarchy Sheet Elements Overlapping

### ISSUE THREAD

**Issue by DeusExBrockina** [Roll20/roll20-character-sheets#3915]
The section at the top of the sheet with the character's attributes appears to be misaligned, with the numbers appearing outside of their areas, and overlapping with (or being hidden behind) the dispositions section below.

![overlap](https://user-images.githubusercontent.com/5420197/42407853-7dbfcf18-8188-11e8-983c-fdcfa3ef23bf.png)

**Comment by Anduh** [comment]
Maybe @clevett would be interested in this? Most these Issues goes unnoticed, it's best to contact the sheet author or someone who have been working on the sheet in question.

**Comment by clevett** [comment]
Oh no!!! I bet the recent changes to R20 caused it. Thanks @DeusExBrockina for reporting it & @Anduh for pinging me. I'll get it fixed tonight. Updates will be added to the code push for next Tuesday.

**Comment by clevett** [comment]
@DeusExBrockina I put in the pull request today to fix this. It should be deployed on Tuesday.

**Comment by DeusExBrockina** [comment]
@clevett Cool, thank you very much!

**Comment by clevett** [comment]
You're welcome. Keep me posted if you have any suggestions or updates. I made a post for feedback on R20's Character Sheets.

**Comment by Anduh** [comment]
@DeusExBrockina you should close this issue if it have been fixed

**Comment by clevett** [comment]
Updated completed
