### ISSUE TITLE
Fellowship should be underneath "Apocalypse World Engine"

### ISSUE THREAD

**Issue by AuthorX** [Roll20/roll20-character-sheets#3944]
Fellowship character sheet was added but should be under the "Apocalypse World Engine" header as it uses the Apocalypse World Engine

**Comment by Anduh** [comment]
@Solarswordsman seemed to have missed this during the last update.

**Comment by Solarswordsman** [comment]
Yup, I'll make sure to add it as apocalypse world engine game with the next sheet push.  Apologies for any confusion!
