### ISSUE TITLE
ShadowrunAnarchy - Attribute tests broken

### ISSUE THREAD

**Issue by Chaithi** [Roll20/roll20-character-sheets#4049]
When clicking on an Attribute, such as wanting to do a AGI+AGI running test, clicking on Agility pops up a window asking for an attribute. Choosing Agility causes it to always roll STR + chosen attribute.

Needed behaviors:
For this game, there are several times that ATTR+ATTR tests are needed. Should be able to click on "Agility" for example, have a window pop up asking for 2nd attribute. Choosing Agility should roll Agility + Agility. Choosing WIL should roll AGI + WIL. 
Also, should be a "none" option so that if you are rolling an untrained skill you can roll just the attribute.

**Comment by clevett** [comment]
Oh no! I'll take a look at this. The intention is certainly for you to click the Attribute button such as is linked to Agility then the query pop up should let you select the 2nd attribute you want to roll with.

**Comment by clevett** [comment]
For sure! If that would get approved it would be utter hype. I'll go find it and upvote that. I am in the process of making a Shadowrun 5e Sheet & the new Warhammer 40k Wrath & Glory game also has a reroll mechanic.

**Comment by Chaithi** [comment]
Submitted a merge request with the fix. You have Strength as the first modifier on each attribute test. Also added a |None,0 option at the end to allow for untrained skill rolls.

**Comment by Chaithi** [comment]
Thank you for merging. How do I refresh my current sheets to use the new push?

**Comment by clevett** [comment]
Greeting @Chaithi 

Thanks for fixing that! The push will get deployed to the Roll20 app tomorrow morning. Unfortunately you cannot refresh the current sheet but rest assured tomorrow the fix you added will go live.

-Cassie

**Comment by clevett** [comment]
I did some spot checking for the fix and it appears working. Going to close this ticket. :)
