### ISSUE TITLE
WOIN character sheet has broken formatting

### ISSUE THREAD

**Issue by BlckKnght** [Roll20/roll20-character-sheets#4079]
The character sheet for the WOIN system has some severely broken formatting for the attributes on the main tab. One number (for Strength) is displayed off the edge of the sheet, and all the other attribute ratings are shown well to the left of where they should be. Here's a screenshot of the problematic section as I see it rendered in Firefox:

![woin character sheet formatting issue](https://user-images.githubusercontent.com/25556/44313198-d05f0c00-a3b8-11e8-84aa-02e9d93b80cd.png)

I've looked at the sheet's code, but I am not savvy enough with CSS to understand how the formatting was supposed to work and how it can be fixed. It may be that the increment and decrement arrows are not supposed to be shown for any of the numbers (the screenshot provided in the repository doesn't have them) but my token research shows that's a tricky thing to control with CSS in a cross-browser way.

There are also some other issues with the sheet that are not specifically formatting related, but I'll make a separate issue to report them, since they'll require a bit more work and maybe some understanding of the game's mechanics.

**Comment by Anduh** [comment]
Ping or contact the author/active editor, if you want this being potentially noticed/addressed in a timely manner.

**Comment by clevett** [comment]
@Newguy12354 Are you perhaps interested in these requests?

**Comment by Newguy12354** [comment]
@clevett

I only have very basic understanding of CSS, but I'll look into the formatting issue and see if I can do anything about it.

**Comment by BlckKnght** [comment]
It looks like @CoalPoweredPuppet is the original author of this sheet.
If anyone wants to discuss this and my other issue, I made [a post on the Roll 20 forums](https://app.roll20.net/forum/post/6714044/woin-character-sheet-formatting-issues-and-other-possible-improvements).

**Comment by clevett** [comment]
@Newguy12354 Thanks for the response. It looks like the original author fix the CSS issue. If you're interested in helping you might check out the post BlckKnght made on the Roll20 forums. By no means feel like you're under any obligation to do so. :)

**Comment by BlckKnght** [comment]
It looks like this formatting issue will be fixed by pull request #4185 .

**Comment by clevett** [comment]
Awesome! Thanks for letting me know. :) Always nice to close an issue.
