### ISSUE TITLE
[Das_Schwarze_Auge_5] add the data-i18n tags to the character sheet

### ISSUE THREAD

**Issue by dyvim** [Roll20/roll20-character-sheets#4087]
Can you please add the i18n data in the character sheet so that it can be translated in other languages (mostly english and french) ?

**Comment by Anduh** [comment]
Anyone could do this, following the wiki guide. You should tag/pin the author/active editor in this issue if you want this to be seen, or post about it on the forums for extra visibility.

 But the fact that you are here on github mean you probably are skilled ebough to do it yourself.

**Comment by clevett** [comment]
@Meteox 

Would you be interested in this?

**Comment by dyvim** [comment]
well I've tried to contact @Meteox on the mail adress he gave in the readme.md but I've had no answer.

I can try to add the i18n data, but it will be a long work (the html file contains 17 000 rows) and as it is my firts time i can make mistakes...

**Comment by dyvim** [comment]
well in fact i'm not sure @Meteox is the guy that has created the readme...
there have been other committers too : @GenX187 , @PJVin  and @wing-it  for example

**Comment by clevett** [comment]
You could also ask for some help over on the [Roll 20 Character Sheet forum](https://app.roll20.net/forum/category/277980).  Adding i18n is a simple but can be a tedious process. Particular if its in a language you are not already familiar with. Some one on the Character Sheet forum may be willing to help.

**Comment by Anduh** [comment]
On large sheet it might be smart to create a script to do this.

Hmm maybe it's possible to create a generic script to do this for any sheet...

**Comment by Meteox** [comment]
I'm in vacation right now. I will look into this when I'm back home at Sunday.

**Comment by Meteox** [comment]
I looked into it but it will take a while. 

And as far as I now are the english/French Version of the game a bit behind contentwise. I have currently  the core rule book, Compendium 1, Bestiary 1 and parts of Magic 1 & 2 and God 1 implemented. The as far as I know are the magic & god books not released in english and the current releases of the french version are unknown to me.

Implementing the translation could be difficult as there is already much stuff which has no official translation. And there will be more in the Shorter future as the Compendium 2 will arrive shortly and there are some books which are already released but not implemented e.g. the Bestiary 2.

I can make the i18n addition with no problem. But there will be much stuff which will need manual translation.

**Comment by dyvim** [comment]
FYI I've done the work for the first thousand lines and will make a pull
request ASAP (this evening if possible)

Concerning the french version and translation :the pdf file of core rule
book has already been released, the bestiary should follow in a few months.
the paper versions will be released in a few months too (before the end of
the year according to the editor)
Concerning the english version : core rule book, Compendium 1 and Bestiary
1 have been released already. God 1 will probably follow.

I suggest that we let the roll20 tool make the automatic translation and
correct it when the official version has been given.

BRgds

**Comment by dyvim** [comment]
pull request #4122 done

**Comment by Meteox** [comment]
Feedback of my current progress:
I added the i18n tags to the first 13000 lines so far. ~3000 lines left. 
Should be finished by end of the week.

**Comment by dyvim** [comment]
Great!

**Comment by dyvim** [comment]
Hello,

Any news? Did you manged to complete the file?

Regards

Dyvim

**Comment by dyvim** [comment]
@Meteox , are you still alive?

**Comment by dyvim** [comment]
Oh cool I've never thought I can see your repository.

Did you test the command to generate the translation.json ?
I think you can commit your actual work (after having generated the translation.json file) and make a pull request. The rest can probably wait till you add the time to do it.
When it will be merged to the main branch, I will be able to begin the translation work.

Thanks for your work.

**Comment by Meteox** [comment]
Yes I did test the command.

Personally I do not want to commit it uncompleted. I will look if I can complete it next week and will upload and commit it then.

**Comment by dyvim** [comment]
OK. Thanks

**Comment by Meteox** [comment]
pull request with finished files has been made
https://github.com/Roll20/roll20-character-sheets/pull/4248

**Comment by dyvim** [comment]
Great!!!

**Comment by clevett** [comment]
Fantastic job working together on this. Are we good to close this issue ticket?

**Comment by dyvim** [comment]
Meteox did all the job :)
Yes the issue ticket can be closed.
