### ISSUE TITLE
[Warhammer Fantasy 2nd edition] Ulrics Fury Test is pure characteristic without bonus.

### ISSUE THREAD

**Issue by realitor** [Roll20/roll20-character-sheets#4100]
The calculation for Ulric's Fury isn't correct. The test is missing the individual bonus from the previous WS test. I didn't test it for BS and Magic. Verify WFRP2 Core Rules page 130: "Roll to hit again, using all the same modifers as for the initial roll.".

**Comment by Almos80** [comment]
This will be corrected in a new update, most likely in the coming weekend. I will probably add a new button specifically for Ulric's Fury to resolve this issue.

**Comment by clevett** [comment]
I'm going to close this issue as it appears to have been fixed in a previous merge.
