### ISSUE TITLE
[Warhammer Fantasy 2nd edition] Initiative rules are false.

### ISSUE THREAD

**Issue by realitor** [Roll20/roll20-character-sheets#4101]
After update the sheet using the old initiative rules and not the rules from WFRP2. 

Before update: Agi+1d10
After update: AgiBonus +1d10

Please verify WFRP2 Core Rules p125: "To determine the order Initiative, 1d10 is rolled and the result is added to the character’s Agility Characteristic.".

Suggestion: Use the settings tab to switch between Initiative rules. Set WFRP2 rules as default.

**Comment by Almos80** [comment]
This was a houserule that mistakenly crept into the code from my private version of the sheet. I will correct it in the next update, and add my houserule as an option.

**Comment by clevett** [comment]
I'm going to close this issue as it appears to have been fixed in a past merge. If it needs to be opened again let me know.
