### ISSUE TITLE
[Starfinder Official] Attacks do not pick up BAB value until you change BAB on your class

### ISSUE THREAD

**Issue by OwlManAtt** [Roll20/roll20-character-sheets#4165]
I am using the Starfinder Official sheet.

A few party members & I have experienced an issue when adding new entries under the 'Attacks' section -- the base attack bonus is stuck at 0 and the sheet will not update this unless you go to the 'Class' section and modify your base attack bonus (BAB) value.

Here is the troublesome BAB field, highlighted in red:

![sf_bab_bug](https://user-images.githubusercontent.com/6432/45250217-438eda80-b2f4-11e8-96d2-d8cda8a41c5e.png)

Oddly, when you minimize the attack entry, the 'Attack' value it shows in the table correctly reflects the BAB. The rolls include it as 0, though.

I would take a stab at fixing this & submit a PR, but I don't know how to test changes to these sheets? If anyone can point me to a dev setup guide, I'd be happy to try fixing it!

**Comment by Kurohyou** [comment]
Should be fixed

**Comment by clevett** [comment]
I'm closing this issue as it should be fixed. Feel free to open it again if it is not. :)
