### ISSUE TITLE
[Basic Fantasy RPG - Expanded] Header image is broken

### ISSUE THREAD

**Issue by drockod01** [Roll20/roll20-character-sheets#4250]
The image on the sheet needs to be changed, since the source image at imgur.com/TprZw4p.png was removed, causing the sheet's image to be replaced with the default "removed" picture from imgur.
The necessary image is on github at: https://raw.githubusercontent.com/Roll20/roll20-character-sheets/master/Basic%20Fantasy%20RPG%20-%20Expanded/bfrpg.png

**Comment by clevett** [comment]
#4273 has fixed the image issue.
