### ISSUE TITLE
Ship Damage Rolls

### ISSUE THREAD

**Issue by CrimsonGuyver** [Roll20/roll20-character-sheets#4408]
https://github.com/Roll20/roll20-character-sheets/blob/0e86fb7e4e7705d0261a03aa7cd40151ff1ffc04/Star%20Trek%20Adventures%20Official/Star%20Trek%20Adventures%20Official.html#L711

I am Using this character Sheet in a Game i am playing we have noticed that every time we roll ship weapon damage that the roller rolls a lot more dice than is required. When I inspected the roll i found that there is a call for @{damageRoll} twice for this function when i delete the extra @{damageRoll} a rolled damage it rolled the correct number of Dice. May I advise that for the next sheet update you amend this line.

**Comment by clevett** [comment]
Updated last Tuesday. Let me know if you have any further trouble.
