### ISSUE TITLE
[The Veil] Allow translations

### ISSUE THREAD

**Issue by WallaceMcGregor** [Roll20/roll20-character-sheets#4439]
Could be possible update **The Veil** sheet by @plexsoup to allow translation?

**Comment by Anduh** [comment]
Anyone can start working on placing the translations tag into any sheet here. [The wiki have a guide for how this is done.](https://wiki.roll20.net/Character_Sheet_i18n)

**Comment by WallaceMcGregor** [comment]
> Anyone can start working on placing the translations tag into any sheet here. [The wiki have a guide for how this is done.](https://wiki.roll20.net/Character_Sheet_i18n)

I am not a Pro user, just a Plus one. I can translate sheets (I've done it before) but I can not modify or upload a sheet.

**Comment by Anduh** [comment]
If you do the legwork of palcing the translation tags in a version of the html sheet, some of us Pro users will hapily generate the needed translation.json file through Roll20.
Anyone can update the sheets on roll20's github, but we other can do do the upload stuff if you do the manual work for inserting translation tags. I have a automated script I've been working on so I could provide a partial start for you to improve in a day or so.

**Comment by WallaceMcGregor** [comment]
I apreciate that but I am not a really programmer. I do not know how to do that and I am not a The Veil player, I am just "preparing" the way when the future spanish version come up.

**Comment by Anduh** [comment]
There is zero programming skills involved, it just a matter of inserting ` i18n-data="some-tag-name"` in the places the guide I linked to tells to put them. By virtue of finding Github and the roll20 repository makes you qualified enough. But oh well, I'll run my script and leave a template that people can start from when someone picks up to do it.

**Comment by AuthorX** [comment]
I looked at the sheet to see if I could just add the translation attributes, but the sheet uses some HTML and CSS tricks that will break the translation method. For example:

<div class="sheet-popupHelp">Veil & Cascade<span>The original RPGs by Fraser Simons</span></div>

If you create a translation attribute for the <div> tag, the translation will include and override the <span> tag. Putting "Veil & Cascade" into a separate span tag would fix that, but mess up the CSS creating the popup effect.

I would recommend asking the original author, Plexsoup and asking them to add translation attributes, as they already know how the HTML and CSS work and may be able to modify it more easily. Someone else could do it if they have the time and inclination to start modifying the HTML, but I don't at the moment.

**Comment by joesinghaus** [comment]
You can actually put spans inside the values of translations, too.

**Comment by WallaceMcGregor** [comment]
Thank you very much.

The spanish edition have to comes out but I'll use a fan translation to watch if everything is ok.

Regards

**Comment by WallaceMcGregor** [comment]
Ok. Here is the PR for the   translation.

#4531

**Comment by clevett** [comment]
That was fast. I'll take a quick look at the CSS this weekend and do some updates for Spanish as needed. :)

**Comment by lindybombette** [comment]
Hi, this seems to have broken my veil game. Crashing my roll20 game at startup.

I checked the console and it's raising this error:

GET https://app.roll20.net/editor/startjs/?timestamp=1545242932&disablewebgl=false&forcelongpolling=false&offsite=false&fbdebug=false&forcetouch=false 500

Can you revert the change back to the last working state?

**Comment by clevett** [comment]
Greetings @lindybombette  I am so very sorry. :( It appears some of the translation files did not generate for some reason. I'll put in a pull request for a fix to this tonight but I'll have request an update tomorrow during working hours.

**Comment by lindybombette** [comment]
Thanks for making the fix!

**Comment by clevett** [comment]
@lindybombette 

A dev saw your issue and fixed it. You should be able to use the Veil sheet in English again.

**Comment by WallaceMcGregor** [comment]
I have seen the new Spanish version of the sheet. There are fields that can not be translated.

https://i.imgur.com/UV9lRNj.png

And I don't know the game system but I think the chat output doesn't work well.

https://i.imgur.com/lbEBtPz.png

**Comment by clevett** [comment]
Thanks for the screenshots. I suspected this might be the case and it would need a second pass. I'll see what else we can potentially add translations into. Sheets do best when they are built to be translated so we may be limited on what we can do.

**Comment by clevett** [comment]
Greetings @WallaceMcGregor 

I think this is about as done as I'm going to get it. The text your seeing in those screen shots aren't text that can be translated via the translation keys at this time. If the original author had shown interest in doing some updates I might advise them but additional fixes are beyond the time I have to offer for the project. 

Is the current changes good enough to close this issue?

**Comment by WallaceMcGregor** [comment]
Ok.

I think the "malfunction" of the chat outputs rolls is out of your hands, right? In that case you can close the issue.

Thank you so much.

**Comment by clevett** [comment]
Yep. It would need a few hours of work to write & test a new rolltemplate. If a sheet author comes along who wants to do it, I would be willing to advise them. Its a bit more than I would like to do myself. :)

Thanks to your post here the sheet is off to a good start. It was a pleasure working with you. I also have written and/or support the **Shadowrun5thEdition**, **ShadowrunAnarchy**, **ReachofTitan**, and **SavageWorldFrench** sheets. If you translate any of those let me know. I will be happy to make adjustments to them for Spanish.

**Comment by WallaceMcGregor** [comment]
The pleasure was mine. Thanks to you.

I have no idea about that games. But Savage Worlds I am almost sure already have a spanish version. Unfortunately I don't have programming knowlege (yet) except to translate some sheets. I also made The Sprawl, Eclipse Phase and Call of Cthulhu 7th.

Regards (and excuse my english).

**Comment by clevett** [comment]
The Savage Worlds Tab sheet has some Spanish translations. I'm working to convert the SavageWorldsFrench sheet into a universal one as its my favorite sheet for the system. :) I did the English translations on it.

Shadowrun5thEdition, ShadowrunAnarchy, & ReachofTitan already have translation keys so they just need some one to edit them on Crowdin. Are you on Crowdin? If not we should get you added.

Your English is better than my Spanish. Feel free to use your preference :) I am currently living in Chile to learn Spanish and could use the practice.

**Comment by WallaceMcGregor** [comment]
Ni siquiera sé lo que es Crowdin.

I don't even know what Crowdin is.

**Comment by clevett** [comment]
[Crowdin](https://github.com/Roll20/roll20-character-sheets#internationalization--translations) is the website we use for Translations. :) It makes translating easier. 

Email team@roll20.net and tell them you'd like to help translate character sheets to Spanish. You can tell them Cassie sent you. 

Nosotros necesito más espanol!
