### ISSUE TITLE
Dark Heresy 2ed not rolling weapon hits

### ISSUE THREAD

**Issue by ekampp** [Roll20/roll20-character-sheets#4444]
Hey there. 

Today I filled out my Dark Heresy charactersheet on Roll20, and found out that it rolls weapon damage just fine, but that weapon hit macros are not working at all. 

I recorded my screen while I interacted with Roll20 to document the problem. 

https://www.dropbox.com/s/tpkr6s6xfe02jtm/Screen%20Recording%202018-11-24%20at%2021.47.42.mov?dl=0

**Comment by clevett** [comment]
Greetings @ekampp ,

Its on my todo list for early next year to get all the sheets requiring an API to be updated or deprecated as part of our new sheet standards. There is a second Dark Heresy sheet in the drop down. You might give that one a try.

Thanks,
Cassie

**Comment by ekampp** [comment]
Perfect. Thanks. I will use another until then.
