### ISSUE TITLE
Mekton Zeta Equipment Name Width

### ISSUE THREAD

**Issue by mrianmerry** [Roll20/roll20-character-sheets#4501]
The width for the Equipment name table row is not set to 100% of the available space.
I did some experimentation with Chrome's Inspect tool, and the value is set to 120px.

Here is all of the information that I found, along with a screenshot of the issue.
<img width="470" alt="equipment name entry" src="https://user-images.githubusercontent.com/25342733/49932391-cfe70580-fec0-11e8-964c-8667c9793d85.png">
<img width="321" alt="incorrect styling" src="https://user-images.githubusercontent.com/25342733/49932477-07ee4880-fec1-11e8-8d5b-3816ebc81bc3.png">

After setting the width to 100%, the following was achieved:
<img width="893" alt="equipment name entry 100 width" src="https://user-images.githubusercontent.com/25342733/49932508-18062800-fec1-11e8-8d65-b567219c210c.png">

Further issues detected:
* The _"Endurance"_ skill has no entry in the `Total` column
* Each Intelligence skill beneath _"Know Language"_ is rolled with the word _"Know"_ before it in the chat log - not an issue as such, but just a cosmetic thing I thought could be pointed out
* When rolling _"Jury Rig"_, the chat log displays _"First Aid"_ in the message
It does still use the correct values for the _"Jury Rig"_ skill
* The skill _"Photography & Film"_ is mistyped as _"Photgraphy"_
* When rolling _"Endurance"_ and _"Aircraft/Shuttle Pilot"_, you get errors in the chat log as below. This persists even with a non-zero skill level.
> No attribute was found for `@{Character|Level-Endurance}`
No attribute was found for `@{Character|Attribute-Aircraft_Shuttle_Pilot}`

**Comment by mrianmerry** [comment]
_(Bonus while anybody is looking at the above: There appears to be no section for putting your character's current funds into your sheet. Not sure if intentional or not!)_

**Comment by clevett** [comment]
@CoalPoweredPuppet I think this was one of yours. Are you interested in doing some updates?

**Comment by CoalPoweredPuppet** [comment]
I will see what I can do.

**Comment by mrianmerry** [comment]
Fantastic!
Also works a charm on mobile, which was an unexpected joy - first time I’ve logged into a Roll20 game on one.

**Comment by mrianmerry** [comment]
Hi @CoalPoweredPuppet 
After playing a session, my group and I discovered some other issues with the sheet which are hopefully simple to fix. I thought I'd put them back in here instead of raising another issue.
_(I'll also update the main issue post to reflect everything once I'm done!)_

* The _"Endurance"_ skill has no entry in the `Total` column
* Each Intelligence skill beneath _"Know Language"_ is rolled with the word _"Know"_ before it in the chat log - not an issue as such, but just a cosmetic thing I thought could be pointed out
* When rolling _"Jury Rig"_, the chat log displays _"First Aid"_ in the message
It does still use the correct values for the _"Jury Rig"_ skill
* The skill _"Photography & Film"_ is mistyped as _"Photgraphy"_
* When rolling _"Endurance"_ and _"Aircraft/Shuttle Pilot"_, you get errors in the chat log as below. This persists even with a non-zero skill level.
> No attribute was found for `@{Character|Level-Endurance}`
No attribute was found for `@{Character|Attribute-Aircraft_Shuttle_Pilot}`

**Comment by CoalPoweredPuppet** [comment]
...joy.  I will work on it.

In the mean time, I can set up a game under my account, make you the GM, and let you run a game if timing is an issue

**Comment by mrianmerry** [comment]
... sorry for being a pain 😬

There's no need to rush, though! We're alternating games between sessions, so it might be a while before we get back to Mekton....

**Comment by Anduh** [comment]
This was fixed by CPP with PR #5322 back in 2019.
@mrianmerry this issue can be closed.
