### ISSUE TITLE
[SavageWorldsFrench] "Conduite" displays "Combat"

### ISSUE THREAD

**Issue by Arnok13** [Roll20/roll20-character-sheets#4508]
Hi,
the display for Conduite Skills is now Combat (we can have two times Combat skill) :

data-i18n="combat">Conduite</button>

there is a mistake in HTML file

Best regards,
Arnok

**Comment by clevett** [comment]
I thought I fixed this in my last push. I'll get it fixed this weekend.

**Comment by Arnok13** [comment]
thanks.

**Comment by clevett** [comment]
You're welcome. PR 4509 should fix this. I found the tags wrong in two places.

**Comment by Arnok13** [comment]
the OPTION without a ">" at the end ?

**Comment by clevett** [comment]
Is there an option without an ">" ? 

The two things I fixed were the data-i18n="" were using "combat" instead of "conduite". Simple mistake when I put in all the tags.

**Comment by Arnok13** [comment]
Visual Studio Code show me 2 OPTIONS without ">" (but can't rember where i fixed them when proptotyping a SWADE version)

**Comment by clevett** [comment]
Yep! I found them. I'll push an update for those as well.

**Comment by Arnok13** [comment]
you're the best ;)

**Comment by Arnok13** [comment]
i'm looking for adapting this sheet to the new edition of Savage World : Adventure Edition and may be to introduce new settings (Last parsec, Flash Gordon, Highspace, Fear Agent, Rippers, ...). But i have not practised HTML for a long time.

**Comment by NathaTerrien** [comment]
@Arnok13 I've got plans to do the SWADE adaptation begining of 2019, and more (notably replacing some dynamic calculations by sheet workers function).
If you can wait (and have not practiced sheet programming), I would suggest waiting for this update :)

**Comment by Arnok13** [comment]
great news !

**Comment by clevett** [comment]
Changes for this should be live. Can you double check this is working?

**Comment by Arnok13** [comment]
Seems perfect !

Arnok

Arnaud

________________________________
