### ISSUE TITLE
[Godbound] Attribute rolls don't include Modifier

### ISSUE THREAD

**Issue by zarlor** [Roll20/roll20-character-sheets#4557]
When rolling for an Attribute it doesn't automatically include the Mod in the roll.

**Comment by Almos80** [comment]
I'm not sure I understand this issue. Attribute checks aren't supposed to include the attribute modifier. Attribute checks in Godbound are made with "1d20 + situational modifiers" vs TN = 21 - Attribute Score.

**Comment by zarlor** [comment]
My bad. Double-checking the rules you are, indeed, correct and my group has been doing it wrong! Sorry about that.
