### ISSUE TITLE
[Godbound] Feature Request: "Gift Granted AC of 3" to Armor options

### ISSUE THREAD

**Issue by zarlor** [Roll20/roll20-character-sheets#4558]
Would it be possible to add under the available Armor a "Gift Granted AC of 3" option since several Gifts provide for a base AC of 3 (I only ever see it for AC3, no other AC value). Dex mod should still apply but no save penalty would be needed, just like None or Light armor is now.

**Comment by Almos80** [comment]
This is an interesting suggestion, and I'll definitely add it as an option for the drop down list in the next update. Meanwhile, there's an input to add a free "bonus" to AC. Adding 6 to no armor would be the same as setting the base AC to 3. Alternatively, choosing heavy armor without checking any save penalty would also have the same effect.

**Comment by Almos80** [comment]
https://github.com/Roll20/roll20-character-sheets/pull/4593
