### ISSUE TITLE
[Godbound] "Attacks" heading may be misleading?

### ISSUE THREAD

**Issue by zarlor** [Roll20/roll20-character-sheets#4559]
Attacks appear to really just be damage rolls which make it a tad confusing. The section seems useful for a Gift or Miracle or the like which auto-hits but it makes it seem like it should just be for any "attack" which it isn't and has caused some confusion for my players. Perhaps changing the name of that section to something like Damage Rolls, or Auto-Hit Attack Rolls or something? Also setting it so you can type in the damage rather than using a drop-down box (just like damage is under Weapons, which, BTW, could probably be better labeled as Attacks, I would think).

**Comment by Almos80** [comment]
This is a good suggestion, and it's helpful to know how groups react to the sheet without guidance. Making it intuitive is important to me. I'll look into doing this for the next update. Damage is hard to handle in Godbound since multiple damage dice are handled independently.

**Comment by Almos80** [comment]
https://github.com/Roll20/roll20-character-sheets/pull/4593

**Comment by zarlor** [comment]
Looks great now!
