### ISSUE TITLE
[Godbound] "Additional Attacks" relabeled to "Multi-Die Damage Attacks"?

### ISSUE THREAD

**Issue by zarlor** [Roll20/roll20-character-sheets#4560]
The Additional Attacks section seems a little confusing as a name as well. Maybe something that better describes the use, like "Multi-Die Damage Attacks" or something like that? It's a fairly useful section for things like Divine Wrath or Corona of Fury. Heck, you might even auto-populate it with those 2 as examples if you can create multiple lines there. Indeed, having multiple lines just like the current "Attacks" section would allow for setting up the names of Gifts or whatnot that are multi-die damage attacks that are already set and ready to go. Additionally it would be awesome if you could work out a way to also reference the damage table for the rolls (and even crazier would be if you could add an Attribute to the mix, like for Attacks, that would auto-add the modifier to the most optimal single die roll... that's probably a pretty pie in the sky request, though.)

**Comment by zarlor** [comment]
Agreed that keeping it usable for free players is good. Still, would it be possible to have a couple of pre-filled versions of the current attack for Divine Wrath and Corona of Fury? And even the possibility of adding lines of your own. Obviously all you're really doing is making a new line with the number and type of dice to roll, but being able to see what those attacks are on the sheet can still be a really helpful reminder. I'm not at all familiar with coding these sheets, though, so my apologies if doing that would require the API to handle it.

**Comment by clevett** [comment]
Greetings @zarlor ,

An update went out that was reference as a fix for this issue. Could you check to see if this is satisfactory to close this issue?

Thanks,

Cassie

**Comment by zarlor** [comment]
Sorry, yes, I'll update all of the ones I put in.
