### ISSUE TITLE
[D&D 5e OGL] Carrying Capacity Modifier does not process decimals (again)

### ISSUE THREAD

**Issue by ToxioD** [Roll20/roll20-character-sheets#4562]
> On the 5e OGL sheet, the "Carrying Capacity Modifier" field in PC settings only accepts integers, not decimal numbers. If I want, for example, the encumbered weight of a 10 str character to be 80 instead of 50, I would put "*1.6", however this doesn't work. If I want to halve a character's carrying capacity, this does not work either.

Even though this ticket was closed:
#3797 
the issue still appears.

**Comment by clevett** [comment]
This should be fixed now with PR #4863 . If its still an issue feel free to reopen it. :)
