### ISSUE TITLE
[Fragged Empire] Trait slots for vehicle skills are botched

### ISSUE THREAD

**Issue by Nitroxylin** [Roll20/roll20-character-sheets#4583]
On the noncombat page of the char sheet, there are slots for traits; one for each Primary (Everyday and Professional) skill, two for each Personal Combat Skill, two for each Vehicle skill. The last ones are botched; the paired slots for each skill are linked - they both contain the same info at all times. Write into one, and the other one repeats; delete from one, and the other one empties as well.

**Comment by Anduh** [comment]
@Nitroxylin was this issue solved with #4679 ? If so, this issue could be closed.
