### ISSUE TITLE
Genesys - Images broken

### ISSUE THREAD

**Issue by clevett** [Roll20/roll20-character-sheets#4590]
Imgur links for background images are no longer functioning. The original images need to be uploaded to GitHub and the links fixed. If that fails then a background color may substitute. 

@KnowledgeRhino , @salmelo 

Do either of you fine sheet authors have backups of these images? Would you find fixing this if possible?

Thanks,
Cassie

**Comment by Anduh** [comment]
I can say that timetravel with [Wayback Machine](https://web.archive.org) came up empty for the eight or so imgur urls I tried. Previously I've manage to fix one or two sheets this way but that have seemingly only worked when they wheren't uploaded to large image-sharing sites like imgur. :man_shrugging:

**Comment by apathy-dude** [comment]
Here's a link to the symbols and dice as png: https://drive.google.com/drive/folders/1S8eR1nYHk9OcSj3p3WXCUFdC5TwPne-K

I'll work on it tonight unless someone steps in before me.

**Comment by clevett** [comment]
@apathy-dude 

I'll keep an eye out for this pull request. If you can get it done tonight before I merge that would be ideal but if not I'll see if I can get a special push out this week for it.

**Comment by apathy-dude** [comment]
Just getting to the code now.  I doubt it'll be ready in time for the merge.

**Comment by apathy-dude** [comment]
Opened related issue in the Genesys api script since it seems to be affected there as well.

I won't be doing a pull request for this issue until I get the api side figured out as well.  Likely tomorrow.

**Comment by clevett** [comment]
Thanks for working on that. :)
