### ISSUE TITLE
Playable Legend (Mongoose) CS

### ISSUE THREAD

**Issue by Dave2211** [Roll20/roll20-character-sheets#4602]
Any chance of this happening? Please :o)

**Comment by Anduh** [comment]
You have better change of getting traction for this request go and [ask in the Sheet Request thread](https://app.roll20.net/forum/post/1503047/sheet-request-thread-consolidated-mk-i) about this, very few people brower the Issues here.

**Comment by Stexinator** [comment]
@Dave2211  if this is resolved, please close it
