### ISSUE TITLE
Warhammer 40k Wrath & Glory - French & Spanish

### ISSUE THREAD

**Issue by clevett** [Roll20/roll20-character-sheets#4636]
@dyvim & @WallaceMcGregor 

Could I beg your help to translate this [character sheet](https://github.com/Roll20/roll20-character-sheets/tree/master/Warhammer40k-WrathandGlory)? This sheet was an exercise to try to make a character sheet , roll templates, and other text 100% translatable. I am in need of translated versions to test with. :)

Anyone else who would be willing to help translate the sheet is most welcome.

Thanks,
Cassie

**Comment by dyvim** [comment]
I'll try to help too.
Is it an english sheet that needs to be translated in french and spanish or
the contrary?

BRgds

Le mar. 29 janv. 2019 20:30, Cassie Levett <notifications@github.com> a
écrit :

**Comment by clevett** [comment]
Greetings!

Thanks Dyvim! It is an English sheet that needs French translations. Its currently in Crowdin and I added context to a few entries. :)

**Comment by dyvim** [comment]
Done except for 3 words for which I need context.
I've seen a typo for "malignancies" in the translation.json.
It won't be an official translation as the game has not yet been official
bought by an editor and translated in french. Some words will probably need
to be changed if the game is published in french.
I've tried to use the good old terms from Warhammer Fantasy RPG when it was
possible. (as I've done for the last version of WFRPG)

BRgds

Thomas Coquery



Le mer. 30 janv. 2019 à 05:10, Cassie Levett <notifications@github.com> a
écrit :

**Comment by clevett** [comment]
WallaceMcGregor,

I can help with this. Can you send me an email at cassie@roll20.net ? I will get you a proper invite to the Spanish translations. 

-------

Thomas,

I added more context in Crowdin and also fixed that typo on my fork for the translation & en.jsons. This unofficial translation is very helpful. :) The fr.json will let me pull the entries you have translated and use them in the sheet. 

Thanks,
Cassie

**Comment by clevett** [comment]
Thanks again for the help! I am going to close this ticket. I have project cards open for myself to make CSS adjustments for French & Spanish. :)
