### ISSUE TITLE
[Low Fantasy Gaming] Adding default values to TF & GS fields?

### ISSUE THREAD

**Issue by Anduh** [Roll20/roll20-character-sheets#4835]
The attribute/skill rolls on the sheet don't function if the TF & GS fields are left empty, and for the everyday users it's not obvious this is the problem. [Forum thread about one user who don't know what's the problem](https://app.roll20.net/forum/post/7288714/bug-low-fantasy-gaming-sheet-has-not-been-working-correctly-since-februari-update)

The Readme nor the free LFG pdf mentions what TF or GS could stand for, so people who haven't seen the Deluxe edition of the rulebook have no idea what's wrong with their sheet. I haven't played the game, but after first looking at the readme, the free rulebook pdf and the sheet code, I didn't manage to understand waht they where for, and only after looking at the git history of the sheet did I find it adressed in the PR by dedurtett.

So I'd suggest to give then default values of 1 & 20 if nothing else, and include some documentation of what the numbers represent. It's a minor thing, but would make using the sheet smoother if you don't have to fill all those fields manually with every new sheet you create. Relating to that, it might be a good idea to give the attributes& attribute max values some default values as well but likely isn't as important as they would need to be filled by the users anyway with whatever stats they've generated for themselves. 

I tagged @dedurrett who made the changes, and is likely best suited to address this issue.

**Comment by dedurrett** [comment]
Thanks for bringing this to my attention. Default values have been added!

**Comment by Anduh** [comment]
Great!

Will you mention them in the documentation or add comments to the code so people have easier to figure lut what they represent? There will probably be more people who doesn't immidielty realize what the acronyms stand for, at least they weren't common enpugh to find on the pdf or on a web search related to the rpg.

**Comment by Anduh** [comment]
Default values added as well as clarifications for the stats added to Readme
