### ISSUE TITLE
Pathfinder Official: Armor Class is broken

### ISSUE THREAD

**Issue by geoidesic** [Roll20/roll20-character-sheets#4846]
Add and remove armor a few times and it totally messes up the AC and won't recalculate it correctly. For example I had a +5 DX modifier, added leather armour, gave me 17 AC, removed the leather armour and now it gives me 13 AC, saying the ability mod is 3. Can't find any way to get it to recalculate correctly.

**Comment by NathaTerrien** [comment]
@geoidesic 
Thanks for you feedback but I'm not able to reproduce the problem.
Are you sure your character is not overloaded (that would reduce DEX mod also) ?
Or have another armor checked as equiped?
Or a condition?
Could you try adding another armor, and/or change your DEX temporarily to provoke an AC recalculation, please.

**Comment by geoidesic** [comment]
@NathaTerrien My bad. A couple of gotchas here:
 
1. I didn't realise that it adds encumbrance penalties to AC
1. To remove armour one has to remove it from both the Armor list and the Gear list it seems.
