### ISSUE TITLE
Numenera_NathasNumenera_English missing .JS file

### ISSUE THREAD

**Issue by mattbell69** [Roll20/roll20-character-sheets#4875]
The Readme.md quotes a .JS file that is needed by the API, but this cannot be found. When clicking on the link it throws a 404 error.

Does someone have a copy that could be submitted back to the project?

**Comment by NathaTerrien** [comment]
Hi. You may try to use this one : https://github.com/Roll20/roll20-api-scripts/blob/master/Numenera_Natha/4.8/Numenera_Natha.js
But I must say I don't maintain this sheet for a long time now, and recommand using the Cypher System one (which has a Numenera "theme") and a companion script (that can be found in the RolL20 script library).

**Comment by mattbell69** [comment]
Hi @NathaTerrien 
Thank you for this. I will have a look at the Cypher System one as you recommend. Maybe that is all I need to do.

**Comment by clevett** [comment]
I'm going to close this issue as it appears answered. If it needs to be open again just let me know.
