### ISSUE TITLE
[D&D 5e OGL] Class Resource / Other Resource disappears unless it has a name

### ISSUE THREAD

**Issue by itamarcu** [Roll20/roll20-character-sheets#4890]
When trying to add more Class Resources or Other Resources, the small box will disappear immediately after setting the value or the maximum value of the resource, unless it was given a name.

The same issue was reported here on reddit:
https://www.reddit.com/r/Roll20/comments/7ikti6/issue_with_saving_other_resources_in_5e_ogl_sheet/
And here's a gif - http://gph.is/2jctTkx

There's a workaround, which is to edit the resource name first, and only then the value. However, the bug still exists.

**Comment by clevett** [comment]
Greetings @itamarcu 

I'll put this on my bug list to take a look at this. Repeating fields are suppose to disappear when data isn't data entered in order to prevent a lot of empty ones. However the 5e sheet is being over zealous with this behavior.

Thanks for reporting this,
Cassie
