### ISSUE TITLE
[Low Fantasy Gaming] Crit damage: Has to be filled manually.

### ISSUE THREAD

**Issue by Dekstier** [Roll20/roll20-character-sheets#4985]
The way attacks look right now on the sheet:
![image](https://user-images.githubusercontent.com/49796099/56442798-4625c980-62f2-11e9-830b-33f67577768a.png)

**The issue** is with the field: 'Crit Dmg'.
The rulebook says: “Critical hits automatically cause maximum damage + half your level (round up) ~ p52 of rulebook”

Right now this has to be filled manually. Is it possible to automate this field? 

Tagged @dedurrett who has worked on this sheet before.

**Comment by Anduh** [comment]
> “Critical hits automatically cause maximum damage + half your level (round up) ~ p52 of rulebook”
I assume "maximum damage" means the max roll of the base dmg, so in you above example, the character is either level 1 or 2, given that  1d4 base dmg results in 4 + 6 = 6 Crit dmg.

Sure, that sounds possible to automate.

**Comment by dedurrett** [comment]
I'll take a look, but given the freedom for die expressions in the base damage field it would be dangerous to make assumptions and try to parse for calculation of the max damage. The functionality provided mimics what I saw in the 4E sheet (the only other system I've played where crits result in "max" damage instead of extra damage).

**Comment by Dekstier** [comment]
@Anduh, It would actually be Str mod + max roll + half level. 

@deburrett, you do make a fair point. The system gives players a lot of freedom to incorporate their own  created character improvements. A player could change the way crit damage works for example. 

Would it be better if i close this issue or do you have an idea to make this work?

**Comment by clevett** [comment]
Greetings,

Per @dedurrett  suggestion in #5083 , I am going to close this issue. This suggestion, while a good one, is viable to implement at this time. If more intricate dice parsing options come along we it could be evaluated again. :)

Thanks,
Cassie
