### ISSUE TITLE
[Low Fantasy Gaming] Initiative: suggested changes.

### ISSUE THREAD

**Issue by Dekstier** [Roll20/roll20-character-sheets#4986]
When rolling initiative it is displayed as followed:
![image](https://user-images.githubusercontent.com/49796099/56443054-35c21e80-62f3-11e9-9cf2-f59cd4450aef.png)

There are **two** noticeable issues right now:
**1. When rolling initiative the character is not automatically added to initiative.** I have seen this functionality on other sheets. Is it possible to add the same here? It would improve the games happy flow as the GM currently has to manually add players to initiative.

**2. To determine the initiative order this system only requires a 1d20 without modifiers.**
The rules say:  "Each player rolls 1d20 for their adventurer, and the GM rolls for the monsters. Resolve Turns from Highest to Lowest. ~ p44 of rulebook".

Tagged @dedurrett who has worked on this sheet before.

**Comment by Anduh** [comment]
1. Yes, it should be possible. It seems some commented out code called "Old Initiative" did have the `&{tracker}` that would add initiative rolls to the tracker. 
2. Personally it sounds odd that there exist no bonus modifiers to initiative, but if that's the way the rules are it certainly sounds it should be changed. It's always possible to make adding modifiers an option, even if it might create extra work. A sheet should certainly function by the official rules.

**Comment by dedurrett** [comment]
Gents-
Currently the sheet supports the initiative procedures laid out in the Deluxe Edition of LFG, which make it a Dexterity attribute check; resolved in groups based on pass/fail of the check without individual initiative numbers. The previous method is still listed as a variant rule, but I was not able to include that option on the sheet in a way that I liked. I have made some other tweaks to the sheet and will take another look at integrating it before I submit the changes.

**Comment by Dekstier** [comment]
@Anduh, you make a very good point about modifiers. For instance when a character currently has a dagger drawn he/she gets a small bonus to initiative. 

@dedurrett, thank you for explaining i did not know that initiative was different in the Deluxe Edition (I don't own them). Thanks for your hard work!

**Comment by clevett** [comment]
Closing this issue as the feature will be implemented in pull request #5083 going out tomorrow.

Thanks for working together on this. :) Its heart warming to see everyone improving community sheets.
