### ISSUE TITLE
[Cypher Systems by Roll20] Initiative

### ISSUE THREAD

**Issue by homiedion** [Roll20/roll20-character-sheets#5000]
When rolling for initiative the sheet does not factor in assets or effort.
Only the roll bonus.

**Comment by NathaTerrien** [comment]
Well, the sheet implements a not very true to the rules behaviour. The roll template will take in account the difficulty beaten with assets and efforts, but also use the raw roll to add the token to the initiative tracket (which is more a Roll20 feature than a Cypher System feature, where what counts is beating the opponent level/difficulty to know if you're acting before or after the opponent). The tracker will be only used, at the GM and players discretion, to decide who acts first between players.
There is no good solution to be honest: either not using the tracker, or creating a "Roll20 house rule" where assets and efforts would be added to the d20 roll.
Feedback welcome on this subject :)

**Comment by homiedion** [comment]
Fair enough point.
