### ISSUE TITLE
[5th Edition OGL by Roll20] Spellcard convenience addition

### ISSUE THREAD

**Issue by vukk** [Roll20/roll20-character-sheets#5002]
The spellcard contains now the spell save DC and save type. E.g. "DC15, Wisdom save".

It would be very useful for the GM if they could select a token or multiple tokens, and just click on the "Wisdom save" text, and it would roll that save for selected token(s). No need to open character pages.

**Comment by clevett** [comment]
Let me think about that and review the code. That would be useful though I'm not sure off the top of head if our current functionality would support it. Its still an interesting suggestion. :)

**Comment by nmbradley** [comment]
Moving this to an internal ticket.
