### ISSUE TITLE
Classic WoD preview/logo wrong(?)

### ISSUE THREAD

**Issue by TopherGopher** [Roll20/roll20-character-sheets#5004]
I was trying to setup a Classic World of Darkness campaign, but the image preview looks wonky. I can't figure out of the preview/logo is wrong, or if the underlying HTML is also off.
I'm looking at [CWorldofDarkness/CWoD.png](https://github.com/Roll20/roll20-character-sheets/blob/master/CWorldofDarkness/CWoD.png) and it looks like it's the sheet for Vampire. Is that intentional?

**Comment by Anduh** [comment]
If you read the Instruction text next to the preview image, its says:
>Classic World of Darkness Sheet:Includes Revised Vampire Warewolf Demon Mummy Mage Hunter + some Homebrew Gargoyles and Diclonius

Yeah, not the best formatting on the instruction, but contains the information necessary to realize it's what you're after. And if you open the sheet in a game, it defaults to show  the "World of Darkness" sheet.

Could update the "instructions" text to be more clear and switch out the preview image for on that shows WoD to reduce future confusion.

**Comment by TopherGopher** [comment]
I'm new to roll20, so I couldn't figure out what one of my incoming players would see. Just wanted to confirm that the HTML itself is right, and it sounds like it is. Thanks @Anduh
