### ISSUE TITLE
DnD5E Request: adding UA Ship tab

### ISSUE THREAD

**Issue by Anduh** [Roll20/roll20-character-sheets#5013]
to [quote a  recent forum post](https://app.roll20.net/forum/post/7388701/adding-different-kind-of-character-sheet):

> I'm not sure if that was ever raised, but i have a D&D campaign which makes use of Vehicles, Ships to be exact. I'm using one of the UE rules for this and i'd really like to setup a different character sheet for the Ship. Considering she has multiple AC/HP and properties. But still use token.The character sheet is fine as a DM i can just put the stats where i want and try to keep track, but this is messy for my players if i want them to control it.
..
Is there a way or should i add a tab on the official character sheet for vehicles ?

**Comment by VinhNPL** [comment]
I would like to link the UA leading to that request. 
[https://media.wizards.com/2018/dnd/downloads/UA_ShipsSea.pdf](https://media.wizards.com/2018/dnd/downloads/UA_ShipsSea.pdf)

**Comment by V2Blast** [comment]
It's worth noting that the ship rules from that UA have now been published in a modified form in Appendix A of the Ghosts of Saltmarsh adventure: https://dnd.wizards.com/products/tabletop-games/rpg-products/ghosts-saltmarsh

**Comment by nmbradley** [comment]
Moving this to an internal ticket.
