### ISSUE TITLE
[5th Edition OGL by Roll20] Global ability check modifier

### ISSUE THREAD

**Issue by YuanRamirez** [Roll20/roll20-character-sheets#5043]
The current "global skill modifier" field does not allow for buffs/debuffs to regular ability checks.

Spells like Guidance, which is the default for the field btw, allow the beneficiary to roll 1d4 to any ability check - not just "skill checks".

On a similar note, Guidance can also be applied to initiative.

In theory, most effects similar to Guidance should have been worded in such a way that they, too, apply to non-"skill checks", because there technically isn't even such a thing as a "skill check" in 5e. There are only ability checks, some of which use skill proficiencies, saving throws, and attacks.

I have, however, not made a comprehensive list of all effects that apply to ability checks but I can't think of one that would differentiate between regular ability checks and checks a character might be proficient in, aka "skills".

**Comment by nmbradley** [comment]
Moved this to an internal ticket.
