### ISSUE TITLE
[Shadowrun 5e] Can't Toggle Between Tabs (Arms/Augs/Core) and Modifiers (To GM/Edge)

### ISSUE THREAD

**Issue by Higgin** [Roll20/roll20-character-sheets#5107]
Steps to reproduce:

1. Start a new game with basic Shadowrun 5e sheet.
2. Create a character.
3. Try to swap between different sub-sheets or modifiers.
4. Watch sadly as nothing happens.

Edit: possibly related to #5082 ?

**Comment by clevett** [comment]
Indeed #5082 fixed this. Sorry for the disruption.
