### ISSUE TITLE
Mothership: Marine starts with +5 Combat but sheet has +0

### ISSUE THREAD

**Issue by jfsantos** [Roll20/roll20-character-sheets#5108]
Maybe the Alpha didn't have this, but in the most recent edition available on DriveThru Marines get +5 in Combat (and an extra +5 if another Marine is helping, but the sheet should not account for that).

https://github.com/Roll20/roll20-character-sheets/blob/29f7271e1766114cd7ae86219c3657a4f60fe9cf/Mothership/Mothership.html#L67

**Comment by sirkerry** [comment]
Made requested change and submitted pull request.

**Comment by Anduh** [comment]
@jfsantos, did #5598 fix this issue? If so, this issue can be closed.

**Comment by jfsantos** [comment]
Yes, closing. Thanks!
