### ISSUE TITLE
Burning Wheel: Calculating Reflexes and Mortal Wound

### ISSUE THREAD

**Issue by jaadus** [Roll20/roll20-character-sheets#5113]
This is a few related small issues that I can split out if needed, but could all be swept up in one go:

First, and I'm having trouble finding the global rule statement on this one, but the math seems wrong for averaging stats of different shades. Specifically I think this case is invalid: `else if(shades[2] >= shades[1] + shades[0]) shade = "3"; //More white that darker = gray. Also covers Black+White=Gray` . The resulting shade should _always_ be the lowest. (For example: "If any of the stats are black shade, Reflexes is black shade." BWG p90). This means lines 3414-3427 can basically be deleted in favor of the `low_shade` variable that's already there.

Second, the character sheet is ignoring the calculated values for Reflexes, and doing simplified math that results in the lowest possible number. (See line 523.) The character burner page seems to be referencing it correctly, but I'm also seeing the wrong number there for some reason... (line 2493)

Third, the Reflexes and Mortal Wound shades are editable when they shouldn't be. Again, they're being calculated when their base stats change, but the values are ignored and the field is a selectable dropdown. (lines 525 & 532).

In the example below, Reflexes should be 4:
![sheet1](https://user-images.githubusercontent.com/2585336/58250511-6cd28800-7d16-11e9-888f-d3c3cced284d.png)
![sheet2](https://user-images.githubusercontent.com/2585336/58250525-71973c00-7d16-11e9-93dd-568e89565994.png)

**Comment by nmbradley** [comment]
Closing this issue as the Burning Wheel sheet has seen major revisions since this was opened. If this is still an issue, please consider submitting a new ticket.
