### ISSUE TITLE
[Cypher System by Roll20] Add Minor, Major and Special Damage translation variables

### ISSUE THREAD

**Issue by lfas** [Roll20/roll20-character-sheets#5141]
The only part we can't translate because of missing variables. Example: 

https://github.com/Roll20/roll20-character-sheets/blob/7189eef20ebc8b2ff2d5c463f2cfd119cd7a3f13/Cypher%20Systems%20by%20Roll20/cypher_systems_by_roll20.html#L1154

**Comment by NathaTerrien** [comment]
Hi @lfas 
Thanks for reporting this!
This will be fixed ASAP.
