### ISSUE TITLE
[Delta Green] [DG] x5 Numbers Don't Always Update

### ISSUE THREAD

**Issue by r2b2grady** [Roll20/roll20-character-sheets#5150]
For NPCs, the **X5** boxes on the *Delta Green* character sheet don't always update after the main stat box is updated, even after waiting for 10-15 seconds. The **Charisma** stat seems to regularly have this issue, while the others only show it every once in a while. This might be present in PC sheets as well, but I've mostly been using it for NPCs so far, so I'm not certain.

I'm using Roll20 and the sheets as follows:
- I'm almost obsessive with hotkeys—I generally navigate between fields using the Tab key, except for Skills.
- I have a Pro subscription, so *hopefully* this isn't an issue with custom scripts.

**Comment by r2b2grady** [comment]
Further behavior I've noticed: It seems to mostly happen when I change the Charisma stat. The Charisma **X5** value will update as needed after I change any *other* stat, but not after I change the main Charisma stat box.

**Comment by JBeighel** [comment]
It looks like there was a worker script that was supposed to run when those fields were updated, but it was missing a trigger for the charisma field.

I have a pending pull request right now, once that's complete I'll submit another one to get this change in.

I have a game open where I was testing the change I made.  If you like you're welcome to join in and kick it around a bit.
https://app.roll20.net/join/4866841/BM_t8A

**Comment by r2b2grady** [comment]
Cool, thanks! I just joined, I'll test it out when I get a chance.

I also noticed another issue that might be a bit trickier to fix—namely, the "h" is missing from the Anthropology Skill, in both the label and the attribute name. The tricky bit is simply when it comes to importing older characters—I'm not super familiar with the Roll20 API, so I don't know how easy it would be to have the Import script recognize that and correct it.

**Comment by JBeighel** [comment]
I've made you a GM in the game, so you should be able to create and mess with things in there to test with.

As for for the renaming, there's no requirement that the text shown on the character screen needs to match what is in the Attribute list.  So changing what is displayed on the sheet, and leaving the attribute name incorrect is possible.

Another option might be to create some worker script on the sheet that looks for "Antropology" and "Anthropology" attributes.  If "Antropology" exists and "Anthropology" does not, copy the value into the correct spelling.  If "Anthropology" exists, then copy its value into "Antropology".  It'd be a mess in the sheet, but it might allow existing macros and characters to continue working.

**Comment by r2b2grady** [comment]
Ooh, that's a good thought.

Also, I noticed that the column names for the Attack fields don't quite line up with the corresponding fields (see attached screenshot). I've used the Dev Console to grab the percent and pixel widths for the fields, would you prefer I make a new pull request or should we just bundle them all into this one?

![image](https://user-images.githubusercontent.com/19891352/61002037-5fa14500-a326-11e9-8b4a-23bf347d7d0b.png)

**Comment by JBeighel** [comment]
Fixed the anthropology business in that test campaign.  When you load the sheet it copies the value from No-H 'Antrpology' into With-H 'Anthropology'.  Then when you change the value it updates both No-H and With-H, this way if there's any macros or whatever they should still work.

The anthropology check box attribute is still spelled wrong, but I don't think it likely anyone is using that directly so I let it alone.

**Comment by JBeighel** [comment]
That attacks table will be more difficult.  The headers are very different sizes than the fields.  Gonna take a bit to try and get them all to line up.  I'll poke around with it and see what can be done without making the sheet wider.

**Comment by r2b2grady** [comment]
Oh, I'd figured that since the main sheet was a static width, you could just kludge the widths by defining them manually, either with pixels:
```
<th   width="167px">WEAPON</th>
<th   width="167px">SKILL</th>
<th width="63px">BASE   RANGE</th>
<th   width="67px">DAMAGE</th>
<th width="51px">DMG   MOD</th>
<th width="67px">ARMOR   PIERCING</th>
<th   width="67px">LETHALITY</th>
<th width="68px">KILL   RADIUS</th>
<th   width="68px">AMMO</th>
<th   width="25px"></th>
```
Or with percentage widths for possible width changes later on:
```
<th   width="20.6170%">WEAPON</th>
<th   width="20.6170%">SKILL</th>
<th width="7.7780%">BASE   RANGE</th>
<th   width="8.2720%">DAMAGE</th>
<th width="6.2960%">DMG   MOD</th>
<th width="8.2720%">ARMOR   PIERCING</th>
<th   width="8.2720%">LETHALITY</th>
<th width="8.3950%">KILL   RADIUS</th>
<th   width="8.3950%">AMMO</th>
<th   width="3.0860%"></th>
```

**Comment by JBeighel** [comment]
Initially I had hoped to merge the two tables.  I couldn't understand why the column headers were in a different table than the data.  Turns out the repeating elements don't work inside tables.

I did try what you suggested, setting field widths.  Doesn't quite work that easy.  Some of the headers (like lethality) are wider than the data entry field.  

If you look at the attacks for the Agent form of the sheet you can see where I got things.  Its definitely closer, but still not quite right.

**Comment by r2b2grady** [comment]
Hm, what about this, for the headers?
```
<th width="178px" style="padding-left: 8px">WEAPON</th>
<th width="167px">SKILL</th>
<th width="63px">BASE RANGE</th>
<th width="67px">DAMAGE</th>
<th width="51px">DMG MOD</th>
<th width="67px">ARMOR PRC</th>
<th width="67px">LETH.</th>
<th width="68px">KILL<br>RAD.</th>
<th width="68px">AMMO</th>
<th width="25px"></th>
```
I tried it in the Chrome Dev Console, but I don't want to make any assumptions about whether that carries over when it's imported into the main files.

**Comment by JBeighel** [comment]
That looks really good.  I applied it to bother versions of that table (NPC and Agents).  

If you're good with that, I'll submit a request to make that live.

**Comment by r2b2grady** [comment]
Sounds good to me!

**Comment by clevett** [comment]
Everything in this issue wrapped up? Can I close it? If you're still working on it no worries. Just trying to keep issues clean. :)

**Comment by JBeighel** [comment]
Not a problem at all.  This one is also complete as well.
