### ISSUE TITLE
(Unofficial Elder Scrolls) major sheet errors occuring

### ISSUE THREAD

**Issue by Nevero** [Roll20/roll20-character-sheets#5153]
I'm hosting a custom campaign on roll20 using the character sheet listed in the tittle of this article, below i have linked screenshot file images of the issues i am expieriencing with the sheet, these issues have been ongoing for roughly the last month to month and a half and are putting a sudden halt in the production of my campaign, any information as to a means of resolving these issues would be much appreciated.
![Screenshot 2019-06-06 at 1 11 25 PM](https://user-images.githubusercontent.com/51458186/59056873-bebef600-885e-11e9-8997-4c292cebeff7.png)
![Screenshot 2019-06-06 at 1 10 57 PM](https://user-images.githubusercontent.com/51458186/59056874-bebef600-885e-11e9-8855-603cd3b45035.png)
![Screenshot 2019-06-06 at 1 10 29 PM](https://user-images.githubusercontent.com/51458186/59056875-bebef600-885e-11e9-93d9-89ac37e321f8.png)

above are three screenshots depicting the issues i am facing, no manually input modifiers are updating on the character sheets for pc's and npc's alike, causing the rolls made to only be the core die being rolled, the character sheets are also displaying aspects of both pc and npc sheets simultaneously, these issues are affecting all character sheets, not just the one in the screen shots

**Comment by nmbradley** [comment]
This issue is now 3 years old and appears to be duplicated by another ticket. I'm going to close this one and leave that one open as this still seems to be an obvious and breaking issue for this sheet.
