### ISSUE TITLE
[Starfinder By Roll20] Removing Equipment

### ISSUE THREAD

**Issue by MTVExtreme** [Roll20/roll20-character-sheets#5203]
Removing an item from the equipment section does not update carried bulk or wealth.

![1](https://user-images.githubusercontent.com/5505510/59883904-8d791680-9384-11e9-93ba-b0d3a0251bf3.PNG)

![2](https://user-images.githubusercontent.com/5505510/59883914-936ef780-9384-11e9-9d57-ac2ab092486e.PNG)

**Comment by Kurohyou** [comment]
Thank you for the report MTVExtreme,

I've found the problem, and will hopefully have the fix out soon.

**Comment by clevett** [comment]
Closing issue as a pull request has been merge to fix this. If its not fixed after tomorrow we can open it again.
