### ISSUE TITLE
[Starfinder By Roll20] Modifier Wizard

### ISSUE THREAD

**Issue by MTVExtreme** [Roll20/roll20-character-sheets#5205]
There are 2 issues i have found regarding the Modifier Wizard:

- We should be able to remove a modifier after adding one, in the case of a mistake being entered or the modifier no longer applying. Currently removing all the modifiers does not remove any of them no matter what is selected. (Our workaround for now is changing the modifier to +0, and removing only some, but not all, of the modifiers works as intended.)

- Secondly we encounter this strange issue from time where clicking on the Bonus Type and Affected Attribute drop-downs will not respond and will at times require clicking on something else or even canceling and reloading the Wizard entirely. At this time I am uncertain of the cause of this.

**Comment by Kurohyou** [comment]
Hi MTVExtreme,
Thank you for the report. The mods in the mod wizard can already be removed. They function like any other repeating section. Simply click the lock icon in the bottom right of the wizard and then click the red trash can icons on each mod you want to remove.

As for the select issue. I'm not sure what's going on there. It's something I can replicate, but I haven't found a solution yet.

**Comment by nmbradley** [comment]
Moving this into an internal ticket.
