### ISSUE TITLE
[Starfinder by Roll20] Can not input Spells higher Level 0

### ISSUE THREAD

**Issue by Markus1204** [Roll20/roll20-character-sheets#5218]
I am playing a Technomancer in a new Starfinder Campagin. We are using this sheet and as stated in the title I can not input Spells higher Level 0. If I add a spell and change the Level from 0 to 1 or higher, the spell disappears immediately and all inputs together with it...

As a Technomancer Level 1 you get 4 Level 0 and 2 Level 1 Spells not including the Bonus Spells for intelligence rank... Do I miss an option in the Sheet or is it just not possible?

**Comment by Kurohyou** [comment]
Thanks for the report Markus,

I'm not able to replicate this issue. Can you provide some screenshots of your character sheet showing the spells section, class details tab, and spellclasses details tab. The only way I'm able to replicate this is if the spell progression select is set to half instead of partial.

**Comment by Markus1204** [comment]
I will include a screenshot which should show everything relevant. If you need more Information, just let me know.

Hope this helps.

![CharSheet Technomancer R20](https://user-images.githubusercontent.com/2684562/60077215-c3721e00-9729-11e9-84c2-8f4a51cae906.jpg)

**Comment by Kurohyou** [comment]
Thank you Markus, can you also provide a screenshot of your class details tab? And then, change your level from 1 to 2 and back again to see if that jogs the sheet into motion.

**Comment by Markus1204** [comment]
Changing Level from 1 to 2 and back fixed the Problem.

Thanks! I'll also close this issue.
