### ISSUE TITLE
[5e Darker Dungeons] Background images failing to load

### ISSUE THREAD

**Issue by LozzieWills** [Roll20/roll20-character-sheets#5223]
Seeing this a couple of times with players.

Looking at the CSS, I can see it retrieving background images from a url. Of course, if for some reason, we fail to retrieve this image on load (I'm not sure how long CSS spends attempting to reach a url), then the sheet is completely toast.

We're encountering this with multiple players. 

So my issue I suppose is:

Why does the implementation retrieve the image via a url? Why can't we just load a relative image? Surely then there's fewer points of failure. 

I've tested this by removing the urls from the css and I'm able to see the issues the players are seeing. 

This is the players page:
![player_issue](https://user-images.githubusercontent.com/44177687/60127097-52615380-9787-11e9-803c-593c058b88a5.png)

This is me pulling out (some of) the urls in the CSS to recreate the issue:
![recreated_issue](https://user-images.githubusercontent.com/44177687/60127098-52615380-9787-11e9-90de-9f1fb0f40ff0.png)

**Comment by clevett** [comment]
@giffyglyph Just letting you know this came through issues.

**Comment by nmbradley** [comment]
Closing as this seems to be resolved. If this is still an issue, please consider submitting a new issue.
