### ISSUE TITLE
[5th Edition OGL by Roll20] encumbrance doesn't apply modifiers

### ISSUE THREAD

**Issue by geoidesic** [Roll20/roll20-character-sheets#5236]
The character sheet calculates encumbrance if the variant rules are selected. However it doesn't do anything with that information other than show a message. It would be much better if the encumbrance penalties were automatically applied – to speed, ability checks, attack rolls and saving throws that use Dex, Str or Con – as per PHB 176.

Am I just missing something or does this functionality not exist?
Also what could I do to add this functionality in?

**Comment by geoidesic** [comment]
I found this thread: https://app.roll20.net/forum/post/6706436/encumbrance-5e-ogl#newtopic
So apparently it doesn't apply the modifications. Why not though? I played PathFinder on Roll20 and the PathFinder character sheet does do this, so obviously it's possible. 

How can we make it happen?

**Comment by geoidesic** [comment]
So I submitted a PR to fix this: https://github.com/Roll20/roll20-character-sheets/pull/5239

**Comment by Anduh** [comment]
Has this been fixed in some later update? If so, this issue could be closed.

**Comment by geoidesic** [comment]
Nope. My PR was denied. Apparently this feature isn't desirable. Really not sure why but there you are.

**Comment by nmbradley** [comment]
Closing as this sheet is no longer present in this repository.  If this is still an issue, I would advise raising it in the [pertinent forum thread](https://app.roll20.net/forum/post/8033570/d-and-d-5th-edition-by-roll20-q1y2020).

**Comment by geoidesic** [comment]
What? What's going on? How can D&D 5th edition no longer be in this repository?

**Comment by nmbradley** [comment]
All of the 'by Roll20' sheets are hosted in a separate, private repo. Nothing to be alarmed over 🙂
