### ISSUE TITLE
[Dungeon World by Roll20] NPC Text boxes

### ISSUE THREAD

**Issue by WallaceMcGregor** [Roll20/roll20-character-sheets#5274]
The NPC sheets need a fix. The text boxes could have dynamic width. When you write two or three tags or longs names, movements, instinct... They don't show all text.

**Comment by clevett** [comment]
Thanks for letting us know. I'll have some one take a look at that.

**Comment by nmbradley** [comment]
I'm under the impression that this was resolved earlier in the year. If it's still a problem, please create a new issue.
