### ISSUE TITLE
Hello guys, here i am again to point out some more problems on our SIFRoleplaing sheet.

### ISSUE THREAD

**Issue by shakasannin** [Roll20/roll20-character-sheets#5302]
Hello to all again, first I would like to thank you @coldrage101 (not sure how to tag a person in roll20), for your amazing work, but, not everything is perfect yet, I believe that this system deserves a proper system since is a great one.

And I'm hoping that you can help all of us SIFRPG system users.

Now that the rolls are fixed, there are some minor bugs, me and a couple of friends tested and found some bugs.

The ability button "Knowledge" is trying to roll the "language" skill, which occurs on syntax error.
In "intrigue and combat" the "initiative" button rolls it correctly, but it shows no text on the chat, not even the results of the rolls. however, it adds to the initiative table successfully. 
Still, on the "Intrigue and Combat" in the weapon section, all the weapons rolls are broken, the same as the first bug that I pointed out. It shows the number of dices, but it doesn't roll it.
And the last but not least, the "Movement" section in the "Intrigue and Combat" is bugged as well, not the whole thing, but there's a system problem regarding the rules from SIRPG. Movement is based on a pattern of "4 yards + RunSpecialty/2 - Bulk/2" This formula is working perfectly, except that in this system we can't have ".5's" never. When it comes to running speed the calculus is                                                                        " 4(4 Yards + Runspecialty/2 - Bulk/2 ) - Bulk. "
For example, Matt has a base movement of 4 yards, he has the run specialty on 2 and bulk of 1. Matt's final movement pool is a Move Speed of 5. and running speed of 5 * 4 - 1 = 19 Yards.

Another Example, Matt2 Has a base movement of 5 yards because of the quality "fast", he has the run specialty of 4 and bulk value of 2. Matt2 Has a Move Speed of 5 + 2 - 1 = 6 Yards. And a Running speed of 5 * 6 - 2 = 28 Yards.

Well, that will be all, thanks again, and I hope you can help us again. Thank you and have a nice day.

**Comment by coldrage101** [comment]
I'll have a look at it over the next few days.

**Comment by coldrage101** [comment]
I have a fix for the education rolling language, and another for language specialities dropping all of their dice.
The issues on with the initiative rolls and on the attacks exist in the original version of this sheet, but I shall look into them both.

I also wonder about the requirement for selecting a target token for attacks. It is very nice to see the requirement to hit along side the roll, but it does require the Narrator to have set up all enemies with there own character sheets, something uncommon to do with mooks, and also tells the players the strength of the opponent, something some GMs like to keep hidden. I would extend this to a lesser extent to the requirement for a token to be selected to roll initiative, though this is less of an issue as a token is needed for the turn tracker. This may however be a discussion for a seperate issue.

An additional bug I would like to mention is that when initiative is rolled for a token without a sheet, it throws an error: `SyntaxError: Expected "(", ".", "[", "abs(", "ceil(", "d", "floor(", "round(", "t", "{", [ |\t], [+|\-] or [0-9] but "s" found.`

**Comment by coldrage101** [comment]
I have now got fixes for the fighting and initiative rolls. I have removed the requirement for a token to be selected in both cases.

@shakasannin can you reiterate on the issues with movement? I lack understanding of the issue.

**Comment by coldrage101** [comment]
I'll do a pull request of the changes I have thusfar tonight.
