### ISSUE TITLE
Shadow of the Demon Lord: NPC issue with insanity and corruption

### ISSUE THREAD

**Issue by Operativ** [Roll20/roll20-character-sheets#5311]
Hello,

I have noticed that in the NPC version of the character sheet, ticking the Insanity and Corruption boxes does not display an editable field. The field is there in the display, non-editable mode, however it cannot be changed.

This is regarding Shadow of the Demon Lord character sheet.

**Comment by Anduh** [comment]
It's better to have the name of the sheet in the title for clarity

**Comment by JBeighel** [comment]
Not sure what tool was used to generate that HTML, but it is not friendly to humans.

However, I think I have what you wanted in place though.  Take a look at the character in this game and let me know what you think:
https://app.roll20.net/join/4934424/cG2JzQ

The functionality is a match for all the other attributes in there.  I don't know the rules for this particular game so I've no idea how to truly handle this.

**Comment by clevett** [comment]
Going to close this. The inputs are there. Just check the box to turn them on. Then when you leave Edit mode there is a hidden input next to the stat.
