### ISSUE TITLE
[Request] Fallout 4.0 Character Sheet

### ISSUE THREAD

**Issue by calebm02** [Roll20/roll20-character-sheets#5335]
A lovely individual from No Mutants Allowed has made a bunch of really nice alterations to Fallout 3.0, and the character sheets aren't on Roll20 yet.  Here is the link to the HTML/CSS

https://drive.google.com/file/d/1ncMuceZ_hCpKurtIR1MXZSarsV990pcj/view

Hope this can be added, thanks!

**Comment by Anduh** [comment]
Hm, Giving the sheet a quick look, it doesn't quite hold up to the current submission standards `<table>` elements, but if someone does some cleanup, it could be submitted.

**Comment by Skyeris** [comment]
I didn't expect someone to put my edits on Github. I was actually working on it today to make it cleaner. The link above doesn't work anymore. Here's the new one.

https://drive.google.com/file/d/1ULy4xMYZmUuwZ0U3Bnn7D2ofREDnWt0e/view?usp=sharing

**Comment by Anduh** [comment]
As it seem to be a fairly simple sheet, changing it to use flexbox or css grid shouldnt be too much work (they are the recommended ways to structure sheets, but not mandatory)

**Comment by Skyeris** [comment]
I can give it a try. I barely know HTML and CSS.

**Comment by Anduh** [comment]
You can follow the [Roll20 guidelines](https://github.com/Roll20/roll20-character-sheets#contributing) and fill in the little info needed, and just submit the sheet as a draft Pull Request here and as here/ the forums if someone want to take a look at what you've done. You need to have access to a Pro game to use custom sheet to preview/test the sheet before submitting it here.
