### ISSUE TITLE
[D&D 5e OGL by Roll20] Ranger class issues

### ISSUE THREAD

**Issue by Operativ** [Roll20/roll20-character-sheets#5395]
Hello,

the Ranger class has issues when creating a character via Charactermancer.

- Favored Enemy (Humanoid) fields display as blank after you type data in & move onto the next step. It saves properly though.
- At level 2, there's some "undefined spell list" under the level 1 spell list.
- at global attack modifier there's "undefined" or "[]" modifier without any description
- when choosing (at least) the Forest favored grounds, it says "undefined"

**Comment by clevett** [comment]
Greetings,

I added these to our backlog and we'll take a look at them soon.

**Comment by nmbradley** [comment]
Closing this ticket as I cannot reproduce these issues, and I believe that they have been resolved. If there are unresolved problems, please consider opening a new issue.
