### ISSUE TITLE
[D&D 5e OGL by Roll20] Fighter - Criminal background does not receive Thieves' Tools proficiency but a blank field proficiency

### ISSUE THREAD

**Issue by Operativ** [Roll20/roll20-character-sheets#5403]
Hello,

When you create a fighter with a criminal background (I picked enforcer) on generating it does not grant the thieves' tools tool knowledge, but a blank field proficiency based off Strength.

**Comment by clevett** [comment]
Greetings,

This should be fixed by #5521 . This will go out next week, 8th October 2019.
