### ISSUE TITLE
Firefly: First column skills improperly formatted

### ISSUE THREAD

**Issue by paladintodd** [Roll20/roll20-character-sheets#5426]
While the Firefly sheet in Roll20 works, if you do a custom sheet using this HTML & CSS there is a problem will the first column of skills. The die graphic will appear on the line below the Craft skill. This line in the CSS appears to be the problem:

.sheet-skills table td:nth-child(2n) {
  border-right: 10px solid white;
}

Change it to this and things are formatted correctly:

.sheet-skills table td:nth-child(2n) {
  border-right: 8px solid white;
}

**Comment by Anduh** [comment]
I submitted a fix for the sheet.

**Comment by Anduh** [comment]
@clevett with issue can be closed thanks to #5555
