### ISSUE TITLE
Phantom Inventory Item

### ISSUE THREAD

**Issue by tobeyun** [Roll20/roll20-character-sheets#5455]
On each of my player sheets, they all have a blank inventory item that cannot be deleted. Looking at the source, they are missing an ID and I assume this is why it cannot be deleted.
![Image 9-8-19 at 1 03 PM](https://user-images.githubusercontent.com/14236299/64492405-1b082c00-d239-11e9-98f8-e895b620633b.jpg)

**Comment by nmbradley** [comment]
Closing this as it hasn't been updated in two years and I can't find any additional bug reports. If this is still an issue, please consider opening another issue.
