### ISSUE TITLE
[WFRP4CharSheet] missing data-i18n tags in WFRP4Charsheet.html

### ISSUE THREAD

**Issue by dyvim** [Roll20/roll20-character-sheets#5464]
Hello, 

There are some data-i18n tags missing in the WFRP4 Sheet.
If someone ( @Medieve  ?) can add them and update the translation.json file.

```
line 15 : <label class="sheet-tab" >PC</label> 
line 17 : <label class="sheet-tab" >GM</label>
line 24 : <label class="sheet-tab" >Main</label>
line 26 : <label class="sheet-tab" >Skills & Talents</label>
line 28 : <label class="sheet-tab" >Gear & Magic</label>
line 30 : <label class="sheet-tab" >Information</label>
line 32 : <label class="sheet-tab" >Experience</label> 

line 665 : <option value="@{Current_SB}*3" >SBx3</option>
line 666 : <option value="@{Current_SB}*2" >SBx2</option>
line 667 : <option value="@{Current_SB}" selected >SB</option>

line 673 :   <option value="@{Current_TB}*3"  >TBx3</option>
line 674 :  <option value="@{Current_TB}*2" selected  >TBx2</option>
line 675 :   <option value="@{Current_TB}" >TB</option>

line 681 : <option value="@{Current_WPB}*3" >WPBx3</option>
line 682 :  <option value="@{Current_WPB}*2" >WPBx2</option>
line 683 :  <option value="@{Current_WPB}" selected  >WPB</option>
```

lines 15 and 17 are not mandatory because they are commented but the other lines are used.

Best Regards

**Comment by dyvim** [comment]
Thx a lot Cassie

**Comment by clevett** [comment]
You're welcome. Keep up the good work. :)

**Comment by dyvim** [comment]
Hello Cassie,

I've seen that you have closed the issue and I 've even seen the tags
you've added (linked to the issue) but strangely I can't see them in the
current code of the WFRP4 sheet (html file or translation.json file).
Is that normal? Will they bee added next week?

BRgds

Thomas Coquery



Le mer. 18 sept. 2019 à 08:33, Cassie Levett <notifications@github.com> a
écrit :

**Comment by clevett** [comment]
@dyvim 

That is odd. I'll take a look this evening.

**Comment by clevett** [comment]
I guess for some really weird reason I closed the Pull Request instead of merging it. O_O

**Comment by clevett** [comment]
@dyvim Are you seeing the new keys now?

**Comment by dyvim** [comment]
Yes! It's OK now, i'm able to translate.
Thanks a lot @clevett .

BRgds

**Comment by clevett** [comment]
You're welcome.
