### ISSUE TITLE
Todays sheet organisation screwed people using the Lancer 1.8 sheet

### ISSUE THREAD

**Issue by G-G-G** [Roll20/roll20-character-sheets#5478]
See here: https://app.roll20.net/forum/post/7774613/lancer-rpg-character-sheet-issues

It looks like the old sheet has been removed from the selectable character sheets, and those people using the newer sheet have been forced onto the older one and have lost a lot of character data.

**Comment by V2Blast** [comment]
I can confirm that the same thing (switched to older sheet, loss of data) seems to have happened in the game I'm a player in as well.

**Comment by clevett** [comment]
I'll look at getting a hotfix for this tomorrow. It looks like the approved yaml update revealed a made when the new Lancer was added.

**Comment by clevett** [comment]
Approved.yaml was fixed and its been pushed live. Thanks for adding a report here.
