### ISSUE TITLE
[Request] Savage Borderlands

### ISSUE THREAD

**Issue by Fashionforpassion** [Roll20/roll20-character-sheets#5490]
Long-time Roll20 user very interested in Borderlands, I've been searching for a while and I found this and was extremely interested, I've seen other variations of Savage Worlds, but this one is my favorite.

https://arfe.net/savage-borderlands/
The character sheets are all in google docs.

![image](https://user-images.githubusercontent.com/55814692/65645490-576bb400-dfbd-11e9-88bc-69998cfbd7d9.png)

  ![image](https://user-images.githubusercontent.com/55814692/65645673-014b4080-dfbe-11e9-815c-ba178d4b3374.png)

**Comment by Anduh** [comment]
Other than looks, does this Borderland sheet version of Savage Worlds differ from how the either of the existing sheets function?

**Comment by Fashionforpassion** [comment]
I'm glad you asked.
Here, as you can see, is the differences in elements, Arcane Background has been specifically assigned to Sirens.

![image](https://user-images.githubusercontent.com/55814692/65812315-35c02780-e18b-11e9-8860-06befb63c826.png)

As well as the introduction of the Element bar.

Not to mention shields.

**Comment by Fashionforpassion** [comment]
I've been looking for someone to run even a moderately adequate game, and with this new sheet I can finally achieve this. 
I'd understand if you said no, however.

**Comment by Anduh** [comment]
Unfortunately I don't have time to take on more sheet requests, I'm just getting you to tell the important parts of this request so, that someone else doesn't have to ask it later.
It's always best to be upfront and clear about what the important parts of the request is, so people don't have to ask for them.

You could also post this request in the [Sheet Request](https://app.roll20.net/forum/post/7781132/sheet-request-thread-consolidated-mk-ii) thread for increased visibility, and check on the suggestions on how to increase the odds on getting your sheet request done.
