### ISSUE TITLE
[5th Edition OGL by Roll20] No background images

### ISSUE THREAD

**Issue by deltmd** [Roll20/roll20-character-sheets#5506]
Is there a reason we are not using the assets for the background images?
Exe: `background: url(/images/dndstyling/CharScroll.svg);`
![image](https://user-images.githubusercontent.com/22157938/65845444-86ed2a00-e2f7-11e9-8db2-1644a7adef21.png)

**Comment by clevett** [comment]
Greetings @deltmd 

I'll need some more details. These images are being used if you have the D&D styling turned on. You can toggle it off and on in the Game Settings.

Thanks,
Cassie

**Comment by deltmd** [comment]
Thank you, I misunderstood.
