### ISSUE TITLE
Last Merge Reverted?

### ISSUE THREAD

**Issue by finderski** [Roll20/roll20-character-sheets#5525]
So, this week the Savage Worlds Tabbed sheet was updated to version 3.9, however today, that version (and the associated changes) are no longer the active character sheet, it's now 3.8.

What happened? When will this be corrected? and What does this mean for updates that are being worked on based on the 3.9 code?

This issue seems to be more than just the Savage Worlds Tabbed sheet, too. See this forum post: https://app.roll20.net/forum/post/7812298/unannounced-rollback

**Comment by Anduh** [comment]
Are you positive you saw the changes live at any point, or is there a chance the changes where never rolled out?

**Comment by finderski** [comment]
Positive.  I have a kanban to assist with coordination of the sheet development. Once I see the update on the Forum about the release update, I go to a test game to validate that the sheet updates are live; once that happens, I move the work over to In Prod. I was also excited that the updates were live, because they will be needed in my game tonight, so I validated the update for that reason, too.

And given that there someone else who is experiencing the same thing, I'm inclined to believe I'm not going crazy. :)

**Comment by clevett** [comment]
This is fixed now. The Submodule was reverted to an old one. We got it fixed earlier today.
