### ISSUE TITLE
[L5R 5th Edition Unofficial] NPC Weapon rolls use skill values from PC version

### ISSUE THREAD

**Issue by MaiFlow** [Roll20/roll20-character-sheets#5528]
When using the macro for a weapon on the NPC version of the sheet, attack rolls use the attribute value for the skill selected, instead of the Martial rating of the NPC. This means NPC stat blocks must have their Melee, Unarmed or Ranged skill set before the macro can be used effectively.

**Comment by saethone** [comment]
Yep, I see the problem there. I'll try to get that corrected this week.

**Comment by TheBalzan** [comment]
Not at all the same issue, however there needs to be a way to set custom endurance, fatigue, vigilance and focus that are not linked to rings on the NPC sheet.
Can fields for NPC advantages, disadvantages, and unmasking be added too?
For that matter can an unmasking field be added to the PC sheet?
Had an issue last night where using a weapon with air wouldn't roll the correct number of dice, only rolled 1 ring die.
Could it be possible to add a mixed roll dice, so you don't have to roll ring and skill dice separately at once.

**Comment by saethone** [comment]
MaiFlow - I've submitted a pull request with your fix - assuming all goes well, it should be updated on Roll20 this week. It will just automatically use the NPC's "Martial" ranks for the skill dice now.

TheBalzan - I don't currently have the time to add any new features to the sheet. 
As for your issue with rolling a weapon with Air, I wasn't able to reproduce the error. Do you have any more info surrounding it that might help me find the problem? Has it happened again?

**Comment by TheBalzan** [comment]
Is it possible to set the endurance fatigue vigilance and focus for NPCs without the autofilling?

**Comment by saethone** [comment]
I'm not sure about that one. It is possible to make it an editable field, but it may cause other problems I'll have to think about. For example, if you change to a custom endurance, then change one of the attributes that affects endurance, it will recalculate it to what you would get now.

It might be a better idea to add a field somewhere for "custom modifiers" or something, but then I'd have to weigh cluttering up the sheet with the benefits. As it stands, this info can be kept in the "Character Description" field pretty easily.

**Comment by nmbradley** [comment]
Closing this as it appears to have been resolved. If there are residual issues, consider opening another issue.
