### ISSUE TITLE
13 th recovery roll is not working

### ISSUE THREAD

**Issue by Daniel1977** [Roll20/roll20-character-sheets#553]
sorry to my english
line 217 is not working to make a roll to recovery..
this is the correct text:
 Recovery Value: [[@{level}@{REC-die}+@{CON-mod}]]"

**Comment by Daniel1977** [comment]
this: <button title="%{REC-check}" type="roll" value="/em rolls for recovery!&#x00A; Recovery Value: [[@{level}@{REC-die}+@{CON-mod}]]" name="roll_REC-check"></button>

**Comment by clevett** [comment]
Hello,

We're looking to resolved old issues. Do you know if this is still a bug in the code? If so can you let me know which sheet it applied to. 

Thank you,
Cassie

**Comment by clevett** [comment]
Hello @Daniel1977 .

Since this issue is 3 years old and I've not heard back the ticket will be closed. If it needs to be opened back up just let me know.

Thanks,
Cassie
