### ISSUE TITLE
[Trudvang Chronicles] add data-i18n tags to the sheet

### ISSUE THREAD

**Issue by dyvim** [Roll20/roll20-character-sheets#5562]
Hello,
Trudvang Chronicles will soon be translated and published in french. I've checked if I'm able to translate the sheet but I'm not because there's no data-i18n tags in the code of this sheet.
@TheAziraphale can you add them?
Or someone else?
BRgds

**Comment by Anduh** [comment]
Hmm, Maybe it's time for me to dust of my ACSI script again. I'll see how well it does.

**Comment by dyvim** [comment]
Thank you Andreas

**Comment by Anduh** [comment]
Alright, so I got a first draft of a translated Trudvang sheet now.  It still have around 45 placeholder text instances that needs language tags, as my script doesn't do them yet.

[Trudvang Chronicles translated files](https://gist.github.com/Anduh/139ca9b9bade98acca76e9a427a2f92e)

**Comment by dyvim** [comment]
data-i18n tags have been added
