### ISSUE TITLE
[7th Sea 2e] add data-i18n tags to the sheet

### ISSUE THREAD

**Issue by dyvim** [Roll20/roll20-character-sheets#5569]
Hello,
7th Sea 2nd edition has been translated and published in french 2 years ago. In my virtual table community i've had a demand to translate the sheet so I've checked if I'm able to do it but I'm not because there's no data-i18n tags in the code of this sheet.
@CoalPoweredPuppet or @BluSponge can you add them ?
or @Anduh can you add them via your ACSI script ?
Or someone else?
BRgds

**Comment by Anduh** [comment]
I'll see if my script can be used on the sheet. If ACSI doesn't do too well on this sheet, and would result in lots of manual fixes or seem to take as much time as doing it manually, I'll let someone with more free time do it.

Will post here again when I know which way it seems to go.

(If you like the speed of translation I manage to do with my script, [please give it a start on giithub](https://github.com/Anduh/acsi) :D )

**Comment by dyvim** [comment]
data-i18n tags have been added
