### ISSUE TITLE
[TheWitcher] add data-i18n tags to the sheet

### ISSUE THREAD

**Issue by dyvim** [Roll20/roll20-character-sheets#5570]
Hello,
The Witcher has been translated and published in french several months ago. In my virtual table community i've had a demand to translate the sheet so I've checked if I'm able to do it but I'm not because there's no data-i18n tags in the code of this sheet.
@Leothedino or @ancallan  can you add them?
Or @Anduh can you add them via your ACSI script ?
Or someone else?
BRgds

**Comment by Anduh** [comment]
I'll see if my script can be used on the sheet. If ACSI doesn't do too well on this sheet, and would result in lots of manual fixes or seem to take as much time as doing it manually, I'll let someone with more free time do it.

Will post here again when I know which way it seems to go.

(If you like the speed of translation I manage to do with my script, [please give it a start on giithub](https://github.com/Anduh/acsi) :D )

**Comment by Leothedino** [comment]
@dyvim hey man, that Witcher Sheet was originally made for a private game and I chose to share it with everybody else, it was also my first attempt at coding a sheet (or pretty much anything). Sadly this means, yeah, it's missing data-i18n tags. Honestly, i'd love to do it, but I just don't have the time these days and it's going to be -alot- of work. 

As it's public for all to view on github, people are welcome to do it (if somebody breaks something, they have to fix though), but for the foreseeable future... I'm just too busy. I am sorry.

**Comment by Anduh** [comment]
@Leothedino , I think you just missed that a PR to include translation tags to your sheet have already been done #5573 :smile: 
I have to say, your Witcher sheet looks and feels amazing, and poking at it while including the translation tags made feel like try it out, just from how great your sheet is.

Thanks for sharing this amazing sheet publicly!

**Comment by Leothedino** [comment]
Oh wow, excellent! That was great of you @Anduh, sorry long day haha.

**Comment by dyvim** [comment]
data-i18n tags have been added

**Comment by Anduh** [comment]
@dyvim Just a FYI, the translations where temporally removed from the sheet as I had broken some parts of the sheet, but they were fixed and added again some week ago.

**Comment by dyvim** [comment]
@Anduh Hello. Yes I've noticed that. I'll have to redo the translations as they have been completely lost. It 'll take me some days...
