### ISSUE TITLE
[Elite Dangerous RPG] Character Sheet Skill Title Changes

### ISSUE THREAD

**Issue by SomewhereSimulated** [Roll20/roll20-character-sheets#5625]
Hello,

Under Personal Combat, the Kinetic Weapons skill name needs to be updated to Ballistic Weapons and reordered alphabetically on the sheet.  

Under Intelligence, Cyber needs to be updated to Bionics/Robotics and reordered alphabetically on the sheet.

Under Vehicle Skills, Systems needs to be updated to SPC Ops and reordered alphabetically on the sheet.

Thanks for the great sheet in advance.

**Comment by Anduh** [comment]
What's the reason for the name-change? Is the current names on the sheet leftovers from some alpha-stage of the game, or have the game gotten some update? I could consider fixing this, but would want to know the reason for this request.

**Comment by SomewhereSimulated** [comment]
Nevermind.  I was going off an old sheet in the sample adventure.  It looks like it was not updated.  Sorry about this.
