### ISSUE TITLE
[Monster of the Week] add data-i18n tags to the sheet 

### ISSUE THREAD

**Issue by dyvim** [Roll20/roll20-character-sheets#5632]
Hello,
Monster of the Week has been translated and published in french several months ago. In my virtual table community i've had a demand to translate the sheet so I've checked if I'm able to do it but I'm not because there's no data-i18n tags in the code of this sheet.
@LethalKitten can you add them?
Or @Anduh can you add them via your ACSI script ?
Or someone else?
BRgds

**Comment by Anduh** [comment]
> Thanks for the quick answer despite your script can't do anything.
> If there is no other answer, i'll try to do it by myself but without the pro account I won't be able to automatically generate the translation.json file.

If you do the work needed on the HTML, I won't mind creating the `translation.json` and checking that it works at some point.

**Comment by Anduh** [comment]
@dyvim How did this turn out? As mentioned above, if you do the work of inserting those i18n-tags in the html, I can take that result and create the `translations.json`-file, as well as fix any minor issues.

I can probably lend a hand with doing more translation stuff again in Summer 2020 otherwise.

**Comment by dyvim** [comment]
@Anduh  I'm still on it... I miss time :(

**Comment by JBeighel** [comment]
Is this still an issue?  I was looking at the sheet and it appears to have all the data-i18n tags.

**Comment by Anduh** [comment]
Yeah seems LethalKitty added it at some point, and the official version of the sheet have translation tags as well, so this issue could be closed. @dyvim

**Comment by dyvim** [comment]
data-i18n tags have been added

**Comment by LethalKitten** [comment]
Sorry I'm late to the party. Yes I added all of them (I hope) for all the base classes and the custom class. I'm still working on the Tome of Mysteries and the unofficial but sanctioned classes I hope this helps everyone who wanted translations :) 

Apologies it took me so long, this is the first time I've ever delved into making character sheets and CSS stuff so I'm learning slowly.

**Comment by Anduh** [comment]
> Apologies it took me so long, this is the first time I've ever delved into making character sheets and CSS stuff so I'm learning slowly.

Thank you for your contributions!

And don't apologize for spending your free time at your own terms :smile:
