### ISSUE TITLE
[Deathwatch] add data-i18n tags to the sheet

### ISSUE THREAD

**Issue by dyvim** [Roll20/roll20-character-sheets#5634]
Hello,
Deathwatch has been translated and published in french several years ago. In my virtual table community i've had a demand to translate the sheet so I've checked if I'm able to do it but I'm not because there's no data-i18n tags in the code of this sheet.
@victor or @CoalPoweredPuppet or @olavmueller or @Craftomega can you add them?
Or @Anduh can you add them via your ACSI script ?
Or someone else?
BRgds

**Comment by Anduh** [comment]
Might look into this sometime in February/March

**Comment by dyvim** [comment]
@Anduh cool

**Comment by Baleine82** [comment]
Hello there.

@Anduh  ,are you still working on the translation or did you give up?

I checked your repository but I didn't found a work in progress.

So, just to keep you in touch, I started to work on the sheet.
If anyone reading this feels that something could be improved (I'm sure there are some needed), just ask, and either I'll do it or we'll raise another issue.

I've started my work anyway, but let me now if I'm doing a job already done.

**Comment by Baleine82** [comment]
My branch is there in case anyone would like to check it out : https://github.com/Baleine82/roll20-character-sheets/tree/DeathwatchTranslation

I still have some work to do because everything is set in a fixed manner in the page, so the translation texts have to comply on not being longer than the english counterpart. I'll see what I can do about it, but I'm really not trained with CSS. I'll try to do as best as I can.

**Comment by dyvim** [comment]
hello @Baleine82 

You are no more able to merge modifications in the translation files directly in github IIRC
You can only modify html and css files and the original translationµ.json according to the new policy ( if i understand correctly)
I say that because i've seen on your repository that you have modified fr.json
Translations have to be done via Crowdin

BRgds 
(it seems that we are both french :) )

**Comment by Anduh** [comment]
> Anduh ,are you still working on the translation or did you give up?

Never looked into it, just plainly forgot.

> I've started my work anyway, but let me now if I'm doing a job already done.

I have nothing, and my auto-i18n creating script is only useful for sheets that have no prior tags, so there probably isn't much for me to contribute, I've mainly helped out with creating translations in cases where my script have been useful at the start by automating some of the simple work.

> I still have some work to do because everything is set in a fixed manner in the page, so the translation texts have to comply on not being longer than the english counterpart. I'll see what I can do about it, but I'm really not trained with CSS. I'll try to do as best as I can.

Assume you're talking about the variance in word length causes trouble in some sections of the sheet that is designed with the specific dimensions of the English text in mind?
On a quick look, I found only minor things that looked odd on the french version. You can check my updated instructions on how to apply these language-dependant looks: https://wiki.roll20.net/I18n#Changing_Language-Specific_Looks

  @dyvim the deathwatch sheet doesn't yet have translations, pretty sure initial translations can be submitted with the update.

**Comment by Baleine82** [comment]
> Assume you're talking about the variance in word length causes trouble in some sections of the sheet that is designed with the specific dimensions of the English text in mind?
> On a quick look, I found only minor things that looked odd on the french version. You can check my updated instructions on how to apply these language-dependant looks: https://wiki.roll20.net/I18n#Changing_Language-Specific_Looks
I did get a quick glance on that, it could help. Isn't there a way in CSS to tell an input to fill with available space in a div? That's something basic in most GUI languages.

I think I'll adjust some spaces here and there as a first step, because if I'm doing huge revamp, it should be in another PR.


> hello @Baleine82
> (it seems that we are both french :) )
Indeed, we are ;)

**Comment by Anduh** [comment]
> Isn't there a way in CSS to tell an input to fill with available space in a div?

Likely, you'll have to google about it, and look at MDN for how inputs behave. Don't have any immediate suggestions on how to do it.

**Comment by Baleine82** [comment]
Indeed, I found what I searched.
It can prove very useful, so I share it here  : https://jsfiddle.net/836c154c/

**Comment by dyvim** [comment]
> @dyvim the deathwatch sheet doesn't yet have translations, pretty sure initial translations can be submitted with the update.
good to know that. thx

**Comment by Baleine82** [comment]
I should be able to create the PR in the next 24h. I'm doing final checks, but the translation should be alright (except for rolls, but I'm looking if I can find an easy solution).

**Comment by Anduh** [comment]
> Indeed, I found what I searched.
> It can prove very useful, so I share it here : https://jsfiddle.net/836c154c/

`display: table-cell;` ?? Lol this ís completely new to me. Thanks for sharing.
