### ISSUE TITLE
[Trudvang Chronicles] add missing data-i18n tags to the sheet

### ISSUE THREAD

**Issue by dyvim** [Roll20/roll20-character-sheets#5637]
2 weeks ago a lot of data-i18n tags have been added to this sheet but there is a part of the sheet that still can't be translated : the part of the skills.
data-i18n tags have not been added because the text to translate is in the property "value" or "placeholder" of the "div" tags.

The problem cencerns the lines between line 291 and line 1022

for example you have this code
`<div class="sheet-row"><input type="text" name="attr_agilityname1" class="sheet-main-skill" value="Agility" readonly></div>`
it should become 
`<div class="sheet-row"><input type="text" name="attr_agilityname1" class="sheet-main-skill"  readonly data-i18n="Agility">Agility</div>`

if someone, perhaps @TheAziraphale or @Anduh, can do something...

**Comment by dyvim** [comment]
I see that you can add **_data-i18-placeholder_** and **_data-i18n-title_** tags.
Does it work for values too? **_data-18n-value_** is a valid property ?

**Comment by dyvim** [comment]
Thanks for all the informations. I'll try to do the dev and submit a pull request.

**Comment by Anduh** [comment]
@dyvim how did this turn out? I'll probably have time during Summer 2020 to help out with these translations things again.

**Comment by dyvim** [comment]
@Anduh I'm still on it but I miss time...

**Comment by nmbradley** [comment]
This looks to me like it was resolved by #5564 but if it's still an outstanding problem, please create a new issue for it.
