### ISSUE TITLE
Delta Green sheet issue with translations

### ISSUE THREAD

**Issue by Lockbox313** [Roll20/roll20-character-sheets#5644]
The sheet is showing the red tags (?) instead of the actual translation.

**Comment by Anduh** [comment]
This also happened to me when I looked at the live sheet on Roll20.

When I looked at the sheet code("Delta Green 2"-folder), I noticed that:
-  [the translation file](https://github.com/Roll20/roll20-character-sheets/blob/master/Delta%20Green%202/translations.json) was named translation**s**.json, not translation.json as normal
- the exists not folder containing the actual translations for the sheet

@clevett , looking at the changelog for the sheet, it seems likely that the typo from the initial sheet submission is the origin of this issue.

**Comment by clevett** [comment]
Oh no!!! Just a typo on my part. We can fix that.
