### ISSUE TITLE
[Forbidden Lands] Some language-specific translation files missing entires

### ISSUE THREAD

**Issue by Anduh** [Roll20/roll20-character-sheets#5670]
Some of the translation files(at least the [Swedish version](https://github.com/Roll20/roll20-character-sheets/tree/master/Forbidden_Lands/translations)) haven't been automatically updated as they should have, and this have resulted in, among things, the Swedish version display some words as missing. Haven't looked closer of other files are missing entries, but looking at the variation of update times, I'm pretty sure it's not the only one.  
[swedish view of sheet](https://app.roll20.net/forum/post/7282548/forbidden-lands-sheet-beta/?pageforid=7899148#post-7899148)

This was first [reported on the forums](https://app.roll20.net/forum/post/7282548/forbidden-lands-sheet-beta/?pageforid=7901961#post-7901961) in a related post, but wasn't identified correctly at first..

@clevett seems like a bug with the i18n tools not updating all files with new entries.
On a related note, Issue #5426 , #5335 , #2458 are solved and could be closed, and #5633 is solved after this week's changes go live.

**Comment by vince-roll20** [comment]
I can't see your image in the post above Andreas. ;-(
Just to add to this; I looked in the Forbidden Lands translation folder last night and if I recall, only some of the language files updated with last weeks pr.  Checking the folder after today's merge, it looks like they were all updated except for one file "[pt-br.json](https://github.com/Roll20/roll20-character-sheets/blob/master/Forbidden_Lands/translations/pt-br.json)" which was last updated 7 months ago...

**Comment by Anduh** [comment]
Vince, it was just the screenshot Calle posted in the thread, changed the link to point to his reply directly.

**Comment by vince-roll20** [comment]
Gotcha.  Thanks

**Comment by Anduh** [comment]
@clevett it seems you successfully updated all translation files for Forgotten Lands, except [pt-br.json](https://github.com/Roll20/roll20-character-sheets/blob/master/Forbidden_Lands/translations/pt-br.json). Looking at the available language options on Roll20, Portuguese(Brazilian) doesn't seem to be an existing option, so I see why it wasn't updated.

The swedish translation now have same amount of entries as the other translation files, so this issue have therefore been resolved.
