### ISSUE TITLE
[Witcher] Recent translation has broken the sheet

### ISSUE THREAD

**Issue by Leothedino** [Roll20/roll20-character-sheets#5671]
@Anduh would it be possible to please take a look at the Witcher sheet translation you recently provided, I am receiving messages and complaints that the armor/equipment tab is broken, as well as multiple miss-spellings of abilities and the NPC tab has plenty of broken code in the titles. 

I know it sounds awful to say this, but I have to ask that whoever last worked on the sheet please ensure it works before pushing it live. Could you take a look, please? Otherwise i'll have to try and revert the sheet to however it was some months ago, with the original code I have on file. Thanks.

**Comment by Leothedino** [comment]
Note: I am not overly used to working with Github, if somebody else has provided files since your update. Please let me know, and I will try to contact them.

**Comment by Leothedino** [comment]
@clevett would it be possible if we could revert the recent translation changes to the Witcher sheet? I've just been made aware that [R.tal's official charity event featuring the original voice actor of Geralt and Mathew Mercer](https://cdn.discordapp.com/attachments/481154197417623552/643849122893529088/BirthofHaresMercer.jpg) could be using this sheet on the 17th, and of course, now my concerns to not hamper that are now becoming paramount. Talk about stressful.

**Comment by Anduh** [comment]
If it's broken, it would be best to revert today @clevett , and I'll resubmit a better tested one sometime in the future.

**Comment by Leothedino** [comment]
@Anduh if we could do some testing/previews on the next attempt, that would be great. I'll personally take part in those if it helps out at all. 

Regardless though, my priority concern now is this sheet being **restored and made ready for this charity event** as soon as we can. I've informed R.Talsorian and the WanderingDM of the situation, so if they choose to use a different online TRPG platform, then that would be a real pity indeed.

**Comment by Anduh** [comment]
I absolutly agree on both counts, but it's out of my hands and for cassie to decide.

**Comment by Leothedino** [comment]
We'll wait and see.

**Comment by Anduh** [comment]
Cassie just reverted it on github, so that will surely go live later today, so the situation is solved. I'll be in touch in a few week's about improving the translation. It's helpful if you list the currently known issues with the sheet.

**Comment by Leothedino** [comment]
I will do, but as it currently appears, all of the issues have been reverted. If I can put aside some time, I should be able to clearly work out the kinks and twists next time. Keep in touch. 

**ISSUE RESOLVED!**
