### ISSUE TITLE
Fallout: reserved character in directory name

### ISSUE THREAD

**Issue by Ulty** [Roll20/roll20-character-sheets#5672]
Last update, a new directory was created, named 'Fallout: Vaults & Deathclaws PNP'
This name is not compatible with Windows, as : is a reserved character. As a consequence, I cannot clone the git on my computer. The message is

fatal: cannot create directory at 'Fallout: Vaults & Deathclaws PNP': Invalid argument

**Comment by vince-roll20** [comment]
"I cannot clone the git on my computer."
Same.  Please fix this.

**Comment by Anduh** [comment]
@clevett this seems like a thing you want to know.

**Comment by clevett** [comment]
I'll rename the folder on Tuesday. 

Fyi, @Skyeris the new folder name is causing issues due to the special characters. I'll rename it on Tuesday. You wont need to do anything but ensure you update your branch.

**Comment by vince-roll20** [comment]
Thanks Cassie.

**Comment by ap3h3ad** [comment]
Hi,
today I tried to checkout the repository, but I keep getting errors from eclipse:

![Error](https://user-images.githubusercontent.com/19926421/69167058-90736100-0af4-11ea-98d6-d4e653eb8310.png)

It seems that the CSS file can't be cloned. Has anyone else encountered this problem?

**Comment by Ulty** [comment]
This is just the same issue with the name of the path.

**Comment by ap3h3ad** [comment]
@clevett Could you also rename the files (CSS and HMLT)?

**Comment by Ulty** [comment]
On my side, this issue is fixed.
