### ISSUE TITLE
[Starfinder by Roll20] sheet is not available in Crowdin

### ISSUE THREAD

**Issue by dyvim** [Roll20/roll20-character-sheets#5677]
Hello, 

The sheet "Starfinder by Roll20" is not available to translate in Crowdin. 
I thought it was because the translation.json file was named with an underscore at the beginning but there are other sheets in the same case that are displayed in Crowdin (13th Age for example) so it does not come from this.
If someone can do something...

**Comment by clevett** [comment]
This should be fixed as of 19th.

**Comment by clevett** [comment]
I'm going to close this. It should be fixed now.

**Comment by dyvim** [comment]
It is fixed indeed. You can close the issue.
Thanks again.
