### ISSUE TITLE
[D&D 5e OGL by Roll20] Request: Spell Points Variant

### ISSUE THREAD

**Issue by saethone** [Roll20/roll20-character-sheets#5697]
An option to toggle between the standard spellcasting and the Spell Points variant would be very helpful. 

It would simply hide the spell slots for each level and give one total spell points field. If it was to be integrated into the charactermancer, that would not be very difficult either - there are no complex calculations - just a flat max spell points based on your class.

**Comment by Anduh** [comment]
At least Spell Points can be tracked with a [Class Resource](https://wiki.roll20.net/5th_Edition_OGL_by_Roll20#.2813.29_Class_.26_Other_Resources) entry, then just ignore the spellslots, or use lvl.1 spell slot max for that purpose.

The [SW5E sheet](https://github.com/Roll20/roll20-character-sheets/tree/master/StarWars5E) (which is based on the DnD 5E sheet) uses spellpoints, and could be used as an example of how to recreate it on the 5E sheet.

**Comment by nmbradley** [comment]
Closing this ticket as we recently merged this new feature. If you feel as though there's something further that needs work, please consider opening a new issue.
