### ISSUE TITLE
[AGE System: The Expanse] Missing Focuses

### ISSUE THREAD

**Issue by Anduh** [Roll20/roll20-character-sheets#5758]
From a recent [Forums post](https://app.roll20.net/forum/post/7998771/the-expanse-character-sheet):
> [...] The current AGE sheet doesn't have all of the focuses that Expanse has. It is missing Accuracy, Fighting, and Intelligence. Also there isn't a single spot to put Talents. Might these features be added? If not then how might I add them myself?

I might take a few moments to look at this in the coming weeks, but thought that @zachhall or @GhostMatter might want to know about this.

**Comment by Kazzirah** [comment]
I reenabled the missing abilites in the character tab and the focuses tab.
Also, I made some minor changes for the expanse.

Some items are still missing, like "Toughness" or "Income", but these seem to be major changes to the sheet and I'm not sure when to find the time to add these.

**Comment by Anduh** [comment]
Cool. I assume you tested your changes in Roll20 and saw that they worked?

**Comment by Kazzirah** [comment]
Yes, sure. 
Made a couple of development tests. (And some functional tests as well.)

Naturally, this does not prevent any new bugs. 😄

**Comment by Anduh** [comment]
btw was this fixed? If so, I could close the issue.

**Comment by Stexinator** [comment]
@Anduh  if this is resolved, please close it
