### ISSUE TITLE
Savage Worlds: what's the point of a sheet without a compendium?

### ISSUE THREAD

**Issue by geoidesic** [Roll20/roll20-character-sheets#5759]
Hi,

Just trying to figure out how to play a Savage Worlds campaign. I don't understand how to run a game with just a character sheet but no compendium... how do you add encounters / monsters / NPC's etc.?

**Comment by Anduh** [comment]
> I don't understand how to run a game with just a character sheet but no compendium... how do you add encounters / monsters / NPC's etc.?

I'd say you copy NPC stats from your books/the web, or create them by whatever rules Savage Worlds have for NPC/monster creation. If you're using the "Savage Worlds: Tabbed" sheet, it has a [wiki page](https://wiki.roll20.net/Savage_Worlds_Tabbed#Ally.2FMook_Sheet) that should be helpful.

If you need more help with using the character sheet after reading the wiki, I suggest you post on the [Character Sheet Forums](https://app.roll20.net/forum/category/277980).

If you need help with creating NPCs/adventures with Savage Worlds, I suggest you seek out some RPG-hub dedicated to it, and they will have plenty of suggestions/ideas/guides. One suggestion is [/r/SavageWorlds](https://www.reddit.com/r/savageworlds/) on Reddit, it seems their [wiki](https://www.reddit.com/r/savageworlds/wiki/index) also have bunch of links and resources that would help you.

And are you aware that 90% of all game systems/sheets on Roll20 don't have compendiums? It's the standard to having to stat out things by yourself for any system beyond the top seven popular ones, and some sheet donesn't even have dedicated NPC sheet incorporated into the character sheet.

**Comment by clevett** [comment]
I'm going to close this GitHub issue as it is not related to any of the programming on this page. Character sheets are at the minimum expected to be used like paper character sheets for tracking data. Some systems have data for additional features.

- Cassie
