### ISSUE TITLE
Character Sheet For D&D 3.5 skill problem

### ISSUE THREAD

**Issue by felipearmat** [Roll20/roll20-character-sheets#576]
Uncheking a skill as a class skill doens't count ranks as half.
Looking at the code I can tell that we should change all {value="class"} camps to {value="1"} camps and then change all camps with {value="@{XXX-mod}+@{SKILLranks}+@{SKILLmiscmod}"} to {value="@{XXX-mod}+floor(@{SKILLranks}/2)+@{SKILLclassskill}*ceil(@{SKILLmiscmod}/2)"}
That change would make would change the skills to auto-calculate values as class skills.

**Comment by suldae** [comment]
It's not supposed to count the ranks as half.  According to the players handbook/srd, when you buy the ranks you only buy half a rank ie if you spend 3 points in a cross-class skill, you record only 1.5 ranks in the skill.

This is the way the paper sheets work and how this version of the sheet is supposed to work.  If you want it to work in the fashion you suggest, I would suggest making and running your own custom version of the sheet.  (as a mentor subscriber, choose custom at the bottom of the list for the character sheet option for the campaign.  You can then paste your own custom html and css code into the appropriate tabs.

**Comment by clevett** [comment]
Hello,

I am going through the old issues and closing ones that seem to be resolved. Based on the conversation this issue will be closed. If it is still an issue let me know.

Thanks,

Cassie
