### ISSUE TITLE
[Call of Cthulhu 7th Edition by Roll20] Improve translations.

### ISSUE THREAD

**Issue by WallaceMcGregor** [Roll20/roll20-character-sheets#5811]
It will be great to improve the translations of the sheet. There is some things that stays in English like skill and type in the Dice Roller or default skills in the skills group. Also will be good to allow the translation of all chat roll templates.

Regards
![Traduccion CoC](https://user-images.githubusercontent.com/17795541/72924113-a26dbc00-3d50-11ea-9d43-3dc9c1f83262.png)

**Comment by clevett** [comment]
Greetings,

I've added a ticket to improve these areas. It should be completed next month. We're working to get the NPC sheet finished then we'll fix these areas. :)

Thanks,
Cassie

**Comment by clevett** [comment]
These should be fixed as of last week. Let me know if you find any more.
