### ISSUE TITLE
[WFRP4CharSheet] missing background on character sheet

### ISSUE THREAD

**Issue by SebastianGrohnert** [Roll20/roll20-character-sheets#5836]
- [X]  Does the pull request title have the sheet name(s)? Include each sheet name.
- [X]  Is this a bug fix?
- [ ]  Does this add functional enhancements (new features or extending existing features) ?
- [X]  Does this add or change functional aesthetics (such as layout or color scheme) ?
- [ ]  If changing or removing attributes, what steps have you taken, if any, to preserve player data ?
- [ ]  If this is a new sheet, did you follow Building Character Sheets standards ?

The character sheet is missing its background-image.

![image](https://user-images.githubusercontent.com/24266943/73684843-48141a00-46c5-11ea-94a7-7931c1d50bdd.png)

**Comment by clevett** [comment]
should be fixed
