### ISSUE TITLE
Rogue Trader 40k Psychic Powers Push Math. 

### ISSUE THREAD

**Issue by mtxdew** [Roll20/roll20-character-sheets#5844]
The Psychic Power Push math asks for a Modifier, then multiplies it with your current psychic rating instead of adding to it and multiplying the result by 5.

Example: Psy Rating of 3, Pushing for 2, with a Willpower of 50 should result in ((3+2)*5)+50 for a total skill of 75 for the roll.

Currently it is doing (3*2*5)+50 for a total of 80.

**Comment by Stexinator** [comment]
Can you provide the page in the rule book?

**Comment by Stexinator** [comment]
@mtxdew  if this is resolved, please close it
