### ISSUE TITLE
[Pokemon Tabletop United] Roll template missing attribute fields used by Edges, outputs incorrectly

### ISSUE THREAD

**Issue by Jeanfeels** [Roll20/roll20-character-sheets#5872]
The "DIS" section of the master roll template for PTU is missing the prereq and cost fields, and seems to also be an incomplete copy from the Feature roll template output.

Current master roll template (relevant section only, from line 1034):
```
 {{/dis}}
        {{#dis}}
            <tr><th colspan="2">{{dis}}:<br/>{{name}}</th></tr>
            <tr><td colspan="2"><span class="tcat">Frequency: </span>{{freq}}</td></tr>
            {{#tar}}
            <tr><td colspan="2"><span class="tcat">Target: </span>{{tar}}</td></tr>
            {{/tar}}
            <tr><td colspan="2"><span class="tcat">Description: </span>{{desc}}</td></tr>
        {{/dis}}
```

Default edge roll output (line 2447):
`&{template:PTU} {{dis=Edge}} {{desc=@{EdgeInfo}}} {{nick=@{nickname}}} {{name=@{EdgeName}}} {{prereq=@{FeatureTarget}}} {{cost=@{FeatureTarget}}}`

I believe this is either unfinished or otherwise needs a fix. In addition to the master roll template missing the fields for `prereq` and `cost`, the output of the roll template seems to have two identical attributes which I presume to be an artefact of them being copied across from the Features template. The actual values of `prereq` and `cost` are contained within `EdgePrereq` and `EdgeCost`.

**Comment by nmbradley** [comment]
This looks like it was resolved by #7375. If it wasn't, please feel free to recreate the issue.
