### ISSUE TITLE
Forbidden Lands translations failed to update with 2/24/20 merge

### ISSUE THREAD

**Issue by vince-roll20** [Roll20/roll20-character-sheets#5899]
Hi Cassie,
it looks like the Forbidden Lands en.json in the translations folder didn't get updated with the translation.json changes...  Any way to get that fixed before next week?  Thanks
https://app.roll20.net/forum/permalink/8159488/

**Comment by clevett** [comment]
My apologies as I'm only seeing this now. I was in/out of the office sick last week. Translations are difficult to hot fix since they require a full server restart which is a whole process. When I run translations tomorrow I'll be sure to load up the Forbidden Lands sheet to look for any missing translations.

- Cassie

**Comment by vince-roll20** [comment]
thanks Cassie

**Comment by vince-roll20** [comment]
Can you double check this Cassie.  It looks like the translation folder json's still didn't get updated with today's merge. ;-(

**Comment by clevett** [comment]
I just merged everything in. They looked okay on my local environment. Everything should be live in about an hour provided all goes well.

**Comment by vince-roll20** [comment]
Maybe the translation json's update when they go live?  The en.json was the only one I checked, and it was missing some keys from the translation.json.  I assume the other languages would also be missing the new keys...

**Comment by vince-roll20** [comment]
Just re-checked and it looks like they have been updated 30 minutes ago.  Cool beans.  Thanks Cassie

**Comment by vince-roll20** [comment]
Resolved.  Feel free to close.  Thanks
