### ISSUE TITLE
[5th Edition OGL by Roll20] CSS seems to be missing for some roll templates

### ISSUE THREAD

**Issue by Zenith-One** [Roll20/roll20-character-sheets#5900]
It seems like some roll template CSS got lost in a recent update (see [this image](https://i.imgur.com/5vYsPvY.png))

**Comment by Zenith-One** [comment]
I would try and fix it and submit a PR, but the code isn't in the repo. I would assume this has something to do with WotC licensing and what not.

**Comment by clevett** [comment]
This should be fixed. I had it fixed midnight last night but we had to wait until it could be pulled it. :) Thanks for the report and offer of help.

- Cassie

**Comment by Zenith-One** [comment]
Awesome, thanks :)
