### ISSUE TITLE
[D&D 5e OGL by Roll20] Charactermancer Feats are always greyed out / disabled

### ISSUE THREAD

**Issue by geoidesic** [Roll20/roll20-character-sheets#5903]
Try creating a Goliath Barbarian 8, Rogue 1. On the `Ability score improvement / feats` button there is only the option to improve scores, the `Feats` tab is greyed out.
![Screenshot 2020-02-29 at 07 37 16](https://user-images.githubusercontent.com/4637995/75603458-6273c480-5ac6-11ea-962f-1b8d297acb10.png)

I thought this might be a multi class issue, but the same thing happens if I take a straight fighter standard human and level it up to lvl 4 – don't get access to the Feats tab; greyed out.

**Comment by Anduh** [comment]
You can't currently add feats at level-up, only at character creation. Roll20 have said they will make it possible at some point, along with proper integrating of what feats does, but there is no timeline.

**Comment by geoidesic** [comment]
Ok. But only variant humans get feats at level 1, so that means you can only use feats if you're a lvl1 variant human. With 20 levels, 23 races and (I can't be Bothered to count) how many sub-races. It works in less than 1% of the time, so they may as well not have bothered with that "feat"ure ;)

**Comment by clevett** [comment]
I'm going to close this issue. It's not really an issue as the level up feats were a feature never implemented rather than a bug. Keep an eye out..... :) They *finger crossed* are coming sooooon.
