### ISSUE TITLE
Shadowrun 5th Edition Skill rating not working

### ISSUE THREAD

**Issue by Laoch97** [Roll20/roll20-character-sheets#5905]
When imputing the skill ratings for the Roll20 Shadowrun 5e character sheet, it's not recognizing the number inputted for either the 'undefined_rating}' value or for 'undefined_rating_modifier}'. I've attached a screenshot of the issue. 
![Issue 1](https://user-images.githubusercontent.com/61660011/75629184-bc9b8500-5bad-11ea-95e7-22c64d533be6.PNG)
![Issue 2](https://user-images.githubusercontent.com/61660011/75629185-befddf00-5bad-11ea-81f3-d30d23478ddb.PNG)

**Comment by clevett** [comment]
Thanks for the report. I'll take a look at it.

**Comment by clevett** [comment]
This should now be resolved. Let me know if its still an issue and we'll reopen the ticket.

**Comment by Laoch97** [comment]
It looks to work perfectly, thank you so much!

**Comment by clevett** [comment]
Your'e welcome. Thanks for reporting this. I don't play the game any more and sometimes bugs slip through my checks.

**Comment by Laoch97** [comment]
I've noticed another issue pertaining to the weapon entry rolls, would you
like me to resubmit on Github?
