### ISSUE TITLE
[Nechronica] Fragments of Memory Issue

### ISSUE THREAD

**Issue by YuuHkiSay** [Roll20/roll20-character-sheets#5925]
As the Fragments of Memory part is set up now, inputting anything into FoM 1's No. field inserts the same thing into FoM 5's Title field and vise versa. 
If I understand how the coding works, I would suggest changing "attr_fragment1" to "attr_fragment1title", "attr_fragment5" just below it to "attr_fragment1no", and "attr_fragment11" to "attr_fragment1content", then just continue that trend through the others there mostly for ease of understanding them at a glance, else I guess you could really just make the aforementioned "attr_fragment5" into "attr_fragment16" to continue that strange trend.
Also, according to the rules, there are supposed to be 6 FoM recorded according to the section on recovering Madness points.

**Comment by nmbradley** [comment]
I'm going to close this as it looks as though this sheet has been broadly redesigned since this issue was created. If there are lingering issues with this sheet, please create a new issue.
