### ISSUE TITLE
[Warhammer 4e] Broken Ranged Weapon rolls

### ISSUE THREAD

**Issue by dawid00s** [Roll20/roll20-character-sheets#5941]
Ranged weapons' modifier replaces the target number instead of adding/substracting from it.

![image](https://user-images.githubusercontent.com/62206112/76701204-4fb0e080-66bf-11ea-8310-c1a65c0c881c.png)

![image](https://user-images.githubusercontent.com/62206112/76701209-593a4880-66bf-11ea-8d7e-124a5631a4b2.png)

**Comment by Djjus** [comment]
Can to test again? The appropriate skill has to have taken ticked in the skills tab. This is because advanced skill are not automatically learned like basic skills, so when you learn them the first like taken needs to be ticked.

**Comment by dawid00s** [comment]
Ah! You're right! We just checked the career box and didn't notice the "Taken" option haha. Thanks a lot for your help!
