### ISSUE TITLE
[Band of Blades] Roll templates are not playing gif animation

### ISSUE THREAD

**Issue by Logicon211** [Roll20/roll20-character-sheets#5950]
I'm not sure if it was an update to Roll20 that possibly broke this functionality but it appears as though the roll template gifs aren't playing.

As a result some of the templates actually obscure the text on screen as they're locked on a frame that's the same color as the text itself

Some rolls appear fine without the animation like this:
![image](https://user-images.githubusercontent.com/6579807/76715852-d3dd8500-670c-11ea-8264-5b83749d470b.png)

But some don't, like this one:
![image](https://user-images.githubusercontent.com/6579807/76715834-bc060100-670c-11ea-8f0e-4d37f94d0d53.png)

**Comment by Stexinator** [comment]
@Logicon211  if this is resolved, please close it

**Comment by Logicon211** [comment]
The animations are still not playing. But I the critical roll template is now readable at least
