### ISSUE TITLE
[RunequestGQS]The Magic modifier is calculated wrong

### ISSUE THREAD

**Issue by idubeda** [Roll20/roll20-character-sheets#5970]
There is a bug in this line: curPow should be curChr.

https://github.com/Roll20/roll20-character-sheets/blob/b105f8715e63d9f11eb7df79fc8cbf3a1bfc9e04/RunequestGQS/RunequestGQS.html#L4849

**Comment by idubeda** [comment]
I have submitted a Pull Request to solve this issue. #5971

**Comment by Anduh** [comment]
If your PR fixed it, you should close this issue.
