### ISSUE TITLE
Shadowrun 5th Edition import not working

### ISSUE THREAD

**Issue by reactormonk** [Roll20/roll20-character-sheets#5974]
The "Import Character" button doesn't do anything, and in the console I get the following error:

> COMPENDIUM_BOOK_NAME is not defined

**Comment by Anduh** [comment]
You need to have a compendium enabled in the campaign for it to work.

Any compendium will do, it's a quirk related to how the Importer is built.

**Comment by reactormonk** [comment]
Aye, that fixed it.
