### ISSUE TITLE
Shadowrun 5th Edition (Advanced) fails to import

### ISSUE THREAD

**Issue by reactormonk** [Roll20/roll20-character-sheets#5975]
This file (just exported via chummer) gives me "Error: invalid Structure* [Little_Lee.json](https://github.com/Roll20/roll20-character-sheets/files/4360823/Little_Lee.txt)

**Comment by reactormonk** [comment]
Stupid Windows and its BOM :-(

**Comment by badaz** [comment]
> Stupid Windows and its BOM :-(

How did you manage to import ?

**Comment by reactormonk** [comment]
I edited the file and removed the https://en.wikipedia.org/wiki/Byte_order_mark at the beginning. notepad should work. It's the weird first character. The first character should be a `{`, delete everything in front of it, should be 1-2 characters.
