### ISSUE TITLE
Star Wars FFG Roll20 - Dice not rolling

### ISSUE THREAD

**Issue by vinnmun** [Roll20/roll20-character-sheets#5985]
I selected the api compatible character sheet for my game room through game settings. I launch the game and I add a character sheet and it shows me the sheet but the buttons on the sheet seem to not activate? Am I missing something?

**Comment by Anduh** [comment]
Pretty sure you need to create roll tables or use some API with the sheet. Ask help on the Roll20 forums in the "Character Sheet" subforum.

**Comment by keithmedlin** [comment]
From your game's homepage (where you launch it)
1. Click Settings
2. Click API Scripts
3. In the search type: Star Wars
4. Select Star Wars: Fantasy Flight Games - Dice Roller

Once it's added, you can launch your game and the die roller should work as expected.

**Comment by Anduh** [comment]
As this isn't an actual bug with he sheet, this issue could be closed as solved.
