### ISSUE TITLE
Problème avec Cri de guerre du barbare

### ISSUE THREAD

**Issue by Mowtcho** [Roll20/roll20-character-sheets#6007]
Bonsoir, j'ai installé hier le script et un de mes joueurs à choisi le cri de guerre de la voie du barbare, qui es tcensé faire -2 au jets d'attaque au créature ayant moins de For et de PV max que le barbare ( gobelin 12 de For 10 pv max, Barbare 15 PV max 16 FOR) lorsque je le lance le cri de guerre apparait dans le tchat lais lorsque je lance les attaques avec les ennemies je ne vois pas apparaître de malus contre lui avec des attaques de contacts, et rien n'empêche de lancé de nouveau son cri plus d'une fois par combat.
Je te remercie en tous cas du super travail effectué c'est un vrai régale pour moi qui vais commencer à MJ avec en plus des nouveaux joueurs c'est super intuitif et promet un vrai gain de temps et une bonne dynamique !
Bonne soirée 
Cordialement

**Comment by Anduh** [comment]
Ask help on the Roll20 forums: https://app.roll20.net/forum/

**Comment by dyvim** [comment]
@Mowtcho quelle fiche est concernée par ton bug? Chroniques Oubliées Fantasy?

**Comment by Mowtcho** [comment]
C'est bon mon problème est résolu, j'avais du mal écrire un truc je pense, cela faisais l'effet seulement sur mes alliés mais maintenant ça fonctionne correctement merci :)
