### ISSUE TITLE
[Alien TTRPG] Secret/GM rolls

### ISSUE THREAD

**Issue by jayy00** [Roll20/roll20-character-sheets#6041]
I'm using the github character sheets to make running my game easier, but I also use the sheet for NPCs and Enemies, so i don't have a quick way to roll for them without letting my players see, i want to hide my rolls with an optional GM roll button, If it could just have a switch like on the D&D roll 20 sheet, it'd be a huge help. I'm sorry if this isn't the right way to request this feature, I'm new to github, so forgive me if this isn't the proper way

**Comment by Anduh** [comment]
study the code for existing sheets with "gm roll" options and adapt to your sheet. If you get stuck, ask help on the [Character Sheet Forums.](https://app.roll20.net/forum/category/277980)

**Comment by runiArnsbjornson** [comment]
I have the same request, i would like to know if someone can help with this because i'm really not proefficient in coding

**Comment by Anduh** [comment]
Same as my initial advice. Few reads the issues here.

**Comment by runiArnsbjornson** [comment]
tried to do it, PR is done, waiting for reviews and merge, was the point of my comment in fact

**Comment by Stexinator** [comment]
@jayy00  if this is resolved, please close it
