### ISSUE TITLE
Torg 4.01 update rejected - no issue 

### ISSUE THREAD

**Issue by G-G-G** [Roll20/roll20-character-sheets#6061]
My most recent pull was apparently rejected, and I dont see why, and didnt recieve any notice.

I don't want to submit another pull only for it to be rejected again with no idea why. 
What happened, and how can i fix it?

It's this one: https://github.com/Roll20/roll20-character-sheets/pull/6052

**Comment by Anduh** [comment]
We concluded yesterday that this was caused by the submitter's use of the Pull-bot, and working with the main branch, therefor not caused by Roll20. Issue is solved in my opinion.
