### ISSUE TITLE
Skill Titles on Roll20 Character Sheet not showing

### ISSUE THREAD

**Issue by Laoch97** [Roll20/roll20-character-sheets#6067]
![Skill Titles Gone](https://user-images.githubusercontent.com/61660011/78079554-5b1c3100-737a-11ea-8b00-466f9162d0d8.PNG)

The Skill Titles are gone, they show when the entry is expanded, but not when collapsed.

**Comment by vince-roll20** [comment]
Which sheet?

**Comment by Laoch97** [comment]
This is in reference to the Shadowrun 5e Roll20 Character Sheet

**Comment by Anduh** [comment]
@clevett sounds like your sheet

**Comment by clevett** [comment]
I wrote a function that should have fixed that on Tuesday, #6014 . If its still broke for you just change the skill and change it back. I added a display attribute to support languages other than English.

**Comment by Laoch97** [comment]
This does look correct now, thank you!

**Comment by clevett** [comment]
Thanks for reporting the issue. :)
