### ISSUE TITLE
[A song to Fire & Ice] Add "data-i18n" tags to the sheet

### ISSUE THREAD

**Issue by Gregb342** [Roll20/roll20-character-sheets#6090]
@Fraetor & @ajott 

I'd like to do a French translation of the "A song of ice & fire" character sheet.

Actually, the html file doesn't include any "date-i18n" tags, so I can create a "translation.json" file nor than a "fr.json" file.

https://github.com/Roll20/roll20-character-sheets/blob/master/A%20Song%20of%20Ice%20and%20Fire/SIFRPNew.html

Would it be possible for you to edit the original html file so I can do the translation ?

Thank you very much

**Comment by Fraetor** [comment]
Hi,
A translation would be great, however I am not actually very experienced in HTML, and have previously only tweaked the dice logic on this sheet, which doesn't require anything fancy. As such I am unsure quite how I would go about readying the sheet for translation.

**Comment by Gregb342** [comment]
Thank you for the anwser @Fraetor 

So is @ajott the main author of the sheet ?

**Comment by Fraetor** [comment]
According to the commit history, the sheet was originally written by @raulhess with major changes subsequently by @CoalPoweredPuppet.

**Comment by dyvim** [comment]
Perhaps @Anduh and his script can help...

**Comment by Baledin** [comment]
I'm willing to take a run at this.

**Comment by Anduh** [comment]
I can run my script at this and see what the results are.

**Comment by Gregb342** [comment]
@Anduh please do, and tell us the results ^^

**Comment by Baledin** [comment]
If be happy to review it following the script (new here so unsure what the
script accomplishes but probably similar to my regex search)

**Comment by noritaka97** [comment]
Hi everyone,
I just push a request to add a army sheet layer to the character sheet.
Next step, i plan to add "data-i18n" tags to the sheet and a french translation. (in 1 ou 2 weeks).

**Comment by noritaka97** [comment]
Hi @Baledin @Gregb342 @Fraetor ,
Today, i just push a update of the character sheet that integrate the translation support.
#6492

**Comment by noritaka97** [comment]
Hi Everyone, 
Translation was merged to the character sheet.
French Translate (my native language and based on the french version of the RPG book) will be available in the next merge #6514, be enjoy to translate to other language.
@Anduh : I think this issued can be mark as solve after the next merge. :-)
