### ISSUE TITLE
[El Resurgir del Dragón] Proficiency Bonus (with Perception Proficiency) is not added to Pasive Perception

### ISSUE THREAD

**Issue by ArturoFigueroaR** [Roll20/roll20-character-sheets#6104]
When the Perception Skill is marked as "Proficient", The Passive Perception only applies Wisdom Bonus and not Proficiency Bonus

**Comment by nmbradley** [comment]
Closing this issue as it appears that this was resolved by #7950. If there are remaining problems, please create a new issue.
