### ISSUE TITLE
[Das Schwarze Auge 5] - Spell comments not saved

### ISSUE THREAD

**Issue by HauRukh** [Roll20/roll20-character-sheets#6125]
-The character sheet allows to fill in a comment field for spells, but the text is not saved after closing the sheet. 
- Only pre-implemented spells are affected. Spells added manually via the "Add" function keep their comments.
- This is reproducible for several people.

**Comment by dyvim** [comment]
@mckee14 have you seen this issue?

**Comment by mckee14** [comment]
Saw it just now. All the fields are missing the attr_ prefix, so nothing is stored.
I can fix that, but it will be a lot of manual work. maybe I can get a regexp working for it, otherwise it will take a while...

**Comment by mckee14** [comment]
OK wow, it went way quicker than i thought. It's fixed and should be included in the next update.
I will also try to fix all the button rolls to include the translations.

**Comment by dyvim** [comment]
wow. thanks a lot

**Comment by HauRukh** [comment]
Agreed, thank you.
