### ISSUE TITLE
Forbidden Lands: translation.json and en.json(as well as other language files) do not match

### ISSUE THREAD

**Issue by vince-roll20** [Roll20/roll20-character-sheets#6134]
For some reason, the en.json file does not match the translation.json file...?  Here's the translation.json submitted with yesterday's pulls
https://github.com/vince-roll20/roll20-character-sheets/blob/304013d4532ad0f1bcc78210019725ce31780600/Forbidden_Lands/translation.json
but here's the current en.json
https://github.com/Roll20/roll20-character-sheets/blob/master/Forbidden_Lands/translations/en.json
Any help?   Thanks.

**Comment by vince-roll20** [comment]
Can I simply update en.json(and any other language files) myself to match translation.json? Thanks

**Comment by vince-roll20** [comment]
I've went ahead and updated the various language files in this week's pr ( #6173 ) to match my latest translation.json.  Hopefully this will solve any discrepancies.

**Comment by nmbradley** [comment]
Closing as this seems to have been resolved.
