### ISSUE TITLE
[Dark Heresy Advanced 2nd Edition] skill rolls not working

### ISSUE THREAD

**Issue by SmutsMuts** [Roll20/roll20-character-sheets#6138]
If you try to click the skills or hit buttons in the character sheet nothing happens. 
I have tried a bit to make sure all attributes exists but even with the existing nothing happens.

this is the command used for the skill rolls: !skill40k @{character_name},@{Agility},20,0,0,0,?{Total Modifiers|0}

**Comment by SmutsMuts** [comment]
Tried a lot with this but I cannot get the "!skill40k" to work, I tried to edit the value for the button to send fixed values but nothing happens in the chat. Feels like the script is not loaded properly for the character sheet?

**Comment by SmutsMuts** [comment]
@messiahcide you seems to be the one that made this from the start? Could you take a glance on this? Would like to get this to work so we can use this during the corona times now and probably ongoing after that as well :)

**Comment by Anduh** [comment]
Do you have the APi script installed? "!skill40k" is clearly an API command, so this clearly can't work without it.

**Comment by SmutsMuts** [comment]
Yeah after i manually added two scripts for the campaign and pasted in the script code it worked. But shouldn't that be automatic? Or is this how it's supposed to work?

**Comment by Anduh** [comment]
API scripts are a Pro-features, and enables some tricky things that can't be done with plain macros. Character sheets are encouraged to be made so that they can work without APIs(so free players can use them), but it's harder for some games than others.

Things are exactly as they should be.

**Comment by SmutsMuts** [comment]
I see! Thanks!
