### ISSUE TITLE
[Star Wars] NPC Add More Custom Skill Slots

### ISSUE THREAD

**Issue by keithmedlin** [Roll20/roll20-character-sheets#6142]
The NPC Character Sheet currently only has 5 slots for Skills. Many of the NPCs in the published adventures have more than this even when taking into account the built-in:
- Cool
- Vigilence
- Lightsaber
- Brawl
- Gunnery
- Melee
- Ranged Light
- Ranged Heavy

_For example:_ 

Onslaught at Arda I:

- Setenna Hase
- General Ran Niall
- Commander Danel Qurno

I think a reasonable number for the NPC would be somewhere between 8 - 10 instead of 5.

**Comment by Anduh** [comment]
Which Star Wars sheet is this? Please give the exact name, and also edit the title of the issue to include it.

**Comment by nmbradley** [comment]
@keithmedlin I assume this is for one of the FFG sheets, but could you specify which exactly?

**Comment by nmbradley** [comment]
This issue is impossible to identify to even begin a fix with the information that has been provided. If there's still an issue here, please recreate the issue with more information.
