### ISSUE TITLE
[Warhammer 4e Character Sheet] Rolls for "Cool" under Combat Actions not accepting modifier

### ISSUE THREAD

**Issue by drockod01** [Roll20/roll20-character-sheets#6152]
When I click to roll for Cool and input a percentile modifier for the test difficulty, the modifier is not added to the Target Number. The other Combat Actions incorporate modifiers normally.

Mousing over the Target Number in the chat, it looks like there's an extra bracket that's throwing off the calculation. The images compare my rolls for Cool and for Perception, both of which should have the same total Target Number
![rollPerception](https://user-images.githubusercontent.com/43644357/79020837-ec905d80-7b47-11ea-8b24-26711ea45161.PNG)
![rollCool](https://user-images.githubusercontent.com/43644357/79020839-ec905d80-7b47-11ea-9a2e-72258bd24edb.PNG)

**Comment by Anduh** [comment]
Looking at the sheet code, I can't see the extra curly bracket. https://github.com/Roll20/roll20-character-sheets/blob/3e7b278e43aaa2e38088c7519b5f04aa21ea00b1/WFRP4CharSheet/WFRP4Charsheet.html#L1012

Have this been fixed? If so, this issue could be closed.

**Comment by drockod01** [comment]
It's not fixed yet; I'll see if I can find more information on the problem
