### ISSUE TITLE
[D&D5th] Character rolls -1+1 on attributes.

### ISSUE THREAD

**Issue by Velocikitty** [Roll20/roll20-character-sheets#6155]
https://i.imgur.com/9g06g6K.png (Picture of the issue.)
https://i.imgur.com/D2kZark.png (The formula when hovered over to explain it.)

@{Jeffery Goodwin |wtype}&{template:simple} {{rname=^{strength-u}}} {{mod=@{Jeffery Goodwin |strength_mod}@{Jeffery Goodwin |jack_bonus}}} {{r1=[[@{Jeffery Goodwin |d20}+@{Jeffery Goodwin |strength_mod}@{Jeffery Goodwin |jack_attr}[STR]]]}} @{Jeffery Goodwin |rtype}+@{Jeffery Goodwin |strength_mod}@{Jeffery Goodwin |jack_attr}[STR]]]}} @{Jeffery Goodwin |charname_output}

Only this single sheet is the one that is the issue. No one else rolls the same issue. I took a look at the sheet, and it was setup the same as my own. My own roll: https://i.imgur.com/s4SZHVy.png

Oddly enough, it disappears when the sheet is turned into an NPC.

(Forwarded to my DM, in case someone wants to get into the game to poke at the sheet.)

**Comment by nmbradley** [comment]
Closing this issue as it is nearly a year old, and no similar issues have been reported. If you feel as though there is still more to do with this problem, please create a new issue.
