### ISSUE TITLE
[Das schwarze Auge 5] - Pain Levels automatically applied to NPC sheets

### ISSUE THREAD

**Issue by HauRukh** [Roll20/roll20-character-sheets#6189]
For NPC sheets, their "supposed HP max" is computed as if they were PCs. Based on that number, they might receive automatic pain levels when their LE value is not set to the computed maximum (that is not visible in NPC mode).

@mckee14 can you have the automatic calculation deactivated when NPC mode is activated?

**Comment by DanieleSuppo** [comment]
Same happened to Savage Worlds - Tabbed, so I feel is something related to the whole last release.
Neither the sheet nor the translations are updated.

**Comment by mckee14** [comment]
I fixed it for the next release.
If you activate the NPC / Minion Sheet Version, all the autocalc (pain, LE, AE, KE) is skipped. The rest should work the same way it did before i changed anything (attacks etc).
You have to track all values including the _max values by hand, tough.

**Comment by HauRukh** [comment]
Thanks a lot!

For NPC sheets manual tracking should be fine, the NPC option is for "I will just set values as I want them, ignoring character rules" after all.
