### ISSUE TITLE
[Stars Without Number Revised] Adjusting max Effort in case of Psychic training foci

### ISSUE THREAD

**Issue by rafjaf** [Roll20/roll20-character-sheets#6211]
Hello,

First of all, thank you for the great job done in creating SWN Revised Character sheet!

One suggestion : according to Psychic Training Foci Level 1, "Your maximum Effort increases by one." However, there does not seem to be a way to edit the maximum amount of Effort on the sheet to reflect this.

Thank you in advance for considering implementing this.

Best regards,
Rafaël

**Comment by clockworkbard** [comment]
When I ran into this situation I dug through the source and found that there is an attribute to handle this, despite there being no UI field to enter it.

Under Attributes and Abilities, create a new Attribute named "psionics_extra_effort" and set it to 1.  Next time you commit or uncommit effort, the sheet will recalculate the Uncommitted effort and include the extra point.

**Comment by joesinghaus** [comment]
It's probably better to report issues in the sheet's own fork: https://github.com/Karlinator/roll20-character-sheets/issues.

For what it's worth, there's actually a UI field for this (though clearly the UX is deficient if neither of you found it). You need to enter the settings menu (gear icon) and there you can find a field for modifying max effort.

**Comment by rafjaf** [comment]
Thank you very much, I had not seen the setting indeed! Now it works perfectly
