### ISSUE TITLE
[Das Schwarze Auge 5] High Contrast Mode (Feature Request)

### ISSUE THREAD

**Issue by HauRukh** [Roll20/roll20-character-sheets#6224]
The character sheet is difficult to read for vision-impaired people, due to the colourful background.

@mckee14 If it is not too much work, would it be possible to have a button in the options tab to replace the brown background picture with the plain white sheet background?
I have a vision impaired player who has trouble reading the black on brown sheet.
The "default" sheet without css loaded would be very readable for him though.

**Comment by mckee14** [comment]
I have literally NO idea about CSS, so sadly no. 
The background picture is the first thing in the CSS file, if you have a PRO account, you can set up your game with your own charsheet.  That way, you could use the files from the R20 repo and just delete the part with the background in the CSS file - it works, I tested it locally.

To change it depending on a checkbox, you would have to go via the R20 forum or some CSS school sites.

**Comment by ap3h3ad** [comment]
@HauRukh I'd suggest to ask this question [https://github.com/Meteox/roll20-character-sheets/issues](here). This is the URL you get when you click on the feedback button in the actual sheet.

Replacing the background image upon clicking on a checkbox is a rather trivial topic in CSS so it should be no problem at all.

**Comment by mckee14** [comment]
The original creator (Meteox) abandoned this project. If you can't get a response from him, you could also ask in the R20 forum and post a link to the rather small CSS file out of the github repository. I'm sure you will get the answer quick. Maybe discuss it with your friend beforehand: What colors would he like? Maybe you can make it even better that just remove the background image.

**Comment by Stexinator** [comment]
@HauRukh  if this is resolved, please close it

**Comment by HauRukh** [comment]
Probably won't happen
