### ISSUE TITLE
[Shadowrun5thEdition] Matrix Initiative

### ISSUE THREAD

**Issue by Utahsinner** [Roll20/roll20-character-sheets#6226]
@clevett 
The Matrix Initiative field isn't accepting dice modifiers (Second box) both Positive and Negative.

Looking at the tooltips on the sheet it appears that the final calculation is calling for @Matrix_Mod + @Matrix_Mod and it probably needs to be @Matrix_Mod + @Matrix_Dice when comparing it to both base initiative and astral initiative, though I'm not familiar enough with Roll20 sheet building to try a hand at any fixes myself!

**Comment by gdelmee** [comment]
One thing which might be interesting regarding matrix initiative is having the choice between AR / VR cold / VR hot in the deck pane and having the right matrix initiative directly calculated.

**Comment by clevett** [comment]
AR initiative just uses Meat Space initiative. 

From my experience of thousand hours with only VR Hot Sim is every used. VR Cold sim can just be handled by adding a negative modifier to the dice if you want it.
