### ISSUE TITLE
[Das Schwarze Auge 5] Some bugs & a request (1.2.7)

### ISSUE THREAD

**Issue by Landorlin** [Roll20/roll20-character-sheets#6281]
Bugs
- Different calculation of Wound Treshold (Wundschwelle) at Main Page and Combat Page: At main page it is correct (.5 rounded up), at combat page it is rounded down
- Attack, Dodge & Weapon Block values wrong at combat page: they all get -3 (which they shouldn't)

Request
- Talent Specialization is missing (Sonderfertigkeit)

Thanks for your work,
L

**Comment by HauRukh** [comment]
Hi Landorlin,
The combat stats might be affected by a states set in the "states" tab. Can you check that there is nothing applied there? (Pain, fear etc.). 

The sheet currently assumes you play with pain levels per percentage health lost, and automatically applies pain levels if you current LP goes below the respective thresholds. if you play with the optional wound focus rules, you might have to overwrite that.
@mckee14 Maybe a checkbox to (de)activate auto calculation for pain in the ooptions would make sense? That could also cover the deactivation for NPCs, maybe just make it an explicit choice?

Talent Specialization IS implemented for skill, the button with the FS on it, next ot the normal roll for every skill is exactly that. Roll the SF button instead of a normal roll when the specialization applies.

**Comment by mckee14** [comment]
On the status page, you can set the modificator for pain to -4. That way, no matter what the sheet calculates, it will end up with pain level 0.

Then you can just add single levels by adjusting the modificator.

Please let me know if you prefer a checkbox in the settings to deactivate the pain level tracking.
(But keep in mind, then will other questions arise, like: why is the modificator not working on the status page?)

I can check wound treshold calculation. The values for attack, dogde and block should be correct. Please check the BE, too (from Armor).

**Comment by HauRukh** [comment]
Hmm, maybe the checkbox for pain tracking could go next to the modifier field in the States tab? Then at least it is obvious to people wanting to manage pain levels that "automatic" is set.

**Comment by Landorlin** [comment]
Hi! One nights sleep and your answers helped.
-> The penalties at AT/PA/Ausweichen resulted from Status Schmerz being at level 4 because the sheet does not autofill hitpoints current to the value of hitpoints max (as it would logically be if it was handwritten at a piece of paper). Adjusting the Lebenspunkte Aktuell in the first tab resolved that.
-> The different outputs of WS remain, but it's not a mistake of floor/ceil/round. It's a mistake with "Eisern" (which I happened to use). This modifier seems to miss at the output at the combat tab. I didn't doublecheck that as the code is a pain to navigate.
-> FS, ah, now I understand those different buttons. Also R now i understand after i read some code last night. This is a key feature and should be mentioned in the readme.md. Or maybe add 2 new templates for the output of them so players understand them intuitivly.

I got another question and a proposal for a feature. Do you prefer github for communication or should I join you at Orkenspalter? Ich kann auch auf deutsch wechseln.

Liebe Grüße,

**Comment by mckee14** [comment]
Hallo Landorlin

Die LE Aktuell möchte ich auf manuelle Eingabe lassen. Beim Erstellen würde es Sinn machen, diesen Wert auf den LE_Max Wert zu setzen, allerdings weiss das Sheet nicht, ob Du einen Char erstellst oder einfach damit spielst. Es wäre recht uncool, wenn du zb. die KO anpasst und dadurch plötzlich deine Lebenspunkte auf Maximum gefüllt werden - und öhm, du weisst dann nicht mehr, wie viele LeP du davor hattest. Mitten im Abenteuer. Daher lasse ich dies auf manueller Eingabe

Wundschwelle schaue ich mir mal an, offenbar wahrscheinlich ein kurzer Fix.

Ja, der Code ist recht schwer zu navigieren - es war vorher rein gar nix dokumentiert, die sheet basiert zur Hälfte noch auf Autocalc und die andere Hälfte machen sheetworker, und es haben auch schon mehrere Leute daran herumgefummelt. Daher versuche ich, so wenig wie möglich an der Grundstruktur zu ändern. Um Autocalc Felder umzustellen, musst du jeden Wert darin zum Ursprung zurück verfolgen und dann vom Anfang aus wieder an jedes mögliche Ende durchspielen, damit Du nichts zerschiesst...

Die Templates für die Würfelausgabe basieren ebenfalls auf Autocalc, zudem bin ich in HTML und CSS voll die Pfeiffe. Ich kann mal schauen, ob ich es geändert bekomme. Leider ist jeder Würfelwurf separat eine Codezeile, muss also mit RegExp arbeiten. Mal schauen, ob ich da eine gute Möglichkeit finde - 650 Zeilen von Hand anpassen habe ich nämlich wenig Lust ;-)

**Comment by Landorlin** [comment]
Hallo mckee,

(es folgt eine wall of text)

ja das mit jedem Würfelwurf eine Zeile hat mich echt umgehauen :) Ich hatte mehrere Stunden im Code gesucht wo das Würfeln mit 3W20 eigentlich ist bevor ich endlich gemerkt habe daß der ganze Code voll davon ist. Und heute erst hab ich verstanden wie der Würfelwurf eigentlich funktioniert. Soviel zu meiner Expertise..

Ich hab dann versucht Makros zu bauen damit und das funktioniert zwar in der Basis, aber es gibt einfach zuviele Variablen die man ändern möchte und nicht kann, somit nicht funktionabel . Wenn man für DSA ein Würfeltool haben will, kommt man an einem Character Sheet nicht vorbei. Und hier komme ich zu meinem Vorschlag:

Ich würde das Sheet um ein Würfeltool ergänzen, womit es möglich ist regelkonforme 3W20 Würfe mit beliebigen Modifikatoren zu machen. In beiden Sheets (also 1.2.7 als auch TSA) läßt sich das mit einfügen (quick & dirty, sag ich mal). Die Idee ist auch eine geeignete Grundstruktur für ein ganz neues Sheet.

Am Würfelwurf ändert sich nix:
```
<pseudo code>
Fertigkeitswert - {1d20-@{CharName|Eigenschaft1_Wert}+Modifiers },0d1}kh1 - {1d20-@{CharName|Eigenschaft2_Wert}+Modifiers },0d1}kh1- {1d20-@{CharName|Eigenschaft3_Wert}+Modifiers },0d1}kh1
--> auslesen & ausgaben mit dem  Template
```

um EINEN solchen Würfelwurf herum baut man jetzt ein neues Tab im Sheet:
```
<input type="radio" name="attr_tab" class="sheet-tab sheet-tab9" value="9" />
	<span class="sheet-tab sheet-tab9" data-i18n="Konfiguration">Konfiguration</span>
<input type="radio" name="attr_tab" class="sheet-tab sheet-tab10" value="10" />
	<span class="sheet-tab sheet-tab9" data-i18n="Würfeltool">Würfeltool</span>
</br>
```

in diesem neuem Tab brauchen wir dann eigentlich nur die Grundeigenschaften (MU, KL, CH...)
wie man das folgende macht weiß ich nicht, es ist ewig her das ich programmiert hab, und html erst recht nicht. Die Maske sollte folgendes mindestens enthalten:

- Buttons mit denen man eine beliebige Eigenschaftskombination, wie man sie für Talentproben braucht, auswählen kann (MU/GE/KK, KL/INI/IN,...)
- eine Eingabe für den Talentwert
- eine Eingabe für die Schwierigkeit (dropdownmenü von -5 bis +5 zb)

Sinn machen würde/könnte auch:

- eine Verknüpfung mit Zuständen (falls sie schon woanders gepflegt werden) und/oder Buttons um Zustände schnell hinzuzufügen (um nicht das Tab wechseln zu müssen)
- eine Möglichkeit die Grundeigenschaften temporär zu verändern (zB wegen magischer Steigerung)
- ein Menü/Menüs/whatever um auf die bereits gepflegten Daten des Sheets zurückzugreifen (-> "Wähle Talent" -> "Klettern" -> automatisch MU/GE/KK auswählen & TaW setzen)
- Optionen für Wilde Magie / Tolpatsch u.ä. (also 1d20cs1cf>19 anstatt 1d20cs1cf20)

und einen dicken Button für würfeln und fertig



Soweit meine Skizze.

Warum das alles:
- ich selber brauch eigentlich nur sowas, kenne roll20 aber erst seit 1 woche und hab mir jetzt noch keinen pro account geleistet
- es ist super praktisch für Spielleiter die ihre Notizen im real life gemacht haben oder einen Char on the fly etwas machen lassen wollen
- es ist super praktisch für Spieler die nicht ihren ganzen char übertragen wollen
- wenn man weiß was man würfelt sollte es schneller gehen als das passende Talent/den passenden Zauber erst im Sheet suchen zu müssen
- kann mit vielen hausregeln umgehen
- weil ein generisches DSA5 würfeltool
- die tausend und ein würfelwürfe im code sind **schrecklich**

**Comment by mckee14** [comment]
Bin grad unterwegs, daher kurzversion per Handy. Heisse auf orkenspalter
übrigens mckee14, kannst mich auch da anschreiben.

Zustände werden bereits berücksichtigt, je nach wunsch inkl BE oder ohne
BE. Kannst mal BE2 rüstung anlegen und 2 stufen betäubung einstellen, bei
den talenten sind dann gewisse um 2 erschwert, andere um 4.

Und (tadaaaa) du kannst ganz oben rechts im sheet “modifikator“ aktivieren.
Danach kannst du bei jedem wurf eine erleichterung/erschwernis mitgeben.
Diese ist kumulativ zu zuständen.

Dann kannst du bei den talenten schon die eigenschaften umstellen, auf die
du würfelst. Da kannst du einfach ein talent nehmen, auf das du nie
würfelst (schiffe fahren oder fliegen oder sowas), und so für jeden
beliebigen wurf dieses talent nehmen - eigenschaften und talentwert kannst
du vor dem wurf anpassen.

In den würfelergebnissen kannst du auch jetzt schon die einzelnen werte
sehen bei mouseover und so prüfen, ob du 19er / 20er geworfen hast.

Das sheet kann also schon alles, was du möchtest, es ist bloss schlecht
dokumentiert :).

Temporäre Modifikatoren auf Grundwerte wären toll, sind aber fast unmöglich
zu implementieren.

Patzer und crits sauber abzufangen auch, egal ob auf 20er oder 19er. Du
müsstest erst rollen, die rolls separat in variablen speichern, danach die
variablen mit javascript durchgehen, resultate wieder in variablen
speichern und diese dann per rolltemplate ausgeben. Rolls lassen sich aber
nicht per script starten, also müsste man für alles 2 mal klicken... Die
DSA proben und r20 sind nicht sehr kompatibel ;)


Landorlin <notifications@github.com> schrieb am So., 26. Apr. 2020, 16:39:

**Comment by Landorlin** [comment]
Ja das ist natürlich ein Hack den ich so garnicht gesehen hab. Richtig zufrieden bin ich mit dieser Lösung aber nicht. Zum einen das Design / die Usability: ich empfinde die Buttons teilweise als zu klein bzw. die (Art und Weise des)  Wechsel(s) zwischen Maus und Tastatur als unangenehm. Da setz ich mir lieber ein Makro mit "/roll 3d20" und rechne selber im Kopf. Zum anderen das Design des Codes. Also reine Prinzipientreterei - sry da meldet sich wohl meine Kultur.. ;) Der ist mit diesen zighundert individuellen Würfelwürfen unnötig aufgebläht und schwer zu verändern bzw. zu warten. (es sind momentan 466 Zeilen des Typs button="roll" vorhanden)

Ja nee, zufrieden bin ich nicht. Ich bin aber, nur um es mal gesagt zu haben, natürlich trotzdem glücklich überhaupt was zu haben und es funktioniert gut für unsere Gruppe (bzw. wird)

Zum Thema 2mal klicken. Wäre das denn so schlimm? Ich werd mir mal ein paar Gedanken machen.

**Comment by HauRukh** [comment]
Da bisher niemand außer mckee am code arbeitet hat der sicher keine lust die core mechanic neu zu schreiben "einfach weil".
So wie ich das verstanden habe wollte er auch nur ein paar bugfixes machen, und weniger re-design. Von daher: aktuell ist unschön aber geht, so lange niemand dran rummachen will ist auch egal ob es dumm implementiert ist. Wer massiv was dran ändern will kann dann ja gerne auch die Mechanik dazu umändern.

Wenn du gerne von hand 3w20 würfeln willst steht dir das ja frei, da muss man dann aber am sheet nichts ändern.

Viele Sachen gehen in roll20 einfach erstmal nicht weil die Scriptsprache nicht Turing-vollständig ist, da muss man sich dann mit abfinden. Ich bin schwer gegen jeden Wurf 2 mal würfeln, da schaue ich lieber bei roten oder grünen Würfen nach obs noch ne zweite 20/1 gab.

**Comment by Landorlin** [comment]
Hallo HauRukh. Ich verlange ja garnix. Beschäftige mich grad selber damit und bin sehr froh darüber hier mit Gleichgesinnten drüber reden zu können. Falls Du meine Beiträge anders wahrgenommen hast entschuldige ich mich. Sind wirklich nur Ideen über die ich mich gerne austauschen will, und das hier war der erste Platz der sich ergeben hat.

Ich denke den Beitrag kann man dann auch schließen. Lg.

**Comment by mckee14** [comment]
Nicht streiten. Dafür gibt es doch Reallife und Waffen! ;-)

Update: Wundschwelle ist angepasst, Vorteil/Nachteil wird nun auch auf der Kampfseite so berechnet wie auf der Hauptseite. Ist im nächsten PullRequest enthalten.

Und ja, der Code ist unschön, aber er ist halt auch über lange Zeit gewachsen. Dabei haben sich R20 features verändert, allenfalls ging das früher nicht anders.
Die würfelmechanik im sheet zu überarbeiten erachte ich als nicht zielführend - da würde ich vorher beim neuen Sheet (Das schwarze Auge 5 - TSA Edition) ansaugen, das ist viel stringenter aufgebaut und wird aktiv entwickelt. Sobald man dort auch Vorteile/Nachteile gut abbilden kann, werde ich wohl auch wechseln, aktuell ist dieses Sheet mit meinen Chars noch besser zum würfeln geeignet.

DSA hat halt schon eine eigene Würfelmechanik, und R20 ist da so rein gar nicht drauf ausgelegt. Zudem bringt R20 mega viele Einschränkungen und Eigenheiten mit sich, die man nicht erwarten würde (und ehrlich gesagt auch nur strunzdumm sind manchmal).

Wieso kann ich kein Kompendium anlegen? Wieso kann ich Würfelwerte nicht direkt in einem script rollen und dann die ergebnisse nutzen? Wieso kann ich keine Daten aus einer Datenbank nutzen (!!EInseLF!1!11). Wir haben das Jahr 2020 und R20 geht davon aus, dass wir DATEN in HTML speichern. Alter Schwede :-).

**Comment by Stexinator** [comment]
@Landorlin  if this is resolved, please close it

**Comment by nmbradley** [comment]
I'm assuming from the last comment from mckee that this issue is resolved to the point that can be managed without changes to the Roll20 infrastructure, so I'm going to close this issue. Please feel free to create another if there are lingering issues.
