### ISSUE TITLE
[Das Schwarze Auge 5] Name Typo

### ISSUE THREAD

**Issue by Ziturion** [Roll20/roll20-character-sheets#6284]
There's a small typo in one of the names of the talents in german.
Correct way: "**Alchemie**"
incorrect way: "Alchimie"

Steps to reproduce:
-create character with alchemy
-roll alchemy
-watch in Chat
![image](https://user-images.githubusercontent.com/10163803/80304380-54a19d80-87f0-11ea-9745-9be4420b2b58.png)

**Comment by mckee14** [comment]
I just checked and - contrary to regular language - within DSA it's really Alchimie. So it's correct, although strange :)

**Comment by Anduh** [comment]
@Ziturion is mckee14's claim about the how it says in the book correct? If the translation is correct as stated in the German books, this issue should be closed.

**Comment by Ziturion** [comment]
I can confirm that it is stated as "Alchimie" in the book. Apparently the name is different from the actual real world which is confusing but @mckee14 is correct. Therefore, I will close this issue. Thanks for your help!
