### ISSUE TITLE
[WFRP4CharSheet] Polish translation issue

### ISSUE THREAD

**Issue by moonwolf-github** [Roll20/roll20-character-sheets#6300]
Commit a826545b84fd5294a9aa3d48a44b944a31cb86b3 introduced error in polish translation (file https://github.com/Roll20/roll20-character-sheets/blob/master/WFRP4CharSheet/translations/pl.json). "Party-Long-Term" should stay as "Długi cel drużyny" (according to rulebook it should be "Długoterminowa ambicja drużyny").

**Comment by moonwolf-github** [comment]
CC: @Reonin

**Comment by Reonin** [comment]
Hi @moonwolf-github that may have happened after our translation script was run. We highly recommend using [Crowdin](https://crowdin.com/) more steps can be found [here](https://wiki.roll20.net/Building_Character_Sheets#Translating_Character_Sheets) and getting in and putting the proper translations. This will help ensure the translations you made don't automatically get overwritten. Cheers!

**Comment by moonwolf-github** [comment]
It wasn't my translation, i just spotted an issue and noticed it was your commit.

**Comment by moonwolf-github** [comment]
Commit 0d203c9479d0274f21039d3eaf7f98ba57afe325 fixed it.
