### ISSUE TITLE
[Das Schwarze Auge 5] - Request: Readable Spells

### ISSUE THREAD

**Issue by HauRukh** [Roll20/roll20-character-sheets#6305]
The spell description when hovering the "?" symbol is often so long it is extremely hard to read.

@mckee14 would it be possible (with limited work effort,i.e. scripted) to make the "?" symbol a button that shows the (translated) spell description text as a pop-up or something like that? (Possibly as a field with scroll bar to go through it)
Click the "?" symbol, get a (scrollable) text field with the description and a button at the end for "Close".

**Comment by mckee14** [comment]
I checked into that a while ago and didnt saw a quick solution.
But there is a hack - open the list with spells on the bottom, this makes
the whole page bigger. Now you can scroll down and then mouseover over the
? and it usually fits with all the text.

HauRukh <notifications@github.com> schrieb am Di., 28. Apr. 2020, 21:27:

**Comment by HauRukh** [comment]
It is what I do now, but with added spell enhancements eve that is sometimes not enough.
It also does nto wrok for poor half-blind wizards that need ultra big letters to read :(

But if there is no easy way, I guess we will have to make do.

**Comment by Stexinator** [comment]
@HauRukh if this is resolved, please close it
