### ISSUE TITLE
The One Ring character sheet polish translation (fan-made)

### ISSUE THREAD

**Issue by Nekromiko** [Roll20/roll20-character-sheets#6312]
Me and my friends are working on a polish version of the character sheet for The One Ring that is already in use in Roll20 games. The source books have not yet been published in our language so to keep the crucial immersion during the game we translated the game terms like atributes, skills, states and other game terms by ourselves. It worked well IRL but since we play on Roll20 we need some help to put all the previous work to good use. Obviously it's all fan-made and unofficial. We wonder if it will be possible to implement such a sheet to Roll20 inner workings. We'd appreciate if someone helped us with the process since we're new to programming.

**Comment by wakulig2** [comment]
Cześć. Zajmuję się tłumaczeniem na Roll20. Karta The One Ring nie jest tym, czym planowałem zająć się w najbliższym czasie, jednak jeśli zależy Ci na szybkim pojawieniu się tłumaczenia, jestem chętny pomóc.

Jeśli przygotowaliście tłumaczenie gotowe do publikacji (pl.json), to mogę poinstruować, jak należy opublikować je, aby mogło pojawić się w następnej aktualizacji.

Jeśli natomiast wasza praca wymaga wcześniejszego przystosowania do implementacji, jeśli dostarczycie tu wyniki waszej pracy, postaram się w wolnej chwili zaimplementować je w ramach weekly translations.

**Comment by clevett** [comment]
The One Ring has translations keys. You just need to get an invite to Crowdin to translate it into Polish. Email cassie@roll20.net requesting access to translate Polish to get an invite.
