### ISSUE TITLE
[Monster of the Week] "The Divine" playbook - The divine armor is missing in the translation json entries. 

### ISSUE THREAD

**Issue by Johneve** [Roll20/roll20-character-sheets#6329]
The "divine-gear6" json entry is missing from the json files.

**Comment by Anistuffs** [comment]
I have fixed it in my fork but will wait until next week before making a pull request as I'm also adding the playbooks from Tome of Mysteries.

**Comment by nmbradley** [comment]
Closing this issue as it seems to have been resolved by #6421
