### ISSUE TITLE
Monster of the Week Spellslinger moves broken

### ISSUE THREAD

**Issue by Osspial** [Roll20/roll20-character-sheets#6362]
The spellslinger moves no longer show up, and instead appear like this:
![image](https://user-images.githubusercontent.com/16296823/80920991-64196d00-8d41-11ea-9342-806e4f8cc413.png)

It appears to have been broken by 0225fd92f889f1f00bac623b070978a89b50a171.

**Comment by Anistuffs** [comment]
Can confirm. I have fixed it in my fork but will wait until next week before making a pull request as I'm also adding the playbooks from Tome of Mysteries.

**Comment by Anduh** [comment]
@Osspial was this fixed by Anistuff's update? If so, you could close this issue.
