### ISSUE TITLE
Question Character Sheet Update

### ISSUE THREAD

**Issue by Tealk** [Roll20/roll20-character-sheets#6390]
Hello,

i'm currently rebuilding the character sheet for [Aborea](https://github.com/Roll20/roll20-character-sheets/tree/master/Aborea), now i wanted to know how to handle it, because the current version doesn't work properly and doesn't comply with the guidelines.
I'm writing the whole arc from scratch. So should I overwrite the old one?

**Comment by Lockbox313** [comment]
You would have to make sure your folder and file names are different from the current  one and  ask for the old sheet be deprecated. It would probably be a good  idea to post something in the character sheet forums informing people you intend to do this. It would also be a courtesy to reach out to the original author.

**Comment by Tealk** [comment]
- So I should create a new character sheet instead of updating the old one?
- How do i ask for the old sheet be deprecated?
- I have already contacted the author and he said that I can rework his sheet.

> It would probably be a good idea to post something in the character sheet forums informing people you intend to do this.

Currently I get feedback from the forum of the rulebook. Since it is a smaller German rulebook, I reach most of the users there.

**Comment by Lockbox313** [comment]
The idea of posting in the character sheet forum is to give anyone that might be working on the sheet or thinking about working on the the sheet the heads up.

**Comment by Lockbox313** [comment]
You can make a request for the old sheet to be deprecated in the pull request for the new sheet or by emailing team@roll20.net.

**Comment by Anduh** [comment]
Yeah I wouldn't email Roll20 for this, just mention the replacement of the old sheet when you submit the new one. The are absolutely swamped with tickets in general.
