### ISSUE TITLE
[City of Mist] Cards Not Retaining Values

### ISSUE THREAD

**Issue by AtomicReaction** [Roll20/roll20-character-sheets#6395]
Mythos cards are wiping mysteries and concepts whenever you close the character sheet. All cards (apart from Crew Theme) have variable names in the power name field, and won't let you add power tags. They also wipe when the sheet is closed.
![image](https://user-images.githubusercontent.com/18200402/81247061-46186a80-8fd6-11ea-8b46-4888b62f11a2.png)

**Comment by vince-roll20** [comment]
While adding translation code to the sheet I accidentally submitted an earlier version of my edits.  More info here:
https://app.roll20.net/forum/post/8615516/city-of-mist-character-sheet
Fix has been submitted here:
City of Mist v1.03 - fixes the last update's i18n/html issues #6385

**Comment by phaldenby72** [comment]
Looks like it's fixed now - thanks Vince.

**Comment by vince-roll20** [comment]
Thanks for the hotfix.  I feel foolish letting something like that pass.  I never thought to even check that all my corrections were included. Sorry for the disruption.  Cheers

**Comment by Anduh** [comment]
If this is fixed, this issue should be closed @phaldenby72

**Comment by phaldenby72** [comment]
I agree, but I'm just another Roll20 user, not an admin or anything. I closed the one I raised. @AtomicReaction, can you close this?

**Comment by Anduh** [comment]
Sorry, tagged the wrong person.

**Comment by AtomicReaction** [comment]
Sorry about the delay. Looks like it is indeed fixed! Thanks for putting in the time.
