### ISSUE TITLE
Deprecate existing character sheet?

### ISSUE THREAD

**Issue by wesbaker** [Roll20/roll20-character-sheets#6397]
Hey there, I'm working on a character sheet—the Old-School Essentials AAC sheet—and hoping it'll replace the existing one one I add Descending AC support to it (wesbaker/roll20-character-sheets#2). 

At that point, the other one will largely be redundant. Is there a way to delete or deprecate an existing character sheet? Deletion sounds like a bad idea since it would affect existing games.

**Comment by wesbaker** [comment]
Similarly, what if I want to rename my character sheet? Is there a way to do that?

**Comment by Anduh** [comment]
You can create a pull request with superficial changes to your sheet, and include in the title and PR body the request of how the sheet should be named in the dropdown menu.
