### ISSUE TITLE
[Ironsworn] Allow translations

### ISSUE THREAD

**Issue by WallaceMcGregor** [Roll20/roll20-character-sheets#6465]
It would be great if the amazing sheet made by @LeeRhodes allows translations.

**Comment by LeeRhodes** [comment]
I was already partly through them but then delve came out and threw everything for a loop. It is likely the next thing I work on after the v2 of the sheet it out. ❤️

**Comment by WallaceMcGregor** [comment]
Ok. Thanks to the work you are doing. I'm waiting for this update to enjoy the upcoming official Spanish release of Ironsworn.

**Comment by Anduh** [comment]
Did you get stuck with the translations?

**Comment by aureyia** [comment]
No it's just on and off with when I can make changes. Been busy with work.

**Comment by WallaceMcGregor** [comment]
Is there any chance in the future that the translations can be set up for the wonderful sheet? The Spanish edition of the game has already been released and the community would be very grateful for the opportunity to have the sheet in their language.

Thanks

**Comment by aureyia** [comment]
Raised the following pull request to enable the translations: https://github.com/Roll20/roll20-character-sheets/pull/8438. Note that I am having to do this in phases, because of the amount of content being ported over.

**Comment by WallaceMcGregor** [comment]
> Raised the following pull request to enable the translations: #8438. Note that I am having to do this in phases, because of the amount of content being ported over. And some background prep I am needing to do for Starforge once that releases.

Thank you so much! Can I start translating?

**Comment by aureyia** [comment]
I'm not 100% clear on the process after this is deployed, other than roll20 handling the translations through Crowdin.

**Comment by nmbradley** [comment]
Closing this issue as it seems to have a resolution. Please feel free to create another issue if there are lingering problems.
