### ISSUE TITLE
[Monster of the week] Sentence building doesn't work with every language.

### ISSUE THREAD

**Issue by Johneve** [Roll20/roll20-character-sheets#6466]
The following structure appears multiple times in the improvement part of the playbooks :
<span data-i18n="another">Take another</span> <span data-i18n="Expert">Expert</span> <span data-i18n="move">move</span>
Using this type of sentence compositing can not apply in all languages, in French for example.

I propose a more linear form easier to translate as : 
<span data-i18n="another-move">Take another move from the playbook</span><span data-i18n="Expert">Expert</span>

**Comment by Anistuffs** [comment]
Will this following structure work? This way we don't need to have the playbook name.
'Take another move from your own playbook'

**Comment by Johneve** [comment]
There is no real need to precise the current playbook.
Yes, I agree with that ! Simple, direct, efficient ! :)

**Comment by Anistuffs** [comment]
Awesome. I have to fix some bugs with some of the item list. I'll include this in the fix :)

**Comment by Johneve** [comment]
Thanks !
