### ISSUE TITLE
[DnD 5e] Macros in initiative modifier

### ISSUE THREAD

**Issue by mileslucas** [Roll20/roll20-character-sheets#6505]
Using the 5e templates, I've tried adding an initiative modifier based off one of my skills, I don't think it's possible. It would be nice if it did (eg Tactical Wit from School of War Magic)

Tried-
    initmod | `@{intelligence_mod}`
    initmod | `[INT]`
    initmod | `[[INT]]`

**Comment by Anduh** [comment]
I think iẗ́'s intended to add any init bonus on the settings page.
https://wiki.roll20.net/D%26D_5E_by_Roll20#Attribute_Options

**Comment by mileslucas** [comment]
Okay, well it’s exactly where I looked to add bonus to my initiative and it only works with digits, while many other attributes work fine with macros. It’s just a quality of life thing so I don’t have to go deep within my page settings every time my intelligence changes.

**Comment by Anduh** [comment]
ask on the forums about it, I'm pretty sure you can do what you're asking for.

**Comment by mileslucas** [comment]
Right, I started by looking through the forums and the web but I haven’t found any discussion about explicitly using a macro inside the initiative modifier. There is no documentation of it either. 

Can you confirm with the code here whether it is possible or not? That seems easier than guessing. I’m curious how this is implemented in the Xanathar compendium, again for the tactical wit feat, if I can’t figure out the initiative modifier.

**Comment by Anduh** [comment]
Ask on the forums about it, I'm pretty sure you can do what you're asking for, but I'm not sure. Sorry I don't have more to say.

**Comment by Stexinator** [comment]
@mileslucas if this is done, please close it
