### ISSUE TITLE
[RunequestGQS] fails to render

### ISSUE THREAD

**Issue by LechPsztyk** [Roll20/roll20-character-sheets#6518]
Only code displays since last committ on Chrome and Firefox

relevant screenshot:

https://pasteboard.co/J96OkCC.png

![bug](https://user-images.githubusercontent.com/46745997/82343923-545d8200-99eb-11ea-8ef8-73f5db3f83c0.PNG)

**Comment by Lockbox313** [comment]
Some extra tags seemed to have gotten added to the front of the file <head></head><body>.  These have no effect in a custom sheet or sandbox but do seem to have an effect in the live system

I have uploaded a fix to remove this but I doubt they would  merge any pull request  this week.  I have asked about getting a rollback.

**Comment by Anduh** [comment]
@LechPsztyk you could edit this issue to state the name of the sheet **[RunequestGQS]**, so others also notice this.

For others who find this Issue, more info can be found in this forum thread: https://app.roll20.net/forum/post/8695053/runequest-character-sheet-issues

**Comment by LechPsztyk** [comment]
Done, and thank you for quick reply

**Comment by Anduh** [comment]
This sheet was fixed today(I tested), so this issue can now be closed: https://app.roll20.net/forum/post/8703742/release-note-for-may-21-2020-hotfix

**Comment by LechPsztyk** [comment]
Fixed, Thank you
