### ISSUE TITLE
[RunequestGQS] Character Sheet fails to render

### ISSUE THREAD

**Issue by ragamer** [Roll20/roll20-character-sheets#6533]
As the title explains. The character sheet tab on PC characters fails to render properly. The last time it was accessed and worked properly was on Monday 18/05/2020.

Language settings of all players seeing the same behaviour is english.

**Comment by Anduh** [comment]
This is a duplicate of #6518, where you can find more info. This should get a fix at latest next Tuesday when community sheets get their weekly updates.

**Comment by ragamer** [comment]
Ok... I see, thanks, when I stumbled over the problem I did a fast scan for similar open issues and the previous one didn't show the Sheet tag on the title, my bad. Closing this one.
