### ISSUE TITLE
Band of Blades Inlinerollresult color is same as background

### ISSUE THREAD

**Issue by clevett** [Roll20/roll20-character-sheets#6541]
Rolling Marshal as an Officer with Risky + Standard + 2 dice.

https://i.imgur.com/EpxXljo.png

`.sheet-rolltemplate-blades .inlinerollresult` sets the **background: transparent** while  `.sheet-rolltemplate-blades .sheet-holder.sheet-action` uses **color: # 333**. This makes the font effectively invisible.  

Recommend setting color to something lighter like #fdfdfe or adding light background to the template.

**Comment by clevett** [comment]
@joesinghaus My apologies for not reporting this via the directions on the readme.

**Comment by joesinghaus** [comment]
(no worries about wrong reporting location)
Hi Cassie, this problem is essentially #6166, which has now gone unfixed for weeks. The background for the roll template is a GIF which quickly moves on to a better contrast, but since the image proxy is broken, it is stuck on a bad frame.

**Comment by joesinghaus** [comment]
If the image proxy issue is going to essentially be unfixed for O(months), I'm going to ask Tim if he can cook up a static background that works, and I can replace the gifs with that...
