### ISSUE TITLE
Mutant Year Zero Character Sheet - Missing symbols 

### ISSUE THREAD

**Issue by m3koenig** [Roll20/roll20-character-sheets#6564]
Hi,

first time here and I hope im at the right point :)

We use the Mutant Year Zero character sheet for several months but now the symbols for grub, water and bullets are msissing.

![image](https://user-images.githubusercontent.com/9989457/82607339-ec5c9680-9bb8-11ea-8e1d-ecb946f2761a.png)

https://github.com/Roll20/roll20-character-sheets/tree/master/Mutant%20Year%20Zero

Tha last commit changes the path for that. I think there was something goes wrong.

greets from germany and btw thanks for that charactersheet!!

**Comment by Anduh** [comment]
@clevett seems like a typo in the new url

**Comment by aptMattKoe** [comment]
![image](https://user-images.githubusercontent.com/57363453/83101034-a9675b00-a0b1-11ea-84a5-6d2fbb2d283f.png)
Works again! thanks! :)

**Comment by m3koenig** [comment]
![image](https://user-images.githubusercontent.com/9989457/83101389-87baa380-a0b2-11ea-82d5-38fd6f543a2b.png)
Works again! thanks! :)

**Comment by Anduh** [comment]
close the issue if this is solved
