### ISSUE TITLE
[Tenra Bansho Zero - Spanish] merged 11 days ago, not yet available

### ISSUE THREAD

**Issue by Ravencrow** [Roll20/roll20-character-sheets#6586]
Hi there!

I have created a totally new version of Tenra Bansho Zero sheet, in spanish.
Can't be treated as translations of the original Tenra Bansho Zero sheet because we used the original sheet scans in spanish so the online character sheet looks the same as the one found in the manual.

The thing is that the commit was approved and merged 11 days ago, but the sheet is not available yet (2 mondays later).

I know we are not supposed to change the approved.yaml file, but I have seen in another issue that some people created a PR changing it just for the roll20 stuff to notice there is something needed to be added.

Should I create a new PR changing myself the approved.yaml file, even if it gets rejected?

Thanks for the responses.

**Comment by Anduh** [comment]
Yeah, I'd say do it. It's not guaranteed they check issues every week, so that's more reliable. The actions I took was exactly for this reason.

**Comment by Anduh** [comment]
Seems Roll20 accepted my edit suggestion to approved.yaml this week and didn't take a look at the issues(like this one), so the doing things yourself seem to be the best approach.

**Comment by Ravencrow** [comment]
Thanks, Anduh 👍
