### ISSUE TITLE
 [Lancer RPG] Broken Pilot HP Styling

### ISSUE THREAD

**Issue by aureyia** [Roll20/roll20-character-sheets#6589]
On, Chrome and Firefox the pilot hp is covering the Pilot Grit. Shown Below:

![image](https://user-images.githubusercontent.com/19798820/82715549-82f98800-9c8b-11ea-93de-b691f3061cae.png)

I believe this is the offending code: 
https://github.com/Roll20/roll20-character-sheets/blob/3e7b278e43aaa2e38088c7519b5f04aa21ea00b1/LANCER%20RPG%20(1.8)/LANCER.html#L323
The `width:145px`. Happy to remove it unless there is a specific reason for this being used?

**Comment by Anduh** [comment]
@spingle any comments?

**Comment by nmbradley** [comment]
Resolved by #9886
