### ISSUE TITLE
[Offworlders] MaxHP limited to 3

### ISSUE THREAD

**Issue by simon-workcircle** [Roll20/roll20-character-sheets#6596]
The maxhpvalue has a max of 3 and min of -1, it should just be min 0 like hpvalue below?

`<div class="maxhpvalue">
<input type="number" min="-1" max="3" value="@{str}+@{agi}+12" name="attr_hp_max" />
</div>
<div class="hpvalue">
<input type="number" min="0" value="@{str}+@{agi}+12" name="attr_hp" />`

**Comment by simon-workcircle** [comment]
Also, ticking 'ship' on the character sheet doesn't seem to persist, always defaults back to normal character.

**Comment by Anduh** [comment]
I submitted a fix for the ship sheet thing, but didn't touch the maxhp thing yet. Am I reading it right that the min should be set to zero, and the max should be removed entirely, as it's by default defined as a number way higher than 3.
