### ISSUE TITLE
Popped Character Sheet - Repeating Rows Modify Button Bug

### ISSUE THREAD

**Issue by MadCoder253** [Roll20/roll20-character-sheets#6641]
A few the sheet users for  the GURPS sheet noticed a bug when the character sheet is popped into it's own window. None of the move bars for dragging and dropping a row works on any of the tables. I tested this out on the D&D 5E sheet and the move bars didn't work. However, the drag-drop works fine when it's still part of the VTT.

![dnd-5e-drag-fails](https://user-images.githubusercontent.com/9192404/83107057-68038b00-a072-11ea-80ce-e736ae46e837.png)

**Comment by Anduh** [comment]
A longer list of known issues when char sheets are popped out: https://wiki.roll20.net/Character_Sheet#Character_Sheet_in_a_separate_window

**Comment by Anduh** [comment]
This isn't a bug with the GURPS sheet, but an inherit limitation of the character sheet system. @MadCoder253 can you close this issue?

**Comment by nmbradley** [comment]
Closing this issue for the reasons stated above.
