### ISSUE TITLE
Unisystem Buffy

### ISSUE THREAD

**Issue by amanwing** [Roll20/roll20-character-sheets#6666]
There is a problem on the NPC sheet. The boxes for the combat maneuvers are to small to show 2 digits.  they need to be a little wider and it should be fine. Tested on different browsers.

**Comment by amanwing** [comment]
I just solved the issue by myself. I just included style="width:70px" to all the wrong boxes.

**Comment by Anduh** [comment]
Could you submit the fix to the repository, or share your version so someone else can make the fix happen for the active Roll20 sheet?

**Comment by amanwing** [comment]
I am sorry first time user here. I thought I did. I created a pull request. Is there something else I need to do?

**Comment by Anduh** [comment]
You did, but it was a minute after I asked my question :smile:
