### ISSUE TITLE
[GURPS] Macro Template Reference

### ISSUE THREAD

**Issue by trev-dev** [Roll20/roll20-character-sheets#6670]
With the default template I can simply add {{Field=Value}} and it will appear in the template in chat. I'm trying to add additional notes to a macro for rolling damage, and I can't seem to get another inline field to appear.

Example:
```
@{selected|roll}&{template:skillRoll} {{type=Damage Roll}} {{characterName=@{selected|character_name}}} {{skillName=Neck Snap}} {{damageRoll=[[(@{selected|swing})*1.5]]}} {{damageType=Crushing}} {{someNote=This is a test where I may expand upon the nuances of neck snapping}}
```
`someNote` Does not appear. What I see is this:
![Screenshot_2020-06-01_10-06-54](https://user-images.githubusercontent.com/28788713/83434629-b1940300-a3ef-11ea-95be-35a418637fd3.png)

Is it possible to explain/expand on the template usage?

**Comment by MadCoder253** [comment]
Hi @trev-dev 
Here's a link to a document that explains the available fields for the skillRoll template. There are some new fields I need to add but it should be helpful.

https://1drv.ms/b/s!AnMvSmU-IUW2jJsp-Eip6ahs8bFMhQ?e=84RXmx

Here are a set of new fields for custom results.

**Text Box One**
noteBoxOneShow = 1 or empty. If 1, the note box will display in the chat area
noteBoxOneLabel = The label of the row. This should contain a value
noteBoxOneContent = The content you want to display

**Text Box Two**
noteBoxTwoShow = 1 or empty. If 1, the note box will display in the chat area
noteBoxTwoLabel = The label of the row. This should contain a value
noteBoxTwoContent = The content you want to display

**Text Box Three**
noteBoxThreeShow = 1 or empty. If 1, the note box will display in the chat area
noteBoxThreeLabel = The label of the row. This should contain a value
noteBoxThreeContent = The content you want to display

**Text Box Four**
noteBoxFourShow = 1 or empty. If 1, the note box will display in the chat area
noteBoxFourLabel = The label of the row. This should contain a value
noteBoxFourContent = The content you want to display

**Comment by trev-dev** [comment]
@MadCoder253 For whatever reason I didn't get notified of your reply, and saw it as my issue was closed. Thank you so much for the doc!

**Comment by MadCoder253** [comment]
You're welcome @trev-dev !
