### ISSUE TITLE
[RunequestGQS] Translations via Crowdin not committed

### ISSUE THREAD

**Issue by dyvim** [Roll20/roll20-character-sheets#6676]
Hello, 

I've proposed french translations of the RunequestGQS sheet via Crowdin 2 weeks ago (may 25th) but the two last commits didn'nt embark them.
Can you do something ? 

BRgds

**Comment by Lockbox313** [comment]
The sheet was rolled back and there are no translation attributes in the current version.
with the offending head and body tags removed.  
https://app.roll20.net/forum/post/8695053/runequest-character-sheet-issues

**Comment by dyvim** [comment]
Thanks for the explanation...
Any chance the tags will be back?

**Comment by Lockbox313** [comment]
No by me
