### ISSUE TITLE
Savage World Tabbed sheet missing + icon to add new skills

### ISSUE THREAD

**Issue by williambbertram** [Roll20/roll20-character-sheets#6698]
Hello, I love the Savage Worlds Tabbed sheet, but I cannot find the + icon to add new skills.  The wiki says there should be a + icon, but I don't see one on the player tab or the configuration tab.  I see where I can rename skills, but I need to add some setting-specific skills for Beasts and Barbarians which is not available under the configuration tab either.

The + skills button is missing where the skills wrench is active or not.  I've tried the Github sheet, as well as the one you can select on Roll20, and it's missing on both.

Am I missing something, or was this feature removed?  Here is the wiki I'm looking at:

https://wiki.roll20.net/Savage_Worlds_Tabbed

thank you in advance.

**Comment by finderski** [comment]
If you click the crossed Hammer/Wrench icon, you can select the Knowledge/Other skill. That will add the + icon at the bottom of the skill list so you can add a custom skill.

The other option would be to rename an existing skill you're not using that uses the same linked attribute.

I hope this helps.

**Comment by nmbradley** [comment]
Closing this issue as it seems to be resolved. If there are residual problems, please feel free to create a new issue.
