### ISSUE TITLE
Where is FATE by Roll20? 

### ISSUE THREAD

**Issue by dhicks** [Roll20/roll20-character-sheets#6711]
I'd like to edit the FATE by Roll20 character sheet, to address some limitations with the sheet as it stands.  (The sheet can't show more than 4 stress boxes; doesn't have a great space for keeping notes; that kind of thing.)  But it doesn't seem to appear in this repo.  None of the folders with "Fate" seem to match this sheet, and searching for "fatebyroll20" turns up 0 results. 

Here's the PNG preview of the sheet I'm talking about:  

![FATE by Roll20 PNG preview](https://app.roll20.net/sheet-previews/fatebyroll20.png?1591537567)

**Comment by clevett** [comment]
Roll20 produced sheets live in their own repository. This one is for the community sheets.

**Comment by pitxels** [comment]
Ok then how can we use this sheet as a starting point for a community one?

**Comment by Anduh** [comment]
Maybe switch to use the one created by Evil Hat? That one is in the repo, is actively updated, and might listen to your requests if the sheet already doesn't behave as you suggested.
