### ISSUE TITLE
Stars-without_number_revised encumbrance

### ISSUE THREAD

**Issue by G-G-G** [Roll20/roll20-character-sheets#6742]
The following line in the character.pug file
+text-input("gear_encumbrance")(type="number", value="0", step="1").center
sets encumbrance to a number field which doesnt allow decimals, as raised in this forum thread: https://app.roll20.net/forum/permalink/8804583/

I'd fix this myself, but I dont work with pug. So I'm pinging people who have edited this sheet @joesinghaus @Karlinator @svmnotn @jrvidal

**Comment by Karlinator** [comment]
That's quite a wide reaching ping you have there! For future reference, we prefer issues be raised over on [the fork where development happens](https://github.com/Karlinator/roll20-character-sheets). The link is in the bottom right of the sheet.

I've looked at it, full response in the forum thread. Arrows are useless at step 0.01, and the only "disallowment" is a validation message that I can overwrite with a title attribute. Unless someone objects that's what I'm going with.
