### ISSUE TITLE
Submitted "Magical Land of Yeld" Sheet isn't showing up in Roll20's sheet dropdown

### ISSUE THREAD

**Issue by Medieve** [Roll20/roll20-character-sheets#6768]
I submitted a sheet successfully in early May https://github.com/Roll20/roll20-character-sheets/pull/6340

It seems to have got pulled correctly but the sheet doesn't show up in the dropdown. I have a similar issue with a Mouseguard sheet and just wanted to see if this is a known issue with new sheets.

**Comment by clevett** [comment]
#6881 has been added as a PR to fix this.
