### ISSUE TITLE
[Scum and Villainy] Muscle resprowess_bonus comes from???

### ISSUE THREAD

**Issue by ShivonQ** [Roll20/roll20-character-sheets#6782]
The MUSCLE character in our game, when resisting is rolling what looks like twice as many dice as he should be.  We have managed to trace it to a attribute called resprowess_bonus but cannot figure out where that is coming from.  
I can see it in the HTML, its an input, but we cant find it in his sheet, or figure out why it would have started as 'activated'.  Doesn't seem correspond to any of his abilities as far as we can tell.  But we've only played about 20 sessions at this point?  
None of the other sheets seem to have this problem, just the Muscle playbook.  My mechanic for example is 3 Hack, 3 Rig, 2 study, but I still only roll 3 dice on that resistance roll.

**Comment by cbrenberg** [comment]
I'm playing a pilot in this same game, and like @ShivonQ I also have no 'resbonus' attributes visible on my attributes and abilities tab, but I do see the same hidden `attr_resbonus_*` inputs in the html of my character sheet (all have zero as the value), and I see the same `resbonus` referenced in the template strings that are presumably used to calculate the number of dice to roll when clicking on insight, prowess, or resolve. However, for unknown reasons our MUSCLE character DOES have resbonus values listed on his attributes and abilities tab with a 3 for resbonus_prowess and a 1 for resbonus_insight.

I scoured the S&V rulebook and couldn't find a situation in which a character would have permanent bonus dice for a particular attribute, so unless it's something that roll20 requires on character sheets, I don't see the purpose of any of the resbonus attributes.

**Comment by joesinghaus** [comment]
In the settings (little gear, top right), there are fields to add a permanent resistance bonus to characters. Set these to 0 to disable this. @ShivonQ Someone must have set these to some value at some point.

**Comment by nmbradley** [comment]
Closing this issue as it seems to be resolved. If there are outstanding problems, please consider creating a new issue.
