### ISSUE TITLE
[Demon Gate Scripted] character sheets not showing up in dropdown as an option

### ISSUE THREAD

**Issue by Deltayn** [Roll20/roll20-character-sheets#6894]
New sheets for Demon Gate (Demon Gate Scripted) have been approved and committed to the master branch but do not show up as an option in the dropdown for character sheets.

**Comment by Azgrymn** [comment]
@clevett   yep,  I believe this one has been overlooked. If we add it in can we place it under the correct Chaos System yet call it Demon Gate v02 or something. It it a totally different sheet than the other but they are all Chaos System

**Comment by Azgrymn** [comment]
This is for the Demon Gate rpg by Arcanum Syndicate

**Comment by clevett** [comment]
I've added this to the approve yaml. It should be live later today.
