### ISSUE TITLE
[GURPS] DR Calculator

### ISSUE THREAD

**Issue by trev-dev** [Roll20/roll20-character-sheets#6911]
This would be a feature request.

My friends and I were going over our layered armor and realized that our DR was starting to get a bit out of hand. We're having to write our DR down in our inventories, decided if we were wearing this or that piece of armor, then having to math out our DRs in various hit locations in the combat tab. It works, but it's clunky. This sheet is amazing with how it calculates most other things.

Is it possible it could do DR as well?

Ideas around how this could work from a UI perspective:

Inventory (or Combat?) tab has a new Armor table where we can add armor, row per row, and enter in the DR in one of two inline inputs. One would be for standard DR, the other for modified DR. This would help with armor that has split values for different damage types (such as flexible ballistic armor). Each row could also have an "on" checkbox, to determine if the character is wearing that piece of armor, or not.

Next, refactor the Hit Locations table to show a sum of each hit location's DR/Modified DR counts respectively. This would only require a simple arithmetic and a loop for on-change/input events in the armor rows, and would be pretty similar to the kinds of events/functions found in many other areas of the sheet.

**Comment by MadCoder253** [comment]
Hi @trev-dev 

Can you try creating this issue on my repo? I have a number of existing items there and have a few projects to track what I'm working on.

https://github.com/MadCoder253/roll20-character-sheets/issues

**Comment by trev-dev** [comment]
Created! https://github.com/MadCoder253/roll20-character-sheets/issues/193
