### ISSUE TITLE
[Apocalypse World 2nd Edition: Burned Over] Harm Calculates Incorrectly

### ISSUE THREAD

**Issue by rvhguy** [Roll20/roll20-character-sheets#6922]
Harm rolls are a 2d6 roll MINUS the Harm you've suffered, not PLUS the Harm you've suffered. The Harm move button on the sheet currently ADDS the Harm inputted instead of SUBTRACTING the Harm inputted. It just needs to be reversed.

**Comment by ughjonnjonzz** [comment]
well that would be an incredibly simple fix, except...

![Capture1](https://user-images.githubusercontent.com/67462479/87984398-2651f800-ca97-11ea-867d-a8cddccc6329.PNG)

now granted, I didn't read through the entire playbook, but that seems pretty cut and dry to me. PbtA games usually are.

**Comment by rvhguy** [comment]
You're reading Apocalypse World 2nd Edition, where you roll+harm as
described. In the Burned Over hackbook, you roll-harm.

THE HARM MOVE
When you suffer harm, roll minus the harm you’ve suffered. On a 10+, the MC
chooses 1:
• The harm you take stands as is, with no additional effect.
• You take -1harm, but the MC chooses 1 from the 7–9 list below.
On a 7–9, the MC chooses 1:
• You lose your footing.
• You lose your grip on whatever you’re holding.
• You lose track of someone or something you’re attending to.
• You miss noticing something important.
On a miss, the MC chooses 1:
• You’re out of action: unconscious, trapped, incoherent or panicked.
• It’s worse than it seemed. Take an additional 1-harm.
• Choose 2 from the 7–9 list above.
The MC can forget or otherwise choose to forgo the harm move, case by case.
The MC can call for the harm move whenever you suffer harm, even if your
armor reduces the
harm you’ve suffered to 0 or negative.

(Apocalypse World: Burned Over, p. 50.)

There are a few changes between Burned Over and vanilla 2E; this is one of
them.

**Comment by ughjonnjonzz** [comment]
I stand corrected. sorry, the only PbtA game I've played is Monsterhearts.
well, like I said, it should be a super easy fix. I'll submit a request in a sec ~~and hopefully not break anything~~
