### ISSUE TITLE
[Monster of the Week Official]

### ISSUE THREAD

**Issue by blalasaadri** [Roll20/roll20-character-sheets#6923]
On July 30th, ["Reinforcements"](https://www.drivethrurpg.com/product_info.php?products_id=130278) was updated and, to quote Generic Games: _"the Hard Case is almost completely changed"_.

It would be good, to have both the legacy Hard Case playbook (for people, who are currently playing it and don't want to switch) and the new Hard Case 2020 playbook available.

**Comment by Anduh** [comment]
think this is directed to your sheet @fredhicks

**Comment by fredhicks** [comment]
Hey there @blalasaadri, I'm aware of this and do have an intention to preserve the older Hard Case for folks already using it. (May be the case for other Reinforcements as well.) Will likely be a couple weeks before we can get the new Reinforcements worked in, regardless.

**Comment by blalasaadri** [comment]
@fredhicks Thanks for the change, looks good!
