### ISSUE TITLE
[Old School Essentials] Remove old (unofficial) Sheet

### ISSUE THREAD

**Issue by FrederickMuench** [Roll20/roll20-character-sheets#6974]
Hi,

I'm part of the [Necrotic Gnome](https://necroticgnome.com/) Team, publisher of the game 'Old-School Essentials'.
OSE has currently two sheets on Roll20. The newer and official version ('Old School Essentials - AAC') is an enhancement of the old sheet ('Old School Essentials'). 
We appriciate the authors  (@Sheershym (?)) work very much, because it laid the foundation for the new one. 
Unfortunately, we don't know how to contact the author of the 'old sheet', that's why we would like to request it's removal here.

Could you please **delete** the sheet 'Old School Essentials' and **keep** 'Old School Essentials - AAC'?

If you are in doubt, you can contact us [here](https://necroticgnome.com/pages/contact) for confirmation (via email, discord, facebook, ...).

**Comment by Anduh** [comment]
Roll20 will likely accommodate you by removing the sheet from the selection, but not strictly delete it from here.
That would break any existing games using it. In that way, any games using the old sheet would still function, but no more games can select the old sheet.

**Comment by FrederickMuench** [comment]
> Roll20 will likely accommodate you by removing the sheet from the selection, but not strictly delete it from here.
> That would break any existing games using it. In that way, any games using the old sheet would still function, but no more games can select the old sheet.

That sounds reasonable. Removing it from selection sounds good! Thank you.

**Comment by clevett** [comment]
Greetings,

I have deprecated the old sheet so new users will no longer be able to select it.
