### ISSUE TITLE
[Spire - The City Must Fall] Allow translations

### ISSUE THREAD

**Issue by WallaceMcGregor** [Roll20/roll20-character-sheets#7027]
Hi.

I don't know if @Medieve plans to update this sheet so that it can be translated. If not, is there any way to translate it? I'm not a programmer (I only know how to translate the sheets) and I don't have a Pro account, this is why I'm asking.

Thanks

**Comment by Medieve** [comment]
I didn't have current plans to put in translation tags but since you asked nicely I can set out some in the next few days.

**Comment by Medieve** [comment]
Submitted a translation file pull

#7028 https://github.com/Roll20/roll20-character-sheets/pull/7028

**Comment by WallaceMcGregor** [comment]
That's amazing! Thank you very much @Medieve

**Comment by Anduh** [comment]
@WallaceMcGregor if this have been implemented, you could close this issue.
