### ISSUE TITLE
[Chronicles of Darkness] Image not updating on Roll20 VTT

### ISSUE THREAD

**Issue by PrimalZed** [Roll20/roll20-character-sheets#7049]
An image was updated in the `master` branch over 3 weeks ago, but the image loaded in the Roll20 character sheet remains the old one.

[Old image](https://github.com/PrimalZed/roll20-character-sheets/blob/614e4d8abb8dfa1201e0b88a97b672b87214c4d6/Chronicles%20of%20Darkness/images/geist.png)

[New image](https://github.com/PrimalZed/roll20-character-sheets/blob/master/Chronicles%20of%20Darkness/images/geist.png)

Image displayed in Roll20 VTT:

![image](https://user-images.githubusercontent.com/4495480/88457370-61637b00-ce4b-11ea-8208-cd0c81c8cda1.png)

The complete url used for loading the image in the VTT is https://imgsrv.roll20.net/?src=https%3A//raw.githubusercontent.com/Roll20/roll20-character-sheets/master/Chronicles%2520of%2520Darkness/images/geist.png

The url as set in the source code can be seen here: https://github.com/Roll20/roll20-character-sheets/blob/master/Chronicles%20of%20Darkness/CofD.html#L206

**Comment by Anduh** [comment]
Did you try to rename the file and use the new name on the sheet to forcefully update it?

**Comment by PrimalZed** [comment]
I'd rather not go with a new filename if it can be avoided.

**Comment by PrimalZed** [comment]
If the point of the question is to see whether there's something wrong with the new file itself, the imgsrv.roll20.net request works just fine if sourced from my repository:
https://imgsrv.roll20.net/?src=https%3A//raw.githubusercontent.com/PrimalZed/roll20-character-sheets/master/Chronicles%2520of%2520Darkness/images/geist.png

(For some reason the request for the image from the Roll20 repository returns a 301 Moved Permanently status code, redirecting to https://s3.amazonaws.com/files.d20.io/images/145490373/NckRfmPHoDwVkDRCIcIhug/max.png while the request for the image from the PrimalZed repository just returns a simple 200 with the image.)

**Comment by PrimalZed** [comment]
Is renaming the image file the only way to overcome the cache for the VTT? Did I somehow stumble into a isolated issue, or is this a broader systemic issue for updating images used in character sheet templates?

@Reonin Since you previously helped out with a systemic issue (getting a new community sheet alternative to the orphaned "by Roll20" sheet), can I ask you to get eyes on this?

**Comment by Reonin** [comment]
So renaming a file is always a good way to bust a cache but before we go to those as viable solutions want to confirm the cache is not being saved on the browser/client side and a hard refresh doesn't resolve it. If that's still the case I'll bring it up tomorrow and see if anything changes in our caching of sheets.

**Comment by PrimalZed** [comment]
I've tried it with different browsers, and with incognito and "disable cache" checked. I'm pretty sure that eliminates the possibility of browser caching.

**Comment by Anduh** [comment]
Yeah, and when I looked at the sheet as well, it showed the old image.

Whatever is going on, it's so pervasive that it's happening for multiple people, and need a proper fix, either manually updating the image with new name, or to check whatever is going on with the roll20 image hosting cache.

**Comment by Reonin** [comment]
Hey @PrimalZed  and @Anduh I was able to reach out to the team this week regarding the image cache. For the here and now renaming the image is the only way to update the cache. There are some limitations on the way we host character sheet images that may be changing in the future. If I hear anymore on this I'll you all know!

**Comment by Anduh** [comment]
the issue should be closed, if this is now fixed

**Comment by PrimalZed** [comment]
I'll close out this issue since we found a workaround I can use, but the root problem that an image used in the character sheets is cached indefinitely is still outstanding.
