### ISSUE TITLE
[Shadowrun5] Sub tabs aren't clickeable anymore

### ISSUE THREAD

**Issue by Warien** [Roll20/roll20-character-sheets#7179]
It is impossible to click on most of the sub tabs. (arms => melee weapon, knowledge, language, magic => rituals, etc)
The issue exist on chrome and edge at least.
![2020-08-12_14h43_22](https://user-images.githubusercontent.com/17216030/90016420-3df15a80-dcaa-11ea-9d55-af9594bbc15c.png)

**Comment by Anduh** [comment]
@clevett this have also been reported on the forums: https://app.roll20.net/forum/post/9064207/shadowrun-5th-edition-macro-character-sheet-bug
