### ISSUE TITLE
[Shadowrun5thEdition] Rolling for Skills and Condition Monitors broken.

### ISSUE THREAD

**Issue by Peberro** [Roll20/roll20-character-sheets#7188]
These issues started recently (in the middle of our game!), possibly after the Hot Sim and Running Silent switches were implemented.
Upon rolling for a skill through the sheet the hit total in the chat is equal to the maximum value (it adds the skill ranks and the attribute being used together instead of rolling the required amount of d6s). This only affect skills, rolling for specific weapons or for attributes seems to be working fine.
![image](https://user-images.githubusercontent.com/28016241/90188578-04107900-ddbc-11ea-9e82-a2c98305890c.png)

Both Condition Monitors display radio buttons instead of filling up in gray.
![image](https://user-images.githubusercontent.com/28016241/90188612-11c5fe80-ddbc-11ea-9be3-b6965f4e0f16.png)

**Comment by clevett** [comment]
Thanks for making an issue. My apologies for the inconvenience.

**Comment by Mazalinus** [comment]
I'd like to add that initiative rolls are broken too. The same principle as skill rolls.
It just counts the number of dice needed to roll, but not rolling.

**Comment by clevett** [comment]
I'll take a look at all roll templates to double check any other issues.
