### ISSUE TITLE
[Warhammer 4e Character Sheet] - 'Melee (Fencing)' skill roll failing due to missing curly bracket

### ISSUE THREAD

**Issue by JacksonReid** [Roll20/roll20-character-sheets#7214]
When rolling the Melee (Fencing) skill from the Skills tab on the character sheet, it shows the following error and the roll fails.

![fencing](https://user-images.githubusercontent.com/55610202/90364516-2c48e380-e019-11ea-9568-ba1c2032ef94.JPG)

This is due to line 7467 of the sheet html file - it currently contains: 
`{{blinded=[[@{BlindedMod]]}}`
when it should be: 
`{{blinded=[[@{BlindedMod}]]}}`

Adding the curly bracket allows this roll to work.

![image](https://user-images.githubusercontent.com/55610202/90366316-0244f080-e01c-11ea-93f9-5a1393f77f4a.png)

https://github.com/Roll20/roll20-character-sheets/blob/master/Warhammer%204e%20Character%20Sheet/Warhammer%204e%20Character%20Sheet.html

**Comment by Djjus** [comment]
Thanks JacksonReid. I will fix this in next release.
