### ISSUE TITLE
[Pathfinder Second Edition by Roll20] Feature request: Process decimal fractions for bulk

### ISSUE THREAD

**Issue by rsimoes** [Roll20/roll20-character-sheets#7286]
Currently decimal fractions are floored to the nearest integer. It would be convenient if they were instead rounded down to the nearest multiple of L, such that, e.g., 0.5 would be equivalent to 5 * L. My personal use case is tracking items that come in bundles, such as arrows. 100 arrows must be represented as 10 due to existing as bundles 10. If they could instead have a bulk of 0.01, one could set the quantity to 100 and still get correct bulk reporting (1 bulk for 100 arrows, 9 * L for 99, etc.).

**Comment by NathaTerrien** [comment]
This has been adressed by adding the bulk property on inventory items.
