### ISSUE TITLE
Stars Without Number Revised - Str/Dex/Con are not editable

### ISSUE THREAD

**Issue by angramainyu74** [Roll20/roll20-character-sheets#7355]
While in edit mode, Str/Dex/Con are not editable. Int/Wis/Cha work as expected.

![image](https://user-images.githubusercontent.com/19170466/92650316-54470200-f2ba-11ea-9de9-63606dbd3ff8.png)

**Comment by Karlinator** [comment]
This is a known bug (fixed by #7354 once Roll20 gets around to merging that).

You can work around it by going into the settings and toggling+untoggling both "AI Character" and "Transhuman Characters".

**Comment by Karlinator** [comment]
Fix is now deployed! You can go ahead and close this, it should work now (forgot to close it from the PR).

**Comment by Karlinator** [comment]
@oliviakristiansen you can go ahead and close this if you want :)

Just so fixed issues aren't filling up the feed.

**Comment by angramainyu74** [comment]
Thanks!
