### ISSUE TITLE
[Electric Bastionland] English translation en.json altered

### ISSUE THREAD

**Issue by morgdalaine** [Roll20/roll20-character-sheets#7386]
It was brought to my attention that when the translations/ directory was created (by @wing-it) the en.json uses "Poor" as the translation for "arm_name", instead of "Arm". 

![image0](https://user-images.githubusercontent.com/1750637/93245854-8987a000-f751-11ea-8e05-ab547ad20aec.jpeg)

**Comment by Anduh** [comment]
I submitted a translation fix to [CrowdIn](https://crowdin.com), so this might be fixed after next week's Tuesday.

**Comment by Anduh** [comment]
Looking at the current English translation file, this should have now been fixed. If you check in a game and it looks good, you can close this issue.

**Comment by morgdalaine** [comment]
Looks great. Thank you for your help!
