### ISSUE TITLE
[GURPS] Feature request

### ISSUE THREAD

**Issue by aulospl** [Roll20/roll20-character-sheets#7412]
Hi, I'd like to request a feature for the GURPS character sheet. I would like to have an option to use the _Perception and Will are separate from IQ_ from the MyGURPS website (http://mygurps.com/pmwiki.php?n=Main.GURPSHouseRules), as I think it's a very used house rule (at least the folks at the SJ forums seems to like it) and I always use it myself.

**Comment by MadCoder253** [comment]
Hi @aulospl, I do a lot of updates for the GURPS sheet. I have a repo with issues. Can you try  adding this request to my issues page? 

https://github.com/MadCoder253/roll20-character-sheets/issues

Thanks,
Ken

**Comment by nmbradley** [comment]
Closing this as it has been relocated to an external tracker.
