### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by ArtySemenov** [Roll20/roll20-character-sheets#7453]
Weapons as Ability or Attributes so they can be used in Macros. Basically this:

As a player I want to have Hit/Damage buttons on my screen for quick access so I don't need to open my character sheet each time and navigate to the Gear section so my rolls take 10 seconds instead of a full minutes.

AC1: When I add a weapon it is automatically translated into Ability

AC2: When I call %Weapon_1_Hit in a macro it is the same as clicking "Hit" on the character sheet

**Comment by Anduh** [comment]
Is this a general feature request, or aimed towards a specific sheet?

Many sheet have the option to drag-n-drop sheet buttons to the Quick Macro Bar. And the buttons you can drag to the macro bar, you can indeed call through  `%{charactername|commandname}`

Example: https://wiki.roll20.net/Macro_quickbar#Character_Sheets

**Comment by ArtySemenov** [comment]
Huh okay, I didn't realise that was a thing. I was messing around in macros and couldn't find a way to quickly call and existing command. I'll investigate. Thanks!
