### ISSUE TITLE
[GURPS] Translation Files Bug

### ISSUE THREAD

**Issue by MadCoder253** [Roll20/roll20-character-sheets#7459]
There's a bug that's adding special characters to all the translation files.

**GURPS/translation.json**

Line #606
`"modifier-label": "Modifier:",`

When the system updates all the files under the translation folder, extra characters are added that are causing a display issue on the character sheet and the chat roll results. 

**Example**

GURPS/translations/en.json

Line #606 
`"modifier-label": "Modifier:$[[3]] ",`

The characters **$[[3]]** were added to each of the translation files.

Pull Request
#7445

**Comment by Anduh** [comment]
Odd, so #7445 remove them, but Git Blame shows that it got added when the weekly translations script where applied to all Roll20 sheets by @oliviakristiansen in this [commit](https://github.com/Roll20/roll20-character-sheets/commit/b6fe539e83e9c442741a66fee24de95090655832). I assume this process involves pulling Translations from CrowdIn, and propagating translation changes on `translation.json` file to the language-specific files.

Digging a bit deeper, seems it was originally added in [this July 28th commit](https://github.com/Roll20/roll20-character-sheets/commit/7eb2c18680ddd67044ffea4b905f4ddcbcaf88df#) by Olivia with the general sheet translation updates. The other thing changed on the GURPS translation in the commit was "Rad"->"Rads", so I think the **$[[3]]** could originate from someone updating the "Rads" word and mistakenly adding the **$[[3]]** as well.

I'd assume this is part of the reason translation change are recommended to be submitted through CrowdIn, after the translation keys are created.

#Suspected Cause
Regarding why it keeps getting re-added, I think it's a bug in Roll20's translation update script, as I've seen this back and forth happen previously with other sheets.

What I remember thinking the last time similar reverts happened, that it seemed to happen when you made changes to both the translations files(`translation.json` & all the version in `/translations`) & the sheet code in the same week, the "translation update" by Roll20 would partially overwrite changes to translations based on the "old" version, presumably coming from CrowdIn. I never confirmed anything, but fairly certain this general issue have been around for at least 2 years, but have been so small and infrequent that nothing have really been done about it.

If I end up digging up past occurrences and get more insight on this, I'll submit a support ticket to Roll20 so they have a proper case to look at and maybe get it fixed.

**Comment by Anduh** [comment]
Through [CrowdIn](https://crowdin.com), I submitted a translation changed for English to change `Modifier:$[[3]] ` to `Modifier:`, which hopefully overrides whatever is making this thing return each week.

If that works out, I'll try to submit the changes to the rest of the languages  so it gets competently removed.

If you want to get access to the CrowdIn Translation tools for the future, send a request email to cassie@roll20.net

**Comment by MadCoder253** [comment]
Thank you @Anduh !

**Comment by Anduh** [comment]
It seems my CrowdIn change to the translations removed the pesky `$[[3]]` on [line 606](https://github.com/Roll20/roll20-character-sheets/blob/210aee7e73c807f6aabdbff2c6bb1a106acda8dc/GURPS/translations/en.json#L606).

If you can verify in a game that it's fixed, you could close this issue.

**Comment by MadCoder253** [comment]
@Anduh  thank you! It's fixed.
