### ISSUE TITLE
[Feast of Legends] cannot add more than 1 Load

### ISSUE THREAD

**Issue by hulm22** [Roll20/roll20-character-sheets#7494]
The Load box only has space for 1 weapon or item.  The bottom part is just freeform text and cannot be used for rolling attacks and such.

**Comment by Anduh** [comment]
Guess I could add a second weapon/item spot to the sheet. Never ended up playing it so haven't basicly touched the sheet since I created it.

Any other minor quality-of-life improvements for it? I might update the Roll Templates so the rolls looks a bit better.

**Comment by hulm22** [comment]
Ill let you know. Planning on running a game for my bday in 2 weeks on
roll20 for laughs.

**Comment by nmbradley** [comment]
@Anduh did you ever resolve this request?

**Comment by Anduh** [comment]
Yeah I did add a second weapon/attack slot to the sheet, forgot to update this issue, so this can be closed.
