### ISSUE TITLE
[Dark Heresy 1st Edition] Range Categories are Incorrect

### ISSUE THREAD

**Issue by RobbaYaga** [Roll20/roll20-character-sheets#7503]
As requested, I am resubmitting this.

Dark Heresy 1st Edition has the following Range Categories.

Point Blank (PB) - usually 3m or less
Short (S) - less than half the weapon's listed range (<R/2)
Medium (M) - Anything from half the weapon's listed range up to twice the weapon's listed range (R/2-R*2)
Long (L) - greater than twice the weapon's listed range (>R*2)
Extreme (E) - greater than three times the weapon's listed range. (>R*3)

This screen shot shows the incorrect categories on the ranged weapon "Not My Father's Bolt Pistol."

![image](https://user-images.githubusercontent.com/70450366/95397672-cd457380-08d1-11eb-82d1-84c30c474771.png)

**Comment by Stexinator** [comment]
Point Blank (PB): 3m
Short (S): <R/2
Medium (M): <R*2
Long (L): >R*2
Extreme (E): >R*3

would be possible. There is not enough space to provide the range.

**Comment by RobbaYaga** [comment]
That looks great other than Medium Range. If there is enough room, I would suggest .5-2 or some variation of that (0.5-2x or .5-2x or whatever). If none of that fits, I would suggest leaving Medium as simply R.

**Comment by Stexinator** [comment]
@mperes something seems off with the rollout of the updates. Can you please verify when the changes will be rolled out? Thanks

**Comment by Stexinator** [comment]
@RobbaYaga please close it when it is fixed

**Comment by Tealk** [comment]
Now it is mega confusing!
The fields contain the maximum values according to the rulebook.

**Comment by Stexinator** [comment]
@Tealk besides the medium range I disagree. But I also dont understand the problem with typing in text. So, I dont object to reverting it. Clarifing the issue in such a small place so that all parties are happy is probably impossible. 

@RobbaYaga you can state your problem with it any maybe we can come to some sort of agreement (e.g. tooltip is more explaining)

**Comment by RobbaYaga** [comment]
I have no problem with the current change, however, if other people are having trouble with it, then just leave them blank and let people look up the ranges in the core book. My original post in this thread explains what the Ranges are according to the core rules and the "maximum values" change in each field depending on the weapon. (A weapon with a range of 30m is going to have vastly different maximums than a weapon with a range of 120m). Simply having the correct range abbreviations works for me. (They are correct now.)

**Comment by Tealk** [comment]
Well, in my rulebook it is a little different than what you wrote in your first post:
Point Blank (PB) up to 3m
Short (S) to range/2
Medium (M) to range *2
Long (L) - to range*3
Extreme (E) - to range*4

of course the minimum always refers to the value before; so the previous version was correct and the current one is faulty, because you can't shoot further than the extreme range according to the rules

**Comment by RobbaYaga** [comment]
What you have here is fine and is identical (if worded differently) to what I put in the post at the top of this thread. Regardless, the most succinct description of ranges comes from the Errata.

"Short range is below half of this number, long range is above double, extreme range is above three times and maximum is above four times. Below 3 metres is point blank range."

**Comment by Tealk** [comment]
> Extreme (E) - greater than three times the weapon's listed range. (>R*3)

But as far as I know, this would mean that the weapon can shoot infinitely far

**Comment by RobbaYaga** [comment]
Sure, that could be inferred from what is listed there. However the things you have listed are too many characters to fit into the available space as it has been described to me "(Extreme (E) - to range*4)." Perhaps yet another box that adds maximum range should be there, but probably not.

Honestly, Tealk, there never were ranges on the ranged weapons on the character sheet originally. So I honestly don't care what goes into the little boxes, since I can simply put the correct range in there anyway. I mostly wanted the range categories to be correct and they are now.

If this is really a problem, my best and final suggestion is to simply remove the range categories again and put the range descriptions on the character sheet in a static text box that reflects the errata wording and let the players / GM calculate them as needed.

We're all spending way too much time on this and I'm just thankful people are willing to work on the sheet at all this many years after the game went out of print. So thank you to you and Sexinator and do whatever seems best.

**Comment by Tealk** [comment]
> I mostly wanted the range categories to be correct and they are now.

no, as I have shown above it is not, because the statement placeholder="> R*3" is wrong as well as placeholder="0.5-2*R"

**Comment by RobbaYaga** [comment]
I feel like there is a real communication problem here.

The categories are correct: PB / S / M / L / E (as opposed to what was there before PB / N / M / F / E).

The details within each category that describes how to calculate each range are also, technically, correct. Extreme Range is, in fact, greater than the Range multiplied by 3 (>R3), just as Medium Range is from one half the Range to two times the Range (0.5-2R). The fact that there is a maximum Range is irrelevant.

HOWEVER, I don't care!!!

I offered my suggestion. Add a block of static text to the character sheet describing the Range categories and let the players / GM work them out. Leave the spaces within each category blank.

If that's not good enough for you, then change those spaces to say whatever you want. Just leave the categories as they are now.

**Comment by Tealk** [comment]
> just as Medium Range is from one half the Range to two times the Range (0.5-2R).

ok that was very ambiguous, it would be better to write 0.5R - 2R. I have assumed a mathematical calculation all the time

> The fact that there is a maximum Range is irrelevant.

Why is that irrelevant? If you want to keep on shooting you ignore the rule?
House rules have no place in the bows in my opinion.

**Comment by Tealk** [comment]
I will insert the following description text that will be displayed when you move the mouse over the fields
> The input fields always show the maximum value for the distance category, the minimum value is always the previous category+1

then everything should be clear

**Comment by RobbaYaga** [comment]
While Short Range is technically incorrect (it's actually less than R/2), I'm fine with these changes as long as the category titles remain correct (PB / S / M / L / E).

**Comment by Tealk** [comment]
> I'm fine with these changes as long as the category titles remain correct (PB / S / M / L / E).

This is regulated by the translation, not by the programming.
You have to contact the Roll20 support and get an account.

**Comment by RobbaYaga** [comment]
I have an account on Roll20 you inconsiderate wretch. I'm sorry that your German translation is not what you want it to be, but on the English character sheet, the Range Categories should read PB/S/M/L/E. Change them back. That was the whole point of this ticket.

**Comment by RobbaYaga** [comment]
@Stexinator What options do I have for reporting this nonsense? Is this a Github issue or a Roll20 issue? I've been as accommodating as I can possibly be and this person just refuses to do anything except what they want and what they want is simply wrong based on the rules of the game.

**Comment by Tealk** [comment]
Any translations you find in the folders below are not changed by GitHub, but by some other tool I don't know myself (I asked for an account once, but never got one)
https://github.com/Roll20/roll20-character-sheets/tree/master/Dark_Heresy/translations

What you say is wrong, because as you can see in the change, there is F and not L too; so this has nothing to do with my changes I mentioned.
https://github.com/Roll20/roll20-character-sheets/commit/d12cb5c5d40ba6bc40c45155c4a3b4680307a275

**Comment by Stexinator** [comment]
@Tealk there is no translation initalization yet for this sheet. One of the points of my change was, to give the english names for the ranges. Instead of reverting my changes you should make a commit which changes the placeholder according to the outcome of your discussion.

It is common to use the english language until that happens. If you want to have a certain language then feel free to start the translation of the sheet.

**Comment by Stexinator** [comment]
@Tealk @RobbaYaga by the way this PR is closed. @Tealk open a new issue which is linked to this one and post a summary into it. Then add your changes to the new issue

**Comment by Tealk** [comment]
> @Tealk there is no translation initalization yet for this sheet. One of the points of my change was, to give the english names for the ranges. Instead of reverting my changes you should make a commit which changes the placeholder according to the outcome of your discussion.
> 
> It is common to use the english language until that happens. If you want to have a certain language then feel free to start the translation of the sheet.

If these are not translations, what are they?
https://github.com/Roll20/roll20-character-sheets/tree/master/Dark_Heresy/translations

**Comment by Stexinator** [comment]
Right, I looked at 2nd edition. @RobbaYaga in this case I have to agree with @Tealk . Please try to get a Crowdin-Account (https://github.com/Roll20/roll20-character-sheets#internationalization--translations) and submit a fix for the english language there

**Comment by RobbaYaga** [comment]
Very well, I apologize to @Tealk for my harsh words. Given the sheet was completely in English when I came upon it, I (arrogantly) assumed it started out that way.

Thanks for being the intermediary, @Stexinator and I will join and ask for a fix.

Despite the mild battle of text we had, I really do appreciate all the efforts from both of you.

**Comment by Tealk** [comment]
Diverse opinions have the potential to improve things.
