### ISSUE TITLE
[Warhammer 4e Character Sheet] New Translation.json not updated properly on roll20 - Need advice

### ISSUE THREAD

**Issue by Djjus** [Roll20/roll20-character-sheets#7509]
Hi Devs, this week my latest PR #7483 was merged. All files have merged up fine as i see in GitHub, but the new translation file was not updated on roll20 live servers giving the sheet some translation errors and i also can't see the updated version on Crowdin. I'm not sure how this happened, the current html/css/json files work fine on a test server/sandbox.  

Could it have anything to do with the fact that GitHub merger was completed on Tuesday, not Monday as usual.. this is a first time that has been the case from me that I'm aware. Maybe this caused it to miss a step this week.

I'm thinking just to try again next Monday, but want to avoid any problem i might be missing? Please advise.

**Comment by Djjus** [comment]
Fixed with new PR this week. I checked the logs on crowding and is does seem like the translation where done Monday night and the Tuesday PR's did not get fully processed. So i'm assume this caused the issue.

**Comment by Anduh** [comment]
The translation process and interaction between changes coming from the repo, vs changes pulled from CrowdIn does seem to have some issues.
Sometimes CrowdIn translations revert changes submitted through the repo, sometime only part of the translations goes through, and probably seen some rare issue that was something else. Those have all been pretty ambiguous in how/when they are caused, and seems nobody have properly investigated if there is something that could be improved in the process, or if its one or more concrete bugs to be ironed out.

**Comment by Djjus** [comment]
Hi Anduh, thanks for you feedback. I think in this case it was a simple sequence of events problem. I am aware of other translation issues as you mention, but lucky I have not experienced these myself. Only been translation a shortly while now to be fair.
