### ISSUE TITLE
SyntaxError: Unexpected token '<' - when activating "Degree Weapons"

### ISSUE THREAD

**Issue by aldaron838** [Roll20/roll20-character-sheets#7525]
When copying in DH_Degrees_Weapons.js in the Script Library the following error is given and script is stopped.

In the settings it's shown I need 3 scripts to get started:

DH_Degrees_Weapons.js 
DH_Degrees_Skills.js
Ammo.js

However, when adding all three I only get a syntax error (see screenshot below). 

![Unexpected Token](https://user-images.githubusercontent.com/33810839/95752958-27af4d00-0ca1-11eb-8b8e-e9d207f9caf0.PNG)

**Comment by Stexinator** [comment]
Please update the title with the sheet name. If it is possible for you try to find out the maintainer (usually written when you choose the sheet) and ping them
