### ISSUE TITLE
[RuneQuestGQS] NPCs Character Sheet has oddly small type for textboxes

### ISSUE THREAD

**Issue by loskylp** [Roll20/roll20-character-sheets#7538]
The Character description, Runes, Spells, Passions and Skill texboxes have a different letter type and size compared to the rest of the Sheet

**Comment by nmbradley** [comment]
@Lockbox313 you appear to be the most recent maintainer of this sheet, would you be able to look at this issue?

**Comment by Lockbox313** [comment]
The fonts on those fields on NPC sheet are that size to prevent the need for scrolling or resizing the textareas,
