### ISSUE TITLE
Add Old School Essentials additional classes?

### ISSUE THREAD

**Issue by chirstius** [Roll20/roll20-character-sheets#7540]
Is there any possibility of adding in support for the extra classes listed in Old School Essentials books such as Assassin, Mystic/Monk, Bard, Druid, etc.?

I'm happy to give the work a try and I can fork but curious if any current authors are interested in doing it, or collaborating on it?

**Comment by Stexinator** [comment]
Which sheet + system are you talking about?

**Comment by Stexinator** [comment]
@chirstius please close this, it seems to be of no interest
