### ISSUE TITLE
[Pathfinder Second Edition by Roll20] Feature request: a way to describe actions with outcome depended on roll result

### ISSUE THREAD

**Issue by LethalGhost** [Roll20/roll20-character-sheets#7544]
Please add a way to describe actions with outcomes like "Critical Success, Success, Failure, Critical Failure" that do not require a savethrow DC.

**Comment by LethalGhost** [comment]
An example how that's look right now.
Please add a way to hide/omit "saveing throw dc" line.
![unknown](https://user-images.githubusercontent.com/2458675/96354231-bed73300-10ed-11eb-8ba9-57ef1cfe239a.png)

**Comment by NathaTerrien** [comment]
Spells now show the success/failure values without the need of a Saving Throw.
Actions don't have inner Saving Throw so you can add these information in the description, using ** to bold.
![image](https://user-images.githubusercontent.com/8142678/116468854-b10b2300-a871-11eb-8c27-e1ddaab3fb68.png)
