### ISSUE TITLE
[Pathfinder 2nd Edition by Roll20] Request: Colored Headers

### ISSUE THREAD

**Issue by Keldin** [Roll20/roll20-character-sheets#7561]
When I asked for where to make this suggestion, I got two answers, with people unsure of which to use, so I'm doing both.  Apologies for people who see it twice.

I would like to request the ability to change the color of the header on the character sheet.  The current situation is difficult to use if you decide to link the name of the spell/trait/weapon/effect that you're using.  Here:

![screenshot-app roll20 net-2020 10 20-14_43_49](https://user-images.githubusercontent.com/3933229/96637100-d7a93980-12e3-11eb-8df7-3044678b00f2.png)

This is the Sanctuary spell, with a link to its location on AoN.  You can see it, but it's quite difficult.  When I cast this spell during one of our sessions, one of the other players outright said the title was blank.  So, if there was a way to select whatever header color you wanted to use -- there are some that work with standard text and some that don't -- like the dropdown between the standard color and color neutral on the options tab, it'd be very helpful?

Thanks in advance!

**Comment by NathaTerrien** [comment]
A bug ticket has been opened to show link in the name as "normal" white header text.
Thanks for the report.
