### ISSUE TITLE
Custom Sheet Sandbox - JavaScript console shows many [violation] handlers which causes slowness

### ISSUE THREAD

**Issue by MadCoder253** [Roll20/roll20-character-sheets#7574]
For the past week I've been encountering a lot these errors that results in slow load times when I try to upload a html, css, or translation file. It also affects the speed of the webpage and character sheets. I also encounter jerky movements when trying to drag a character sheet around on the map.

Here's a screenshot.

![custom-sheet-errors](https://user-images.githubusercontent.com/9192404/97093326-c2901b80-15ff-11eb-9c9e-91ed3e3a15f9.png)

**Comment by Anduh** [comment]
I suggest you submit a [Help Center Reques](https://roll20.zendesk.com/hc/en-us/requests/new)t on this issue.

Roll20 doesn't really pay much attention to github issues as they are meant to target the community sheets themselves, not issues with the Roll20 platform.

**Comment by MadCoder253** [comment]
Thanks
