### ISSUE TITLE
D&D_3-5 Character Sheet weapon damage

### ISSUE THREAD

**Issue by Bruweiz** [Roll20/roll20-character-sheets#7612]
Hi.
There is currently no sensible way to add weapon damage to a weapon on the character sheet. 
Functionally, this can be done by editing the hardcoded 1d6 damage in the macros used for damage and crit damage rolls. This seems to be bad practice, as users inexperienced with "Code Stuff" are often unwilling to to make changes to the attack macros.

![Capture](https://user-images.githubusercontent.com/18149185/97801148-fcce6e00-1c3a-11eb-8ae4-3d4f7d08840d.PNG)

A possible solution would be to add two new textfields for die amount and die size respectively, and letting the macro get the needed information for an attack out of those fields.

**Comment by adamkost** [comment]
or a single text field could be used, to house "2d6" for example. I would also recommend an additional field to be added at the end to add additional damage of a different type, such as +1d6 fire damage for a flaming weapon. You may need to have a 2nd row for additional details due to limited real estate, much like the official character sheets produced by [WotC](https://dd5echaractersheet.co/wp-content/uploads/2018/11/DD-3.5-Character-Sheet-PDF-Files.jpg)

**Comment by nmbradley** [comment]
@42shadow42 you were the last sheet author to update this sheet; would you be willing to explore solving this issue?

**Comment by nmbradley** [comment]
Thanks for the update. I'll tag this appropriately, then.

**Comment by Bruweiz** [comment]
Hey, i didn't expect to see a reply to this Issue at this point. 

If wanted, i can add the textfield with a '1d6' as default and edit the macro. In fact, i've done that on a local version.
I'm not aware what the practice is for new people to contribute on a sheet, so unless there's an issue with that, i'll commit my changes to a branch later this week.

**Comment by nmbradley** [comment]
We tend to give a little preference to the original sheet author, but everyone should feel free to contribute. Please feel free to make a PR with changes!

**Comment by Bruweiz** [comment]
Hey everyone.
I'm about done with the changes to the character sheet, and have been looking up ways to actually test the sheet on the roll20 wiki. I can't find either the custom sheet option for games on roll20, nor does the link to the sheetsandbox lead me anywhere. Are those options discontinued?
Is there a way for me to load my character sheet and view it with the correct formatting/css?

**Comment by hoyer555** [comment]
Hi, I added two field for weapon damage, please look this test version:
https://app.roll20.net/join/10242897/UAl6gg
If you like it, I can release officially.

**Comment by hoyer555** [comment]
With this release I added two fields for damage and variable damage.
For new PC the damage macro reads the new fields, but for old ones probably you have already change the old macro so you should change the macro manually
