### ISSUE TITLE
[GURPS] Several translations are not working

### ISSUE THREAD

**Issue by MadCoder253** [Roll20/roll20-character-sheets#7654]
I haven't looked at the sheet for a couple of weeks due to work. I just noticed that translations that used to work are no longer working. I did merge in all the latest updates and the translations are working for both the main development file `translation.json` and the other `/translations/en.json.` on my sandbox.

Here's a screenshot of the issue I'm seeing.

![broken-translations](https://user-images.githubusercontent.com/9192404/98504186-2e32d500-220b-11eb-8997-c586ff2ed6fe.png)

**Comment by Anduh** [comment]
There was some [ups and downs with that yesterday, but it should be solved now](https://app.roll20.net/forum/post/9382237/translation-and-crowdin-changes). Have you checked if the translations work today?

**Comment by MadCoder253** [comment]
Hi @Anduh that looks good! thank you!
