### ISSUE TITLE
Pathfinder 2e: @{Level} in cantrip expressions gives character level, not cantrip level

### ISSUE THREAD

**Issue by hyphz** [Roll20/roll20-character-sheets#7693]
@{Level} in the damage block for a cantrip will roll based on the character's level, not the spell's level. For example, a level 5 character rolling @{Level}d4 with a cantrip will roll 5d4, when they should roll 3d4 (because Level 3 spells are the highest available to a level 5 character)

**Comment by Stexinator** [comment]
Please update the title with the exact sheet name

**Comment by NathaTerrien** [comment]
User @{spelllevel} or @{current_level}
