### ISSUE TITLE
Nephilim Legende: Alchemy Difficulty calculation incorrect in "Oeuvre au blanc"

### ISSUE THREAD

**Issue by Antelbxl** [Roll20/roll20-character-sheets#7721]
@fennelin 
Le calcul des transmutations ("Difficulté") de l'Oeuvre au Blanc est incorrect:
actuel: les 2 Ka-éléments sont additionnés
réel: seul le plus petit des 2 Ka est pris en compte. (encart des règles page 220)

**Comment by fennelin** [comment]
Le calcul a été corrigé. Le comportement est maintenant le suivant :

oeuvre au noir somme des deux (pour tenir compte des deux positions)
oeuvre au blanc : seul le plus petit Ka des deux est pris en compte

**Comment by Stexinator** [comment]
@Antelbxl if this is resolved, please close it
