### ISSUE TITLE
I am touching Mutants and Masterminds 3E

### ISSUE THREAD

**Issue by Medieve** [Roll20/roll20-character-sheets#7725]
Just announcing I'm going to be putting my thumbprint on the sheet, mostly styling but I'll be working on the powers section too to make it more svelte and collapsible. I'll be updating my progress on the [forums](https://app.roll20.net/forum/post/9504317/mutants-and-masterminds-3e-sheet-restyling):

Let me know if there's any conflicts or just overall disagreements with what I'm doing here: @Anduh @clevett @Wosser1sProductions

**Comment by Anduh** [comment]
I've only made some bug fixes by request, haven't used the sheet, and welcome any updates to it. All the more likely I might play it one day.
