### ISSUE TITLE
[Old Dragon Aprimorado] Clérigo com Sab 17 fica com 1d4 mortos para afastar ao invés de 1d6

### ISSUE THREAD

**Issue by killerasus** [Roll20/roll20-character-sheets#7727]
@johcker Estava passando a Eledriel para o Roll20 e percebi pelo Livro Básico Aprimorado ela deveria afastar 1d6 Mortos Vivos, mas o cálculo apresenta apenas 1d4.

**Comment by johcker** [comment]
@killerasus o cálculo da quantidade afastada se baseia no Carisma e não na sabedoria, com carisma 14 ela só afasta 1d4 mesmo.

**Comment by killerasus** [comment]
Caramba, li errado então, cancelando o issue
