### ISSUE TITLE
DE Translation is wrong

### ISSUE THREAD

**Issue by Gabbalo** [Roll20/roll20-character-sheets#7745]
According to the official translation of the corebook by Ulisses Spiele there are several other wordings used. 
I whould update those by myself, but it is much faster to open this issue that to install git and get it running as a non-gitter -.-

Line 8: Aufgeregt -> Aufgebracht
Line 15: Kraftakt -> Kraft
Line 19: Berechnen -> Rechnen
Line 21: Einschmeicheln -> Einfühlen
Line 23: Ermitteln -> Untersuchen
Line 28: Rolle -> Archetyp
Line 30: Glück -> Glückspunkte
Line 31: Antrieb -> Motivation
Line 36: Bezugsperson -> Anker
Line 38: SC -> Kind
Line 43: Versteck -> Geheimversteck

Source: Charactersheet from the official german corebook
![charactersheet](https://user-images.githubusercontent.com/5897819/99855414-1eaa7900-2b87-11eb-973c-b05d3cd01f1e.jpg)

Here is the fixed translationfile for someone to submit.
[de.json.txt](https://github.com/Roll20/roll20-character-sheets/files/5576366/de.json.txt)

**Comment by Stexinator** [comment]
Translations are done via Crowdin. I suggest you create an account and submit the fix

**Comment by Gabbalo** [comment]
I can only access unfinished translations over there (or I have no clue how to access the finished charactersheets). How can I modify a finished translation?
<img width="907" alt="2020-11-21 18_45_02-Translating Roll20 Official Character Sheets to German language" src="https://user-images.githubusercontent.com/5897819/99883750-be204800-2c29-11eb-80fc-805d0ab8da0b.png">

**Comment by Anduh** [comment]
It seems that sheet's translations is in the regular sheet project, here: https://crowdin.com/translate/roll20-character-sheets/9978/en-de?filter=basic&value=0

**Comment by Gabbalo** [comment]
Ok, I think I managed to update the options. I guess, now I have to wait if the translation manager or whoever accept the wording or denies it (which whould be sad because it's the official wording ;) ) 
Thank you for your help in doing this 👍

**Comment by Stexinator** [comment]
@Gabbalo please close this issue when you got a solution

**Comment by Gabbalo** [comment]
Translation is now working. Thank you 👍
