### ISSUE TITLE
[The Burning Wheel] Open-ended tickbox no longer visible unless hovered over.

### ISSUE THREAD

**Issue by aureyia** [Roll20/roll20-character-sheets#7755]
The open-ended tickbox on The Burning Wheel Sheet are now no longer visible unless you hover over the element: 
![image](https://user-images.githubusercontent.com/19798820/99907504-fe88d000-2cd4-11eb-8c9b-fa1089164d35.png)
![image](https://user-images.githubusercontent.com/19798820/99907560-49a2e300-2cd5-11eb-8212-d44f5f654f5e.png)

Most players will now not know that it exists and will assume it is taken into account by the sheet.

Proposed Solution: Show the outlined symbol, currently only visible on hover, all the time.

**Comment by Seraaron** [comment]
This was intended for a cleaner look. The star symbol is explained in the documentation (see the README link button next to the sheet version number) and on the roll20 mainpage when you select the sheet while setting up a new game. I also think it's fairly implicit from being able to see stats that start open-ended by default, a curious player can find out it's there naturally.

But if enough people want this changed back or altered to your suggestion then I'll do it. (Note that I did try your suggestion while developing the sheet, but it looked very bad in my opinion; having a largely unused star / checkbox next to every ability in the game no matter how faint, was distracting).

**Comment by Seraaron** [comment]
Actually, since I'm submitting a pull request this week anyway for other updates I might as well add it back in and see what the response is. It won't break anything afterall :)
