### ISSUE TITLE
Tales from the Loop Sheet at zero or negative dices

### ISSUE THREAD

**Issue by Gabbalo** [Roll20/roll20-character-sheets#7777]
Hi everyone,

if you have multiple conditions you might run into zero or even negative dice count. Based on the corerulebook, that can only happen in one situation: If you are broken (where you have zero dices and everything fails by default). Otherwise you always have at least one dice to roll. So if you click on the action and you are mathematically on less than one dice it should roll one dice. 
I don't know if that is scriptable on that action, but last session it was kinda annoying to always have to reroll those rolls :(

Greetz
Gabbalo

**Comment by Stexinator** [comment]
@Gabbalo this is doable. Please tag the sheet author so he sees your request

**Comment by Gabbalo** [comment]
That might be @nmbradley as far as I can see from the history of that sheet.

**Comment by nmbradley** [comment]
Apologies, must have missed this when it was first posted. I'll see what can be done to resolve this.
