### ISSUE TITLE
freeseamlesstextures.com is down, breaking FantasyCraft sheet

### ISSUE THREAD

**Issue by bitspersecond** [Roll20/roll20-character-sheets#780]
One of the sites I use for a background image is down and has been.  I've been getting mail asking me to fix it, so I changed the background image to something (and somewhere) else.

Can someone push this change sooner rather than later?  The sheet is pretty unusable like this...

**Comment by clevett** [comment]
Hello,

I am going through the old issues and ensuring they have been resolved. I will assume this pull request went out in 2015. If it is still an issue please let me know.

Thanks,
Cassie
