### ISSUE TITLE
[The Burning Wheel] Cannot switch tabs on character sheet

### ISSUE THREAD

**Issue by rotoclone** [Roll20/roll20-character-sheets#7819]
As of today (November 30th), the buttons on the top of the character sheet to switch tabs are no longer switching tabs. They were working fine the last time my group played on November 25th. We are all seeing this issue in Chrome, Firefox, Edge, and Safari.

If I manually change the `value` attribute of the `input` tag with class `sheet-tabstoggle`, the shown tab does change. And changes made to the sheet seem to still be synced across the network.

We can work around the issue for now by manually changing the `value` attribute, but it makes it very hard to play.

**Comment by rotoclone** [comment]
Found an issue for this in Seraaron's fork: https://github.com/Seraaron/roll20-character-sheets/issues/3

**Comment by Anduh** [comment]
Roll20 Character Sheet Backend Changes where rolled out yesterday, are likely the cause of this issue. Seem [my comment](https://app.roll20.net/forum/permalink/9556767/) in the main thread for an full explanation.

The issue is identified, and a fix will be out later today, is what I was just told.

**Comment by rotoclone** [comment]
I'm not seeing this issue anymore as of today
