### ISSUE TITLE
[GURPS] Script and autocalc fields are broken Urgent

### ISSUE THREAD

**Issue by MadCoder253** [Roll20/roll20-character-sheets#7826]
Several users reported in the GURPS thread that the sheet is now broken. The last set of updates were two weeks ago, I do have a pending pull request but it hasn't been merged yet.

Here's a link to the first reported incident.

https://app.roll20.net/forum/permalink/9554202/

Thank you,
Ken

**Comment by Anduh** [comment]
Roll20 Character Sheet Backend Changes where rolled out yesterday, are likely the cause of this issue. Seem [my comment](https://app.roll20.net/forum/permalink/9556767/) in the main thread for an full explanation.

The issue is identified, and a fix will be out later today, is what I was just told.

**Comment by MadCoder253** [comment]
Thanks @Anduh !
