### ISSUE TITLE
MGT Traveller 2e can't change tabs

### ISSUE THREAD

**Issue by JCDJ101** [Roll20/roll20-character-sheets#7835]
Hi,

I've been designin a MGT2 traveller game during 1 week and everything was working perfectly. But today I wanted to create a character and I just realized I cannot switch tabs inside the character sheet. Its just "locked" and cant change from for example " Prime " to "Skill" tab... 

If you know what it can cause this please I await your response.
Ty.

**Comment by Anduh** [comment]
this should be fixed now. Please close the issue if it was resolved.
