### ISSUE TITLE
[ChroniquesOublieesContemporain] - Modificateurs d'Attaque restent actifs après suppression 

### ISSUE THREAD

**Issue by Vyzzini** [Roll20/roll20-character-sheets#7836]
Bonjour,

J'ai le bug suivant sur la fiche ChroniquesOublieesContemporain:
- Je n'ai aucun modificateur d'attaque.
- J'ajoute un modificateur d'attaque "Ajuster" avec un bonus de +2.
- Je fais un jet d'attaque, le bonus de +2 est bien pris en compte.
- Je supprime le modificateur d'attaque "Ajuster".
- Je fais un jet d'attaque, le bonus de +2 pour "Ajuste" est toujours pris en compte même si il n'apparait plus sur la fiche.

Le même problème existe pour les Modificateurs de Dommage.

**Comment by nmbradley** [comment]
@stephaned68 it looks as though you are maintaining ChroniquesOublieesContemporain. Do you know if these are still issues?

**Comment by stephaned68** [comment]
@nmbradley I never got the original notification from Github thus was not aware about the problem, abd therefore did not look into it ;)
@Vyzzini Poster en français sur le Github de Roll20 n'est pas la meilleure manière d'avoir une réponse à ton bug, la preuve je viens juste d'être mis au courant. Dommage, j'ai posté à de maintes occasions sur le forum BBe pour indiquer que les retours de bug pouvaient se faire sur le forum ou sur mon Github perso où j'ai une copie de la fiche COC. Je regarde ça dès que possible

**Comment by stephaned68** [comment]
@Vyzzini Je viens de jeter un bref coup d'oeil au problème et effectivement, quand on part d'une liste de modificateurs d'atk ou de dm vide, ça n'actualise pas correctement les jets d'attaque. Le bug est corrigé et la correction sera disponible dans la prochaine version de la fiche COC (3.9.0). Pour tes prochains rapports de bug, si tu veux une réponse plus rapide : https://github.com/stephaned68/ChroniquesContemporaines/issues

**Comment by stephaned68** [comment]
@nmbradley Issue resolved by PR #8608. Please close.

**Comment by nmbradley** [comment]
Thank you for attending to this!

**Comment by stephaned68** [comment]
@nmbradley Hey, shouldn't the merge of the PR mentioned above have closed this issue ? Can you close it please ?

**Comment by nmbradley** [comment]
I would have assumed so, but I wonder if there's something odd in the repo configuration. I'll look into it. Thanks for the update!
