### ISSUE TITLE
[Anima Beyond Fantasy] Add popup when opening newly created sheet to explain some uses

### ISSUE THREAD

**Issue by simchanu29** [Roll20/roll20-character-sheets#7851]
Hi, 

I wanted to use this sheet for my Anima campaign but I wasn't able to find where to specify level and class. After some question to the discord server of the french community I finally found where. 

I think there may be some ergonomy issue since I struggled to find the area to specify the level. The top bar where the level and xp are showed are misleading since it led me to believe that the level was computed with xp.

**So I propose an improvement :** 
Why not showing when opening the sheet for the first time a popup with some version, author, description information an dsome tips to use the sheet, such as the fact that the level is handled in the settings of the sheet. The "when opening for the first time" part could be handled with a show_popup variable set to false when the user clock on a button "do not show again" on the popup instead of "ok".

**Comment by Anduh** [comment]
A more practical and community collaborative approach would be to create a page for the sheet on the Roll20 Community Wiki, were everyone could share tips & tricks, and no coding for the sheet would be needed.

If you follow this link and save some info, a page will be created: https://wiki.roll20.net/index.php?title=Anima_Beyond_Fantasy&action=edit&redlink=1
It would then be accessible at the address: https://wiki.roll20.net/Anima_Beyond_Fantasy
The link could then be added to the sheet's instruction page, and the sheet.

**Comment by Stexinator** [comment]
@simchanu29 when this is solved, please close it

**Comment by simchanu29** [comment]
I added a tip inside the wiki page of the sheet.
https://wiki.roll20.net/Anima_Beyond_Fantasy
