### ISSUE TITLE
[Shadowrun 5th Edition] Attributes skills names are now in french and can't be properly linked

### ISSUE THREAD

**Issue by Akefal** [Roll20/roll20-character-sheets#7863]
Hi,

I don't know why as I don't see a recent sheet's release but skills are no longer properly linked because their Attributes name is now in french.

For example, score of @{primary_melee_weapon_skill} is no longer added to the dice pool.
When I check Attributes & Abilities, I can see that Attributes are translate in french.

So when @{primary_melee_weapon_skill} try to catch @{unarmedcombat} it can't do it because it's now named @{combatàmainsnues}.

Is there a solution to correct this automaticaly ? I have more than 50 PJs and PNJs in my campaign, I can't imagine correct manualy all Attributes names on every single sheets...

**Comment by Akefal** [comment]
Ok, Roll20 has deployed crowdin for translations. I presume that the issue is linked.

**Comment by Noctifer1011** [comment]
Yeah, I'm not seeing this in my Shadowrun character sheets, but I'm using English, as are my players, so I suspect you're right about the Crowdin translator mucking with things it shouldn't.

**Comment by Akefal** [comment]
These issue is not relating with github translations files.
