### ISSUE TITLE
[DSA 5 - Tsa Bogen] collapsible talent kategories

### ISSUE THREAD

**Issue by Stexinator** [Roll20/roll20-character-sheets#7898]
Für die Übersichtlichkeit wäre es gut, wenn die verschiedenen Talentgruppierungen nicht untereinander sind. Ich sehe hierfür zwei Möglichkeiten: die Gruppen zuklappbar machen, oder Sub-Reiter machen

@Trestolt arbeitest du noch aktiv an dem Sheet?

**Comment by Trestolt** [comment]
Hi @Stexinator, ich habe gerade zuwenig Zeit für zuviel Projekte, daher sammle ich jetzt erst einmal weiteres Feedback, bevor ich einen neuen Sprint starte. Zu deiner Idee: Ich hatte schon eine längere Diskussion mit meinen Beta-Testern, wie das Layout der Talente aussehen könnte, da wurde die Gruppierung in Sub-Reiter  eher abgelehnt. Aber die zuklappbaren Gruppen werde ich mir nochmal anschauen. Danke

**Comment by Stexinator** [comment]
@Trestolt ich kann mich da auch gerne selber dran setzen. Ich wollte dir nur nich ins Handwerk pfuschen :)

**Comment by Stexinator** [comment]
@Trestolt ich habe es selber implementiert und es ist live. Daher mache ich das zu
