### ISSUE TITLE
[Nephilim Legende] 

### ISSUE THREAD

**Issue by Yamings** [Roll20/roll20-character-sheets#7930]
Bonjour @Zakarik. 
Suite au changement de fiche sur Nephilim Légende, voici quelques retours suite à une partie.

**Côté bugs :** 
- [ ] Lorsqu'on lance un sort, que l’on fait une confrontation de Kabbale ou qu’on fasse une alchimie, le titre du lancer n'est pas centré, contrairement aux autres jets de dés.
- [ ] Dans l'alchimie, lorsqu'on modifie les valeurs des œuvres (au-dessus de la voie initiatique), les difficultés des formules ne sont pas actualisées.
- [ ] Dans l'alchimie, concernant les formules de l’œuvre au blanc, il ne faut prendre en compte que le Ka le plus faible des deux, et non pas la somme des deux Ka de la formule.
- [ ] Dans l’onglet Combat, il manque l’option « Personnalisé » dans la liste des époques d’incarnation.
- [ ] Le degré de métamorphe actif n’est pas pris en compte pour les sorts et la Kabbale.
Pour ce dernier point, cela est dû à la première condition : `if(ka_element = "kaair")`  qu’il faudrait modifier simplement avec un `==`. L'erreur est présente à deux endroits dans le script.

**Côté améliorations possibles :** 
- Il serait pratique d’ajouter, dans l’onglet Combat, une section pour tenir compte des objets d’alchimie synthétisés que l’on a sur soi.
- Dans la section Simulacre, il serait pratique d’ajouter une section répétable pour noter l’équipement acheté au fur et à mesure des parties sans encombrer la section « ressources et possessions notables »
- Dans la section Alchimie, on pourrait remettre la possibilité de sélectionner les différents constructs utilisables pour le joueur, étant donné que le nombre est limité par la voie initiatique. Idéalement, il ne faudrait afficher que ces constructs dans l’onglet associé.
- Dans les onglets de Magie, d’Alchimie et de Kabbale, il serait intéressant de mettre le score de Difficulté visible même lorsque les objets sont repliés. Vu qu’il s’agit du seuil de réussite du lancer de dé, c’est une information qu’il est important d’avoir sous les yeux rapidement sans avoir à déplier les sort ou invocations. 

**D'un point de vue plus visuel :** 
- Pour les sorts, formules d’alchimies et invocations de Kabbale, il serait plus agréable à la lecture, lorsque tous les objets sont dépliés, d’avoir une meilleure délimitation visuelle entre les différents objets. Actuellement, les différents objets sont peu séparés les uns des autres, rendant la lecture complexes lorsque tout est déplié.
- Dans l’onglet Magie, il serait bien d’élargir un peu les colonnes de durée et portée pour que cela soit lisible sur des écrans plus petits. Cela est d’ailleurs fait pour l’alchimie.

**Concernant les éléments en doublons :** 
- Pourquoi avoir fait en doublons les époques d’incarnation dans l’onglet Combat ? En plus d’avoir des différences avec l’onglet incarnation (select non identique), cela alourdit grandement la lecture et rend l’accès aux armes et équipement fastidieux à atteindre. 
- De même pour l’encadré du degré de métamorphe actif, visible sur une grande partie des onglets. L’information est redondante d’un onglet à l’autre et peut alourdir l’affichage.

Merci de votre retour.

**Comment by Zakarik** [comment]
J'ai envoyé une mise à jour de la fiche :

>     * [ ]  Lorsqu'on lance un sort, que l’on fait une confrontation de Kabbale ou qu’on fasse une alchimie, le titre du lancer n'est pas centré, contrairement aux autres jets de dés.
C'est corrigé.

>     * [ ]  Dans l'alchimie, lorsqu'on modifie les valeurs des œuvres (au-dessus de la voie initiatique), les difficultés des formules ne sont pas actualisées.
C'est corrigé.

>     * [ ]  Dans l'alchimie, concernant les formules de l’œuvre au blanc, il ne faut prendre en compte que le Ka le plus faible des deux, et non pas la somme des deux Ka de la formule.
Je vais me renseigner auprès de l'éditeur (car c'est une commande) pour être certains, et je verrai, au besoin, pour corriger ça.

>     * [ ]  Dans l’onglet Combat, il manque l’option « Personnalisé » dans la liste des époques d’incarnation.
C'est corrigé.

>     * [ ]  Le degré de métamorphe actif n’est pas pris en compte pour les sorts et la Kabbale.
>       Pour ce dernier point, cela est dû à la première condition : `if(ka_element = "kaair")`  qu’il faudrait modifier simplement avec un `==`. L'erreur est présente à deux endroits dans le script.
C'est corrigé.

>     * Il serait pratique d’ajouter, dans l’onglet Combat, une section pour tenir compte des objets d’alchimie synthétisés que l’on a sur soi.
C'est ajouté.

>     * Dans la section Simulacre, il serait pratique d’ajouter une section répétable pour noter l’équipement acheté au fur et à mesure des parties sans encombrer la section « ressources et possessions notables »
C'est ajouté.

>     * Dans la section Alchimie, on pourrait remettre la possibilité de sélectionner les différents constructs utilisables pour le joueur, étant donné que le nombre est limité par la voie initiatique. Idéalement, il ne faudrait afficher que ces constructs dans l’onglet associé.
C'est ajouté.

>     * Dans les onglets de Magie, d’Alchimie et de Kabbale, il serait intéressant de mettre le score de Difficulté visible même lorsque les objets sont repliés. Vu qu’il s’agit du seuil de réussite du lancer de dé, c’est une information qu’il est important d’avoir sous les yeux rapidement sans avoir à déplier les sort ou invocations.
C'est compliqué, car je manque beaucoup de place, donc je ne vois pas où y mettre de manière "simple".

>     * Pour les sorts, formules d’alchimies et invocations de Kabbale, il serait plus agréable à la lecture, lorsque tous les objets sont dépliés, d’avoir une meilleure délimitation visuelle entre les différents objets. Actuellement, les différents objets sont peu séparés les uns des autres, rendant la lecture complexes lorsque tout est déplié.
J'ai ajouté des séparations claire (une double bordure) entre chaque, ça devrait être mieux.

>     * Dans l’onglet Magie, il serait bien d’élargir un peu les colonnes de durée et portée pour que cela soit lisible sur des écrans plus petits. Cela est d’ailleurs fait pour l’alchimie.
J'ai augmenté la taille, de manière similaire à celles de l'Alchimie.

>     * Pourquoi avoir fait en doublons les époques d’incarnation dans l’onglet Combat ? En plus d’avoir des différences avec l’onglet incarnation (select non identique), cela alourdit grandement la lecture et rend l’accès aux armes et équipement fastidieux à atteindre.
>
>     * De même pour l’encadré du degré de métamorphe actif, visible sur une grande partie des onglets. L’information est redondante d’un onglet à l’autre et peut alourdir l’affichage.
Parce qu'il s'agissait d'une demande de l'éditeur pour éviter d'avoir à switch trop souvent entre les onglets.
