### ISSUE TITLE
[Shadowrun5th] Will Missing from Advanced Shadowrun Drain-Attribute Dropdown

### ISSUE THREAD

**Issue by jstreeky** [Roll20/roll20-character-sheets#7954]
[
![willmissing](https://user-images.githubusercontent.com/2574951/102724034-74835580-42da-11eb-9927-c994f24f7dea.png)
](url)

Will is missing as a Drain-Attribute, Gypsy get Will + Will, which is cheese, but should be possible in the character sheet

**Comment by Stexinator** [comment]
@jstreeky I think this can be closed.
