### ISSUE TITLE
[Vaesen-dodgepong] Translation files and small improvements request

### ISSUE THREAD

**Issue by mdanielak** [Roll20/roll20-character-sheets#7964]
Hello @dodgepong 

Your card is pretty good, however would you mind having a look and improving it a bit? I have two requests, I hope those are small. At least the first one should be.

1. What do you think about adding in brackets information to which attribute given skill is connected? Like Agility [PH].

2. Translation files would make everything more fun. At least playable character sheets. Switching languages mid game always disrupts immersion.

Thank you and regards,
Maciek

**Comment by dodgepong** [comment]
Sadly my Vaesen game ended several months ago and I don't particularly have much interest in maintaining this anymore. Feel free to fork it and submit updates to the official repo!

**Comment by mdanielak** [comment]
I would love to do it, sadly I don't have a pro account.

**Comment by dodgepong** [comment]
I let my pro account expire after the free trial they gave out for Free RPG day.
