### ISSUE TITLE
[Vaesen] Translation files and small improvements

### ISSUE THREAD

**Issue by mdanielak** [Roll20/roll20-character-sheets#7965]
Hello @starshipsandsteel 

I would love to use your card to play Vaesen, It has everything it needs, however it misses two functionalities. One is crucial for me.

1. I really miss NPC/Vaesen character sheets. Writing down on notepad characteristics and health points doesn't look like fun to me. Is it possible for you to add such character sheet type?

2. Translation files would make everything more fun. At least playable character sheets. Switching languages mid game always disrupts immersion.

Thank you and regards,
Maciek

**Comment by starshipsandsteel** [comment]
Hi @mdanielak 

1.  I am not sure what you mean here, the sheet in roll20 has tabs at the top of the character sheet that allow a roll20 "Character" to be a PC, NPC, or Vaesen for tracking and rolls.  If you mean something else I think I will require clarification.

![image](https://user-images.githubusercontent.com/68384161/102899080-a229e500-4427-11eb-86b7-d9f88f57ae8d.png)

2. As in you are playing the game in non-english, and although they are playable, you find mentally switching back and forth to not be ideal?  It is something I could look into, but it is not something I have any experience with.  I will add it to my list of things to do with this sheet.

Thank you for the feedback, it is appreciated!

**Comment by mdanielak** [comment]
Thank you for a fast reply @starshipsandsteel ! First of all, my bad. There are two versions of Vaesen character sheets on roll20 and I have mistaken yours with the other one, sorry! Yours is the one that we (me and my friends) agreed to use during our campaign. 

1. It is not related to your character sheet.
2. Yes, this is exactly what I meant. Sorry for not being clear.
3. Would it be possible to add next to the skill an information in brackets to which attribute specific skill is connected? Just first two letters of an attribute. For instance `Agility **[PH]**`, and so on. Thanks to it players would understand more how skills are connected with attributes and it would be easier for them to select next skills while leveling up.
Smaller issues/improvements:
4. Fields on the left column have description below closer than fields on the right column. Is it intended to be aligned that way or is that a bug? 
![image](https://user-images.githubusercontent.com/6941778/102900566-c4922180-446c-11eb-80b4-36f4294d4b16.png)
5. Clicking use on equpment adds dices to Dice mod field. Players have to remember to clear the Dice mod field after using equipment (or at any other situations when they are adding or substracting dices). Is it possible to to clear the bonus dice after using skill? Or another proposition, maybe a good solution would be to implement a popup window when using a skill which says "Bonus dice?" and input number instead of Dice mod field at the bottom right corner? I saw this approach in Tales from the loop character sheet and in the other Vaesen sheet.

Anyway, whole project looks awesome. I love the graphics and look and feel.

**Comment by starshipsandsteel** [comment]
1) Ahhh! Ok, no problem!
2) No worries, something I can look into, but don't hold your breath on it being a quick thing.
3) Yes.  That can be added, I use a similar layout for a Conan sheet and ended up doing the same thing.
4) This is a result of "Labels" on objects displaying differently against a input field and a text area field.  It is certainly not optimal, and something that can be fixed, this sheet could use a little sprucing up in general.
5) Unfortunately short of the API there is no way to have making the roll trigger a clearing of the button.  As for the pop-up, certainly something like that is possible.  This is a personal preference, and generally I prefer to not use them unless it is something that needs to be added everytime and is often forgotten.  My personal preference is to have a modifier as I have implemented so you can just click "Add" to the equipment and have it jump in there.  Might be able to implement both though.  I will give it some thought and see what I can come up with.

This was my first character sheet and although I don't play Vaesen a lot, as I find it to be.....taxing... to put together a mystery, the few times I have played it have been awesome.

Glad you are getting some use out of the sheet!

**Comment by starshipsandsteel** [comment]
Just pushed some updates.  General sprucing up as well as adding ph,pr,lo,em suffixes to the skills.  I haven't looked at the styling on the NPC/Vaesen/HQ sheets but I will work on them as time permits.  You should see the changes next week maybe, not sure how Roll20 is doing merges over Xmas.

Cheers!

![image](https://user-images.githubusercontent.com/68384161/102922683-a962ea00-444b-11eb-8446-350bc317e8a5.png)

**Comment by mdanielak** [comment]
Thank you for a fast reaction! The new style looks awesome! I'm looking forward to translation files (but no pressure). Happy Xmas!

**Comment by starshipsandsteel** [comment]
Oh wow.  They rolled it in already!  Should be there for you to take a look at.  Wasn't expecting that!

**Comment by Stexinator** [comment]
@mdanielak if this is done please close it

**Comment by nmbradley** [comment]
This appears to be resolved, so I am going to close the issue. If there are any oustanding problems, please consider creating a new issue.
