### ISSUE TITLE
[Star Wars FFG Alternate] Wrong "Stun" qualities for weapons

### ISSUE THREAD

**Issue by erikjordan** [Roll20/roll20-character-sheets#7985]
@timothyyuen-ty 

Thank you so much for your sheet! Of all the ones out there I like it the best.

The character sheet seems to have several problems with it related to "Stun" qualities for weapons. Here is what I see:

![image](https://user-images.githubusercontent.com/1298330/103160591-d8a38f00-479c-11eb-9f45-09ecb61d09de.png)

This Stun quality, based on the description, should be called "Stun Damage" per the rules, and based on the tooltip information on the sheet. From F&D:

![image](https://user-images.githubusercontent.com/1298330/103160609-12749580-479d-11eb-999c-58ff90b995e7.png)

Moreover, the sheet is missing the actual "Stun" quality. Again, here is the F&D description:

![image](https://user-images.githubusercontent.com/1298330/103160614-2c15dd00-479d-11eb-8282-51c928dd27a4.png)

It's an active quality and is ranked.

**Comment by timothyyuen-ty** [comment]
Hi there!  Thank you.

You're right.  I had made the current Stun toggle for the first entry "Stun Damage" - basically just noting whether or not the weapon has a stun setting.  I can add another ranked Stun entry under the weapon qualities.  I can probably add this sometime in  next week, depending on my work schedule.

Tim :-)

**Comment by timothyyuen-ty** [comment]
Hi Erik,

I've added the Stun quality to the sheet and have submitted a PR to Roll20.  If you'd like to pick it up earlier, grab it from my repo.  Thank you and have fun!

https://github.com/timothyyuen-ty/roll20-character-sheets/tree/master/Star%20Wars%20FFG%20Alternate


Tim 🙂


________________________________

**Comment by nmbradley** [comment]
This appears to have been resolved, so going to close this issue. If there are any remaining problems to resolve, please consider creating another issue.
