### ISSUE TITLE
[Nephilim Legende] Rollback de fonctionnalités

### ISSUE THREAD

**Issue by Yamings** [Roll20/roll20-character-sheets#8018]
Bonjour @Zakarik 

La dernière pull request effectué sur la fiche de roll20 a engendré un rollback des dernières fonctionnalités implémentées, en plus d'avoir cassé le lien des différentes images de la fiche, la rendant difficilement utilisable.

Un petit exemple de ce que cela donne pour le pentacle de l'onglet Nephilim : 
![image](https://user-images.githubusercontent.com/76000028/103620998-ccee6000-4f34-11eb-858d-47b88e5ee096.png)

De même; il y a a nouveau le bug de calcul au niveau du degré de métamorphe actif.
Il est difficile d'utiliser la fiche dans ces conditions.

**Comment by Zakarik** [comment]
Désolé pour ça ! 
Je ne sais pas ce qu'il s'est passé exactement, j'ai du m'embrouiller, mais c'est corrigé à présent.
