### ISSUE TITLE
Discipline needs added to weapons in Star Wars FFG API-Compatible

### ISSUE THREAD

**Issue by raymondh3** [Roll20/roll20-character-sheets#8020]
so i was looking at the weapons list and we have  these
`   <option value="skill(@{rankBrawl}|@{brawn})" data-i18n="brawl">Brawl</option>
                                                    <option value="skill(@{rankGunnery}|@{agility})" data-i18n="gunnery">Gunnery</option>
                                                    <option value="skill(@{rankMelee}|@{brawn})" data-i18n="melee">Melee</option>
                                                    <option value="skill(@{rankLight}|@{agility})" data-i18n="rangedlight">Ranged - Light</option>
                                                    <option value="skill(@{rankHeavy}|@{agility})" data-i18n="rangedheavy">Ranged - Heavy</option>
                                                    <option value="skill(@{rankLightsaber}|@{charLightsaber})" data-i18n="lightsaber">Lightsaber</option>
                                                </optgroup>
                                                <optgroup label="General Skills">
                                                    <option value="skill(@{rankMechanics}|@{intellect})" data-i18n="mechanics">Mechanics</option>
                                                    <option value="skill(@{rankMedicine}|@{intellect})" data-i18n="medecine">Medicine</option>
                                                    <option value="skill(@{rankResilience}|@{brawn})" data-i18n="resilience">Resilience</option>`

but when i tried to add this
`                                                    <option value="skill(@{rankDiscipline}|@{willpower})" data-i18n="discipline">Discipline</option>
`
at line 1732 not sure if there is more places i needed to edit

it failed and spat out [this](https://imgur.com/xyk4Uoc)

so yeah if someone can add it everyone using unleash / force lighting would be grateful ^^

**Comment by raymondh3** [comment]
update i must have messed up at first when i did it since i went back and tried again and it worked in my test so ill likely do an update to the sheet if no one else does

**Comment by Stexinator** [comment]
@raymondh3 can this be closed?

**Comment by nmbradley** [comment]
Closing as it seems this was resolved by #8026. If there are residual problems, please feel free to create a new issue.
