### ISSUE TITLE
[Shadowrun 5] Import broken

### ISSUE THREAD

**Issue by Stexinator** [Roll20/roll20-character-sheets#8046]
Recently the import functionality broke down. On  first glance I could not find a reason.

@clevett are you still maintaining this sheet? Or should I dig more into it?

**Comment by Anduh** [comment]
- Is it broken for any files you try importing?
- have either the sheet or Chummer recently been update? could be the cause
- when was the last time the importer worked?

**Comment by Stexinator** [comment]
The button does not open the import interface.
The sheet was updated but not the part of the import.
Somewhen last year around october november was the last time I imported something

**Comment by clevett** [comment]
I've dropped all support for Roll20 Character Sheets. You can find the source code here, https://github.com/clevett/Roll20-character-sheet-Shadowrun-5th-Edition

**Comment by clevett** [comment]
This should now be resolved.
