### ISSUE TITLE
[Conan: Adventures in an Age Undreamed Of] Talent display suggestions

### ISSUE THREAD

**Issue by Pusikas** [Roll20/roll20-character-sheets#8054]
Hello and thanks for this nice character sheet!

Here are some suggestions for improvement of the display of talents:
1. There is a "Skill" dropdown. Not all talents are based on skills, though. An example would be the "Berserker" talent from Conan the Barbarian, or the Fortune talent line from the core book. It would be really nice if you would make it possible to just leave this field empty. Or at least add an option like "none" or "other".
2. The "Skill" dropdown is not sorted in any way. This is kind of annoying. Makes it harder to find stuff. Maybe sort it alphabetically?
3. There is a dice-button. I first thought that this would roll the corresponding skill for you, but instead it displays talent in chat and tells others that you are gonna use it. I like that! But the icon seems just wrong. Maybe replace it with a speech bubble or whatever. It's just that the die suggests that you are going to roll something, which is probably not the case.
4. I like that you do not have to scroll through the effect text like on the original Conan sheet. But if you copy in a longer effect text, this field becomes awfully large. It would be really cool if you could style this more like items and spells on the DnD 5e or Pathfinder sheets. Where only the name is displayed, but you can post it to chat or read and modify it anytime.
5. "Rank" is displayed in chat even when empty. Would be nice to not display it for talents without rank.
6. There is a "Base" dropdown. Which is not sorted alphabetically, but that's probably intended. I get what the first few options until "Other" are meant for. But what are the attribute names after that for? Also, it would probably nice to have an entry for talents that were bought with XP.

**Comment by nmbradley** [comment]
@Riccarr bringing this to your attention as the original sheet author. Don't feel compelled to solve this, but I thought it best to nudge you in the first instance.

**Comment by nmbradley** [comment]
Great update, thanks! I'm sure @Pusikas will be delighted to hear it!

**Comment by Riccarr** [comment]
New version 1.3 now pending MERGE request to Roll20.  See above comments for changes.
