### ISSUE TITLE
Cannot choose "Teens in Space" template

### ISSUE THREAD

**Issue by Gabbalo** [Roll20/roll20-character-sheets#8083]
Even while listed in the Github repo, you cannot choose Teens in Space as system for a Roll20 game. 
I remember I could maybe 3-4 weeks ago, but now, my game is system-less and I cannot choose that system anymore.

<img width="579" alt="no_TIS" src="https://user-images.githubusercontent.com/5897819/104507887-b35db000-55e7-11eb-9c25-db5867823306.png">

<img width="727" alt="yes_TIS" src="https://user-images.githubusercontent.com/5897819/104508007-e30cb800-55e7-11eb-848a-8004eee2d6aa.png">

Anyone knows, why?

**Comment by Anduh** [comment]
just search the dropdown for the sheet, and it appears

![teens](https://user-images.githubusercontent.com/2890634/104818776-6588b800-5832-11eb-955b-6591ed051780.png)

**Comment by Gabbalo** [comment]
Yes, I figured out, I cannot choose the game from the frontpage of the game (where you set the description and stuff), but I can choose the game in the configuration page to setup the character sheets. 
So, the issue is not present and therefor closed.
