### ISSUE TITLE
[Generation] character sheet files have CRLF instead of LF

### ISSUE THREAD

**Issue by MadCoder253** [Roll20/roll20-character-sheets#8092]
Hi, 

I just did a `git merge upstream/master` and the files for Generation use CRLF. This is causing me issues since git is showing that I modified the files because I follow the rule of `pull line endings as is` but `commit using LF`. Can someone fix these files?

Thanks.

**Comment by Anduh** [comment]
Seems the line endings are fixed two days ago, so this issue should be resolved: https://github.com/Roll20/roll20-character-sheets/tree/master/Generation

**Comment by MadCoder253** [comment]
Thanks @Anduh
