### ISSUE TITLE
RuneQuest Glorantha Character sheet

### ISSUE THREAD

**Issue by Anhkwearer** [Roll20/roll20-character-sheets#8113]
The graphic for the dice rolls on the full sheet are all Luck runes. No matter what type of roll it is. While on the Quick sheet, they are dice symbols for normal rolls, x? for multiplied characteristic rolls, and -p% symbols for modified rolls. 

Please change the art on the graphics. While the Luck rune is thematic for the setting (if you have the old books), it isn't present in the new version of the game and is not as informative as a symbol of dice. Doubly so when you have two different types of rolls next to each other, both with the same symbol.

I ask because I am highlighting Roll20 and this sheet in a video for Chaosium on Jan 30th and would sure love to pitch using this sheet to new players without misleading symbols I have to explain to people in the video.

**Comment by Anduh** [comment]
@ragamer and @Lockbox313 are the last two to have updated the sheet, does either of you have any insight or interest looking into this?

**Comment by Lockbox313** [comment]
This is a very entitled request. Also the Luck rune is in the new version of the game on page 15 of the Runequest Roleplaying in Glorantha rulebook .  It is also on page 193 of the Glorantha Sourcebook and page 149 of the Guide to Glorantha Volume 1.  Both core books for this version.

**Comment by Anhkwearer** [comment]
I agree. This is an entitled request. I am asking as the Director of
Organized Play from Chaosium Inc., so it might not be unearned entitlement.
And yes, the rune is present in the setting. But not on character sheets,
nor as something that has rules in the game.

**Comment by Lockbox313** [comment]
If you had lead with your title  the request would have had a been better response.  It strange that this is the first time that  anyone from Chaosium has even  acknowledged the existence of custom sheets for their products on Roll20 and then labels one of them as "misleading".  
Anyway I have already added tool tips to the double buttons and a header over the buttons for characteristic rolls.  What would you suggest as an alternative graphic ?

**Comment by Lockbox313** [comment]
![sample](https://user-images.githubusercontent.com/8994813/105398945-dce78e80-5c1a-11eb-831c-e38d21956a86.jpg)

**Comment by Anhkwearer** [comment]
First time on GitHub. So thank you for your guidance.

We have tons of CoC stuff, but yes. We are increasing our support for
RuneQuest and love it that people like you are working in that area.

The preferred graphic is the one that is on the quick start sheet seen on
Roll20 by toggling the character sheet view in the top left option box.

**Comment by Lockbox313** [comment]
![sample3](https://user-images.githubusercontent.com/8994813/105410313-a49b7c80-5c29-11eb-9dfc-e6789b67b92a.jpg)

**Comment by Anhkwearer** [comment]
Very close. The right die of every pair might instead have the "-?" symbol
to indicate it is modified.

But thank you so much for this fix!

**Comment by Lockbox313** [comment]
That's not a quick fix.   It will take a few days before I can get around to that.

**Comment by Anhkwearer** [comment]
Sure, that makes sense. Again, my deadline is Jan 29th. Is that a workable
date for you?

Also, contact me directly at todd@chaosium.com so I can include an
incentive when you are done.

**Comment by Lockbox313** [comment]
Should be

**Comment by Lockbox313** [comment]
This has been done so this issue cab be closed
