### ISSUE TITLE
[Ars Magica 5] Sheet tabs are rendered as plain radio buttons

### ISSUE THREAD

**Issue by Riernar** [Roll20/roll20-character-sheets#8116]
Hi @Medieve and everyone,

I think there is a problem with the tabs selector on the Ars Magica 5 sheet: it is rendered as 5 plain radio buttons instead of the nice headers visible [on the forum](https://app.roll20.net/forum/post/8479777/slug%7D). I tried with firefox, on both windows and unix.

Unfortunately, I don't now html/css and I have no idea how to fix this. If anyone has pointers, I can try integrating a fix in #8094 . This is minor as it doesn't break the sheet, but the sheet is otherwise stunning and it would be nice to restore those beautiful headers.

Best !

**Comment by Medieve** [comment]
This is just the state of the sheet in Firefox, I honestly have no idea why Firefox won't render the headers.

**Comment by Anduh** [comment]
> This is just the state of the sheet in Firefox, I honestly have no idea why Firefox won't render the headers.

Sometime around a year ago Firefox changed how something worked, resulting it that specific way many older sheets use of trying to show tabs not working any longer. This isn't the only sheet that's affected.

The current example on [CSS Wizardry](https://wiki.roll20.net/CSS_Wizardry#Tabs) works on firefox, but changes the radio inputs to action buttons.

**Ambition & Avarice** and **Stargate-RPG** sheet are two examples that use the radio-input + span method that actually works with firefox, and should be somewhat close to how the Ars Magica 5 sheet have implemented it.

**Comment by Riernar** [comment]
Looks like I completely missed that section in CSS Wizardey (oops!). Thank you so much, I'll use the Stargate/Ambition & Avarice sheet to adapt tabs to firefox.

**Comment by Riernar** [comment]
I ported the code to the recommended style on the wiki, as it seems much simpler and possibly more compatible with other browsers (e.g. Safari). My progress is [on a new branch](https://github.com/Riernar/roll20-character-sheets/tree/arm5-tabs) that I will merge into the PR once ready.
There are still bugs:
+ The tab button are confined on only half the sheet width, the rolling button using the other half. I would like the tab button to use whatever wpace they need to be on a single row.
+ The critical button still has a dice icon before the text. The roll and botch do not, and I copied their code, so I am at a lost

I'm completely new to CSS, so I could use a hand on those matters if someone has the time to lok into the HTML/CSS:
- html: https://github.com/Riernar/roll20-character-sheets/blob/d538bd057455e1a85587e5eab58ae8fc589666fc/Ars_Magica_5th/template.html#L50
- css: https://github.com/Riernar/roll20-character-sheets/blob/d538bd057455e1a85587e5eab58ae8fc589666fc/Ars_Magica_5th/Ars_Magica_5th.css#L93

**Comment by Anduh** [comment]
https://wiki.roll20.net/CSS_Wizardry#Button_Styling

**Comment by Riernar** [comment]
Oh thanks, I forgot to add the critical button to the CSS selector doing that !
I got most things working now, just got to figure out how to select the tab currently opened in CSS to change de button background.

**Comment by Riernar** [comment]
Layout is working, merged in #8094
