### ISSUE TITLE
[DSA5-TSA]  Button names

### ISSUE THREAD

**Issue by MartiniSz** [Roll20/roll20-character-sheets#8142]
Wäre es möglich den wichtigsten Würfelbuttons Namen zu geben?
Makros wären dadurch deutlich einfacher.
Wäre es außerdem möglich Würfelergebnisse oder das Resultat (geschafft oder nicht) irgendwo zwischen zu speichern also in den Attributen?
Ziel wäre es Kämpfe etwas schneller zu gestalten indem Spieler sofort einen Gegner anwählen können den sie angreifen und dann deren Verteidigungswurf direkt mit zu werfen.
Eine Möglichkeit die Angriffe von NPCs als token actions zu gestalten ist momentan sehr viel Handarbeit und würde auch von Namen für buttons oder speichern der verschiedenen Angriffe in den Attributen profitieren. Falls das schon möglich ist und ich einfach nur zu blind war tut es mir leid.

**Comment by Stexinator** [comment]
Ich verstehe das Problem nicht.

Du kannst dir doch ein targeted Makro schreiben, welches den Angriff macht und einen W20 hinterher würfeln. Wenn du willst, dass da auch steht ob eine Verteidigung erfolgreich war, müssen die Spieler Zugriff auf die Werte des Zieltokens haben.

Falls das Problem, das herausfinden des Würfelns ist, ist der Trick, einmal das entsprechend im Sheet zu machen und danach im kleinen Fenster den Pfeil nach oben zu drücken. Das gibt den ausgeführten Text.

**Comment by Stexinator** [comment]
@MartiniSz kann das zu?

**Comment by MartiniSz** [comment]
Ja kann zu

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by Stexinator** [comment]
@MartiniSz das kann nur der Autor
