### ISSUE TITLE
Ficha de Gurps 

### ISSUE THREAD

**Issue by Oparrudo** [Roll20/roll20-character-sheets#8184]
[gurps-3e-ficha-de-personagem-v-bruno-ikeda-biblioteca-elfica.pdf](https://github.com/Roll20/roll20-character-sheets/files/5900512/gurps-3e-ficha-de-personagem-v-bruno-ikeda-biblioteca-elfica.pdf)

**Comment by Stexinator** [comment]
@Oparrudo what do you want to say with this issue?

**Comment by nmbradley** [comment]
It's unclear what this issue is references so I'm going to close it. @Oparrudo if you want to make a new issue with an explanation of what this is referring to, please feel free.
