### ISSUE TITLE
CRLF issues for Generation/sheet.json

### ISSUE THREAD

**Issue by MadCoder253** [Roll20/roll20-character-sheets#8191]
I can't complete my pull request due to another issue with CRLF. I follow the suggested process of creating a fork, merging upstream/master to remain in-sync. I have GIT setup using the standard method of handling CRLF; when making commits all CRLF are automatically converted to LF. I rebased my forked master branch to the Roll20 master branch and everything is identical, but when I make changes to a file and try to commit, the Generation/sheet.json is shown has being updated due to the CRLF issue. 

Here's my Pull Request
https://github.com/Roll20/roll20-character-sheets/pull/8190

Is there an automated check to prevent users from doing a Pull Request if the CRLF is wrong?

Thank you,
Ken

**Comment by vince-roll20** [comment]
I had the same issue when I submitted a pull on another sheet...  I ended up closing my first pull and re-submitting a separate pull for the generation sheet and the pathfinder sheet.  I have no clues why the generation sheet.json caused an issue with my local fork and branch...

**Comment by MadCoder253** [comment]
Thanks @vince-roll20
