### ISSUE TITLE
Equipment list reordering problem

### ISSUE THREAD

**Issue by Arkundar** [Roll20/roll20-character-sheets#8242]
Hi, 
I have an issue with reordering equipment.
Nothing moves.
I tried and tried.
Sometimes an item moves outside the list. (see images attached).
I disabled all my add-ons and tried on Chrome and Firefox. Not working.

![SR5_item_reorder1](https://user-images.githubusercontent.com/69141037/107151225-727b6180-692f-11eb-99bb-64b693625a9b.gif)
![2021-02-03 07_14_23-Kowalski — Mozilla Firefox](https://user-images.githubusercontent.com/69141037/107151279-b3737600-692f-11eb-8ced-db941d877017.jpg)

**Comment by Karlinator** [comment]
Are you experiencing this with only one sheet, or on others as well? If this happens in different sheets (that is, in multiple different game systems) you should report it to Roll20 [here](https://help.roll20.net/hc/en-us/requests/new).

And which character sheet are you experiencing this in?

**Comment by Arkundar** [comment]
I confirm the problem occured in Shadowrun 5th (Advanced) sheet and in D&D 5E by Roll20 sheet (see animated gif below).
![Kowalski-—-Mozilla-Firefox-2021-02-07-23-06-03](https://user-images.githubusercontent.com/69141037/107175211-39c4a200-699a-11eb-8366-2b74a89bfa8b.gif)

**Comment by MadCoder253** [comment]
Do you have the character sheet popped out into a separate window? If so, this is a known bug, but I have no clue if they made any progress with that bug. Drag-drop should work when the character sheet is part of the Virtual Desktop.

**Comment by Arkundar** [comment]
It is indeed popping in a separate window. I forced Firefox to open it in a separate tab but it doesn't fix the problem.

**Comment by Arkundar** [comment]
In settings "use window popouts for characters" was checked. When unchecked the sheet opens in the VD. Item drag-drop works fine now. Ty
________________________________

**Comment by nmbradley** [comment]
This is a known issue with the VTT, so I am closing this issue as it doesn't specifically pertain to sheet development. If you feel as though there are outstanding problems, please consider opening a new issue.
