### ISSUE TITLE
Shadowrun5th (Advanched) sheet doesnt take JSON imports.

### ISSUE THREAD

**Issue by tarlockgod** [Roll20/roll20-character-sheets#8324]
Tried to import multiple characters, didnt work, only feedback i got was 'Error in Skills'. The other players in the group have the same issue. JSON cant be the issue, it worked before and the other 5e sheet takes the data and imports it correctly.

**Comment by differentsmoke** [comment]
My group has the same issue

**Comment by differentsmoke** [comment]
@Stexinator could it have been your pull request?

**Comment by Stexinator** [comment]
Yep, it was mine. I implemented a safeguard so it should not happen, but it didnt work.
Already made some fixes to it https://github.com/Roll20/roll20-character-sheets/pull/8323

**Comment by bananaferret** [comment]
This is happening to my group too currently, even testing multiple sheets that have been imported before.

**Comment by Stexinator** [comment]
The last merges came earlier then expected, the fix to the safeguard was not included. So I used the time and finished the feature and removed the safeguard https://github.com/Roll20/roll20-character-sheets/pull/8368

**Comment by Stexinator** [comment]
@mperes is it possible to assign issues to show that someone is working on it?

**Comment by Stexinator** [comment]
@tarlockgod it is fixed. Please close it
