### ISSUE TITLE
[Warhammer Fantasy Roleplay 4e Official] Initiative not rolling properly

### ISSUE THREAD

**Issue by Fliptop023** [Roll20/roll20-character-sheets#8366]
When setting a character's initiative roll type to 1D10+Initiative bonus+ agility bonus, the sheet is returning the error of **No attribute was found for @{Nachmir|initiatve_bonus}** 

There seems to be a spelling mistake for initiative_bonus

Also certain talents are still spamming on the talent section on the main page, mainly acute senses (sight) for wood elves

**Comment by Stexinator** [comment]
@nmbradley
