### ISSUE TITLE
[Ars Magica 5th] Roll20 image server gives outdated image

### ISSUE THREAD

**Issue by Riernar** [Roll20/roll20-character-sheets#8380]
In #8094 , I updated some images used in the Ars Magica 5 sheet, to make the boundaries between background image repetitions look less rough. The changes were merged into master, but not reflected on the Roll20 website. It seems the roll20's image server is caching the old image and is not updating its cache.
Indeed:
+ the image on the master branch of this github has integrated the changes: https://github.com/Roll20/roll20-character-sheets/blob/master/Ars_Magica_5th/images/paintbar.jpg
+ the image served by the Roll20's image proxy server for this URL has not: https://imgsrv.roll20.net//?src=https%3A%2F%2Fraw.githubusercontent.com%2FRoll20%2Froll20-character-sheets%2Fmaster%2FArs_Magica_5th%2Fimages%2Fpaintbar.jpg 

I though the cache would be invalidated after some time, or otherwise notified of the change, but this does not seems to be the case.
Do I need to do anything to notify the image server of the changes ?

Thank you for your help !

**Comment by Anduh** [comment]
it's a weird issue that pops up now and then. A workaround is to rename the new files and their references, so roll20 is forced to use different images than the old cached ones.

**Comment by Riernar** [comment]
Thank you for your help. I was wondering if there was a better way, I'll rename the image then.

**Comment by Anduh** [comment]
submitting a help center ticket about it would be a good idea. 

I added a mention of this issue to the wiki: https://wiki.roll20.net/Image_use_in_character_sheets
