### ISSUE TITLE
Unwanted file from other collaborator locally

### ISSUE THREAD

**Issue by danimagaming** [Roll20/roll20-character-sheets#8463]
A file names Adventures/adventures.css has showed up on my local machine as a change that I made. And when I try to remove it gives me errors. The only way I could get rid of it was by pushing the commit. But after that, I was unable to submit a pull request since on the Roll20 Repo, it says there is more than one collaborator on more than one folder and gives an error. I'm new to Github but have been following guides religiously and don't understand how this could happen.

**Comment by Stexinator** [comment]
This happens sometimes due to different line endings. To fix this issue, commit the file and then drop the commit. Your Git should then realise that there are no changes and should not prompt you again to commit this file.

**Comment by elminster** [comment]
Hi. I am also having this issue. A commit makes it go away but as soon as I remove the commit with a git reset the issue comes back. Just to confirm what you mean by 'drop the commit'

**Comment by Stexinator** [comment]
I remembered incorrectly. For me every other master update fixes all these issues

**Comment by elminster** [comment]
I never did get it to go away. I just have to make sure I am not lazy and not do an add all. But it is annoying its always hanging around as an unstaged change.

**Comment by Stexinator** [comment]
I commit it with a specific name, and sometimes when I rebase it tells me there are conflicts regarding this file. Then I accept all incoming changes and drop mine and the problem is gone

**Comment by Stexinator** [comment]
This issue is coming up more often again

**Comment by elminster** [comment]
Been a while but i think I ended up getting around it by adding such files to

 .git/info/exclude

on my local copy

**Comment by Stexinator** [comment]
This is still happening

**Comment by Stexinator** [comment]
See https://github.com/Roll20/roll20-character-sheets/issues/9450
