### ISSUE TITLE
[Troika] Letters dissapearing from name and background

### ISSUE THREAD

**Issue by TBigLyfe** [Roll20/roll20-character-sheets#8534]
I think there is a major bug with the Sheet. Whenever me or my players try to write in some parts of the Sheet (Mainly Name and Background) and we close the sheet, whatever was previously written there gets deleted!
Not sure if this is a known bug, if i'm doing something wrong or another reason, idk; But it happened just now; If ya have a way to solve this or knows what is happening please tell me!

**Comment by TBigLyfe** [comment]
@david-janning

**Comment by david-janning** [comment]
Hi @TBigLyfe 
Thanks for spotting this. 
The name and background inputs didn't have the type="text" attribute on them so it wasn't saving. As I was updating the old character sheet those values already existed in my data so it looked ok.
Have put in a bug fix here;-
https://github.com/Roll20/roll20-character-sheets/pull/8543

**Comment by nmbradley** [comment]
@david-janning @TBigLyfe could either of you confirm that this has been resolved with the PR merge?

**Comment by david-janning** [comment]
> @david-janning @TBigLyfe could either of you confirm that this has been resolved with the PR merge?

Can confirm is working as expected after PR merge.
