### ISSUE TITLE
Shadowrun 5 advanced: Import from Chummer doesn't work anymore

### ISSUE THREAD

**Issue by linkendel** [Roll20/roll20-character-sheets#8570]
Hello ! 
In the sheet "Shadowrun5th (advanced)", the "Chummer Import" functionality doesn't seem to work anymore.

How to reproduce:
Create a new Character
Edit the new character
Go in tab "Character Sheet" to show the Shadowrun Sheet
Go in tab "Character"
Past the JSON of your character in the field "Chummer Import"
Click on button "Import", it will display the message "This will override everything"
Click on the button "I Accept", it will display "Please Wait!"
Here you can wait 2 hours, it doesn't do anything.

I have tried with several characters. I attached the simplest one.
[charactJsonExample.txt](https://github.com/Roll20/roll20-character-sheets/files/6195224/charactJsonExample.txt)

**Comment by Nailsonnb** [comment]
still continues with the bug. im verify the warning i see in console and if fix then solve the import but im not sure that.

**Comment by Nailsonnb** [comment]
I created a new game with a custom sheet and it worked. have some minor bugs but whatever. great job.

**Comment by Stexinator** [comment]
This is resolved.

@Nailsonnb can you please create another issue with the bugs? Thanks

**Comment by Stexinator** [comment]
@linkendel

**Comment by Stexinator** [comment]
fixed by #8679

**Comment by Stexinator** [comment]
@linkendel  please close this

**Comment by Stexinator** [comment]
@nmbradley apparently @linkendel does not have the time to close this. Can you do it? Thanks
