### ISSUE TITLE
Shadowrun 5e hide unused and show all buttons no longer work

### ISSUE THREAD

**Issue by bananaferret** [Roll20/roll20-character-sheets#8577]
Clicking the buttons hide unused skills and show all do not do anything when clicked, tested in multiple browsers. There is no way to add points to skills that were previously hidden, or default on them if they were previously hidden.

Edit: it is the Shadowrun 5th Edition (Advanced) version

**Comment by Stexinator** [comment]
Go to Attributes and Abilities => search for skillshowcheckbox and write on for the skills you want to see

**Comment by bananaferret** [comment]
> 
> 
> Go to Attributes and Abilities => search for skillshowcheckbox and write on for the skills you want to see

There is no Attributes and Abilities page or skillsshowcheckbox on this sheet. There is a "main" page where attributes are, and a "skills" page where they are. On the skills page there is a list of every skill and buttons above each section that say 'hide unused ' and 'show all' and clicking these buttons used to make the skills appear. Now they do nothing.  There is no way to add in skills.

![image](https://user-images.githubusercontent.com/79460695/112442628-495d3780-8d09-11eb-90cf-1f8688e82c5c.png)

**Comment by Stexinator** [comment]
Even above that. Roll20 provides 3 tabs: Bio, Character and Attributes&Abilities I think.

The buttons should be fixed together with the import, when the code is merged next time

**Comment by bananaferret** [comment]
> 
> 
> Even above that. Roll20 provides 3 tabs: Bio, Character and Attributes&Abilities I think.
> You can also trigger it for single skills. They are ordered in appearance
> 
> The buttons should be fixed together with the import, when the code is merged next time

Yes, as you can see above when i tried the method you suggested, everything was deleted. All physical skills disappeared and I could not find a way to bring them back when I put "on" in the areas you said to, so that did not work and didn't turn out to be a viable work around.

**Comment by CaptainFrosty55** [comment]
I am also facing the issue and have managed to find a temporary work-around!
once more, go to the "Attributes & Abilities" tab.
There, find all the "skillhideunusedcheckbox(number)" and "skillshowcheckbox(number)" lines
Their values will either be 0 or "on". Both of these values are incorrect and result in hiding the skills.
What you want to do is switch the value to "1". Doing that reveals the box whose value you've changed.
The buttons still don't work but at least all the skill are visible now and none of the previously modified skill were changed.
Hope this helps!

**Comment by Stexinator** [comment]
This is resolved

**Comment by Stexinator** [comment]
@bananaferret
