### ISSUE TITLE
[Mutants & Masterminds 3e] CSS for background and Powers/Adv/Eq tabs not working

### ISSUE THREAD

**Issue by fangdelicious** [Roll20/roll20-character-sheets#8623]
After the recent Roll20 Character sheet troubles, the Mutants & Masterminds 3e sheet's CSS is not working properly. The background image and halftone images do not display and the repeating powers/advantages/etc. sections are missing their colors and styling. Image attached
![Capture](https://user-images.githubusercontent.com/81777990/113352030-bbd1a700-9309-11eb-80f8-40cf70e27ca4.JPG)

**Comment by nmbradley** [comment]
Outlined the cause of the problem [here](https://app.roll20.net/forum/post/9948381/alien-rpg-charactersheet-background). I've escalated this to an internal bug ticket. 

Leaving this open for visibility until the issue is resolved.
