### ISSUE TITLE
Mothership Offical sheet is broken

### ISSUE THREAD

**Issue by switchboardOp** [Roll20/roll20-character-sheets#8667]
stylesheets aren't loading in the app

![Screen Shot 2021-04-06 at 7 28 56 PM](https://user-images.githubusercontent.com/10817100/113793630-63861500-970e-11eb-8f49-26672a5d6214.png)

**Comment by nmbradley** [comment]
I'll look into this. Thanks for the report!

**Comment by switchboardOp** [comment]
rolling back to ae2cb7b using a custom sheet seemed to fix it.

**Comment by nmbradley** [comment]
I think merging from an older branch overwrote the sheet.json legacy switch. Whoops!

**Comment by switchboardOp** [comment]
yeah now that you mention it I had to turn on legacy support to get it to work.
