### ISSUE TITLE
Rolling some type of dices.

### ISSUE THREAD

**Issue by irc-developer** [Roll20/roll20-character-sheets#8695]
Hello,

It is not an error as such but I think it could be a source of error trying to roll dice with negative value, a solution would be to parse it to absolute value for example.

![image](https://user-images.githubusercontent.com/19609516/114241945-54130000-998a-11eb-9ad5-8bf90d7dc546.png)

**Comment by nmbradley** [comment]
Hi, thanks for the report!

This github repo is specifically for the Roll20 Character Sheet system, rather than the VTT as a whole. I'll make sure this gets passed on to the relevant internal devs, and close this issue. Feel free to let me know if I've misunderstood and need to re-open.
