### ISSUE TITLE
[Cypher System by Roll20] Speed roll cost calculation error

### ISSUE THREAD

**Issue by MarekStaron** [Roll20/roll20-character-sheets#8703]
When rolling a general Speed task, the final cost doesn't include the additional cost set in the Action Section/Roll Queries.

![Roll20_CS_CharacterSheet_SpeedRollCostBug](https://user-images.githubusercontent.com/59612033/114306863-90a34080-9add-11eb-9542-9104e6abaffd.png)

**Comment by NathaTerrien** [comment]
This will be investigated. Thanks for the report.

**Comment by nmbradley** [comment]
Hey, just wanted to confirm that this issue was resolved and a fix was pushed for it!
