### ISSUE TITLE
Shadowrun 5 advanced: Blank chat in Roll20, no rolling going on.

### ISSUE THREAD

**Issue by 3D-vice** [Roll20/roll20-character-sheets#8762]
Please also refer to the following post in the Roll20 forum:
https://app.roll20.net/forum/post/10003302/shadowrun-5-games-chat-and-sheets-do-not-work-anymore

I run my own Shadowrun 5 game, as well as participate in a Shadowrun 5 game of a friend of mine. We both use the Shadowrun 5th Edition (Advanced) character sheet template and both of us do not have any APIs running.

Today, I encountered the follwowing problem:

- The game did load without any problems, but
- the chat window is empty, even the Roll20 startup stuff is not showing, and
- the character sheets did load, but rolls are not made/displayed in the chat window
- I cleared the chat archive and starte the game again, then the chat SEEMD to work (write text), but
- rolls made with the character sheet are still not made/displayed
- After completely logging out of Roll20 and signing in again, the chat window is empty again.

This bug appears in both my own Shadowrun 5 game, as well as in the Shadowrun 5 game of my friend (where I am just a player). Also, I have asked a friend of mine to log into the game and try out the chat, but she gets the same odd bug: No chat, not character sheet functioning.

This bug seems to be linked to both of our Shadowrun 5 games using the Shadowrun 5th Edition (Advanced) character sheets. It happens on multiple computers using different browsers.

In addition: When I completely log out of Roll20, clear the browser cache, close the browser (Firefox) and sign into Roll20 and my game again, the chat windows just displays the last text message, but nothing more. When I try to roll or write something, the already displayed text (if there is any) gets repeated again. However, when I klick on "View all chat entries of this game" at the top, the dice rolls are shown correctly in another browser window, but they are still not displayed in the chat window.

Not sure this is something to blame on Roll20.  Someone submitted changes to the sheet just a few days ago well after the sheet framework issues were stabilized.  This is a community sheet, which Roll20 doesn't make changes to... I think it is unlikely Roll20 had anything to do with this particular issue.  Especially since the submitted changes affect the Roll Template which is what displays in chat.

I'll put the Firefox Console Log up here. This is what I get when I try to post something in the chat window in my own game:

Uncaught Error: Unclosed section "rollGreater() wounds_num 0" at 2449
    a https://app.roll20.net/assets/app.js?1618521011:267
    parse https://app.roll20.net/assets/app.js?1618521011:267
    render https://app.roll20.net/assets/app.js?1618521011:267
    render https://app.roll20.net/assets/app.js?1618521011:267
    incoming https://app.roll20.net/assets/app.js?1618521011:609
    o https://app.roll20.net/assets/app.js?1618521011:609
    r https://app.roll20.net/assets/base.js?1618520755:6
    setTimeout handler*nrWrapper https://app.roll20.net/editor/:429
    debounce https://app.roll20.net/assets/base.js?1618520755:6
    c https://app.roll20.net/assets/app.js?1618521011:609
    startup https://app.roll20.net/assets/app.js?1618521011:609
    Zb https://app.roll20.net/assets/firebase.2.4.0.js:203
    gc https://app.roll20.net/assets/firebase.2.4.0.js:52
    cc https://app.roll20.net/assets/firebase.2.4.0.js:30
    dc https://app.roll20.net/assets/firebase.2.4.0.js:29
    Ob https://app.roll20.net/assets/firebase.2.4.0.js:221
    Ob https://app.roll20.net/assets/firebase.2.4.0.js:259
    f https://app.roll20.net/assets/app.js?1618521011:608
    f https://app.roll20.net/assets/app.js?1618521011:608
    delay https://app.roll20.net/assets/base.js?1618520755:6
    setTimeout handler*nrWrapper https://app.roll20.net/editor/:429
    delay https://app.roll20.net/assets/base.js?1618520755:6
    defer https://app.roll20.net/assets/base.js?1618520755:6
    f https://app.roll20.net/assets/app.js?1618521011:608
    m https://app.roll20.net/assets/app.js?1618521011:608
    l https://app.roll20.net/assets/app.js?1618521011:608
    r https://app.roll20.net/assets/app.js?1618521011:608
    a https://app.roll20.net/assets/app.js?1618521011:608
    success https://app.roll20.net/assets/app.js?1618521011:607
    jQuery 6
    _posthookrollrequest https://app.roll20.net/assets/app.js?1618521011:607
    _doRemoteRollRequest https://app.roll20.net/assets/app.js?1618521011:607
    setTimeout handler*nrWrapper https://app.roll20.net/editor/:429
    _doRemoteRollRequest https://app.roll20.net/assets/app.js?1618521011:607
    r https://app.roll20.net/assets/base.js?1618520755:6
    setTimeout handler*nrWrapper https://app.roll20.net/editor/:429
    debounce https://app.roll20.net/assets/base.js?1618520755:6
    performRemoteRoll https://app.roll20.net/assets/app.js?1618521011:607
    process https://app.roll20.net/assets/app.js?1618521011:607
    a https://app.roll20.net/assets/app.js?1618521011:608
    r https://app.roll20.net/assets/app.js?1618521011:608
    r https://app.roll20.net/assets/app.js?1618521011:608
    l https://app.roll20.net/assets/app.js?1618521011:608
    r https://app.roll20.net/assets/app.js?1618521011:608
    a https://app.roll20.net/assets/app.js?1618521011:608
    l https://app.roll20.net/assets/app.js?1618521011:607
    setTimeout handler*nrWrapper https://app.roll20.net/editor/:429
    l https://app.roll20.net/assets/app.js?1618521011:607
    taskComplete https://app.roll20.net/assets/app.js?1618521011:607
    process https://app.roll20.net/assets/app.js?1618521011:607
    initiateRolls https://app.roll20.net/assets/app.js?1618521011:607
    process https://app.roll20.net/assets/app.js?1618521011:607
    a https://app.roll20.net/assets/app.js?1618521011:608
    r https://app.roll20.net/assets/app.js?1618521011:608
    r https://app.roll20.net/assets/app.js?1618521011:608
    l https://app.roll20.net/assets/app.js?1618521011:608
    r https://app.roll20.net/assets/app.js?1618521011:608
    a https://app.roll20.net/assets/app.js?1618521011:608
app.js:267:1340
Uncaught Error: Unclosed section "rollGreater() wounds_num 0" at 2449
    a https://app.roll20.net/assets/app.js?1618521011:267
    parse https://app.roll20.net/assets/app.js?1618521011:267
    render https://app.roll20.net/assets/app.js?1618521011:267
    render https://app.roll20.net/assets/app.js?1618521011:267
    incoming https://app.roll20.net/assets/app.js?1618521011:609
    o https://app.roll20.net/assets/app.js?1618521011:609
    r https://app.roll20.net/assets/base.js?1618520755:6
    setTimeout handler*nrWrapper https://app.roll20.net/editor/:429
    debounce https://app.roll20.net/assets/base.js?1618520755:6
    c https://app.roll20.net/assets/app.js?1618521011:609
    startup https://app.roll20.net/assets/app.js?1618521011:609
    Zb https://app.roll20.net/assets/firebase.2.4.0.js:203
    gc https://app.roll20.net/assets/firebase.2.4.0.js:52
    cc https://app.roll20.net/assets/firebase.2.4.0.js:30
    dc https://app.roll20.net/assets/firebase.2.4.0.js:29
    Ob https://app.roll20.net/assets/firebase.2.4.0.js:221
    Ob https://app.roll20.net/assets/firebase.2.4.0.js:259
    f https://app.roll20.net/assets/app.js?1618521011:608
    f https://app.roll20.net/assets/app.js?1618521011:608
    delay https://app.roll20.net/assets/base.js?1618520755:6
    setTimeout handler*nrWrapper https://app.roll20.net/editor/:429
    delay https://app.roll20.net/assets/base.js?1618520755:6
    defer https://app.roll20.net/assets/base.js?1618520755:6
    f https://app.roll20.net/assets/app.js?1618521011:608
    m https://app.roll20.net/assets/app.js?1618521011:608
    l https://app.roll20.net/assets/app.js?1618521011:608
    r https://app.roll20.net/assets/app.js?1618521011:608
    l https://app.roll20.net/assets/app.js?1618521011:608
    r https://app.roll20.net/assets/app.js?1618521011:608
    r https://app.roll20.net/assets/app.js?1618521011:608
    A https://app.roll20.net/assets/app.js?1618521011:608
    forEach https://app.roll20.net/assets/base.js?1618520755:6
    A https://app.roll20.net/assets/app.js?1618521011:608
    a https://app.roll20.net/assets/app.js?1618521011:608
    o https://app.roll20.net/assets/app.js?1618521011:608
    o https://app.roll20.net/assets/app.js?1618521011:608
    doChatInput https://app.roll20.net/assets/app.js?1618521011:608
    <anonymous> https://app.roll20.net/assets/app.js?1618521011:608
    jQuery 8
    <anonymous> https://app.roll20.net/assets/app.js?1618521011:608
    jQuery 2
    nrWrapper https://app.roll20.net/editor/:429
    nrWrapper https://app.roll20.net/editor/:429
    jQuery 7
    <anonymous> https://app.roll20.net/assets/app.js?1618521011:608
    jQuery 11

I've contacted the sheet author via Roll20 private messaging, but I thought it would be a good idea to open an issue here at the sheets source.

I'd appreciate any help. Thanks!

**Comment by bananaferret** [comment]
This happened to me as well. I discovered it ONLY happened when the Advanced Template was assigned to the room. Most of the time upon entering/refreshing the room the chat was blank, and sometimes it just returned repeating messages from the past. When I changed the room template to NONE, the chat populated as normal, messages were sent/received, rolling with /roll worked, but obviously no one had access to their sheets. 

Turning the template back on again, the chat broke once more. IMO It's definitely the template. It seems every week someone submits changes that breaks things.

**Comment by 3D-vice** [comment]
> 
> 
> This happened to me as well. I discovered it ONLY happened when the Advanced Template was assigned to the room. Most of the time upon entering/refreshing the room the chat was blank, and sometimes it just returned repeating messages from the past. When I changed the room template to NONE, the chat populated as normal, messages were sent/received, rolling with /roll worked, but obviously no one had access to their sheets. Edit: Forgot to say, this also applied to MULTIPLE browsers (firefox and chrome)
> 
> Turning the template back on again, the chat broke once more. IMO It's definitely the template. It seems every week someone submits changes that breaks things. (Edit: Also because none of my other games with different templates are broken in this way)

Hello there, thanks for your response. You described exactly what is still happening.

Uhm, I have a question, since I am totally new to Github: So the recent changes were not necessarily submitted by the original sheet author, but by someone else? And if so, is there a chance to see who has made the changes, in order to contact the editor?

**Comment by Stexinator** [comment]
fixed by #8763

**Comment by Stexinator** [comment]
I request a hotfix

**Comment by Stexinator** [comment]
@mperes @nmbradley

**Comment by Stexinator** [comment]
Hotfix is live, the sheet can be used again

**Comment by 3D-vice** [comment]
Awesome! Thank you very much.
