### ISSUE TITLE
[Only War Enhanced] Dead Sheet (Resolved)

### ISSUE THREAD

**Issue by eternalflip** [Roll20/roll20-character-sheets#8800]
![oof](https://user-images.githubusercontent.com/83255134/116176103-68633680-a6c6-11eb-9f13-03c8e651000a.png)

The tabs at the bottom of this image cannot be switched between upon clicking, and the automatic calculation of the target numbers (white numbers at the top of the image), net characteristic bonuses, the weight capacity, character movement, are also not working. The initiative button is also non-functional.

**Comment by Anduh** [comment]
@johnmoney-code is this related to the recent #8788 ?

**Comment by sirfrog** [comment]
Me, all the other players and the GM in the group have been having this exact issue, it's 'locking' our character sheets to whatever tab we had open last. Rolls seem to work. Tested on both Firefox 87.0 and Chromium 89.0.
It's making the game more or less unplayable, since some players had less-than-useful tabs open last time.

**Comment by Ludricio** [comment]
Having the same issue. Forms-tabs are working fine but the on-sheet tabs are completely dead. Chrome 90.0

**Comment by johnmoney-code** [comment]
Rogue comment, sorry about that. If you guys have Pro accounts you can copy the code into the "Custom" option for sheets, otherwise it's just wait and hope this update gets out soon.

**Comment by johnmoney-code** [comment]
Basically, roll20's Javascript is extremely allergic to improper comments or brackets, and will not hesitate to kill all the scripts if so much as one spare "*/" is found

**Comment by eternalflip** [comment]
Thanks, guys! The sheet's working! My best regards <3
