### ISSUE TITLE
[Only War Enhanced] Accurate checkbox for ranged weapons not working

### ISSUE THREAD

**Issue by Ludricio** [Roll20/roll20-character-sheets#8907]
The accurate checkbox is not working as intended for ranged weapons. Accurate's supposed functionality is to add +10 to BS tests when used with an aim action. This bonus is not added into the roll target equation.

With accurate:
![image](https://user-images.githubusercontent.com/27059417/118492865-c365d780-b720-11eb-94ad-fc551464b0a7.png)
![image](https://user-images.githubusercontent.com/27059417/118492912-d7113e00-b720-11eb-88a1-61d0d370ad08.png)

Without accurate:
![image](https://user-images.githubusercontent.com/27059417/118493019-f27c4900-b720-11eb-8f1f-2c84ba0ddfed.png)
![image](https://user-images.githubusercontent.com/27059417/118493045-f90ac080-b720-11eb-85aa-3d9997232393.png)

Furthermore, when firing a single shot from a weapon with the accurate quality, it is supposed to add 1d10 of damage for every 2 Degrees of Success (DOS). When shooting a weapon with the accurate checkbox checked, it asks for the amounts of DOS:
![image](https://user-images.githubusercontent.com/27059417/118493960-f2307d80-b721-11eb-8d5b-f80f1d99460c.png)

But then completely ignores it in the resulting damage formula:

With 1 DOS
![image](https://user-images.githubusercontent.com/27059417/118493907-e3e26180-b721-11eb-8895-dc2fdfffe076.png)

With 4+ DOS
![image](https://user-images.githubusercontent.com/27059417/118494019-feb4d600-b721-11eb-8b89-e15fd0b9ccb0.png)

As can be seen, the damage remain the same no matter what amount of DOS are chosen. That along with the +10 to BS tests not being added means that the Accurate checkbox is currently completely non-functional, and really does nothing other than suggest to players that there is a working in-sheet functionality for the Accurate quality.

**Comment by nmbradley** [comment]
@johnmoney-code It seems like you have been doing the most work on this sheet recently. Pinging you for visibility on this issue.

**Comment by johnmoney-code** [comment]
#9029 should hopefully get the d10s sorted properly. Originally, "accurate" d10s were filed under a nonexistent separate section on the rolltemplate; now, it'll be counted as part of the damage box. (These added d10s will not proc Righteous Fury.)

As for automatically adding +10 to the to-hit, that needs some JS sheetworker to read those values, and if it's done wrong, the whole sheet will break for a few days. I can draft code that would properly add +10, but without Pro I'd need someone to offer to test it.

**Comment by johnmoney-code** [comment]
#9192 should add the +10 to hit if everything is in order. If this PR does its job, that should be all for this issue.

**Comment by johnmoney-code** [comment]
That PR has caused more problems than it's solved:
1. Normal Ranged Weapons still do not correct for the Accurate +10
2. Accurate checkboxes automatically turn on all other Accurate checkboxes in the list of weapons
3. Even if all the factors line up, DMG button never once asks for DoS
Absolutely disappointing that Roll20 expects me to pay the $10/mo to test development for a public sheet, I'll just roll back #9192 and hope someone else wants to take this over in a way that works

**Comment by johnmoney-code** [comment]
#9199 should pick up all 3 bugs

**Comment by johnmoney-code** [comment]
@Ludricio Accurate should work exactly as intended now, should we close the issue?

**Comment by Ludricio** [comment]
@johnmoney-code II tried it out and from what I can see everything is working as it's intended by the accurate quality.
Great job man!
