### ISSUE TITLE
[Shadowrun] "Error with Weapons TypeError: Cannot read property '0' of null" when importing a character

### ISSUE THREAD

**Issue by StrifeRider** [Roll20/roll20-character-sheets#8933]
Hello, I've been trying to import a character to my shadowrun game from Chummer, and it keeps giving me this error: "Error with Weapons TypeError: Cannot read property '0' of null". I've been reading through the weapons section of my json but I can't seem to find where the error comes from, and my character looks fine in chummer. I have no idea if that's happenned to any one else but I just wanted to report that and hope it gets fixed!
Have a good day.

Here is my json export from Chummer: [anastasia.zip](https://github.com/Roll20/roll20-character-sheets/files/6515665/anastasia.zip)

**Comment by Stexinator** [comment]
I modifed your export so that it works
[anastasia.zip](https://github.com/Roll20/roll20-character-sheets/files/6518948/anastasia.zip)

**Comment by Stexinator** [comment]
Fixed by #8930 which is already merged. So please try again before using the modified export

**Comment by StrifeRider** [comment]
Thank you very much for the fast answer, and I'll try that!

**Comment by Stexinator** [comment]
@StrifeRider if it works as expected please close this issue

**Comment by Stexinator** [comment]
@StrifeRider

**Comment by StrifeRider** [comment]
Thanks it worked

**Comment by Stexinator** [comment]
![grafik](https://user-images.githubusercontent.com/69796777/119262899-205c0480-bbdd-11eb-88b5-2a4972034a75.png)
