### ISSUE TITLE
[Agon] Island character sheet is buggy

### ISSUE THREAD

**Issue by Megarancor** [Roll20/roll20-character-sheets#9051]
In a previous version of the sheet for the game, there were only two different modes for the sheet of a character - the Player sheet and the Strife sheet. The Strife sheet contained both the celestial sky, the island log and also a section at the bottom where the strife can roll the dice for a challenge tweaking its options.

In the current version it seems the Strife sheet only contains the celestial sky and island log, and a new mode has been created as an "Island" sheet, for the sole purpose of keeping track of opponents and rolling the strife dice.

The Island sheet is buggy, so far I've noticed:
- After creating the sheet and adding a first batch of opponent, you can roll the strife dice, by default set to d8, and it works; however, if you change the dice to any other, rolling the dice does not work anymore (even after setting it back to d8 or attempting to use a different opponent). Only way I've found for it to work again is to create a new Island sheet - but you cannot change it from d8 either
- After adding a batch of opponents, I tried setting the divine favor dice at the top - it cause the batch of opponents to be deleted. I tried several times with the same result, but after that it never happened again (maybe it stopped after breaking the rolling with the first bug)

**Comment by nmbradley** [comment]
@mperes I think this is your work? @fredhicks I think this sheet belongs to Evil Hat?

**Comment by fredhicks** [comment]
Is this for the [Agon] sheet, or the [Agon Official] sheet? I see there are two folders in the repository, tho the non-Official was last touched 3 years ago so I think it's not for the 2nd edition of the game, so my assumption based on that is that it's the [Agon Official] one. That's not a sheet that I've personally touched much/at all, but Sean Nittner would know the history there better than I. I've referred him to this post.

**Comment by seannittner** [comment]
Hi Megarancor,

We are unable to recreate this problem, which is usually an indication that the reported behavior is browser-specific. Can you please provide more information on this with that in mind, and/or potentially try using it on a different browser?

Here's a screnshot of on my end (Windows 10, Google Chrome browser) creating an Island and two island characters who both have non-d8 trait dice. I also added d10 Divine Wrath after creating them.

https://www.dropbox.com/s/04qm9bymo6febjr/Example%20of%20changing%20Strife%20Dice%20and%20using%20Divine%20Wrath.png?dl=0

**Comment by Megarancor** [comment]
I am going to try again right now, I will let you know what happens (if I can reproduce it, I could create a video for you)

**Comment by Megarancor** [comment]
Hello, I managed to reproduce it, with a kick - when playing to put this exactly as you had it in the screenshot, I wrote the name of the character, and then it was fixed for that character! So it seems by virtue of the character's name, the character is protected against this bug (or rather the name should be a required field and indicate that to the user for it to work properly).

This is amusingly fitting for the game, actually :)

I captured it in a video, in case you want to reproduce it or fix it in any fashion:

https://youtu.be/xPZ9lDeyAt0
