### ISSUE TITLE
Incomplete merge and build of MYZ sheet

### ISSUE THREAD

**Issue by dwarfwing** [Roll20/roll20-character-sheets#9054]
Hi,
The PR https://github.com/Roll20/roll20-character-sheets/pull/8953 for the Mutant: Year Zero sheet was approved and merged but then reverted. However, the sheet and CSS seem to have made it into production while the translation did not. 

This is causing this sheet to not display or work properly, since the sheetworkers use the translations too and the displayed attributes are dependent on those working. I have had one person contact me about this already. 

It is possible that the attached translation file will solve it. I will also be creating another PR towards this sheet with fixes, which will include the updated translation.json. 

[translation.zip](https://github.com/Roll20/roll20-character-sheets/files/6619154/translation.zip)

**Comment by dwarfwing** [comment]
I have found that on the Dev site has the previous version of the sheet, while the new one with the wrong translation is only on the Prod server.

**Comment by vince-roll20** [comment]
IME, I've found the Dev is often "out-of-sync" with the Main server... ;-(
