### ISSUE TITLE
Mutant Year Zero - Not usable

### ISSUE THREAD

**Issue by m3koenig** [Roll20/roll20-character-sheets#9070]
The last few weeks there are several updates into this. Before this updates the sheet was good.
But today its totaly unusable. Before there was only some...translation misstakes but now its destroyed :/

![image](https://user-images.githubusercontent.com/9989457/121582563-6f07fc00-ca2f-11eb-94aa-b9219fc676e5.png)

https://github.com/Roll20/roll20-character-sheets/tree/master/Mutant%20Year%20Zero

**Comment by Anduh** [comment]
#9071 is likely an emergency fix to this

**Comment by dwarfwing** [comment]
@Anduh Correct. That PR needs to be merged with some priority.

**Comment by dwarfwing** [comment]
This issue should now be resolved by the approval and merge of the linked pull request.

**Comment by nmbradley** [comment]
Can I check @dwarfwing and @m3koenig that this has been resolved?

**Comment by dwarfwing** [comment]
I would say so, but perhaps up to MaKo who opened it to to approve closing it.

**Comment by m3koenig** [comment]
Oh sorry, I was happy about the update but forget to approve it.
Yes! It is great! Thanks! :)
