### ISSUE TITLE
Roll20 rollback?

### ISSUE THREAD

**Issue by Tealk** [Roll20/roll20-character-sheets#9080]
Why was the character sheet in Roll20 reverted to an older version?

GitHub:
https://github.com/Roll20/roll20-character-sheets/blob/2ea12241225c900c0403469d7068b97022c23976/ButterflyAspect/ButterflyAspect.html#L511

Roll20
![image](https://user-images.githubusercontent.com/12276250/121743094-0db05d80-cb01-11eb-85ef-41a7c21ea36d.png)

**Comment by nmbradley** [comment]
I don't believe we rolled back anything, but happy to be corrected. Could you point me to an explanation of precisely what it is that you think has been rolled back?

**Comment by Tealk** [comment]
The character sheet, as you can see from the screenshot. At the time of my contribution was the current version 21.04.2 this was also already online, because I have already played with this version.

A few days later, however, only the version 21.04 was online.

I have introduced the version number to see if something like this happens, because I have often discovered online errors that I had already fixed.
More evidence than a screenshot I can not offer at this time.


I have also written to the Roll20 support, because there often came the statement that they had reset something.

**Comment by nmbradley** [comment]
Hi Tealk.

Sorry for the slow response to this question. My understanding is that the sheet service sometimes requires a manual rebuild. If you're seeing issues where the character sheet versioning is incorrect, this is a good indication that a job has failed. Please feel free to reach out in the future if this continues to be an issue. 

For now, this seems to be resolved so closing this issue.
