### ISSUE TITLE
Change the name of a sheet in the Roll20 list ?

### ISSUE THREAD

**Issue by Zakarik** [Roll20/roll20-character-sheets#9081]
Hello, is it possible to change the name under which a sheet appears in the Roll20 list?

It is for the sheet "Seigneur des Arcanes", there is an error in its name and it should appear under the name "Seigneurs des Arcanes".

It's related to the name error I mentioned in the last pull request you validated yesterday @nmbradley.

**Comment by nmbradley** [comment]
I changed the approved.yaml to change this. It might take a few hours to appear correctly.
