### ISSUE TITLE
[Roll20] Sheets in GitHub that are not maintained and can not be played

### ISSUE THREAD

**Issue by Stexinator** [Roll20/roll20-character-sheets#9129]
There is a bunch of sheets in the repository that are not maintained and can not be choosen when creating a new game.

I would like to see them deleted. If this is not wished or possible I would like to know why.

**Comment by Anduh** [comment]
Those sheets are discontinued sheet usually replaced by a newer better made sheet. They have been left to be accessible to the old games that still uses them, while preventing them from being selected in new games.

**Comment by Stexinator** [comment]
Some of them dont even contain valid html. While html is quite lenient I dont think all will work

**Comment by Anduh** [comment]
> Some of them dont even contain valid html. While html is quite lenient I dont think all will work

Please link these example so that something can be done. We have over 1000 folders here.

**Comment by nmbradley** [comment]
In general, it is the policy of Roll20 not to delete sheets from the repository, even if they're broken. 

Is there a good argument to be made for their removal?

**Comment by Stexinator** [comment]
> 
> 
> > Some of them dont even contain valid html. While html is quite lenient I dont think all will work
> 
> Please link these example so that something can be done. We have over 1000 folders here.

The Witcher/The_Witcher_Pen_&_Paper_RPG.html In this sheet there are several issues and it cannot be choosen. 



> 
> 
> In general, it is the policy of Roll20 not to delete sheets from the repository, even if they're broken.
> 
> Is there a good argument to be made for their removal?

See the example above. I wanted to improve the Witcher sheet and run into the wrong one at first. There is no mark, that this is not playable, same thing for some of the Shadowrun 5 Sheets. A person new to the Roll20 repository has to do additional work to find out which sheets are in use and which sheet the person wants to edit.

Additionally it is common good practice to remove obsolete/unused code to reduce the overall complexity of the code and to keep it clean and slick

**Comment by clevett** [comment]
Some one did an update that broke my Shadowrun 5th Edition sheet. I was tempted to fix it but decided against it because I do not want to deal with this bloated repository.

When I was managing this repository, I actually did deleted a large number of character sheets that were not in the approved.yaml. It had been a policy to allow any sheet into the repo years ago which was adding to the bloat. I'm in total agreement that any character sheets that have been deprecated for over a year should be removed.
