### ISSUE TITLE
[Talessya] Sheet merged but not added to approved.yaml

### ISSUE THREAD

**Issue by jorsermar** [Roll20/roll20-character-sheets#9153]
Following this discussion on the PR https://github.com/Roll20/roll20-character-sheets/pull/9090, the Talessya sheet was merged into the master branch but hasn't been added to the approved.yaml so we cannot use it yet on the app. What would be the next step for this?

**Comment by jorsermar** [comment]
Hello @nmbradley , is there anything I can do to see this published?

**Comment by nmbradley** [comment]
My apologies, I must have overlooked this during the original merge. I will ensure this gets done today.

**Comment by nmbradley** [comment]
@jorsermar I've added this to the approved.yaml, and should be appearing sometime in the next 15 minutes or so. I'll check in a bit to make sure everything has gone through.

**Comment by nmbradley** [comment]
It appears something in this sheet is breaking the sheet select. My experience with this is that it is normally because the CSS file confuses the CSE. I've made some changes on #9200 that I'd like you to review to see if we can resolve this issue

**Comment by fubra-api-user** [comment]
Hi, sorry for not replying before. I´ve been disconnected during summer. Thanks for fixing it, we can see it's working now. 
You can close the ticket, and again, thanks for all your help.

**Comment by jorsermar** [comment]
Hi, sorry for not replying before. I´ve been disconnected during summer. Thanks for fixing it, we can see it's working now.
You can close the ticket, and again, thanks for all your help.
