### ISSUE TITLE
SpyCraft Version 2.0 Sheet Error

### ISSUE THREAD

**Issue by Percenterino** [Roll20/roll20-character-sheets#916]
On the SpyCraft 2.0 character sheet the 'Talent' and 'Speciality' fields always set to the same input as the other (eg. if you type 'Roll20' into the Talent field it appears in the Speciality field and vice versa). This is quite annoying and makes it harder to keep track of who has what bonuses.

I believe that the issue is in the first section of HTML but I can't pinpoint the error myself, although it look like it might have two lines to set the Talent instead of one of the Talent and one for the Speciality.

**Comment by jhon** [comment]
I created a small patch for this issue and have submitted a pull request #1509

**Comment by clevett** [comment]
Hello,

We are clearing up the old issues that are still open. This one appears to have been patched so I am going to close this one. 

Thanks,
Cassie
