### ISSUE TITLE
Call of Cthulhu Character Sheet calculations

### ISSUE THREAD

**Issue by jasoncameron** [Roll20/roll20-character-sheets#920]
CoC 7th ed character sheets seem to be calculating  max HP and MP incorrectly and locking it out. 
Hit Points: Con + SIZ divided by 2. Round up any fractions.
Magic Points: Same as POW

This is not the calculation being shown. 
![capture](https://cloud.githubusercontent.com/assets/10457161/8538342/0385e00c-2439-11e5-9b42-2f0f1bcaba46.JPG)

**Comment by Villadelfia** [comment]
The calculations are correct. You entered your stats wrong. You need to multiply them by 5.

**Comment by aquaalex** [comment]
Yes I have made some changes for sanity and movement calculations
But the HP and MP is correct.

As @Villadelfia said, your stats must  be converted to % so times 5 :)

**Comment by aquaalex** [comment]
So please close this issue :)
