### ISSUE TITLE
[dragon-prince] roll20-character-sheets/Dragon-Prince-fanmade/ not showing up in Roll20 correctly.

### ISSUE THREAD

**Issue by apsalari** [Roll20/roll20-character-sheets#9302]
I'm seeing an issue with the character sheet dragon-prince.

The Author and preview shows up as null, when I try to select it. When I select it and create a game, character sheets show up as blank.  Additionally, as this is being looked at could it be moved from under "Cortex Plus" to "Cortex System" please?

![image](https://user-images.githubusercontent.com/61309459/128053756-106ba345-0b2e-4969-b2a3-5c0a95c2daec.png)

Thanks!
Senjak

**Comment by apsalari** [comment]
Still not showing up correctly after latest update.  Please let me know if there is something else I should do.

**Comment by cbkcook** [comment]
The exact same thing is happening with my new sheet for Escape from Dino Island. They have someone looking into it, but it's a weird issue apparently, and may take some time to sort out.

**Comment by apsalari** [comment]
Oh sweet!  Escape from Dino Island!  I wrote one once upon a time, but never published it.  That looks to be a very fun game!

**Comment by cbkcook** [comment]
It's fantastic - really nails the vibe, and so well produced! I don't love reading TTRPG books, so I was making sheets for ones I've played/run that are awesome and don't have sheets.

**Comment by nmbradley** [comment]
@apsalari and @cbkcook I think these have now been resolved. Can you both confirm that this is now working?

**Comment by cbkcook** [comment]
Escape from Dino Island is showing up properly for me - thanks!
