### ISSUE TITLE
HeroSystem6eHeroic: duplicate files "HitLocations.png" and "hitLocations.png" causing repo problems for windows users

### ISSUE THREAD

**Issue by vince-roll20** [Roll20/roll20-character-sheets#9358]
There are duplicate image files on the repo, which is not allowed on windows systems.
![image](https://user-images.githubusercontent.com/10321187/129424710-ebb509a5-0718-4304-8ea6-fa2baf2787df.png)
[HeroSystem6eHeroic](https://github.com/Roll20/roll20-character-sheets/tree/master/HeroSystem6eHeroic/images)

This is causing some windows users issue since you cannot have more than one file of the same name in the same directory.  Most windows systems are case insensitive so even though they are named differently via their case, windows only allows one of the files to exist locally.  This causes issues when making commits/pr's to the repo since there will always be a file change detected for this sheet.

Requesting that a repo manager delete or rename one of these files so that windows (and possibly mac) users won't have issues with their local forks.

**Comment by Villain1nGlasses** [comment]
@vince-roll20 I think if we simply deleted "hitLocations.png" that wouldn't cause any problems to the sheet. I tried to do that, but I couldn't seem to add the fix to this pull request.

**Comment by vince-roll20** [comment]
Thanks for the follow up.  This isn't the first time this has come up...  Maybe the repo manager can take care of it?
