### ISSUE TITLE
D&D_3-5/charsheet is not calculation total attributes and attr mod.

### ISSUE THREAD

**Issue by viniciuscdeandrade** [Roll20/roll20-character-sheets#9380]
The file D&D_3-5/charsheet_3-5.html has a problem the total attr and attr_mod the inputs are disable and the sheet can't calculate the total values. We should change the "disabled" back to readonly="readonly".
![attr_being_calculated](https://user-images.githubusercontent.com/15006900/130305130-6ce7fafb-2e50-450a-9f6b-99d830efd491.png)
![attr_not_being_calculated](https://user-images.githubusercontent.com/15006900/130305131-ac1dd378-3950-4ac8-b66c-9593d1b99b06.png)

**Comment by nmbradley** [comment]
@hoyer555 Bringing your attention to this as the person that last made changes to this sheet.
