### ISSUE TITLE
DH2E Advanced Character Sheet

### ISSUE THREAD

**Issue by Dustin1230** [Roll20/roll20-character-sheets#9508]
We've been using this sheet for awhile now and have just been dealing with the issues but I'm curious what steps I would need to take in order to fix this.

It looks like certain things just weren't completed and most of the HTML is done but calculations are not being done for items that can be added by the player.  I'm not familiar with how things function in roll20, we donate to the host for him to maintain a sub but I don't really have a desire to sub myself just to fix a couple bugs.

If I get the fixes input on git does roll20 handle the upload?
Is there a way for me to verify my work without subbing?

Thanks

**Comment by Stexinator** [comment]
I think you need to provide more context. Which sheet is DH2E? Is there an active maintainer? What exactly are you missing? What do you mean by "donating to the host"? (Is this the gm and you help with the subscription?)

If your GM is willing to have him host a custom sheet sandbox to test your changes. Review and testing is not activly done in this repo. If you provide changes via a pull request then will get live soon after

**Comment by Dustin1230** [comment]
Seems like you managed to get the gist of the inquiry.

Yes, Host = GM.  Though I'm not trying to inconvenience anyone else if I don't have to, if he creates a new game can he grant me admin permissions or some such in that game so I wouldn't need him to upload/test each time?

DH2E = Dark Heresy 2nd Edition, sorry just used to abbreviating

Missing: It looks like the work was stopped prior to completion, the html seems finished but the calculations for player added advancements, gear, and a couple other things were left out so everything must be entered manually atm.  I have some experience in coding but nothing professional, though I should be able to use the example code from the functional basic DH2E sheet to get things plugged in properly.

Just to clarify, if I get the fixes added via a pull request then you guys handle getting it added to the current sheet?  I read somewhere else about non-functional sheets still being on the site and don't want to add a new sheet but rather have this one updated.

**Comment by Stexinator** [comment]
Unfortunately he has to upload it every time.

> Just to clarify, if I get the fixes added via a pull request then you guys handle getting it added to the current sheet? 
Well Roll20 handles it.

**Comment by Dustin1230** [comment]
Thank you Stex, you can consider this matter resolved.
