### ISSUE TITLE
[Super RED] Macro Bar

### ISSUE THREAD

**Issue by marioapunkt** [Roll20/roll20-character-sheets#9537]
Since the last update (around 09-20-21) I can't delete anything from my macro quick bar. Before I could drag the dice buttons from the sheet to the macro quick bar and remove them by right clicking and choosing delete.

**Comment by nmbradley** [comment]
This does not sound like functionality specific to a particular sheet and has been inactive for more than 18 months. 

Closing this issue, please create a helpdesk ticket if you still require assistance.
