### ISSUE TITLE
Stars Without Number: Attack roll buttons not working

### ISSUE THREAD

**Issue by kevinsearle** [Roll20/roll20-character-sheets#957]
Reported from a user:

> you embedded roll buttons for attacking do not work. The rolls turn out to have waaay to many addition signs, just straight up breaking the roll.

**Comment by jfredett** [comment]
I'm on it, can't get past the black loading screen atm, but once I do; I suspect it's probably just a missing default.

**Comment by jfredett** [comment]
Hmm, they seem to be working for me. Was this in a forum post? I'm wondering if they left the attack bonus section blank, I don't think that gets defaulted in the weapon section.

**Comment by jfredett** [comment]
Yep, definitely due to the AB not defaulting on either the weapon AB or the player AB. I think they all start at 0. At work, so I can't check the book now, but should have a patch this evening.

**Comment by jfredett** [comment]
in the meantime, adding an AB and Weapon AB value should fix it.
