### ISSUE TITLE
[Knight] In "Combat" and "Vehicule" tabs, effects and improvements are not displayed correctly anymore

### ISSUE THREAD

**Issue by KamuiShiro** [Roll20/roll20-character-sheets#9646]
**Steps to reproduce**

1. Open the cheatsheet for a Knight PJ
2. Select the tab "Combat"
3. At the bottom of the sheet, select one weapon effect
4. Note that under the effect selected, the relevant description is not displayed, but you can see instead "[name-of-the-effect]-description"
You can reproduce it with _Amélioration (structurelle) des armes_, _Amélioration d'ornement des armes_, and also in the vehicule tab of the sheet. 

**Expected result**

When an effect is selected in the dropdownlist, the description of the effect should be displayed in the cell below. 

** Screenshot **

![Bug Knight](https://user-images.githubusercontent.com/1635598/138193843-a6cd3972-051d-479b-9078-c0aef6211e43.png)

**Comment by Zakarik** [comment]
It is corrected!
