### ISSUE TITLE
Das_Schwarze_Auge_4-1 - Dice rolls very hard to read

### ISSUE THREAD

**Issue by kaiHabighorst** [Roll20/roll20-character-sheets#969]
In the DSA stylesheet it is very hard to read the dice rolls. This is important to distinguish between two or three critical dices.

A simple change to the stylesheet will help, make the dices more visible.

.basicdiceroll {
    color: yellow;
    font-size: 1.15em;
    font-style: bold;
}

This would help us a great deal. We really like the tool and the character sheet. 

Thanks for all the work.

Best regards,
 Kai

**Comment by Meteox** [comment]
thanks for the idea, i´ve added it to the pullrequest
