### ISSUE TITLE
[Zweihänder Grim & Perilous] new french translations are not applied

### ISSUE THREAD

**Issue by dyvim** [Roll20/roll20-character-sheets#9693]
Hello, 

I've submitted new french translatons via crowdin one weeks ago (before the 22/10). I can see them in github in the roll20-character-sheets/Zweihänder Grim & Perilous/translations/fr.json but when I launch a new game in the website, i can not see the new translations.
Is there a delay between the commit in github and the use of the file in the website?
Is there a rule about the commit of the translations and the appliance on the site? (ex we commit the translations on github every wednesday at 5 PM and they are applied on the website 3 days later or something like that)

BRgds

**Comment by dyvim** [comment]
@wing-it @nmbradley 
is it possible that you have a look on this issue?

**Comment by nmbradley** [comment]
Hi @dyvim 

It appears to me that the translations are appearing on the sheet?

![image](https://user-images.githubusercontent.com/7937613/140387571-eef2fdfa-233b-4b4c-8c11-d1e87920f03b.png)

Translations will only take place if you have selected that as the language on the main roll20 site in your account settings.

**Comment by dyvim** [comment]
@nmbradley  Yes there are already translations (in fact for several months or years). But they are not the most recent ones that i submitted via crowdin.
In fact they are even not the one that can be seen on github in the fr.json file.

For example : Order alignment is translated in "Alignement d'ordre" instead of " Alignement (ordre)", Ancestry is translated in "Ancêtres" when it should be "Ethnie" and Sex gives "Sexe" when it should give "Genre"

When I check the fr.json file on gitbub i can see that there is a red cross at the right of the name of the file. When i click on it it diplays "2 failing checks". Perhaps it's tied to the problem... not sure.

BRgds

**Comment by nmbradley** [comment]
Okay, understood. I've opened an internal investigation and will respond here when we have more clarity on the issue.

Thanks!

**Comment by dyvim** [comment]
the problem is solved

@nmbradley just out of curiosity, what was it?
