### ISSUE TITLE
[Mutants and Masterminds 3E Official] Equipment, Vehicle, and Headquarters generated attacks do not parse correctly when rolled using the Attack macro button.

### ISSUE THREAD

**Issue by ManfranMike** [Roll20/roll20-character-sheets#9704]
**Summary:**

![image](https://user-images.githubusercontent.com/7898733/139729195-5dad9036-2d8d-422d-9048-7f8ba20ddcca.png)

When building attacks in the sheet from the center menu under Powers, the attack will be added to the Attacks section on the sheet. Clicking the button in the Attacks section for this attack will function normally and output the macro to chat through the roll template.

However, when doing this same procedure but under any section of the center menu other than Powers (i.e. Equipment), the macro will not be able to find the descriptor attribute for the attack.

If you manually set an attribute in the roll20 menu (third tab for Attributes & Abilities) and name it "descriptor", then the macro will use that value instead.

**Steps to Reproduce:**
1. Log into Roll20 and select Create a new game
![image](https://user-images.githubusercontent.com/7898733/139727513-171540b2-faa8-4472-8e79-95c7b41f4d6b.png)

2. Give the game any name, select "Mutants and Masterminds 3e Official" for the character sheet, and hit "I'm ready, Create Game!"
![image](https://user-images.githubusercontent.com/7898733/139727724-2e821d4a-ec49-440d-9e2a-5c2f8f9222d6.png)

3. Select "Launch Game" to open the game
![image](https://user-images.githubusercontent.com/7898733/139727883-81fc0119-5200-4852-a50a-4500ca506a79.png)

4. Navigate to the Journals tab on the right side and add a Character
![image](https://user-images.githubusercontent.com/7898733/139727964-dee3b2c4-ca8e-4709-aab6-e87a64fb5533.png)

5. Click "Save Changes" on the character, then navigate to the "Character Sheet" tab of the Character window
![image](https://user-images.githubusercontent.com/7898733/139728174-a83bb8f2-1c45-4966-85ac-653d6879929f.png)

6. In the center menu of the sheet near the bottom, switch to the Equipment tab instead of Powers and hit the Pencil icon to edit
![image](https://user-images.githubusercontent.com/7898733/139728320-ada8c873-aa1f-4865-8a88-894920c58fd0.png)

7. Create an Attack with any name, any rank, and any descriptor. Descriptor can be blank or have any value.
![image](https://user-images.githubusercontent.com/7898733/139728544-3c1e6c35-4bab-400f-b076-876d896ca53b.png)

8. Click on the Attack that was generated in the Attacks section of the character sheet and observe the chat message and error.
![image](https://user-images.githubusercontent.com/7898733/139728717-71f62ef8-c9ef-49c7-ad02-e17f67de4bdb.png)

**Suggestions/Theories**
It appears to my uneducated eyes, that the roll template is not receiving the descriptor inputted by the user. I think this because you can manually add the attribute into the Attributes & Abilities section of the character (like where you can see sheet_version), and the roll template will use that value when it goes to the chat. This also won't affect the attacks made through the Power tab of the center menu, as those will still pull from what was inputted by the user in the edit menu of Powers.

**Comment by Medieve** [comment]
Pushing a fix to this issue
