### ISSUE TITLE
[Mutants & Masterminds 3e Official] Alteration to Affliction DCs output

### ISSUE THREAD

**Issue by Ardrikk** [Roll20/roll20-character-sheets#9714]
So, I love that Affliction powers show the defense that resists it, the different levels of effects if you fail, and numbers that tell the thresholds for degrees of failure.  However, the first number, for 1st Degree of Failure, is wrong:
![image](https://user-images.githubusercontent.com/52671357/140078033-66fc6c68-f94a-4fa2-8c9b-115812d9835d.png)
![image](https://user-images.githubusercontent.com/52671357/140078063-a76fe919-e87f-42e7-bd05-8db6a659ecf1.png)

16 is the DC to resist this, so a 15 would result in the 1st Degree of Failure of Dazed.  A 16 means the target succeeds in resisting.
For additional clarification:
It shouldn’t have the word Dazed out from it, then, if it’s intended to be the result that has no effect on you.
Whereas the 2nd entry is 5 below the DC and that IS 2 degrees of failure and gives you the Compelled Condition (in this example).
Same with a 6 being 10 below and giving you the 3rd degree. But the 1st degree of failure comes from being 1-4 below the DC.
![image](https://user-images.githubusercontent.com/52671357/140078267-9c630d8e-0057-42fc-9341-ef9fb3412825.png)

**Comment by nmbradley** [comment]
@Medieve Another bug report.

**Comment by Medieve** [comment]
Working as intended.

**Comment by Ardrikk** [comment]
My point still stands, though, that rolling a 16 does not result in the 1st Degree of Failure (Dazed) taking place. Showing a 16 is in line with how Damage Resist DCs are shown (show the number you need to roll not to get hurt), but putting the name of the 1st Degree of Failure beside it is confusing.
