### ISSUE TITLE
[Hexxen-1733-Ulisses-Spiele(Official)] 2 translation.json in Crowdin

### ISSUE THREAD

**Issue by dyvim** [Roll20/roll20-character-sheets#9789]
there are 2 translation.json files to translate in Crowdin for the HeXXen1733 character sheet. it's one too much.

edit : in fact it's one translation.json and one translation**s**.json

**Comment by nmbradley** [comment]
I deleted the extraneous file. Feel free to reopen this issue if it continues to be a problem.

**Comment by dyvim** [comment]
It's OK. Thanks.

Thomas Coquery



Le ven. 10 déc. 2021 à 20:30, Nic Bradley ***@***.***> a
écrit :
