### ISSUE TITLE
Rogue Trader Ranged Weapons->Misfortunes section overlapping Insanity/Corruption Section.

### ISSUE THREAD

**Issue by Kevin138** [Roll20/roll20-character-sheets#986]
When you add Ranged Weapons, Gear, and/or Acquisitions everything begins to shift downward but does not move the next section of the sheet (Wounds/Fate Points/ Insanity/Corruption) down as well. You can add a Melee Weapon and things will shift down just fine.

This issue was also posted on the forms here: https://app.roll20.net/forum/post/2229833/slug%7D

**Comment by AlanLane** [comment]
I've already posted on the board. 
I think I've managed a solution. 
The sheet builder is around here? :+1:
