### ISSUE TITLE
Cannot update or checkout master due to files with invalid path

### ISSUE THREAD

**Issue by Stexinator** [Roll20/roll20-character-sheets#9883]
These files are flagged as invalid path

invalid path 'Sig: City of Blades/Images/1.png' 
invalid path 'Sig: City of Blades/Images/2.png' 
invalid path 'Sig: City of Blades/Images/3.png' 
invalid path 'Sig: City of Blades/Images/4.png' 
invalid path 'Sig: City of Blades/Images/5.png' 
invalid path 'Sig: City of Blades/Images/6.png' 
invalid path 'Sig: City of Blades/Images/7.png' 
invalid path 'Sig: City of Blades/Images/8.png' 
invalid path 'Sig: City of Blades/Images/AshenKeysLogo.jpg' 
invalid path 'Sig: City of Blades/Images/DaughtersLogo.jpg' 
invalid path 'Sig: City of Blades/Images/GlimmerKnightsLogo.jpg' 
invalid path 'Sig: City of Blades/Images/ReforgedBladesLogo.jpg' 
invalid path 'Sig: City of Blades/Images/VoidStridersLogo-fixed.jpg' 
invalid path 'Sig: City of Blades/Images/dia-checked.svg' 
invalid path 'Sig: City of Blades/Images/dia-unchecked.svg' 
invalid path 'Sig: City of Blades/Images/hex-h-checked.svg' 
invalid path 'Sig: City of Blades/Images/hex-h-unchecked.svg' 
invalid path 'Sig: City of Blades/Images/hex-v-checked.svg' 
invalid path 'Sig: City of Blades/Images/hex-v-unchecked.svg' 
invalid path 'Sig: City of Blades/sheet.json' 
invalid path 'Sig: City of Blades/sigcob.css' 
invalid path 'Sig: City of Blades/sigcob.html' 
invalid path 'Sig: City of Blades/sigcob.png' 
invalid path 'Sig: City of Blades/translation.json'

**Comment by vince-roll20** [comment]
;-(
Repo suggestion:  Can the repo use Push Rules: https://docs.gitlab.com/ee/push_rules/push_rules.html
to prevent these kinds of issues...?

**Comment by nmbradley** [comment]
This appears to be a gitlab related link, which won't work here. But I think that this issue was resolved by #9885

**Comment by vince-roll20** [comment]
> This appears to be a gitlab related link, which won't work here. But I think that this issue was resolved by #9885
Yep.  Andreas brought that up on Discord.  My bad.  Thanks for addressing the issue though!
