### ISSUE TITLE
Vast Grimm Character Sheet Merged, not showing up on Roll20

### ISSUE THREAD

**Issue by infinitebrian** [Roll20/roll20-character-sheets#9948]
The Vast Grimm character sheet was merged 3 days ago but isn't showing up as a template option. Thanks for looking into this.

**Comment by nmbradley** [comment]
Apologies for taking so long to respond to this, but it seems to have been resolved. Feel free to open a new issue if there continues to be issues.

**Comment by infinitebrian** [comment]
Thanks for looking into it!
