### ISSUE TITLE
Wilson-Homebrew.css

### ISSUE THREAD

**Issue by Skillafizer** [Roll20/roll20-character-sheets#998]
.charsheet thead td {
    font-weight: bold;
}

.charsheet td {
    padding-right: 1em;
}

.charsheet input[type=text], .charsheet input[type=number] {
    padding-left: 2px;
    border: 1px solid #333333;
}

.charsheet table {
    margin-bottom: 0.5em;
}

.sheet-formblock {
    width: 22em;
    margin-bottom: 1em;
}

.charsheet textarea {
    width: 95%;
    max-width: 95%;
    min-width: 95%;
    resize: vertical;
    overflow-y: auto;
    min-height: 5em;
    border: 1px solid black;
}

.sheet-thiefabilities input, .sheet-savingthrows input, .sheet-turnundead input {
    width: 5em;
}

.sheet-shortnum {
    width: 2.5em;
    text-align: center;
}

.sheet-spelltable {
    margin-top: 0.5em;
}

.sheet-spelltable td {
    padding: 0px;
    text-align: center;
}

**Comment by clevett** [comment]
Hello,

I'm working on closing the old issues from the GitHub. If this is still an issue please let us know.

Thanks,
Cassie
